### ISSUE TITLE
The instructions are wrong in several ways

### ISSUE THREAD

**Issue by AronT-TLV** [MicrosoftDocs/azure-docs-cli#1042]
1/ To create a certificate and store it in a key vault, the proper command on Linux (as in the help):
az ad sp create-for-rbac --name "myServPrin" --keyvault myKeyVault --cert myCert --create-cert

i.e. the service principle name has to be in quotes and the key vault must exist already or else you will get an error. Also you should clarify that there are default roles and assignments that will happen unless you explicitly define them here

2/ this is not necessarily an issue with the documentation, but with the product. If you download the certificate in the vault, you can't login with it. The PEM format gives this error:

Error:Invalid Certificate: Expected Start of Certificate to be '-----BEGIN RSA PRIVATE KEY-----'

In other words the certificate is created in the openssl format and the az login is expecting openssh format!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3f84bdc-9ed0-eb85-f3af-9711e8083a95
* Version Independent ID: 03a47d06-5fbf-4764-0882-99cd8bd41110
* Content: [Use Azure service principals with Azure CLI 2.0](https://docs.microsoft.com/en-us/cli/azure/create-an-azure-service-principal-azure-cli?view=azure-cli-latest)
* Content Source: [docs-ref-conceptual/create-an-azure-service-principal-azure-cli.md](https://github.com/Azure/azure-docs-cli-python/blob/master/docs-ref-conceptual/create-an-azure-service-principal-azure-cli.md)
* Service: **role-based-access-control**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment]
@AronT-TLV - Thanks for the detailed information about the discrepancy between the documentation and what the CLI is expecting. While we can update the documentation, you do correctly identify that the CLI expects OpenSSH and KeyVault exports PEM. If you could file a bug with the engineering team and link back to this ticket, I'd appreciate it. File the bug at: https://github.com/azure/azure-cli/issues

**Comment by AronT-TLV** [comment]
I raised the issue [here](https://github.com/Azure/azure-cli/issues/7404) I also put in a support request

**Comment by sptramer** [comment]
Closing due to lack of response.
