### ISSUE TITLE
describe how to retrieve the APP_ID using the command line

### ISSUE THREAD

**Issue by xtofs** [MicrosoftDocs/azure-docs-cli#1199]
On one hand the article focuses on automation using Azure CLI, on the other hand it completely relies on the user to look at the APP_ID of the SP created in the first step and replace the placeholder in the remaining snippets.   It would be great to actually have a step that retrieve the APP_ID based on the ServicePrincipal Name and assign it to a variable. something like `appId=$(az sp list ... )`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3f84bdc-9ed0-eb85-f3af-9711e8083a95
* Version Independent ID: 03a47d06-5fbf-4764-0882-99cd8bd41110
* Content: [Use Azure service principals with Azure CLI](https://docs.microsoft.com/en-us/cli/azure/create-an-azure-service-principal-azure-cli?view=azure-cli-latest)
* Content Source: [docs-ref-conceptual/create-an-azure-service-principal-azure-cli.md](https://github.com/Azure/azure-docs-cli-python/blob/master/docs-ref-conceptual/create-an-azure-service-principal-azure-cli.md)
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by xtofs** [comment]
Great new additions to the article/post.  but the comment was not addressed as far as i can tell.

Please add some notes that describe how to  save appId (and similar ) into shell variables after running `az ad sp create...` so that these scritp snippets can be used in automation and not run manually.

**Comment by sptramer** [comment]
Fixed in #1468.
