### ISSUE TITLE
Installion fails on Ubuntu via apt

### ISSUE THREAD

**Issue by mataralhawiti** [MicrosoftDocs/azure-docs-cli#1201]
the installation instructions for Liunx apt (Ubunut) fails on last step with following error :
"Unable to locate package azure-cli"

Using below instrcutions, I sucessfully was able to install in on my Ubuntu 18.04
https://github.com/twitchax/azure-docs-cli-python/blob/key_fix/docs-ref-conceptual/install-azure-cli-apt.md

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe1526a9-7f22-504e-484c-0f3edc11b178
* Version Independent ID: c5dec108-efcd-aa77-04b5-803b6b894dba
* Content: [Install the Azure CLI on Linux with apt](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-apt?view=azure-cli-latest#signingKey)
* Content Source: [docs-ref-conceptual/install-azure-cli-apt.md](https://github.com/Azure/azure-docs-cli-python/blob/master/docs-ref-conceptual/install-azure-cli-apt.md)
* Product: **azure**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by jochenvanwylick** [comment]
+1 Same problem here - same solution worked

**Comment by sptramer** [comment]
@mataralhawiti The instructions you linked are out of date. To fix the installation issue, I need more information on which installation of Ubtunu you are using and all console output from running the complete installation instructions.

**Comment by sptramer** [comment]
Just installed on Ubuntu 18.04 without issue, following the instructions. The problem you experienced may be related to the behavior of pasting into the Terminal app window, which will eat user input when a prompt appears. This would explain why the repo wasn't available: The first command to use `sudo` appears in a text block before he install instructions. I'll fix this.

Before pasting any text into your terminal, run `sudo -v` to prime `sudo` to run commands, and see if copy/paste works then.

**Comment by brennaman** [comment]
Anybody experience things hanging on "Unpacking azure-cli"?

**Comment by mataralhawiti** [comment]
> Just installed on Ubuntu 18.04 without issue, following the instructions. The problem you experienced may be related to the behavior of pasting into the Terminal app window, which will eat user input when a prompt appears. This would explain why the repo wasn't available: The first command to use `sudo` appears in a text block before he install instructions. I'll fix this.
> 
> Before pasting any text into your terminal, run `sudo -v` to prime `sudo` to run commands, and see if copy/paste works then.

Thanks @sptramer , but I'm sorry I didn't quit understand what you were trying to say.
I'd gladly try to reinstall it and see if I'm still see the same issue.

**Comment by gshockim** [comment]
In my case 

sudo apt-key --keyring /etc/apt/trusted.gpg.d/Microsoft.gpg adv \
     --keyserver packages.microsoft.com \
     --recv-keys BC528686B50D79E339D3721CEB3E94ADBE1229CF

failed so the apt-get update failed.
So I googled it and I found solution for me.

curl -sL "http://keyserver.ubuntu.com/pks/lookup?op=get&search=0xEB3E94ADBE1229CF" | sudo apt-key add

did this then it worked for me.

**Comment by sptramer** [comment]
@gshockim What was the error that you saw when running `apt-key`, and which version of Ubuntu are you using? Are you running on WSL? Our [troubleshooting](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-apt?view=azure-cli-latest#troubleshooting) includes instructions on how to handle certain apt-key failures.

**Comment by sptramer** [comment]
@mataralhawiti Let me know if the new instructions worked for you. If they don't:

1. Run `sudo -v`
2. Start with step 1 on the instructions as normal

Let me know if either of these worked for you so that I can update instructions if needed.

**Comment by sptramer** [comment]
@mataralhawiti @gshockim - Please let me know if my comments or any updates to the apt install article resolved your issues:

https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-apt?view=azure-cli-latest

**Comment by cbrooksmsft** [comment]
$ sudo apt update

...
Err:1 https://packages.microsoft.com/repos/azure-cli bionic InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY EB3E94ADBE1229CF
...


$ sudo apt-key --keyring /etc/apt/trusted.gpg.d/Microsoft.gpg adv      --keyserver packages.microsoft.com      --recv-keys BC528686B50D79E339D3721CEB3E94ADBE1229CF

Executing: /tmp/apt-key-gpghome.hNrqKufT1D/gpg.1.sh --keyserver packages.microsoft.com --recv-keys BC528686B50D79E339D3721CEB3E94ADBE1229CF
gpg: connecting dirmngr at '/tmp/apt-key-gpghome.hNrqKufT1D/S.dirmngr' failed: IPC connect call failed
gpg: keyserver receive failed: No dirmngr

**Comment by b-long** [comment]
Second @gshockim .  Fixes the error:
```
root@computer:/var/log# sudo apt-key --keyring /etc/apt/trusted.gpg.d/Microsoft.gpg adv      --keyserver packages.microsoft.com      --recv-keys BC528686B50D79E339D3721CEB3E94ADBE1229CF
Executing: /tmp/apt-key-gpghome.fclNTwsYG3/gpg.1.sh --keyserver packages.microsoft.com --recv-keys BC528686B50D79E339D3721CEB3E94ADBE1229CF
gpg: keyserver receive failed: Server indicated a failure
```
cc/ @sptramer

**Comment by xsqian** [comment]
sudo apt-key --keyring /etc/apt/trusted.gpg.d/Microsoft.gpg adv \
>      --keyserver packages.microsoft.com \
>      --recv-keys BC528686B50D79E339D3721CEB3E94ADBE1229CF
Executing: /tmp/apt-key-gpghome.IkdxYuOmCx/gpg.1.sh --keyserver packages.microsoft.com --recv-keys BC528686B50D79E339D3721CEB3E94ADBE1229CF
gpg: connecting dirmngr at '/tmp/apt-key-gpghome.IkdxYuOmCx/S.dirmngr' failed: IPC connect call failed
gpg: keyserver receive failed: No dirmngr

**Comment by xsqian** [comment]
I got this error while running the installation steps:
gpg: connecting dirmngr at '/tmp/apt-key-gpghome.IkdxYuOmCx/S.dirmngr' failed: IPC connect call failed
gpg: keyserver receive failed: No dirmngr

**Comment by sptramer** [comment]
@xsqian That error indicates that you're running on WSL. Please follow the WSL troubleshooting instructions.

**Comment by MattMcL4475** [comment]
For the latest version of Linux Mint, "lsb_release -cs" returns "tessa"

Therefore, I had to update "tessa" to "bionic" in /etc/apt/sources.list.d/azure-cli.list

1.  sudo nano /etc/apt/sources.list.d/azure-cli.list
2.  Change "tessa" to "bionic" and save 
3.  sudo apt-get update && sudo apt-get install azure-cli

**Comment by ChristopherGLewis** [comment]
I had the dirmngr issue with WSL.  This command did the trick:

    curl http://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -

**Comment by sptramer** [comment]
Removed the `dirmngr` and `apt-key` parts of the instructions to avoid issues with older WSL versions and some other Linux installs.
