### ISSUE TITLE
Instructions result: azure cli installed, but doesn't remember it's logged in

### ISSUE THREAD

**Issue by BrBill** [MicrosoftDocs/azure-docs-cli#1248]
When I install azure-cli as directed, it works. az login runs a browser, I log in, it works.
But the next command I run immediately forgets I'm already logged in:

$ az account list
Please run "az login" to access your accounts.
[]

So either the instructions or the product are faulty.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d09ed623-c83f-6bae-639e-a5f9a31fe3bb
* Version Independent ID: c5d0d722-aacd-47a3-3fcf-982c02c4d0e9
* Content: [Install the Azure CLI for macOS](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-macos?view=azure-cli-latest)
* Content Source: [docs-ref-conceptual/install-azure-cli-macos.md](https://github.com/Azure/azure-docs-cli/blob/master/docs-ref-conceptual/install-azure-cli-macos.md)
* Product: **azure**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment]
This seems like a product bug if logging in doesn't result in you being able to run commands. Please file an issue with engineering: https://github.com/azure/azure-cli/issues
