### ISSUE TITLE
Version 2.0.55 Release Date

### ISSUE THREAD

**Issue by Rychard** [MicrosoftDocs/azure-docs-cli#1254]
The release date of Version 2.0.55 appears to be wrong (with a year of `2018` instead of `2019`).

Am I missing something?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0e8d9ef-f25b-bb46-7f1a-bd3588be3343
* Version Independent ID: cd392600-a90d-0145-5ea6-6b01ab8f4ab9
* Content: [Azure CLI release notes](https://docs.microsoft.com/en-us/cli/azure/release-notes-azure-cli?view=azure-cli-latest#december-20-2018)
* Content Source: [docs-ref-conceptual/release-notes-azure-cli.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/release-notes-azure-cli.md)
* Product: **azure**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment]
Closed by https://github.com/MicrosoftDocs/azure-docs-cli/pull/1256
