### ISSUE TITLE
Exporting all zones in single CLI would be great

### ISSUE THREAD

**Issue by rahulskicks** [MicrosoftDocs/azure-docs-cli#1257]
Thanks for bringing out CLI For Import/Export Aure DNS Zones however it would be great if we have a way to Import/Export Azure DNS Zones via single command execute for eg:- Using text file with list of all zones that can be exported from Azure DNS. Additionally, can we expect powershell cmdlets too?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21632cd2-aec0-1521-a9b0-f96f69ab15ed
* Version Independent ID: d6ab81e8-1aba-b922-9984-4523386c83cf
* Content: [Manage Azure subscriptions with the Azure CLI](https://docs.microsoft.com/en-us/cli/azure/manage-azure-subscriptions-azure-cli?view=azure-cli-latest)
* Content Source: [docs-ref-conceptual/manage-azure-subscriptions-azure-cli.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/manage-azure-subscriptions-azure-cli.md)
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by tjprescott** [comment]
Hi @rahulskicks I think your issue should probably be posted here:
https://github.com/Azure/azure-cli

**Comment by sptramer** [comment]
@rahulskicks - Please file this as a product enhancement request at https://github.com/azure/azure-cli/issues
