### ISSUE TITLE
Deprecation info not showing on CLI online docs

### ISSUE THREAD

**Issue by adewaleo** [MicrosoftDocs/azure-docs-cli#1263]
Deprecation information being generated for the docs team is not being used online. 

Compare cli output (az monitor autoscale-settings -h) to [online docs output](https://docs.microsoft.com/en-us/cli/azure/monitor/autoscale-settings?view=azure-cli-latest).

The command group deprecation message is not being shown.  "This command group has been deprecated and will be removed in a future release. Use 'monitor autoscale' instead."

This also applies to deprecated commands and parameters. Like "az cognitiveservices list" and "az monitor activity-log list --filters".

This information is being passed along as "Deprecated" fields in the xml generated by the sphinx-based azhelpgen.py scripts.

For example:

```
                        <field>
                            **<field_name>Deprecated</field_name>**
                            <field_body>
                                <paragraph>Option ‘–filters’ has been deprecated and will be removed in version ‘2.1.0’.</paragraph>
                            </field_body>
                        </field>
                        <field>
                            <field_name>Summary</field_name>
                            <field_body>
                                <paragraph>OData filters. Will ignore other filter arguments.</paragraph>
                            </field_body>
```
```
    <index entries=""></index>
    <desc desctype="clicommand" domain="" noindex="False" objtype="clicommand">
        <desc_signature first="False" ids="cognitiveservices\ list"><desc_addname xml:space="preserve">cognitiveservices list</desc_addname></desc_signature>
        <desc_content>
            <field_list>
                    **<field_name>Deprecated</field_name>**
                    <field_body>
                        <paragraph>This command has been deprecated and will be removed in a future release. Use ‘az cognitiveservices account list’ instead.</paragraph>
                    </field_body>
                </field>


```

**Comment by sptramer** [comment]
Related to #1264 - @tjprescott this should be handled in a similar way.

**Comment by tjprescott** [comment]
@dend do you have a repo for this?

**Comment by sptramer** [comment]
@dend Checking in on this issue since it has been open for 6 months.

**Comment by sptramer** [comment]
This has been filed as an officialrequest with the devrel feature team, so closing this.
