### ISSUE TITLE
No mention of python 3.7.x compatibility

### ISSUE THREAD

**Issue by marstr** [MicrosoftDocs/azure-docs-cli#1270]
> In Azure/azure-cli#6745 @smereczynski says:
> On Mac (using homebrew) azure-cli is installed with Python 3.7 (as for 08.07.2018). It worls but there is no clear information in repo and documentation about compatibility with 3.7.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d09ed623-c83f-6bae-639e-a5f9a31fe3bb
* Version Independent ID: c5d0d722-aacd-47a3-3fcf-982c02c4d0e9
* Content: [Install the Azure CLI for macOS](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-macos?view=azure-cli-latest)
* Content Source: [docs-ref-conceptual/install-azure-cli-macos.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/install-azure-cli-macos.md)
* Product: **azure**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment]
Fixed in #1305.
