### ISSUE TITLE
Nonsense login mechanism

### ISSUE THREAD

**Issue by DoychinDoychev** [MicrosoftDocs/azure-docs-cli#1281]
Hi there,

I've spent over 2 hours on this and so far there is no clear solution.

I've pulled microsoft/iotedgedev from docker and followed https://github.com/Azure/iotedgedev (step 3) &gt; iotedgedev init which as you can imagine requires me to authenticate. 

So, I came here and I read "If the CLI can open your default browser, it will do so and load a sign-in page." which is not applicable in my case simply because the container doesn't run gui. So i figured let's try "az login -u myAzurePortalUsername", entered my password and it tells me "Get Token request returned http error: 400 and server response: {"error":"invalid_grant","error_description":"AADSTS50034: The user account does not exist in the MY_DIRECTORY directory."

I've been spinning in circles for something as basic as cli login. 

Please help

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d884a3fe-07cf-e518-085d-602425fe2480
* Version Independent ID: 1636994b-e193-74e2-9936-a07e43913326
* Content: [Run Azure CLI in a Docker Container](https://docs.microsoft.com/en-us/cli/azure/run-azure-cli-docker?view=azure-cli-latest)
* Content Source: [docs-ref-conceptual/run-azure-cli-docker.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/run-azure-cli-docker.md)
* Product: **azure**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by mathieu-benoit** [comment]
The recommendation could be to use this approach: https://docs.microsoft.com/en-us/cli/azure/authenticate-azure-cli?view=azure-cli-latest#sign-in-with-a-service-principal

**Comment by sptramer** [comment]
@DoychinDoychev If you will be using interactive logins, simply use `az login`. This will present you with a token that you can use to log in with via a website, and supports using Microsoft accounts and other accounts with 2FA:

```
az login
```

If you are intending to automate a process using the docker container, please follow @mathieu-benoit's advice to set up a service principal. See the [Create an Azure service principal with the Azure CLI](https://docs.microsoft.com/en-us/cli/azure/create-an-azure-service-principal-azure-cli?view=azure-cli-latest) documentation, or [use the portal](https://docs.microsoft.com/en-us/azure/active-directory/develop/howto-create-service-principal-portal).
