### ISSUE TITLE
adding apt gpg key fails - No keyserver available

### ISSUE THREAD

**Issue by trstn70** [MicrosoftDocs/azure-docs-cli#1290]
I try to install az cli tool via apt on Ubuntu 1804 by:
https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-apt?view=azure-cli-latest

Adding the gpg key fails:
sudo apt-key --keyring /etc/apt/trusted.gpg.d/Microsoft.gpg adv      --keyserver packages.microsoft.com      --recv-keys BC528686B50D79E339D3721CEB3E94ADBE1229CF
Executing: /tmp/apt-key-gpghome.7euFB6xM79/gpg.1.sh --keyserver packages.microsoft.com --recv-keys BC528686B50D79E339D3721CEB3E94ADBE1229CF
gpg: keyserver receive failed: No keyserver available

Access is possible:
telnet packages.microsoft.com 80
Trying 13.80.10.205...
Connected to apt-wu-d.cloudapp.net.
Escape character is '^]'.
^CConnection closed by foreign host.

telnet packages.microsoft.com 443
Trying 13.80.10.205...
Connected to apt-wu-d.cloudapp.net.
Escape character is '^]'.

**Comment by sptramer** [comment]
Not the only report of a keyserver failure, will investigate but likely a temporary infrastructure problem.

**Comment by sptramer** [comment]
On a fresh Ubuntu install (running `ubuntu:latest` in a container):

```
root@291c72d02316:/# sudo apt-key --keyring /etc/apt/trusted.gpg.d/Microsoft.gpg adv \
>      --keyserver packages.microsoft.com \
>      --recv-keys BC528686B50D79E339D3721CEB3E94ADBE1229CF
Executing: /tmp/apt-key-gpghome.CFyJHTj64V/gpg.1.sh --keyserver packages.microsoft.com --recv-keys BC528686B50D79E339D3721CEB3E94ADBE1229CF
gpg: key EB3E94ADBE1229CF: public key "Microsoft (Release signing) <gpgsecurity@microsoft.com>" imported
gpg: Total number processed: 1
gpg:               imported: 1
```

Looks like the keyserver issue was temporary. Please try getting the key again and reopen this issue if the error still occurs, along with some configuration information, including if you are behind a proxy that may block the keyserver.

**Comment by SteveBurkettNZ** [comment]
Am here as was getting a **gpg: keyserver receive failed: Connection timed out** error earlier when trying to install AzureCLI on my WSL 1809 install (with Ubuntu 18.04, no web proxy).

Managed to work around it with:

`wget https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb`
`sudo dpkg -i packages-microsoft-prod.deb`
`sudo apt-get update`

That package seems to install the GPG key as part of its install.

**Comment by shweta-sah** [comment]
@SteveBurkettNZ Your workaround worked like a charm!

**Comment by elliot-resdiary** [comment]
Also seeing this error **gpg: keyserver receive failed: Connection timed out** when running `sudo gpg --keyserver packages.microsoft.com --recv-keys 52E16F86FEE04B979B07E28DB02C46DF417A0893` in cloud-init.

**Comment by etiennetremel** [comment]
@elliot-resdiary the following command seems to do the trick:
```
$ gpg --keyserver https://packages.microsoft.com/keys/microsoft.asc --recv-keys BC528686B50D79E339D3721CEB3E94ADBE1229CF
```
