### ISSUE TITLE
npm package option?

### ISSUE THREAD

**Issue by jpsear** [MicrosoftDocs/azure-docs-cli#1292]
As much as I love homebrew, it would be nice to have an OS-agnostic supported version of this that can be distributed with projects.

For example, I would like to have the Azure CLI available as a `devDependency` in the package.json of an Azure Function, so I can write npm deployment scripts.

The only other option I have is using `serverless`, but the local testing functionality is just not up to scratch :(

**Comment by sptramer** [comment]
If you would like to suggest NPM as a distribution alternative, please [file a feature request](https://github.com/azure/azure-cli/issues).
