### ISSUE TITLE
Add example to show most common output situation

### ISSUE THREAD

**Issue by markgar** [MicrosoftDocs/azure-docs-cli#1312]
Nearly all calls to the Azure CLI return an unnamed array of records.  This example doesn't show that situation.  Can I suggest adding a sample that shows how to us az account list to filter on where isDefault is true and display the account name?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e60c12ef-d293-5626-c7aa-c7e9241bf975
* Version Independent ID: 7acca1dd-b735-7e1f-afd9-2b5b6ea06b1c
* Content: [Query command results with Azure CLI](https://docs.microsoft.com/en-us/cli/azure/query-azure-cli?view=azure-cli-latest)
* Content Source: [docs-ref-conceptual/query-azure-cli.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/query-azure-cli.md)
* Product: **azure**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment]
This is actually covered in the article already, under the [get properties in an array](https://docs.microsoft.com/en-us/cli/azure/query-azure-cli?view=azure-cli-latest#get-properties-in-an-array) heading. If you need a more detailed example, see the [JMESPath homepage](http://jmespath.org/).
