### ISSUE TITLE
Dependencies handled manually

### ISSUE THREAD

**Issue by pemj** [MicrosoftDocs/azure-docs-cli#1316]
Typically, a .deb package file defines the dependencies for that package. You can usually find those dependencies by running apt-cache depends &lt;package-name&gt;. If you run that against azure-cli like so:
'apt-cache depends azure-cli'
you get a list of dependencies that looks something like this:
azure-cli
    Depends: libc6
    Depends: libssl1.0.0

Step 1, "install prerequisite packages" lists a separate list of dependencies. Is there a reason that "apt-transport-https lsb-release software-properties-common dirmngr" aren't included in the list of dependencies in the .deb package?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe1526a9-7f22-504e-484c-0f3edc11b178
* Version Independent ID: c5dec108-efcd-aa77-04b5-803b6b894dba
* Content: [Install the Azure CLI on Linux with apt](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-apt?view=azure-cli-latest)
* Content Source: [docs-ref-conceptual/install-azure-cli-apt.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/install-azure-cli-apt.md)
* Product: **azure**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment]
The listed prerequisites are prerequesites for the installation steps. Not every Debian-based distribution has the `apt` tools used in these instructions installed.
