### ISSUE TITLE
The current version of the CLI is 2.0.58.

### ISSUE THREAD

**Issue by way2arun** [MicrosoftDocs/azure-docs-cli#1322]
the document is referring to 2.0.58 but the latest version coming through msi installer is 2.0.59 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8246b90a-efb1-03ce-f642-d3eb2441fc30
* Version Independent ID: 2fdd20ef-7bd3-57bc-7957-93f4bb5377ce
* Content: [Install the Azure CLI for Windows](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-windows?view=azure-cli-latest)
* Content Source: [docs-ref-conceptual/install-azure-cli-windows.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/install-azure-cli-windows.md)
* Product: **azure**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment]
Documentation is published on the site at 3PM. Release notes have been updated, but we'll work to get the site updates happening concurrently with CLI releases from now on.
