### ISSUE TITLE
install on server core

### ISSUE THREAD

**Issue by bospoort** [MicrosoftDocs/azure-docs-cli#1324]
would be great to have instructions to install from the command line (e.g. server core). that would include the link to the msi. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8246b90a-efb1-03ce-f642-d3eb2441fc30
* Version Independent ID: 2fdd20ef-7bd3-57bc-7957-93f4bb5377ce
* Content: [Install the Azure CLI for Windows](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-windows?view=azure-cli-latest)
* Content Source: [docs-ref-conceptual/install-azure-cli-windows.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/install-azure-cli-windows.md)
* Product: **azure**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment]
@bospoort This would be considered an advanced installation method, which we don't cover on the install documentation currently. If you want to install via CMD, then you can use the standard [msiexec](https://docs.microsoft.com/en-us/windows/desktop/Msi/command-line-options) command.

**Comment by EdiWang** [comment]
@bospoort I believe you can install on server core via choco here: https://chocolatey.org/packages/azure-cli
