### ISSUE TITLE
RaspberryPi

### ISSUE THREAD

**Issue by drwill-ms** [MicrosoftDocs/azure-docs-cli#1326]
This works on a RaspberryPi except for the hardcoded processor architecture of amd64. When I ran that, I got an error "/usr/bin/az: line 2: /opt/az/bin/python3: cannot execute binary file: Exec format error".

We should update the step to indicate the right processor architecture for your linux target.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe1526a9-7f22-504e-484c-0f3edc11b178
* Version Independent ID: c5dec108-efcd-aa77-04b5-803b6b894dba
* Content: [Install the Azure CLI on Linux with apt](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-apt?view=azure-cli-latest)
* Content Source: [docs-ref-conceptual/install-azure-cli-apt.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/install-azure-cli-apt.md)
* Product: **azure**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment]
@tjprescott Do we currently offer an ARM package for the CLI, or is this also a feature request?

**Comment by tjprescott** [comment]
No, we don't.
https://github.com/Azure/azure-cli/issues/7368

**Comment by sptramer** [comment]
@drwill-ms It looks like ARM packages are still a feature request at this point. You should follow the issue linked by @tjprescott above, and see when they're made available. At that time I'll update the documentation to take processor architecture into account.

**Comment by stefanzvonar** [comment]
Am receiving this same error on a Raspberry Pi 3 B+ (Arm64).  Any advice on how to get past this?

`pi@raspberrypi:~ $ az login
/usr/bin/az: line 2: /opt/az/bin/python3: cannot execute binary file: Exec format error
`
Using steps in doco:
https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-apt?view=azure-cli-latest


Am trying to create basic iotedge image recognition, with the raspberry pi.  Essentially this lab:  https://dev.to/azure/creating-an-image-recognition-solution-with-azure-iot-edge-and-azure-cognitive-services-4n5i

**Comment by sptramer** [comment]
@stefanzvonar As I mentioned above on this thread, there are no arm64 binaries. The install page will be updated when some are available.

**Comment by Joseluismantilla** [comment]
I created a few minutes another thread for ARM binaries due to those are boards for developers, it would be unacceptable don't have it the cli.

**Comment by Philmon22** [comment]
The libraries have been release for .NET core 3.0.  https://docs.microsoft.com/en-us/dotnet/core/linux-prerequisites?tabs=netcore30. I have installed the dotnet 3 on the raspberry pi, but the client states I need dotnet core 2.1.

**Comment by codepoet80** [comment]
Another vote for Raspberry Pi binaries, please. The NodeJS samples are broken, and without the CLI, the Python Quickstart is useless too. The Pi has to be the most common IOT device out there...

**Comment by markvogt** [comment]
HERE IT IS MAY 2020... 
... and while the RaspberryPi (I used RPi4) is far-and-AWAY the MOST POPULAR "Edge Device" on the PLANET... 
... MICROSOFT (yeah - the "Microsoft <heart> Linux" Microsoft) still HASN'T created an AzureCLI with binaries for the RPi4's ARM64 architecture. 

WHAT WILL IT TAKE Microsoft ????? 

FYI, I TRIED the github.com project from 2 years ago, and it WORKS, but it's MISSING the command "az webapp up" that I NEEDED to deploy new API Apps to the Azure Cloud Services, so THAT option is a BUST as well :-( ... 

BACK to coding Python on my WINDOWS 10 laptop - BUMMER...

**Comment by Philmon22** [comment]
I have azure kicking off a Jenkins job on my pi so i guess I am fine with it.

**Comment by dbradish-microsoft** [comment]
@fengzhou-msft , is "an AzureCLI with binaries for the RPi4's ARM64 architecture." in the backlog, or has this CLI product request been delivered in a different way?

**Comment by fengzhou-msft** [comment]
@dbradish-microsoft it's tracked here: https://github.com/Azure/azure-cli/issues/7368
