### ISSUE TITLE
gpg: keyserver receive failed: No dirmngr

### ISSUE THREAD

**Issue by docgregt** [MicrosoftDocs/azure-docs-cli#1329]
Problem with ubuntu installed from Windows 10 setup:
sudo apt-key --keyring /etc/apt/trusted.gpg.d/Microsoft.gpg adv      --keyserver packages.microsoft.com      --recv-keys BC528686B50D79E339D3721CEB3E94ADBE1229CF
Executing: /tmp/apt-key-gpghome.TAkAqlbJN0/gpg.1.sh --keyserver packages.microsoft.com --recv-keys BC528686B50D79E339D3721CEB3E94ADBE1229CF
gpg: connecting dirmngr at '/tmp/apt-key-gpghome.TAkAqlbJN0/S.dirmngr' failed: IPC connect call failed
gpg: keyserver receive failed: No dirmngr

sudo apt-get install dirmngr does not work as it is already installed. Uninstalling and reinstalling does not help.

I solved it by using following:
curl -SL "http://keyserver.ubuntu.com/pks/lookup?op=get&search=0xEB3E94ADBE1229CF" | sudo apt-key add

This was on a fairly clean install.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe1526a9-7f22-504e-484c-0f3edc11b178
* Version Independent ID: c5dec108-efcd-aa77-04b5-803b6b894dba
* Content: [Install the Azure CLI on Linux with apt](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-apt?view=azure-cli-latest)
* Content Source: [docs-ref-conceptual/install-azure-cli-apt.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/install-azure-cli-apt.md)
* Product: **azure**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by NitroAMD** [comment]
https://github.com/Microsoft/WSL/issues/3286

**Comment by sptramer** [comment]
@docgregt This issue is often seen by people running on an outdated version of Windows. Please update to at least Windows 1809 to receive the WSL fix which resolved a number of IPC problems, including those which were causing this error.

**Comment by docgregt** [comment]
I had the latest version of Windows 10 based upon Windows update at the time I reported the issue. I do not track windows versions so I don’t know if there is a newer version of windows since I reported the problem that fixes the problem. In any case the work around worked for me.

Gregory Turner
Chief Architect
________________________________________
i4 Insight, Inc.

cell: +1.720.335.1744
greg.turner@i4-insight.com<mailto:greg.turner@i4-insight.com>

A member of the Lloyd’s Register Group

**Comment by sptramer** [comment]
Can you check the version of Windows/WSL by following these instructions, and make sure that it's at least 1809? Some administered environments block updates.

https://github.com/Microsoft/WSL/issues/1728

**Comment by docgregt** [comment]
![image](https://user-images.githubusercontent.com/43346207/54625856-ae546780-4a35-11e9-82aa-acca3a66a6a9.png)

Looks like I have 1803 and there is no admin that blocks my updates. I do not know why Windows Update has not given me the latest. Maybe it is a Dell thing.

What I read on numerous blogs was that it was a linux bug and someone needs to fix the linux bug so I don't think updating Windows will matter, but you would know that better than me.

**Comment by sptramer** [comment]
It might be a Linux bug, but there were definitely WSL bugs related to IPC that were fixed in 1809. I wonder why that version isn't available for you, it was the Windows Fall Creator update, and tagged as installed on 10/1/18 on my machine.

It might be the case that you need to update manually (which would be recommended, for the security fixes.) Follow the Windows 10 October update instructions: https://support.microsoft.com/en-us/help/4028685/windows-10-get-the-update

I'd be curious to hear if you're able to get the current Ubuntu install instructions to work if you're able to successfully upgrade to 1809.

**Comment by githnt** [comment]
Hi,
I have Windows 10.0.17134, WSL 1 and Ubuntu 18.04 (bionic). Does it mean that there is no way to make it work on this configuration? I keep getting the error:
-----
gpg: connecting dirmngr at '/tmp/apt-key-gpghome.ljJpIgUmcc/S.dirmngr' failed: IPC connect call failed
gpg: keyserver receive failed: No dirmngr
-----
