### ISSUE TITLE
Az login --service-principal does not support keys that contain sepecial characters

### ISSUE THREAD

**Issue by SamirFarhat** [MicrosoftDocs/azure-docs-cli#1333]
Is this a Bug or a missing note.
When making Az login --service-principal and use an SPN key that contains special characters (Example:  L;#d:$!D&gt;s?&}=$&gt;=%:?{;$-[p$1%@]!|!*[#8/{^^/[&gt;$_}&gt;), i receive the following error:

The filename, directory name, or volume label syntax is incorrect.
The system cannot find the path specified

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93174b3a-3e97-8304-83fc-807be75198fe
* Version Independent ID: 1155045b-ce8c-2def-7b0e-043283f8be01
* Content: [Sign in with the Azure CLI](https://docs.microsoft.com/en-us/cli/azure/authenticate-azure-cli?view=azure-cli-latest)
* Content Source: [docs-ref-conceptual/authenticate-azure-cli.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/authenticate-azure-cli.md)
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment]
@SamirFarhat Make sure that your SPN key is properly quoted and escaped for your operating system. For an `sh`-compatible shell like `bash`, this would mean putting the key name in single quotes (and escaping any single quotes inside of the key.)

If correctly quoting the key still doesn't work, this may be a product issue, but your error message indicates that it's a result of the shell trying to interpret your key as a file path.

**Comment by SamirFarhat** [comment]
Finally, it worked when the password is quoted  between ' ' and not " ".
Thanks
