### ISSUE TITLE
Installation via chocolatey is missing

### ISSUE THREAD

**Issue by Leon99** [MicrosoftDocs/azure-docs-cli#1342]
Linux installation guides use a package manager. Why Windows' installation experience can't be the same?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8246b90a-efb1-03ce-f642-d3eb2441fc30
* Version Independent ID: 2fdd20ef-7bd3-57bc-7957-93f4bb5377ce
* Content: [Install the Azure CLI for Windows](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-windows?view=azure-cli-latest)
* Content Source: [docs-ref-conceptual/install-azure-cli-windows.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/install-azure-cli-windows.md)
* Product: **azure**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment]
The chocolatey package for Azure CLI is not officially maintained by Microsoft, and so is not a documented installation method.

**Comment by Leon99** [comment]
Ok then why do you maintain macOS/Linux versions  of the packages installable via package managers but not the Windows one? Am I wrong in thinking that Microsoft supposed to back their own products? Using GUI to install a CLI doesn't make much sense.

**Comment by sptramer** [comment]
If you'd like to see an official Chocolatey package, file a feature request with engineering: https://github.com/azure/azure-powershell/issues
