### ISSUE TITLE
Url to packages is incorrect on Ubuntu

### ISSUE THREAD

**Issue by srrengar** [MicrosoftDocs/azure-docs-cli#1345]
I am using the Ubuntu subsystem on Linux. The correct path is http://packages.microsoft.com/repos/azure-cli/dists/bionic/main/ but the path used in the instructions with excluded "dists" in the url

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe1526a9-7f22-504e-484c-0f3edc11b178
* Version Independent ID: c5dec108-efcd-aa77-04b5-803b6b894dba
* Content: [Install the Azure CLI on Linux with apt](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-apt?view=azure-cli-latest#feedback)
* Content Source: [docs-ref-conceptual/install-azure-cli-apt.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/install-azure-cli-apt.md)
* Product: **azure**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment]
The path that you reference isn't a URL, it's a repository description. These descriptions are used by the Ubuntu package manager, which automatically examines the `dists/${platform}/main` URL to find packages to install.
