### ISSUE TITLE
How to loop each value in the returned result?

### ISSUE THREAD

**Issue by imeya** [MicrosoftDocs/azure-docs-cli#1358]
I have a such cli command which would return a json format, like below:

az acr repository list -n xxxx

![cli](https://user-images.githubusercontent.com/25738099/54596496-bcbf7500-4a6f-11e9-9916-9d663e798309.JPG)

I want to echo each of the item in the results which is in json format(or anyother format like table, tsv), and I try use a variable, then use for to try to echo each of the item, but it just echo the json totally.

![cli3](https://user-images.githubusercontent.com/25738099/54596814-630b7a80-4a70-11e9-83a3-ee9551207112.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b233e045-b444-e6d9-7893-36a72ee4a70b
* Version Independent ID: f2c47d3a-4976-ebe4-e732-e7c18dd4bed8
* Content: [Overview of the Azure CLI](https://docs.microsoft.com/en-us/cli/azure/?view=azure-cli-latest)
* Content Source: [docs-ref-conceptual/index.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/index.md)
* Product: **azure**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment]
Use the `-o tsv` format which produces output separated by whitespace and newlines, which is friendly to shell commands like looping or `xargs`. JSON output is always considered a single string emitted to `stdio` and without a JSON parser, you cannot iterate over it.
