### ISSUE TITLE
Certificate stored in keyvault doesn't work for cli - login. It should be removed from the documentation

### ISSUE THREAD

**Issue by koroseman** [MicrosoftDocs/azure-docs-cli#1360]
The following section should be removed from the documentation because when a user runs the command below, they won't be able to login and would get this error.
```python 
[('PEM routines', 'PEM_read_bio', 'no start line')]
```
The certificate created and stored on keyvault is malformed. Hence, running the command before would not achieve the goal of this doc.

~~_The --keyvault argument can be added to store the certificate in Azure Key Vault. When using --keyvault, the --cert argument is required._~~

```azurecli-interactive
az ad sp create-for-rbac --name ServicePrincipalName --create-cert --cert CertName --keyvault VaultName
```
---

~~_For certificates stored in Key Vault, retrieve the certificate's private key with [az keyvault secret show](/cli/azure/keyvault/secret#az-keyvault-secret-show). In Key Vault, the name of the certificate's secret is the same as the certificate name._~~

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3f84bdc-9ed0-eb85-f3af-9711e8083a95
* Version Independent ID: 03a47d06-5fbf-4764-0882-99cd8bd41110
* Content: [Use Azure service principals with Azure CLI](https://docs.microsoft.com/en-us/cli/azure/create-an-azure-service-principal-azure-cli?view=azure-cli-latest#feedback)
* Content Source: [docs-ref-conceptual/create-an-azure-service-principal-azure-cli.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/create-an-azure-service-principal-azure-cli.md)
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment]
@koroseman This isn't a documentation issue, but rather a bug in the CLI. The problem is that KeyVault PFX/PEM exports are in binary, which are called out in the documentation as being incompatible with the CLI. The CER exports also do not contain the `KEY START/KEY END` headers, which appear to be what this error message is referring to.

Please file a bug with the CLI team at https://github.com/azure/azure-cli/issues describing the problem.

**Comment by sptramer** [comment]
To be clear, there is a workaround to this problem: Generate your own certificate client-side, and then upload that certificate to Key Vault. You will need to hold onto the private key portion of the certificate locally, which should include the correct private key certificate headers.

**Comment by sensei-wu** [comment]
if this is a known limitation, then why is the documentation not updated? (I just raised it in SO before noticing this thread https://stackoverflow.com/questions/61802199/azure-login-with-service-principal-using-certificate-from-keyvault)

**Comment by carlowahlstedt** [comment]
If someone lands here in the future, here's a quick discussion that got me going: https://github.com/Azure/azure-cli/issues/7489
