### ISSUE TITLE
given example is not working

### ISSUE THREAD

**Issue by dlenin** [MicrosoftDocs/azure-docs-cli#1363]
az find -q secret is not working in cli  without -q option its working.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c268a98-afcb-d2c2-87c7-880d52900533
* Version Independent ID: 4c835da4-38bc-22a8-67b4-dd522adcc0e3
* Content: [Get started with Azure CLI](https://docs.microsoft.com/en-us/cli/azure/get-started-with-azure-cli?view=azure-cli-latest)
* Content Source: [docs-ref-conceptual/get-started-with-azure-cli.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/get-started-with-azure-cli.md)
* Product: **azure**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment]
@dlenin Thanks for the report, this was a change in the CLI that the documentation has not been updated for.

**Comment by sptramer** [comment]
This should be fixed in today's publish.
