### ISSUE TITLE
How can I use azure cli and authenticate it in my .NET application which was using ARM template deployment 

### ISSUE THREAD

**Issue by anushreeringne** [MicrosoftDocs/azure-docs-cli#1365]
I have a .NET application which uses a AuthToken and makes ARM requests to Azure to create my Resources.
Can I write a powershell script using az cli and then call it from within my .NET application?
How will I authenticate in that case to az cli?
Can you please show some examples?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93174b3a-3e97-8304-83fc-807be75198fe
* Version Independent ID: 1155045b-ce8c-2def-7b0e-043283f8be01
* Content: [Sign in with the Azure CLI](https://docs.microsoft.com/en-us/cli/azure/authenticate-azure-cli?view=azure-cli-latest)
* Content Source: [docs-ref-conceptual/authenticate-azure-cli.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/authenticate-azure-cli.md)
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment]
If you are trying to interact with Azure from within a .NET application, you should not spawn a subprocess calling the CLI. Instead, you should use the [Azure .NET SDK](https://docs.microsoft.com/en-us/dotnet/azure/).
