### ISSUE TITLE
Is there a auto update option available ? 

### ISSUE THREAD

**Issue by akramwaseem** [MicrosoftDocs/azure-docs-cli#1370]
Hi,
Wondering if there is an auto update option available tp update az to latest version ? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d09ed623-c83f-6bae-639e-a5f9a31fe3bb
* Version Independent ID: c5d0d722-aacd-47a3-3fcf-982c02c4d0e9
* Content: [Install the Azure CLI for macOS](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-macos?view=azure-cli-latest)
* Content Source: [docs-ref-conceptual/install-azure-cli-macos.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/install-azure-cli-macos.md)
* Product: **azure**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by coreygo** [comment]
Hi @akramwaseem, 

It seems the [brew recipe for Azure CLI](https://github.com/Homebrew/homebrew-core/blob/master/Formula/azure-cli.rb) does not have `auto_updates true` set; so Azure CLI on MacOS likely needs to be updated using whatever Homebrew update mechanism you prefer.

If you don't have some Homebrew upgrade automation already (there's a few options and discussion on GitHub) you can upgrade Azure CLI only by setting a cron job to run `brew update && brew upgrade azure-cli`.

Regards,
Corey

**Comment by akramwaseem** [comment]
@coreygo -- got it. thanks.
