### ISSUE TITLE
Docker container is not available as per the documentation 

### ISSUE THREAD

**Issue by kgopi05** [MicrosoftDocs/azure-docs-cli#1381]
docker run -it microsoft/azure-cli:0.10.17
Unable to find image 'microsoft/azure-cli:0.10.17' locally
docker: Error response from daemon: manifest for microsoft/azure-cli:0.10.17 not found.
See 'docker run --help'.
i tried with version 0.10.14 and able to launch the docker container . 

But still i'm unable to manage the Azure Classic vm's from this cli .

**Comment by sptramer** [comment]
@kgopi05 The docker container is now hosted on an Azure ACR, and [the documentation](https://docs.microsoft.com/en-us/cli/azure/run-azure-cli-docker) has been updated to reflect this. The Azure classic CLI is not part of the Docker container. If you would like it to be published as part of it, please file a ticket with engineering: https://github.com/azure/azure-cli/issues
