### ISSUE TITLE
Example for logging in with service principal and avoid displaying your password is not working.

### ISSUE THREAD

**Issue by LioDiera** [MicrosoftDocs/azure-docs-cli#1391]
The example for logging in with service principal and avoid displaying your password does not seem to work. 
$AzCred = Get-Credential -UserName &lt;app-url&gt;
az login -u $AzCred.UserName -p $AzCred.GetNetworkCredential().Password --tenant &lt;tenant&gt;

This is what is working for me. 
$AzCred = Get-Credential -UserName &lt;AppID&gt;
az login --service-principal -t &lt;tenantID&gt; -u $AzCred.UserName -p $AzCred.GetNetworkCredential().Password

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93174b3a-3e97-8304-83fc-807be75198fe
* Version Independent ID: 1155045b-ce8c-2def-7b0e-043283f8be01
* Content: [Sign in with the Azure CLI](https://docs.microsoft.com/en-us/cli/azure/authenticate-azure-cli?view=azure-cli-latest#feedback)
* Content Source: [docs-ref-conceptual/authenticate-azure-cli.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/authenticate-azure-cli.md)
* Technology: **azure-cli**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment]
Thanks for the feedback, this document hasn't been updated since the introduction of the `--service-principal` flag.

**Comment by sptramer** [comment]
This should be fixed in today's publish.
