### ISSUE TITLE
How to create the certificate for Azure CLI

### ISSUE THREAD

**Issue by sujith3g** [MicrosoftDocs/azure-docs-cli#1393]
The documentation is not clear enough, for someone to create a certificate and login with service principal. Which key file to use? 
How should someone create the certificate file and use it with a service principal? I've tried with `.crt & .pfx ` file and it is throwing the following error

```
[('PEM routines', 'PEM_read_bio', 'no start line')]
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3f84bdc-9ed0-eb85-f3af-9711e8083a95
* Version Independent ID: 03a47d06-5fbf-4764-0882-99cd8bd41110
* Content: [Use Azure service principals with Azure CLI](https://docs.microsoft.com/en-us/cli/azure/create-an-azure-service-principal-azure-cli?view=azure-cli-latest)
* Content Source: [docs-ref-conceptual/create-an-azure-service-principal-azure-cli.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/create-an-azure-service-principal-azure-cli.md)
* Technology: **azure-cli**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment]
@sujith3g I recently answered this question in another comment thread: https://github.com/MicrosoftDocs/azure-docs-cli/issues/1360

It seems like there is a CLI bug regarding processing PEM/CER base64-encoded files which are missing the PEM header, and the key without headers is what is exported by Azure Key Vault. Right now the workaround would be to generate your own certificate client-side, upload that to Key Vault, and use your local PEM.
