### ISSUE TITLE
Package 'gpg' has no installation candidate

### ISSUE THREAD

**Issue by edemen** [MicrosoftDocs/azure-docs-cli#1397]
Section Install point 1 produces error on Ubuntu 16.04.4 LTS:
&gt; Package 'gpg' has no installation candidate
Change 'gpg' to 'gnupg' or make a note of it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe1526a9-7f22-504e-484c-0f3edc11b178
* Version Independent ID: c5dec108-efcd-aa77-04b5-803b6b894dba
* Content: [Install the Azure CLI on Linux with apt](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-apt?view=azure-cli-latest#feedback)
* Content Source: [docs-ref-conceptual/install-azure-cli-apt.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/install-azure-cli-apt.md)
* Product: **azure**
* Technology: **azure-cli**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment]
Will be fixed on the next site publish.
