### ISSUE TITLE
Upgrade problem 

### ISSUE THREAD

**Issue by mlonexus** [MicrosoftDocs/azure-docs-cli#1410]
I have 2.0.29 installed and want to upgrade to 2.0.62, but as I dont have the 2.0.29 msi I cannot uninistall and upgrade. Now I'm stuck :(

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8246b90a-efb1-03ce-f642-d3eb2441fc30
* Version Independent ID: 2fdd20ef-7bd3-57bc-7957-93f4bb5377ce
* Content: [Install the Azure CLI for Windows](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-windows?view=azure-cli-latest#feedback)
* Content Source: [docs-ref-conceptual/install-azure-cli-windows.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/install-azure-cli-windows.md)
* Product: **azure**
* Technology: **azure-cli**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment]
You can always download the latest MSI to install over a previous version. Additionally, you do not need an MSI to uninstall: You can also uninstall from the "Apps & Features" pane in settings. The application to remove is "Microsoft CLI 2.0 for Azure". The uninstall instructions will be updated to reflect this.

**Comment by sptramer** [comment]
This will be fixed at the next documentation site publish.
