### ISSUE TITLE
Markdown table

### ISSUE THREAD

**Issue by twem** [MicrosoftDocs/azure-docs-cli#1416]
Could you add the option to output in markdown table not just ASCII table.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 48273ba7-da5a-95f0-7ffc-8c6d5282313d
* Version Independent ID: 83d348f9-fd1f-1041-0304-d8634e5526d4
* Content: [Output formats for Azure CLI](https://docs.microsoft.com/en-us/cli/azure/format-output-azure-cli?view=azure-cli-latest#feedback)
* Content Source: [docs-ref-conceptual/format-output-azure-cli.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/format-output-azure-cli.md)
* Product: **azure**
* Technology: **azure-cli**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment]
This is a feature request, please file an issue with the engineering team: https://github.com/azure/azure-cli/issues
