### ISSUE TITLE
Document az cli bot V4 release (breaking) changes

### ISSUE THREAD

**Issue by scheyal** [MicrosoftDocs/azure-docs-cli#1423]
We've introduced a few changes that impact the usage behavior of az bot cli. We need to document those changes. The proposal is to document it closest to where the tool usage is being mentioned e.g. Deploy your bot to Azure section.
Changes from Previous Versions (preliminary, not final)
The latest release V4.5 of az bot cli command extension contains the following improvements impacting usage:
The default value for --version parameter is now v4, not v3 (except for az bot prepare-publish which is only for v3 bots).
The --lang parameter no longer defaults to Csharp. If the command requires --lang and it is not provided, the command will error out.
The --appid and --password args for az bot create are now required and can be created via az ad app create.
The az bot create -v v4 does not create or use a Storage Account or Application Insights.
Instead of mapping Application Insights regions for az bot create -v v3, the command only accepts regions where Application Insights is creatable.
The az bot update is no longer a generic update command, but instead can affect specific properties of a bot.
All --lang flags now accept and advise users to use Javascript instead of Node. Node is no longer the default --lang (but is accepted for back compatibility).
Added Typescript support to az bot prepare-deploy
The az bot prepare-deploy returns true if successful and has helpful verbose logging.
Added additional Application Insights regions to az bot create -v v3

**Comment by scheyal** [comment]
@stevengum - note issue transferred to azure-docs-cli

**Comment by sptramer** [comment]
@scheyal This is related to reference material or release notes, please refer to the Azure CLI team in charge of reference documentation: https://github.com/azure/azure-cli/issues
