### ISSUE TITLE
AZ_REPO value in ubuntu

### ISSUE THREAD

**Issue by miccioest** [MicrosoftDocs/azure-docs-cli#1430]
this line in step 3 set AZ_REPO as "disco"  
AZ_REPO=$(lsb_release -cs)
disco does not exist in https://packages.microsoft.com/repos/azure-cli/dists/
I had to set manually AZ_REPO to "bionic", then I could run the next steps without problems.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe1526a9-7f22-504e-484c-0f3edc11b178
* Version Independent ID: c5dec108-efcd-aa77-04b5-803b6b894dba
* Content: [Install the Azure CLI on Linux with apt](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-apt?view=azure-cli-latest#feedback)
* Content Source: [docs-ref-conceptual/install-azure-cli-apt.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/install-azure-cli-apt.md)
* Product: **azure**
* Technology: **azure-cli**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by marstr** [comment]
A request has been issued to publish 2.0.63 to a newly minted `disco` repository. The package should be available later today. Also, our release infrastructure has been updated so future versions are automatically pushed to this repository.

**Comment by sptramer** [comment]
@marstr Is `disco` now a supported distribution, and should the officially supported distribution list be updated?

**Comment by marstr** [comment]
Yes! This package is now available and supported. Thanks for closing the loop, @sptramer.

**Comment by sptramer** [comment]
This will be updated at the next live site publish.
