### ISSUE TITLE
How to update Azure CLI if expired / bad key

### ISSUE THREAD

**Issue by imcdnzl** [MicrosoftDocs/azure-docs-cli#1445]
If an Ubuntu / Debian machine won't update due to the following error (e.g. expired key):

The following signatures couldn't be verified because the public key is not available: NO_PUBKEY

Then this fixes it:
curl -L https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -

It would be useful to add this to https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-apt under the Update section

**Comment by imcdnzl** [comment]
Though re-reading the original page it might be best just to point to step 3 of installation earlier as gpg is being referenced (not entirely sure why)

**Comment by sptramer** [comment]
@imcdnzl There used to be a reference to requiring a key update on this page due to a GPG signing change, but as the key was updated over 1 year ago, this notice was recently removed.

**Comment by imcdnzl** [comment]
@sptramer - it was on a machine I must admit I hadn't used in a long time. I guess most people would eventually work it out. Took me about 5 minutes to find it
