### ISSUE TITLE
How do I install the previous version of a azure-cli on Mac

### ISSUE THREAD

**Issue by akramwaseem** [MicrosoftDocs/azure-docs-cli#1454]
Hi,
I am having issues with my current version of azure-cli and I am trying to figure out a way to move back to the old version, is there a way it can be done. I dont see it on the documentation above.
Please update the documentation 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d09ed623-c83f-6bae-639e-a5f9a31fe3bb
* Version Independent ID: c5d0d722-aacd-47a3-3fcf-982c02c4d0e9
* Content: [Install the Azure CLI for macOS](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-macos?view=azure-cli-latest#feedback)
* Content Source: [docs-ref-conceptual/install-azure-cli-macos.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/install-azure-cli-macos.md)
* Product: **azure**
* Technology: **azure-cli**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment]
Please follow the [homebrew instructions for using a previous version](https://docs.brew.sh/Tips-N%27-Tricks#installing-previous-versions-of-formulae). If an earlier version is not available, Homebrew offers the [brew extract](https://github.com/Homebrew/brew/pull/4563) command.
