### ISSUE TITLE
Update "Sign in with credentials on the command line" section to address bug when using short argument (-p) and password beginning with a - (hyphen)

### ISSUE THREAD

**Issue by richardspitz** [MicrosoftDocs/azure-docs-cli#1456]
Python bug affecting az login user experience when password starts with a - (hyphen)
https://github.com/Azure/azure-cli/issues/7054

Solution: Add this to the "Sign in with credentials on the command line" section

When using a password that beings with a - (hyphen) and the short argument for the password (-p), the "expected one argument" error will occur. Use the long argument (--password) and the assignment operator to work around this.

Example:
az login --username=azureUserName@contoso.com --password=-azurePassword

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93174b3a-3e97-8304-83fc-807be75198fe
* Version Independent ID: 1155045b-ce8c-2def-7b0e-043283f8be01
* Content: [Sign in with the Azure CLI](https://docs.microsoft.com/en-us/cli/azure/authenticate-azure-cli?view=azure-cli-latest)
* Content Source: [docs-ref-conceptual/authenticate-azure-cli.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/authenticate-azure-cli.md)
* Technology: **azure-cli**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment]
This is because the shell considers any non-quoted string starting with a `-` to be an argument passed to the processor, which in the case of `-p -azurePassword` results in the command trying to resolve an empty `-p` argument, and a `-a` argument with the value of `zurePassword`. The correct way to pass a string beginning with a `-` token is to quote it, as `-p '-azurePassword'`.

Also, please note that the `--user/--password` authentication method is deprecated and will be removed in a future release.

**Comment by richardspitz** [comment]
![Capture](https://user-images.githubusercontent.com/15606759/57946986-86954a80-7892-11e9-8ee9-260eb087dd5b.JPG)

**Comment by sptramer** [comment]
Is this is the case, then this is a bug and non-standard behavior for a CLI tool. Please [file a bug report](https://github.com/azure/azure-cli/issues).

**Comment by richardspitz** [comment]
The bug already exists, with no path to fix it https://github.com/Azure/azure-cli/issues/7054

What I want to achieve here is a doc update pointing to the workaround, as mentioned in the original comment on this issue https://github.com/MicrosoftDocs/azure-docs-cli/issues/1456#issue-444554881
