### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by v-wilock** [MicrosoftDocs/azure-docs-cli#1459]
mcr.microsoft.com/azure-cli redirects me to the generic page https://azure.microsoft.com/en-us/services/container-registry/. This page tells me about how I should sign up for a container registry rather than anything specific to Azure CLI.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d884a3fe-07cf-e518-085d-602425fe2480
* Version Independent ID: 1636994b-e193-74e2-9936-a07e43913326
* Content: [Run Azure CLI in a Docker Container](https://docs.microsoft.com/en-us/cli/azure/run-azure-cli-docker?view=azure-cli-latest#feedback)
* Content Source: [docs-ref-conceptual/run-azure-cli-docker.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/run-azure-cli-docker.md)
* Product: **azure**
* Technology: **azure-cli**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment]
@v-wilock This page is not intended to be loaded in a browser, since it refers to a docker container location. Use this URL with docker commands only, as described in the documentation.
