### ISSUE TITLE
Windows CLI Installer does not work as described

### ISSUE THREAD

**Issue by treefishuk** [MicrosoftDocs/azure-docs-cli#1465]
Followed instructions [here ](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-windows?view=azure-cli-latest) but having downloaded and ran the MSI I get "az is not recognized".

So either: 
a) The installer is broken
b) There are pre-requisites which the docs don't state
c) There is something to do after running the MSI which is not stated in the docs

Any help greatly appreciated

**Comment by treefishuk** [comment]
If python is installed prior to running installer it works. If python is required to be installed prior to running the MSI then the docs should ideally indicate that.

**Comment by sptramer** [comment]
@treefishuk The latest CLI version is now 2.0.66, can you try the latest MSI installer and see if it works for you?

**Comment by sptramer** [comment]
Going to close this on the advice of @marstr since there have been no updates in >1mo.

**Comment by marstr** [comment]
True, I did advise this gets closed! However @treefishuk, if you're still experiencing trouble here, please let us know.
