### ISSUE TITLE
openSUSE 42.2 lifetime

### ISSUE THREAD

**Issue by slowik21861** [MicrosoftDocs/azure-docs-cli#1469]
From OpenSUSE Wiki:

The following distributions have reached their end of life and should not be used:
openSUSE Leap 42.2 - Jan 26th 2018 - (done)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 26961ab6-af63-1bb9-53d1-566e4acc2896
* Version Independent ID: 2c26a785-ca52-321a-ba33-4622ed9d37a2
* Content: [Install the Azure CLI on Linux with zypper](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-zypper?view=azure-cli-latest)
* Content Source: [docs-ref-conceptual/install-azure-cli-zypper.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/install-azure-cli-zypper.md)
* Product: **azure**
* Technology: **azure-cli**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment]
The next site publish will add information clarifying which versions of OpenSUSE and SLES the CLI package should work on.
