### ISSUE TITLE
Azure CLI updated to 2.0.65 but Homebrew formulae is outdated

### ISSUE THREAD

**Issue by TitaniumDave** [MicrosoftDocs/azure-docs-cli#1472]
Microsoft have revised the Azure CLI to 2.0.65, but for the first time (certainly in the last 3-6 months anyway) the Azure CLI installation [page](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli?view=azure-cli-latest) has been updated, but the Homebrew **azure-cli** [Formula page](https://formulae.brew.sh/formula/azure-cli) still shows 2.0.64 so the Azure CLI releases are not at parity on Windows and macOS.

**Comment by sptramer** [comment]
@achandmsft Please publish the latest release to homebrew. Not sure what caused this issue in the release pipeline. Will close this when the correct CLI version is published.

**Comment by TitaniumDave** [comment]
Now the homebrew formula has been updated to **2.0.66** but the [Microsoft Install the Azure CLI](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli?view=azure-cli-latest) page still states that the current version is 2.0.65.

Once that is updated this can be closed. Thanks for the help!

**Comment by sptramer** [comment]
The version update only goes live at our regular publish time, which should be 3PM daily.
