### ISSUE TITLE
CLI Command to Remove Azure Subscription

### ISSUE THREAD

**Issue by Kannancsq** [MicrosoftDocs/azure-docs-cli#1477]
We are automating Subscription Creation & Removing process using CLI Scripts.

az account create is being using for creating subscription. However i was not able fine CLI command for Remove / De-Activate Subscription

Can you please let me know, the CLI Command to remove subscription.

**Comment by sptramer** [comment]
There is not currently a command to delete subscriptions from the CLI. Feel free to [file a feature request](https://github.com/azure/azure-cli/issues).
