### ISSUE TITLE
 GPG keys  is not correct for this package.

### ISSUE THREAD

**Issue by CondormanFr** [MicrosoftDocs/azure-docs-cli#1485]
When i try to install azure-cli on centos, I get this error : 
The GPG keys listed for the "Azure CLI" repository are already installed but they are not correct for this package.
Check that the correct key URLs are configured for this repository.

It was working in the past... But it seems that a new azure-cli version has been released ...

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: f9f55d23-7802-e0da-6d12-b71f6da8a1d4
* Version Independent ID: 192846d7-baae-bcba-698b-22bdcdae468a
* Content: [Installation d’Azure CLI pour Linux avec yum](https://docs.microsoft.com/fr-fr/cli/azure/install-azure-cli-yum?view=azure-cli-latest#feedback)
* Content Source: [docs-ref-conceptual/install-azure-cli-yum.md](https://github.com/MicrosoftDocs/azure-docs-cli.fr-FR/blob/live/docs-ref-conceptual/install-azure-cli-yum.md)
* Product: **azure**
* Technology: **azure-cli**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by icycle77** [comment]
Yes, I can confirm this error on my end as well, hit it today.

**Comment by icycle77** [comment]
I found that when following the [instructions](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-yum?view=azure-cli-latest) this install works fine. So the issue must be with my Artifactory proxy of the remote repository.

**Comment by sptramer** [comment]
@CondormanFr The GPG signing key was changed sometime in the last year, and the new key is required if you have not updated since approximately May 2018. Please follow the full install instructions to reinstall the Azure CLI and update your signing keys.
