### ISSUE TITLE
The current version of the CLI is 2.0.66

### ISSUE THREAD

**Issue by BoSoeborgPetersen** [MicrosoftDocs/azure-docs-cli#1486]
Not 2.0.65

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b7bd326-07b2-caaa-7155-5852fc2dfa3f
* Version Independent ID: c44d0547-d5cd-8934-00f8-79e2f4df53ac
* Content: [Install the Azure CLI](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli?view=azure-cli-latest#feedback)
* Content Source: [docs-ref-conceptual/install-azure-cli.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/install-azure-cli.md)
* Product: **azure**
* Technology: **azure-cli**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment]
@BoSoeborgPetersen The CLI version information has been updated with the release, but is only published at 3PM Pacific daily. This means that the version numbers and release notes are occasionally out of step with the current published package.
