### ISSUE TITLE
Querying with --odata-query

### ISSUE THREAD

**Issue by SeanFeldman** [MicrosoftDocs/azure-docs-cli#1489]
The option to query with `--odata-query` doesn't appear to be documented anywhere, but on a few individual pages.
An example, [here](https://docs.microsoft.com/en-us/azure/event-grid/how-to-event-domains#search-lists-of-topics-or-subscriptions). Would be great if the options available with `--odata-query` would be documented.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e60c12ef-d293-5626-c7aa-c7e9241bf975
* Version Independent ID: 7acca1dd-b735-7e1f-afd9-2b5b6ea06b1c
* Content: [Query command results with Azure CLI](https://docs.microsoft.com/en-us/cli/azure/query-azure-cli?view=azure-cli-latest#feedback)
* Content Source: [docs-ref-conceptual/query-azure-cli.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/query-azure-cli.md)
* Product: **azure**
* Technology: **azure-cli**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment]
OData is specifically used only by a very small subset of CLI commands and is incredibly complicated. This means that this section of the docs site, focused on general CLI querying, is not an appropriate place for a full OData reference or tutorial.  The best way to understand OData querying is to use the [OData specification site](https://www.odata.org/getting-started/basic-tutorial/#queryData).

**Comment by SeanFeldman** [comment]
@sptramer I did not ask for a full OData reference or tutorial for in the context of AZ CLI. What I did ask is to clarify what is possible with OData syntax querying and AZ CLI. Specifically, where and what is possible with `--odata-query`. It showed up in a single AZ command I've run into, for a specific ARM extension and have not seen it before.

**Comment by sptramer** [comment]
Again, the best way to understand OData is to go to their specification site. The query article will be updated with a link to the OData materials.

The primary differences between `--odata-query` and `-query` are the syntax and that OData filtering is performed server-side, so it may result in faster responses.

**Comment by sptramer** [comment]
Since OData isn't a general purpose CLI feature, closing this as WONTFIX. Individual services and commands affected by OData should be responsible for explaining why those individual commands benefit from the use of it, why users would want to perform server-side filtering, and cover associated topics.

**Comment by SeanFeldman** [comment]
> Individual services and commands affected by OData should be responsible for explaining why those individual commands benefit from the use of it, why users would want to perform server-side filtering, and cover associated topics.

You're correct, as a customer and the external person I should chase the individual teams to address the question of odata with Azure CLI usage and options, rather than an internal MSFT person would make the effort. How foolish of me.

**Comment by arob98** [comment]
Hi Sean, Following up on this thread, I'm going to share your feedback so we can improve. I apologize for any frustration you have experienced. Angela
