### ISSUE TITLE
Azure CLI Latest show "????" in Chinese

### ISSUE THREAD

**Issue by tcbjc** [MicrosoftDocs/azure-docs-cli#1502]
We install CLI latest version according to https://docs.microsoft.com/zh-cn/cli/azure/install-azure-cli-yum?view=azure-cli-latest. It can not show Chinese Information. 

[root@qiyulabvm ~]# az -v
azure-cli                         2.0.67

Name              CloudName        SubscriptionId                        State    IsDefault
----------------  ---------------  ------------------------------------  -------  -----------
????              AzureChinaCloud  28e46b22-2a44-49db-887a-0aade89f44b6  Enabled  False
????              AzureChinaCloud  1cbf0d6c-c40d-4bb4-a1fe-968b2821f119  Enabled  False
???               AzureChinaCloud  665ad261-97c5-4710-8930-7834e264a28d  Enabled  False
??                AzureChinaCloud  82b30eb8-0444-4a1b-ad4a-f75302fde566  Enabled  False
????              AzureChinaCloud  915c5f01-b0b6-4475-8386-e19ff59da587  Enabled  False
????              AzureChinaCloud  c418acaa-b468-4922-ad8e-4fb973fffe83  Enabled  False
????              AzureChinaCloud  ab2cdb8c-9c93-4040-a5c0-aa7fe2f2d113  Enabled  False
PowerBI           AzureChinaCloud  b5f152d9-2177-4161-802e-4b2b32fdfc20  Enabled  False

**Comment by sptramer** [comment]
This seems like an issue with localization and proper language support. Please [file an engineering ticket](https://github.com/azure/azure-cli/issues).
