### ISSUE TITLE
az cli commands running slowly/hang than before

### ISSUE THREAD

**Issue by alvinsjtu** [MicrosoftDocs/azure-docs-cli#1505]
Hello az cli team, 

I'm raising the ticket on behalf of my high profile customer. We met an interesting issue since yesterday morning GMT+8, 

Issue Description:
Most of the az cli(azure-cli (2.0.17)) commands started to have slowness than before.For instance, 

Slow normal command run time:
a=$(az storage account keys list -g "xxxxxx" -n "xxxxxx" -o json --debug)

Working command run time:
$(az storage account keys list -g "xxxxxx" -n "xxxxxx" -o json --debug)

We notice there was an new version updated 3days ago, but didn't see the information coudl impact the services, wondering if there is anyting cloud be changed in the server side?

https://github.com/Azure/azure-cli/releases
https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/release-notes-azure-cli.md

Thank you.

**Comment by sptramer** [comment]
Update to the [latest CLI release](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli?view=azure-cli-latest). Version 2.0.17 is __50 releases out of date__, which means that for a release cadence of 2x a month, 25 months out of date - __over two years__. Engineering will likely not support such an old version but you are welcome to [file an engineering issue](https://github.com/azure/azure-cli/issues).
