### ISSUE TITLE
tsv format is NOT easy without field documentation

### ISSUE THREAD

**Issue by gjustice** [MicrosoftDocs/azure-docs-cli#1508]
It would be easy to use tsv format as suggested by the above document to pipe to other commands for selection/processing if a definition of the fields/columns were available for any given az cli command.  Eg how do I know how to decipher the output of:
   az network nsg list
The table output gives 5 columns with headings but tsv output gives 13 fields.  How do I get the documentation of these 13 fields?  And the "solution" has to be extended to each and every command!  Another real example of something I need to do:
   az network nsg rule list --nsg-name $NSGname

Again, the table and tsv output are quite different!  How do I decode the tsv output so I know which fields to select?

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 48273ba7-da5a-95f0-7ffc-8c6d5282313d
* Version Independent ID: 83d348f9-fd1f-1041-0304-d8634e5526d4
* Content: [Output formats for Azure CLI](https://docs.microsoft.com/en-us/cli/azure/format-output-azure-cli?view=azure-cli-latest#tsv-output-format)
* Content Source: [docs-ref-conceptual/format-output-azure-cli.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/format-output-azure-cli.md)
* Product: **azure**
* Technology: **azure-cli**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment]
Adding field headers to TSV output would be a feature request, which you can submit to the engineering GitHub issues: https://github.com/azure/azure-cli

**Comment by sptramer** [comment]
Going to reopen this since this is technically a `--query`-supported feature that should be documented.

**Comment by sptramer** [comment]
The format documentation has been updated so that it's now clear how to order TSV output.
