### ISSUE TITLE
Release Notes for 2.0.68 do not address anomalies in installation

### ISSUE THREAD

**Issue by TurtleBeach** [MicrosoftDocs/azure-docs-cli#1517]
After updating from 2.0.67 to 2.0.68, (on Windows 10 Professional, v1809, build 17763.557) the following anomalies appear/occur:
C:\Users\Admin&gt;az --version
azure-cli                         2.0.68
command-modules-nspkg               2.0.2 *
core                              2.0.68
nspkg                              3.0.4
telemetry                          1.0.3

Extensions:
azure-cli-iot-ext                  0.7.0

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\Admin\.azure\cliextensions'

Python (Windows) 3.6.6 (v3.6.6:4cf1f54eb7, Jun 27 2018, 02:47:15) [MSC v.1900 32 bit (Intel)]

Legal docs and information: aka.ms/AzureCliLegal

You have 1 updates available. Consider updating your CLI installation. &lt;--*************

ISSUE 1 --- WHY does the above line appear. 2.0.68 is supposedly the latest. I have no idea what **command-modules-nspkg** is, or how to update it beyond using the msi installer to update the CLI.

C:\Users\Admin&gt;az extension update --name azure-cli-iot-ext
Unable to load extension 'azure-cli-iot-ext'. Use --debug for more information.

ISSUE 2 what is the basis for the "Unable to load extension 'azure-cli-iot-ext' message??? Note that immediately after the message it appears that the extension is being updated; and issuing a second az --version (see below) appears to reflect that the iot-hub extension was in fact updated.

 - Installing ..
C:\Users\Admin&gt;az --version
azure-cli                         2.0.68

command-modules-nspkg               2.0.2 *
core                              2.0.68
nspkg                              3.0.4
telemetry                          1.0.3

Extensions:
azure-cli-iot-ext                  0.7.1

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\Admin\.azure\cliextensions'
Python (Windows) 3.6.6 (v3.6.6:4cf1f54eb7, Jun 27 2018, 02:47:15) [MSC v.1900 32 bit (Intel)]
Legal docs and information: aka.ms/AzureCliLegal
You have 1 updates available. Consider updating your CLI installation.

CORE ISSUE: Why can MS not get simple updates of critical tools to work without this aggravation (inconsistent and ambiguous messages that instill zero confidence that the intended operations succeeded - and as soon as something else happens later, a developer is left to struggle with "Is it a problem with the tool installation" or "Is it a problem with the way I am trying to use the tool" - and this in the context of generally abysmal documentation for substantive use cases
Jack

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0e8d9ef-f25b-bb46-7f1a-bd3588be3343
* Version Independent ID: cd392600-a90d-0145-5ea6-6b01ab8f4ab9
* Content: [Azure CLI release notes](https://docs.microsoft.com/en-us/cli/azure/release-notes-azure-cli?view=azure-cli-latest)
* Content Source: [docs-ref-conceptual/release-notes-azure-cli.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/release-notes-azure-cli.md)
* Product: **azure**
* Technology: **azure-cli**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment]
@TurtleBeach There appears to be a bug with the current version of `az` where it always reports a need to upgrade. Since you've experienced this problem among others, you should file a [bug report](https://github.com/azure/azure-cli) with the engineering team.
