### ISSUE TITLE
Title is "Install or update" but no instructions on update.  

### ISSUE THREAD

**Issue by eric-camplin** [MicrosoftDocs/azure-docs-cli#1523]
When installing from link on Windows- received "need to update" in power-shell after running `az --version` but no instructions on the update command syntax

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8246b90a-efb1-03ce-f642-d3eb2441fc30
* Version Independent ID: 2fdd20ef-7bd3-57bc-7957-93f4bb5377ce
* Content: [Install the Azure CLI for Windows](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-windows?view=azure-cli-latest#feedback)
* Content Source: [docs-ref-conceptual/install-azure-cli-windows.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/install-azure-cli-windows.md)
* Product: **azure**
* Technology: **azure-cli**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment]
There's currently a bug where `az --version` always reports a need to upgrade. However the section you're referring to on the page is called [Install or Upgrade](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-windows?view=azure-cli-latest#install-or-update). The process identical for Windows.
