### ISSUE TITLE
Debian Buster not supported

### ISSUE THREAD

**Issue by zobelhelas** [MicrosoftDocs/azure-docs-cli#1524]
zobel@gjallar ~ % AZ_REPO=$(lsb_release -cs)
echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" | \
    sudo tee /etc/apt/sources.list.d/azure-cli.list
deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ buster main
zobel@gjallar ~ % sudo apt-get update
sudo apt-get install azure-cli
...
Ign:14 https://packages.microsoft.com/repos/azure-cli buster InRelease                                                   
Hit:15 https://packages.microsoft.com/repos/vscode stable InRelease 
Err:16 https://packages.microsoft.com/repos/azure-cli buster Release
  404  Not Found [IP: 13.80.10.205 443]
...
Reading package lists... Done

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: fe1526a9-7f22-504e-484c-0f3edc11b178
* Version Independent ID: c5dec108-efcd-aa77-04b5-803b6b894dba
* Content: [Installieren der Azure CLI unter Linux mit apt](https://docs.microsoft.com/de-de/cli/azure/install-azure-cli-apt?view=azure-cli-latest#feedback)
* Content Source: [docs-ref-conceptual/install-azure-cli-apt.md](https://github.com/MicrosoftDocs/azure-docs-cli.de-DE/blob/live/docs-ref-conceptual/install-azure-cli-apt.md)
* Product: **azure**
* Technology: **azure-cli**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment]
Debian Buster is not listed among the supported distributions (Debian Wheezy, Jessie und Stretch). @achandmsft what is the ETA for a Buster package?

**Comment by martinffx** [comment]
ETA on the buster packages?

**Comment by sptramer** [comment]
Please follow https://github.com/Azure/azure-cli/issues/9880 for any updates on Debian Buster support. When that ticket is closed, the install instructions will be updated to show that Buster is a supported distribution.

**Comment by aueelis** [comment]
The issue is closed and Buster is now supported.

**Comment by aueelis** [comment]
@sptramer The issue of supporting Buster is closed but the documentation wasn't adjusted yet!

**Comment by sptramer** [comment]
My mistake. I'll adjust the documentation.

The site is normally published from documentation at least 2x a week, but sometimes the publishing schedule is interrupted. Issues are closed when we merge the fix, not when the fix goes live on the site.
