### ISSUE TITLE
CLI configuration 

### ISSUE THREAD

**Issue by rawadhmd** [MicrosoftDocs/azure-docs-cli#1525]
when I run this command: az storage account show-connection-string -g Basebot -n basebot --DefaultEndPointsProtocol basebot | sed -n 2p cut -d '"' -f 4

I got the following error, what is wrong? where can I find help?

sed : The term 'sed' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:102
+ ... g Basebot -n basebot --DefaultEndPointsProtocol basebot | sed -n 2p c ...
+                                                               ~~~
    + CategoryInfo          : ObjectNotFound: (sed:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by sptramer** [comment]
@rawadhmd The Azure CLI examples are all written for the `bash` script, as clearly stated on the [CLI landing page](https://docs.microsoft.com/en-us/cli/azure/?view=azure-cli-latest#azure-cli-resources). It looks like you're running these examples on CMD or PowerShell. That means they may not work and you will need to find equivalent Windows commands for `sed` and `cut`, standard UNIX tools.
