### ISSUE TITLE
Missing dependency

### ISSUE THREAD

**Issue by croeck** [MicrosoftDocs/azure-docs-cli#1528]
Hi,

there is a missing dependency in Step 1: ca-certificates
If I do not install it, the apt-get update will fail without a specific error message.

Tested with docker image debian:stretch-slim following exactly your steps above.

Regards
Cedric

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: fe1526a9-7f22-504e-484c-0f3edc11b178
* Version Independent ID: c5dec108-efcd-aa77-04b5-803b6b894dba
* Content: [Installieren der Azure CLI unter Linux mit apt](https://docs.microsoft.com/de-de/cli/azure/install-azure-cli-apt?view=azure-cli-latest)
* Content Source: [docs-ref-conceptual/install-azure-cli-apt.md](https://github.com/MicrosoftDocs/azure-docs-cli.de-DE/blob/live/docs-ref-conceptual/install-azure-cli-apt.md)
* Product: **azure**
* Technology: **azure-cli**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment]
Thanks for the report, this should be fixed in the next site publish. Localization into DE will take longer.

I would also recommend filing an issue with Debian to include `ca-certificates` even on `-slim` images, since it makes HTTPS interactions with authorities that check CA chains difficult.
