### ISSUE TITLE
Check when Service Principal Signed In

### ISSUE THREAD

**Issue by liamfoneill** [MicrosoftDocs/azure-docs-cli#1541]
Is there somewhere I can when when the credentials were used to sign in with a service principal? I checked sign-in logs in AAD but that only seems to be for users, rather than service principals.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3f84bdc-9ed0-eb85-f3af-9711e8083a95
* Version Independent ID: 03a47d06-5fbf-4764-0882-99cd8bd41110
* Content: [Use Azure service principals with Azure CLI](https://docs.microsoft.com/en-us/cli/azure/create-an-azure-service-principal-azure-cli?view=azure-cli-latest#feedback)
* Content Source: [docs-ref-conceptual/create-an-azure-service-principal-azure-cli.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/create-an-azure-service-principal-azure-cli.md)
* Technology: **azure-cli**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment]
Sorry, I'm not sure of the answer. You may have more success by leaving a comment on [Sign-in logs](https://docs.microsoft.com/en-us/azure/active-directory/reports-monitoring/concept-sign-ins), although that article does explicitly state that it only tracks __interactive__ sign-in.
