### ISSUE TITLE
az cli - arm architecture

### ISSUE THREAD

**Issue by Joseluismantilla** [MicrosoftDocs/azure-docs-cli#1549]
Hello

Keeping in mind the ARM are used for developers boards, I'd like to have the az ure-cli for armbian, ubuntu, debian ARM64, it would be unacceptable the az cli doesn't work on boards for developers.

**Comment by sptramer** [comment]
This is a duplicate of #1326. The installation instructions will be available (and that ticket closed) when an ARM package is made available.
