### ISSUE TITLE
copy/paste command doesn't work

### ISSUE THREAD

**Issue by geperezg** [MicrosoftDocs/azure-docs-cli#1552]
doing copy/paste in a bash shell had trouble with the back slash:

VM2_IP_ADDR=$(az vm create -g TutorialResources \
  -n TutorialVM2 \
  --image UbuntuLTS \
  --generate-ssh-keys \
  --subnet $SUBNET_ID \
  --query publicIpAddress \
  -o tsv)

got the following error: "az vm create: error: the following arguments are required: --name/-n"

Was able to move forward after deleting the back slash

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bc5a121-5a89-6c37-6ccd-afe396046882
* Version Independent ID: bda58565-6191-a991-9646-e5b9bd58896a
* Content: [Create virtual machines with the Azure CLI](https://docs.microsoft.com/en-us/cli/azure/azure-cli-vm-tutorial?tutorial-step=8&view=azure-cli-latest#feedback)
* Content Source: [docs-ref-conceptual/azure-cli-vm-tutorial.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/docs-ref-conceptual/azure-cli-vm-tutorial.yml)
* Product: **azure**
* Technology: **azurecli**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment]
What shell were you using to run these commands? I'm able to get the correct behavior in my environment.

**Comment by geperezg** [comment]
I am using bash on WSL

I am copying with the "Copy" button, and also with Right-click->Copy. Pasting in bash with Right-click

$ bash -version
GNU bash, version 4.4.19(1)-release (x86_64-pc-linux-gnu)

**Comment by sptramer** [comment]
When clicking the `Copy` button from the codeblock, I'm not seeing any errors pasting it into a bash terminal. One thing about the `\` escape is that if it's immediately followed by whitespace _other_ than a newline, it will error out.

What browser are you using? That might be a factor here as well.

**Comment by sptramer** [comment]
No response to the browser question, and unable to reproduce in my environment. Closing this issue.

**Comment by alexmlopez** [comment]
this tutorial does not work on a regular, linux box,or regular shell that should be explained, with more detail .
AWS does a great explanation on CLIs. 
Trying to learn Azure , but most of the tutorials all full of bugs 
hope it helps
