### ISSUE TITLE
Malformat `az keyvault storage sas-definition create` document

### ISSUE THREAD

**Issue by Juliehzl** [MicrosoftDocs/azure-docs-cli#1569]
https://docs.microsoft.com/en-us/cli/azure/keyvault/storage/sas-definition?view=azure-cli-latest#az-keyvault-storage-sas-definition-create

![image](https://user-images.githubusercontent.com/49508232/63750837-cbdd0580-c8e0-11e9-8a5b-c9cac4a59495.png)

The commands in one code snippet should align, but now  besides the first command, others are in  unexpected  indentation.

**Comment by Juliehzl** [comment]
@daxianji007 Can you have a look at this?

**Comment by daxianji007** [comment]
fixed.
