### ISSUE TITLE
Permissions for creating Azure service principal

### ISSUE THREAD

**Issue by BrightRan** [MicrosoftDocs/azure-docs-cli#1578]
To create an Azure service principal, whether the Azure AD administrator or Azure administrator role is required?
On Azure portal, if a AAD member is not administrator, how to assign permissions to allow he can create Azure service principal?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3f84bdc-9ed0-eb85-f3af-9711e8083a95
* Version Independent ID: 03a47d06-5fbf-4764-0882-99cd8bd41110
* Content: [Use Azure service principals with Azure CLI](https://docs.microsoft.com/en-us/cli/azure/create-an-azure-service-principal-azure-cli?view=azure-cli-latest)
* Content Source: [docs-ref-conceptual/create-an-azure-service-principal-azure-cli.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/create-an-azure-service-principal-azure-cli.md)
* Technology: **azure-cli**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment]
@BrightRan Sorry, but this page is only meant to be a quick overview of how to use the CLI to create a service principal, and doesn't discuss which permissions are required. You may have better luck with the [Azure Active Directory](https://docs.microsoft.com/en-us/azure/active-directory/) documentation.
