### ISSUE TITLE
CLI 2.0

### ISSUE THREAD

**Issue by marcissimus** [MicrosoftDocs/azure-docs-cli#1581]
Several links to GitHub should be update to https://github.com/azure/azure-cli

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9bfdd999-341a-7aa8-04cf-f3808d813051
* Version Independent ID: 76d4e553-fdd3-8339-6a11-870d53efdeb2
* Content: [Install the Azure classic CLI](https://docs.microsoft.com/en-us/cli/azure/install-classic-cli?view=azure-cli-latest#feedback)
* Content Source: [docs-ref-conceptual/install-classic-cli.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/install-classic-cli.md)
* Product: **azure**
* Technology: **azure-cli**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment]
This article is explicitly for installing the Azure "classic" CLI, so all of the links are correct.
