### ISSUE TITLE
Missing instruction

### ISSUE THREAD

**Issue by cosmicbubble69** [MicrosoftDocs/azure-docs-cli#1582]
The unix install of the client tells you how to install the client but not how to register the server into the Azure Portal into the File Sync group. The client is installed but wheres the step to register the server into the Azure File Sync service.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93174b3a-3e97-8304-83fc-807be75198fe
* Version Independent ID: 1155045b-ce8c-2def-7b0e-043283f8be01
* Content: [Sign in with the Azure CLI](https://docs.microsoft.com/en-us/cli/azure/authenticate-azure-cli?view=azure-cli-latest#feedback)
* Content Source: [docs-ref-conceptual/authenticate-azure-cli.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/authenticate-azure-cli.md)
* Technology: **azure-cli**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment]
Sorry, but this article only covers the installation of the Azure CLI. I looked for one, and didn't see a CLI extension for File Sync, either. The best way to find the information that you're looking for is to check the  [Azure Files](https://docs.microsoft.com/en-us/azure/storage/files/) documentation.
