### ISSUE TITLE
Add a note on the CLI core version setup

### ISSUE THREAD

**Issue by daveRendon** [MicrosoftDocs/azure-docs-cli#1588]
Tried: 
az ad sp list --show-mine --query '[].{"id":"e55ad3ae-ec31-4f88-xxxx-xxxxxxxx", "tenant":"f6d82f6e-xxxx-4cd2-xxxx-xxxxxx"}'

Output:

You have CLI core version 2.0.72 and this extension requires a min of 2.0.50.dev0 and max of 2.0.61

quick workaround to get the id: 

az ad sp show --id xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxx

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3f84bdc-9ed0-eb85-f3af-9711e8083a95
* Version Independent ID: 03a47d06-5fbf-4764-0882-99cd8bd41110
* Content: [Use Azure service principals with Azure CLI](https://docs.microsoft.com/en-us/cli/azure/create-an-azure-service-principal-azure-cli?view=azure-cli-latest)
* Content Source: [docs-ref-conceptual/create-an-azure-service-principal-azure-cli.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/create-an-azure-service-principal-azure-cli.md)
* Technology: **azure-cli**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment]
I need some more information to be able to take action on this. Can you provide the full output of `az --version` on your system, as well as OS information, Linux distribution (if relevant), and which install method you used?

**Comment by dbradish-microsoft** [comment]
@daveRendon , This GitHub issue is resolved, I believe, by either the new [az upgrade](https://docs.microsoft.com/en-us/cli/azure/reference-index?view=azure-cli-latest#az_upgrade) command or by the new Azure CLI extension feature that prompts users to install needed extensions upon first use.  If you are still having issues with upgrading or installing the Azure CLI, please open a new issue and we will assist you.

Kindly,

Delora

**Comment by daveRendon** [comment]
Thank you @dbradish-microsoft
