### ISSUE TITLE
Please update homebrew repository

### ISSUE THREAD

**Issue by cpunella** [MicrosoftDocs/azure-docs-cli#1600]
Hi there, 

I just tried to upgrade the cli using brew but the latest package version uploaded is azure-cli-2.0.72_1.mojave.bottle.tar.gz.

Can you update it, please?

---
#### Dettagli del documento

⚠ *Non modificare questa sezione. È necessaria per i collegamenti relativi ai problemi tra docs.microsoft.com ➟ GitHub.*

* ID: d09ed623-c83f-6bae-639e-a5f9a31fe3bb
* Version Independent ID: c5d0d722-aacd-47a3-3fcf-982c02c4d0e9
* Content: [Installare l'interfaccia della riga di comando di Azure per macOS](https://docs.microsoft.com/it-it/cli/azure/install-azure-cli-macos?view=azure-cli-latest)
* Content Source: [docs-ref-conceptual/install-azure-cli-macos.md](https://github.com/MicrosoftDocs/azure-docs-cli.it-IT/blob/live/docs-ref-conceptual/install-azure-cli-macos.md)
* Product: **azure**
* Technology: **azure-cli**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment]
I'm checking in with the engineering team to see if this release channel didn't get the latest update and I'll let you know when I have an answer.

**Comment by sptramer** [comment]
It looks like the [current homebrew formula](https://formulae.brew.sh/formula/azure-cli#default) is v2.0.74, the latest.
