### ISSUE TITLE
single quote and double quotes in query value

### ISSUE THREAD

**Issue by prabhakarreddy1234** [MicrosoftDocs/azure-docs-cli#1603]
In Azure CLI commands with JMESPATH queries, i observed similar examples with single quote and double quotes used in different occasions. I had issues when i used single quote where double quote could have been used. So i don't find any documentation explaining when to use single quote and when to use double quote in `--query`  value?

For e.g  https://docs.microsoft.com/en-us/cli/azure/query-azure-cli?view=azure-cli-latest#get-multiple-values

![image](https://user-images.githubusercontent.com/1984707/65882571-2d373f00-e38d-11e9-8cc2-0d261a722836.png)

**Comment by sptramer** [comment]
This has to do with how the `bash` shell treats string arguments. When an argument is wrapped in `"..."`, the contents are interpreted by the shell if they have any characters which might be picked up by it. When `'...'` is used, the shell does not interpret any characters.

There's the additional issue that in JMESPath, all strings must be wrapped in `'...'`. That means that any query parameter closed in quotes (which you should always do!) must use `"..."` or escape the single quotes.

Hopefully that explains the difference in when to use which, although the style is not consistent across the documentation site. Right now we're actively working on making our samples easier to read across sections of the site, and one of those things will now be making sure quoting style is consistent.

Hope that helps!
