### ISSUE TITLE
Popup during linux script blocks install

### ISSUE THREAD

**Issue by DavidLangworthy** [MicrosoftDocs/azure-docs-cli#1607]
On mint and WSL a popup comes up when running the one line install script from an XTerm.  This does not occur over ssh.  The title is Configuring libssl1.1:amd64 and it asks for permission to restart services. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe1526a9-7f22-504e-484c-0f3edc11b178
* Version Independent ID: c5dec108-efcd-aa77-04b5-803b6b894dba
* Content: [Install the Azure CLI on Linux with apt](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-apt?view=azure-cli-latest#feedback)
* Content Source: [docs-ref-conceptual/install-azure-cli-apt.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/install-azure-cli-apt.md)
* Product: **azure**
* Technology: **azure-cli**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment]
@DavidLangworthy This sounds like it would be an issue with the script or the general install process, and possibly with WSL. In order to get a script issue addressed, you will need to [file a bug report with engineering](https://github.com/Azure/azure-cli/issues/new?assignees=&labels=&template=Bug_report.md&title=).

**Comment by MaurGi** [comment]
This happened to me and blocked my installation on WSL - left in a bad state and had to reinstall Ubuntu....

**Comment by rasmusgude** [comment]
This also happens to me on WSL Ubuntu 18.04. On WSL Ubuntu 16.04 it works just fine.

**Comment by TechArtistG** [comment]
Did anyone file a bug against this?  Just hit it on Ubuntu 18.04

**Comment by toniwillberg** [comment]
A workaround for those hit with this problem:
 When the popup appears, hit ctrl+z and run "killall whiptail", then resume the installation by running "fg".

**Comment by DavidLangworthy** [comment]
I opened a bug against the cli  https://github.com/Azure/azure-cli/issues/10793
