### ISSUE TITLE
Downloading a script and running it is a bad security practice, especially as root.

### ISSUE THREAD

**Issue by jjensenj** [MicrosoftDocs/azure-docs-cli#1612]
Hi,

The page https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-apt?view=azure-cli-latest contains:

`curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash`

This is a bad security practice. User should not be instructed to download a script and blindly execute that as root.

**Comment by sptramer** [comment]
@jjensenj I agree with you! This is why there are still step-by-step manual instructions on the page, and users are encouraged to examine the script before installing if they choose to use it.
