### ISSUE TITLE
Instructions do not work for default Visual Studio Code online Linux host

### ISSUE THREAD

**Issue by jake-bladt** [MicrosoftDocs/azure-docs-cli#1649]
Appears to be Ubuntu 18.04.1 (output of uname -a is "Linux 4f95409cc772 5.0.0-1023-azure #24~18.04.1-Ubuntu SMP Wed Oct 2 20:23:29 UTC 2019 x86_64 GNU/Linux.") Fails on "lsb_release -cs."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe1526a9-7f22-504e-484c-0f3edc11b178
* Version Independent ID: c5dec108-efcd-aa77-04b5-803b6b894dba
* Content: [Install the Azure CLI on Linux with apt](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-apt?view=azure-cli-latest#feedback)
* Content Source: [docs-ref-conceptual/install-azure-cli-apt.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/install-azure-cli-apt.md)
* Product: **azure**
* Technology: **azure-cli**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by BharathNimmala-MSFT** [comment]
@jake-bladt  Thank you for reaching out to us, we will further look into this and get back to you at the earliest.

**Comment by BharathNimmala-MSFT** [comment]
@jake-bladt  Thanks again for bringing this to our notice,  our product team is looking into this and have reference attached above. Please look for updates accordingly on the thread. Thank you

**Comment by fengzhou-msft** [comment]
I set up a vsonline VM following the [doc](https://docs.microsoft.com/en-us/visualstudio/online/how-to/vscode#install) and can not reproduce this issue.
`lsb_release -cs` gives me `stretch`. `uname -a` gives me `Linux 08633513c3c0 5.0.0-1027-azure #29~18.04.1-Ubuntu SMP Mon Nov 25 21:18:57 UTC 2019 x86_64 GNU/Linux`.

There's a discrepancy in these two commands, I think `uname` is wrong. The system is actually `debian stretch`. Anyway, I can install azure-cli successfully.

**Comment by fengzhou-msft** [comment]
Close as the issue is caused by the underlying image.
