### ISSUE TITLE
Can I create a service principal with certificate and password based authentication at the same time?

### ISSUE THREAD

**Issue by krysickij1** [MicrosoftDocs/azure-docs-cli#1650]
I want to automate service principal provisioning - currently I'm using --create-cert --cert option, but then in output I see "Null" next to password parameter. My organisation is using both authentication methods so I would like to be able to have password as well as certificate stored in Key Vault. Is it possible to do it now in one step?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3f84bdc-9ed0-eb85-f3af-9711e8083a95
* Version Independent ID: 03a47d06-5fbf-4764-0882-99cd8bd41110
* Content: [Use Azure service principals with Azure CLI](https://docs.microsoft.com/en-us/cli/azure/create-an-azure-service-principal-azure-cli?view=azure-cli-latest)
* Content Source: [docs-ref-conceptual/create-an-azure-service-principal-azure-cli.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/create-an-azure-service-principal-azure-cli.md)
* Technology: **azure-cli**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by BharathNimmala-MSFT** [comment]
@krysickij1 Thank you for reaching out to us, we will further look into this and get back to you at the earliest.

**Comment by BharathNimmala-MSFT** [comment]
@krysickij1 Apologies for the delayed response on this. Currently you can only store the certificate in the key vault, the password automatically gets stored in to Azure Active Directory. To answer your specific query "No" we cannot store both password and certificate to Azure Key vault. 

As a work around you can write a script to get the password when using pass-based authentication mechanism and read the output and password parameter out of it and [create a key/secret with in Azure Key vault](https://docs.microsoft.com/en-us/azure/key-vault/quick-create-cli#add-a-secret-to-key-vault). 

However you can always share your feedback using [az feedback](https://docs.microsoft.com/en-us/cli/azure/reference-index?view=azure-cli-latest#az-feedback) , which would give our product team an opportunity to further evaluate your ask. 

Currently we don't see need for any further edits or updates to existing documentation. Will go ahead and close this issue for now however if you have any further queries please feel free to tag us in your reply will be more than happy to continue the conversation. Thank you
