### ISSUE TITLE
OpenSUSE package for Azure CLI needs to be updated

### ISSUE THREAD

**Issue by HQJaTu** [MicrosoftDocs/azure-docs-cli#1665]
In OpenSUSE Leap 15.1 the az-command doesn't work anymore. This is because Python version 2 to 3 transition. The current status of RPM-package doesn't reflect reality anymore leading into situation where Python PIP-package requirements are badly tangled. Some commands work from Python 3, some from Python 2.

Optimally all this mess would be untangled and a working Python 3 version would be packaged.

**Comment by AjayKumar-MSFT** [comment]
@HQJaTu, Thanks for the feedback! Could you also kindly share the Azure doc for which this feedback is applicable to?

**Comment by HQJaTu** [comment]
Sure, the docs are at https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-zypper?view=azure-cli-latest

Number of issues at the docs, OpenSUSE 42.2 is not relevant version anymore. There are references to Python 2, which will be obsoleted in a month. In the official zypper-repository of Azure-CLI, there is a semi-working version of `az`, but given Python 2 obsoletion, I keep bumping into modules that fail to work without errors and/or warning. Trying to manually fix the problems by `pip3 install` does not solve the problem.

Earlier this year, before this Python 2 to 3 transition, everything worked as expected. I fully understand, that we're in the middle of migration and I guess six months from now, everything will be back in order. Right now, not so much.

**Comment by BharathNimmala-MSFT** [comment]
@HQJaTu Thanks for bringing this to our attention and taking time to provide additional context. Given that [Python 2 is being end-of-lifed on January 1, 2020](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-zypper?view=azure-cli-latest) .  Will share your feedback with our document authoring team and Product teams to further evaluate and see what we can improve in regards to documentation so that this transition to Python 3 is smooth. Thank you

**Comment by HQJaTu** [comment]
I noticed the removed product-bug -label.

This is a bug. A regular update:
```
# zypper update
Loading repository data...
Reading installed packages...

The following package update will NOT be installed:
  azure-cli-core
```

Forced update:
```
# zypper update azure-cli-core
Loading repository data...
Reading installed packages...
Resolving package dependencies...

Problem: nothing provides python3-azure-mgmt-resource >= 4.0 needed by azure-cli-core-2.0.77-lp151.22.1.noarch
 Solution 1: do not install azure-cli-core-2.0.77-lp151.22.1.noarch
 Solution 2: break azure-cli-core-2.0.77-lp151.22.1.noarch by ignoring some of its dependencies
```

Given none of the "soft" methods work, I attempted to force the update into my box. As you might expect, that really broke everything. Ultimately I cannot run _az-cli_ from that VM at all. On some other Linux-distros the _az-cli_ still works.

**Comment by chasewilson** [comment]
Hey @HQJaTu , Sorry for the _very_ slow response. I'll be closing this issue for now as it's really out of date and teams isn't supporting this. 

If there is more to it or you have more feedback, feel free to respond here and we'll review and see what we need to do. 

Thanks and have a good one!
