### ISSUE TITLE
More information would be helpful.

### ISSUE THREAD

**Issue by v-davit** [MicrosoftDocs/azure-docs-cli#1673]
In the Note at the beginning of the page, you say that some examples may need to be modified if we're not running Bash. Can you provide more details on what those changes might be? Or at least a link to a page that describes them?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c268a98-afcb-d2c2-87c7-880d52900533
* Version Independent ID: 4c835da4-38bc-22a8-67b4-dd522adcc0e3
* Content: [Get started with Azure CLI](https://docs.microsoft.com/en-us/cli/azure/get-started-with-azure-cli?view=azure-cli-latest#feedback)
* Content Source: [docs-ref-conceptual/get-started-with-azure-cli.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/get-started-with-azure-cli.md)
* Product: **azure**
* Technology: **azure-cli**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by MonikaReddy-MSFT** [comment]
Hello @v-davit , Thanks for brining this to our attention. We will investigate it further and update you shortly.

**Comment by MonikaReddy-MSFT** [comment]
@v-davit , 
The examples are written for a specific shell (bash). But the Azure CLI can be run in PowerShell, CMD, or bash. The modifications depend on which shell you are using. For example, both PowerShell and bash have robust variable capability. CMD only supports environment variables, so you can't easily capture output from one command to be used in another. PowerShell and bash support line continuation. CMD does not. Redirection works differently in PowerShell compared to bash and CMD.

I hope this information helps.

**Comment by v-davit** [comment]
Hi, Monika—

Thanks for clarifying. Is this information stated succinctly (like this) somewhere online? What I was getting at with the comment that I left is that for rookies like me, it would be helpful to have this info out there, and to have it linked to by pages like the one I commented on.

--David T.

**Comment by MonikaReddy-MSFT** [comment]
@v-davit , Unfortunately at this moment, there is no document that specifies this information. But we will work with Product team to include this information as well. Thanks again bringing this to our attention. 

We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.

**Comment by v-davit** [comment]
Sounds good. Thanks for your prompt replies!
