### ISSUE TITLE
Windows MSI System Path

### ISSUE THREAD

**Issue by calvinwonghk** [MicrosoftDocs/azure-docs-cli#1689]
after installation, i tried to type az login it is not in system path, i need to manually go to path "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin" to type this az command !!!!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8246b90a-efb1-03ce-f642-d3eb2441fc30
* Version Independent ID: 2fdd20ef-7bd3-57bc-7957-93f4bb5377ce
* Content: [Install the Azure CLI for Windows](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-windows?view=azure-cli-latest#feedback)
* Content Source: [docs-ref-conceptual/install-azure-cli-windows.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/install-azure-cli-windows.md)
* Product: **azure**
* Technology: **azure-cli**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by MonikaReddy-MSFT** [comment]
@calvinwonghk ,Thanks for your question. We will investigate it further and update you shortly.

**Comment by SamaraSoucy-MSFT** [comment]
@calvinwonghk I have a few questions for you to try to track down the cause of the issue:

1. Which OS are you using? (7, 8, or 10)
2. What method did you use to install the package?
3. Is "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin" in your path variable?
4. Did you restart Powershell after installing the CLI?
5. Does uninstalling/reinstalling or manually adding it to the path resolve the issue?

**Comment by SamaraSoucy-MSFT** [comment]
@calvinwonghk I'm going to close this thread due to lack of response. If reinstalling or manually updating the path variable doesn't work, you can ping me in your comment and I will try to assist you further.

**Comment by myselfme0194** [comment]
I do have the same concern.DO i have to restart anything after Msi installation being done?..I can see the path is already updated via the installer.
But az --version doesnt get recogininze from any other path
