### ISSUE TITLE
Missing file-based and env-variable information for setting the default cloud name

### ISSUE THREAD

**Issue by stan-sz** [MicrosoftDocs/azure-docs-cli#1691]
Upon code inspection, the config file has 

```
[cloud]
name = AzureCloud
```

This leads to the fact that `AZURE_CLOUD_NAME` environment variable allows to set the default cloud name, without the need to call `az cloud set --name <cloud name>`. This information is missing from the documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb42002e-9aa3-233d-9832-353235b7cd0f
* Version Independent ID: e8b320b1-5805-67ba-46b2-48111861facc
* Content: [Azure CLI configuration options](https://docs.microsoft.com/en-us/cli/azure/azure-cli-configuration?view=azure-cli-latest)
* Content Source: [docs-ref-conceptual/azure-cli-configuration.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/azure-cli-configuration.md)
* Product: **azure**
* Technology: **azure-cli**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by ManojReddy-MSFT** [comment]
@stan-sz We are looking into this and will get back to you shortly.

**Comment by stan-sz** [comment]
For more context, the fact that `AZURE_CLOUD_NAME` works comes from this line: https://github.com/Azure/azure-cli/blob/3fa3de4fe7ddff0f58a33eb6ae62e358c91718e6/src/azure-cli-core/azure/cli/core/cloud.py#L312 and the way `knack` handles setting config values in the config file.

**Comment by MonikaReddy-MSFT** [comment]
@stan-sz - Thank you for bringing this to our attention. And apologies for the delay here. 
I'm going to assign this to the document author so they can update the document accordingly.

**Comment by stan-sz** [comment]
I see https://docs.microsoft.com/en-us/cli/azure/azure-cli-configuration?view=azure-cli-latest is updated with the necessary wording. Thanks!

**Comment by MonikaReddy-MSFT** [comment]
@stan-sz , Thanks again for bringing this to our attention. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
