### ISSUE TITLE
az network application-gateway url-path-map create: error: 'Namespace' object has no attribute 'firewall_policy'

### ISSUE THREAD

**Issue by mathieugravil** [MicrosoftDocs/azure-docs-cli#1696]
Hello
Since new version it failed:
mathieu@Azure:~$ az network application-gateway url-path-map create --resource-group rg-total-hp2-we-msapprd --gateway-name MSAPPRD-APGA-WE-HP2 --name msa-api-pprodmyPathMap --paths '/document/*'  --subscription tototot--address-pool "msa-pprod-document-service-backendpool"  --default-address-pool "MSAPPRD-HP2-AKS"  --default-http-settings "msa-pprod-document-service-http-settings"  --http-settings "msa-pprod-document-service-http-settings"   --rule-name "msa-pprod-document-service-rule" --verbose --debug -o table
Command arguments: ['network', 'application-gateway', 'url-path-map', 'create', '--resource-group', 'rg-total-hp2-we-msapprd', '--gateway-name', 'MSAPPRD-APGA-WE-HP2', '--name', 'msa-api-pprodmyPathMap', '--paths', '/document/*', '--subscription', 'tototototototo', '--address-pool', 'msa-pprod-document-service-backendpool', '--default-address-pool', 'MSAPPRD-HP2-AKS', '--default-http-settings', 'msa-pprod-document-service-http-settings', '--http-settings', 'msa-pprod-document-service-http-settings', '--rule-name', 'msa-pprod-document-service-rule', '--verbose', '--debug', '-o', 'table']
Event: Cli.PreExecute []
Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x7f76d86bad08>, <function OutputProducer.on_global_arguments at 0x7f76d81f5b70>, <function CLIQuery.on_global_argumentsat 0x7f76d8221bf8>]
Event: CommandInvoker.OnPreCommandTableCreate []
Installed command modules ['acr', 'acs', 'advisor', 'ams', 'apim', 'appconfig', 'appservice', 'backup', 'batch', 'batchai', 'billing', 'botservice', 'cdn', 'cloud', 'cognitiveservices', 'configure', 'consumption', 'container', 'cosmosdb', 'deploymentmanager', 'dla', 'dls', 'dms', 'eventgrid', 'eventhubs', 'extension', 'feedback', 'find', 'hdinsight', 'interactive', 'iot', 'iotcentral', 'keyvault', 'kusto', 'lab', 'managedservices', 'maps', 'monitor', 'natgateway', 'netappfiles', 'network', 'policyinsights', 'privatedns', 'profile', 'rdbms', 'redis', 'relay', 'reservations', 'resource', 'role', 'search', 'security', 'servicebus', 'servicefabric', 'signalr', 'sql', 'sqlvm', 'storage', 'vm']
Loaded module 'acr' in 0.007 seconds.
Loaded module 'acs' in 0.019 seconds.
Loaded module 'advisor' in 0.001 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'ams' in 0.006 seconds.
Loaded module 'apim' in 0.002 seconds.
Loaded module 'appconfig' in 0.003 seconds.
Loaded module 'appservice' in 0.010 seconds.
Loaded module 'backup' in 0.004 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'batch' in 0.009 seconds.
Loaded module 'batchai' in 0.003 seconds.
Loaded module 'billing' in 0.002 seconds.
Loaded module 'botservice' in 0.003 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'cdn' in 0.002 seconds.
Loaded module 'cloud' in 0.001 seconds.
Loaded module 'cognitiveservices' in 0.002 seconds.
Loaded module 'configure' in 0.001 seconds.
Loaded module 'consumption' in 0.002 seconds.
Loaded module 'container' in 0.002 seconds.
Loaded module 'cosmosdb' in 0.007 seconds.
Loaded module 'deploymentmanager' in 0.002 seconds.
Loaded module 'dla' in 0.004 seconds.
Loaded module 'dls' in 0.003 seconds.
Loaded module 'dms' in 0.002 seconds.
Loaded module 'eventgrid' in 0.002 seconds.
Loaded module 'eventhubs' in 0.004 seconds.
Loaded module 'extension' in 0.001 seconds.
Loaded module 'feedback' in 0.001 seconds.
Loaded module 'find' in 0.001 seconds.
Loaded module 'hdinsight' in 0.002 seconds.
Loaded module 'interactive' in 0.000 seconds.
Loaded module 'iot' in 0.008 seconds.
Loaded module 'iotcentral' in 0.001 seconds.
Loaded module 'keyvault' in 0.006 seconds.
Loaded module 'kusto' in 0.002 seconds.
Loaded module 'lab' in 0.003 seconds.
Loaded module 'managedservices' in 0.002 seconds.
Loaded module 'maps' in 0.002 seconds.
Loaded module 'monitor' in 0.006 seconds.
Loaded module 'natgateway' in 0.002 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'netappfiles' in 0.003 seconds.
Loaded module 'network' in 0.033 seconds.
Loaded module 'policyinsights' in 0.002 seconds.
Loaded module 'privatedns' in 0.005 seconds.
Loaded module 'profile' in 0.002 seconds.
Loaded module 'rdbms' in 0.006 seconds.
Loaded module 'redis' in 0.002 seconds.
Loaded module 'relay' in 0.003 seconds.
Loaded module 'reservations' in 0.003 seconds.
Loaded module 'resource' in 0.007 seconds.
Loaded module 'role' in 0.004 seconds.
Loaded module 'search' in 0.002 seconds.
Loaded module 'security' in 0.002 seconds.
Loaded module 'servicebus' in 0.005 seconds.
Loaded module 'servicefabric' in 0.002 seconds.
Loaded module 'signalr' in 0.002 seconds.
Loaded module 'sql' in 0.008 seconds.
Loaded module 'sqlvm' in 0.002 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'storage' in 0.036 seconds.
Loaded module 'vm' in 0.018 seconds.
Loaded all modules in 0.285 seconds. (note: there's always an overhead with the first module loaded)
Extensions directory: '/home/mathieu/.azure/cliextensions'
Found 2 extensions: ['azure-devops', 'aks-preview']
Extensions directory: '/home/mathieu/.azure/cliextensions'
Extension compatibility result: is_compatible=True cli_core_version=2.0.77 min_required=2.0.69 max_required=None
Extensions directory: '/home/mathieu/.azure/cliextensions'
Loaded extension 'azure-devops' in 0.024 seconds.
Extensions directory: '/home/mathieu/.azure/cliextensions'
Extension compatibility result: is_compatible=True cli_core_version=2.0.77 min_required=2.0.49 max_required=None
Event: CommandLoader.OnLoadCommandTable []
Extensions directory: '/home/mathieu/.azure/cliextensions'
Loaded extension 'aks-preview' in 0.003 seconds.
Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x7f76d7a2d598>]
az_command_data_logger : command args: network application-gateway url-path-map create --resource-group {} --gateway-name {} --name {} --paths {} --subscription {} --address-pool {} --default-address-pool {} --default-http-settings {} --http-settings {} --rule-name {} --verbose --debug -o {}
metadata file logging enabled - writing logs to '/home/mathieu/.azure/commands'.
Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x7f76d7a16268>]
Event: CommandInvoker.OnPostArgumentLoad []
Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x7f76d79c4f28>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x7f76d795f158>]
Event: CommandInvoker.OnCommandTableLoaded []
Event: CommandInvoker.OnPreParseArgs [<function _documentdb_deprecate at 0x7f76d5aff2f0>]
Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x7f76d81f5bf8>, <function CLIQuery.handle_query_parameter at 0x7f76d8221c80>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x7f76d795f048>, <function handler at 0x7f76d59cc6a8>, <function DevCommandsLoader.post_parse_args at 0x7f76d51e50d0>]
usage: az network application-gateway url-path-map create [-h] [--verbose]
                                                          [--debug]
                                                          [--output {json,jsonc,table,tsv,yaml,none}]
                                                          [--query JMESPATH]
                                                          [--subscription _SUBSCRIPTION]
                                                          --resource-group
                                                          RESOURCE_GROUP_NAME
                                                          --gateway-name
                                                          APPLICATION_GATEWAY_NAME
                                                          --name ITEM_NAME
                                                          --paths PATHS
                                                          [PATHS ...]
                                                          [--address-pool ADDRESS_POOL]
                                                          [--http-settings HTTP_SETTINGS]
                                                          [--redirect-config REDIRECT_CONFIG]
                                                          [--default-address-pool DEFAULT_ADDRESS_POOL]
                                                          [--default-http-settings DEFAULT_HTTP_SETTINGS]
                                                          [--default-redirect-config DEFAULT_REDIRECT_CONFIG]
                                                          [--rule-name RULE_NAME]
                                                          [--no-wait]
az network application-gateway url-path-map create: error: 'Namespace' object has no attribute 'firewall_policy'
az_command_data_logger : exit code: 2
telemetry.save : Save telemetry record of length 2718 in cache
telemetry.check : Negative: The /home/mathieu/.azure/telemetry.txt was modified at 2019-12-12 19:11:05.798272, which in less than 600.000000 s
command ran in 0.532 seconds.

**Comment by kobulloc-MSFT** [comment]
@mathieugravil Thank you for the feedback!  We are investigating this and will get back to you shortly.

**Comment by SubhashVasarapu-MSFT** [comment]
@mathieugravil , Thanks for your feedback. Could you please share the document link here in the description that you are referring to.

**Comment by haroldrandom** [comment]
Hi, @mathieugravil . This is Harold from the [Azure CL](https://github.com/Azure/azure-cli)I team and responsible for network-related commands.

I noticed that the feature was added since https://github.com/Azure/azure-cli/pull/11421 on Dec 11, 2019, and the corresponding release for it was on [12/11/2019](https://github.com/Azure/azure-cli/milestones?direction=asc&sort=title&state=closed).
![image](https://user-images.githubusercontent.com/14357159/96429989-2b5c4a00-1234-11eb-88be-514d4d01a023.png)

Look like you are an early user for this. Maybe you are running this command on a previous Azure CLI? :)
Could you try it again against the latest Azure CLI?

If the problem can still reproduce, you could fire a bug issue in https://github.com/Azure/azure-cli/issues/new/choose.
Thanks!

**Comment by dbradish-microsoft** [comment]
This issue is being closed as no response has been received since December 2019
