### ISSUE TITLE
the --output option none is not listed on the doc page

### ISSUE THREAD

**Issue by ChrisGibson1982** [MicrosoftDocs/azure-docs-cli#1707]
The --output option "none" is not listed on docs page (https://docs.microsoft.com/en-us/cli/azure/format-output-azure-cli?view=azure-cli-latest).   

https://github.com/Azure/azure-cli/pull/8198/files shows the text 
'No output, except for errors and warnings.' 

 It would be helpful to have this in the doc
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 48273ba7-da5a-95f0-7ffc-8c6d5282313d
* Version Independent ID: 83d348f9-fd1f-1041-0304-d8634e5526d4
* Content: [Output formats for Azure CLI](https://docs.microsoft.com/en-us/cli/azure/format-output-azure-cli?view=azure-cli-latest&source=docs#feedback)
* Content Source: [docs-ref-conceptual/format-output-azure-cli.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/format-output-azure-cli.md)
* Product: **azure**
* Technology: **azure-cli**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by MonikaReddy-MSFT** [comment]
@ChrisGibson1982 ,Thanks for brining this to our attention. We will investigate it further and update you shortly.

**Comment by SamaraSoucy-MSFT** [comment]
I've submitted a pull request to update the table. It will go live once the doc author has approved it.
