### ISSUE TITLE
Version of the Azure CLI is 2.0.77

### ISSUE THREAD

**Issue by edervaldonetoMS** [MicrosoftDocs/azure-docs-cli#1717]
Hello,
Just to update the document. The current version of the Azure CLI is 2.0.78.
Thanks

---
#### Detalhes do Documento

⚠ *Não edite esta secção. É necessário para a ligação de problemas docs.microsoft.com ➟ GitHub.*

* ID: fe1526a9-7f22-504e-484c-0f3edc11b178
* Version Independent ID: c5dec108-efcd-aa77-04b5-803b6b894dba
* Content: [Instalar a CLI do Azure no Linux com o apt](https://docs.microsoft.com/pt-pt/cli/azure/install-azure-cli-apt?view=azure-cli-latest)
* Content Source: [docs-ref-conceptual/install-azure-cli-apt.md](https://github.com/MicrosoftDocs/azure-docs-cli.pt-pt/blob/live/docs-ref-conceptual/install-azure-cli-apt.md)
* Product: **azure**
* Technology: **azure-cli**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by kobulloc-MSFT** [comment]
@edervaldonetoMS Thank you for bringing this to our attention!  We'll investigate this and update the document shortly.

**Comment by kobulloc-MSFT** [comment]
@edervaldonetoMS Thank you again for bringing this to our attention!  Since this is a localized version that will require a new release notes link, I'm going to assign this to the document author to make sure that everything gets updated appropriately.

**Comment by dcaro** [comment]
@kobulloc-MSFT please assign this issue to @achandmsft

**Comment by Krullet** [comment]
Still wrong version of Azure CLI. Should be 2.5.1 not 2.4.0. Thanks

**Comment by dbradish-microsoft** [comment]
@Krullet, the current version of the Azure CLI is 2.13.0 which is now correctly reflected in https://docs.microsoft.com/pt-pt/cli/azure/install-azure-cli-apt?view=azure-cli-latest.
![image](https://user-images.githubusercontent.com/58762114/96312047-a963eb00-0fbf-11eb-99d4-9648d5c9d263.png)

I am closing this GitHub issue as it is resolved.  Thank you for bringing this to our attention and following-up in April. 

Kindly,

Delora
