### ISSUE TITLE
Debian Azure CLI Repository Error

### ISSUE THREAD

**Issue by InitionsJulius** [MicrosoftDocs/azure-docs-cli#1741]
As of today, the **Azure CLI debian software repository** seems to have an error, since there seems to be a file size (or checksum?) mismatch. This error seems to be related to the new release (v 2.0.79), since last week everything was working fine.

The **error message** reads: 
Failed to fetch https://packages.microsoft.com/repos/azure-cli/dists/bionic/main/binary-amd64/Packages.bz2  File has unexpected size (7745 != 7578)

**Occurence of the error** when executing either one of the commands in an Ubuntu (bionic) environment:
1. curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
2. AZ_REPO=$(lsb_release -cs)
    echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" | 
    sudo tee /etc/apt/sources.list.d/azure-cli.list
    sudo apt-get update

Has anyone else experienced the same error? Are there any workarounds?

Thanks

**Comment by KrishnaG-MSFT** [comment]
@InitionsJulius Glad to know that the issue is resolved. Thanks for the update.
For the benefit of broader audience who might face similar issue, do you mind sharing information on what was done to resolve the issue. Thanks.

**Comment by InitionsJulius** [comment]
The problem was resolved by Microsoft developers upon contacting them.
