### ISSUE TITLE
Additional data point - Section "Sign in with a service principal"

### ISSUE THREAD

**Issue by kalyankadiyala-Microsoft** [MicrosoftDocs/azure-docs-cli#1752]
While the resources to be gathered is clear, it helps to add a caution where the PEM should have both the Private Key and the Certificate information as a bundle, in the following format.

	-----BEGIN PRIVATE KEY-----
	...
	-----END PRIVATE KEY-----
	-----BEGIN CERTIFICATE-----
	...
	-----END CERTIFICATE-----

This will help folks generating the private key and the certificate (DER formats for example) to make sure they perform one more step - which is to append the contents of the Certificate (DER, CER, CRT) to the .pem file which has the private key by default. This way, when folks try to jump straight to the login sequence as service principal using the certificate approach, need not face the issue of invalid certificate formats, etc.

Here's one anticipated error if users gloss over this detail to bundle the entries into a common .pem file (sensitive information stripped away for privacy reasons).

$ az login --service-principal --username &lt;service_principal_id&gt; --password &lt;path_to_the_file_that_has_both_privateKey_and_certificate&gt; --tenant &lt;tenant_id_from_your_default_directory&gt; --subscription &lt;subscription_id&gt;
Subscription 'Visual Studio Enterprise' not recognized.
Get Token request returned http error: 401 and server response: {"error":"invalid_client","error_description":"AADSTS700027: Client assertion contains an invalid signature. [Reason - The key was not found., Thumbprint of key used by client: 'CA40045B951F68BBF3B25DEDC112F0F97F8893AF', Please visit 'https://developer.microsoft.com/en-us/graph/graph-explorer' and query for 'https://graph.microsoft.com/beta/applications/&lt;application-id-representing-service-principal-in-app-registrations&gt;' to see configured keys]\r\nTrace ID: bd430ac8-fd4f-42d7-a590-d32041b5d000\r\nCorrelation ID: d699fef3-a8a9-4ce3-a03b-066824513347\r\nTimestamp: 2020-01-13 21:26:37Z","error_codes":[700027],"timestamp":"2020-01-13 21:26:37Z","trace_id":"bd430ac8-fd4f-42d7-a590-d32041b5d000","correlation_id":"d699fef3-a8a9-4ce3-a03b-066824513347","error_uri":"https://login.microsoftonline.com/error?code=700027"}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93174b3a-3e97-8304-83fc-807be75198fe
* Version Independent ID: 1155045b-ce8c-2def-7b0e-043283f8be01
* Content: [Sign in with the Azure CLI](https://docs.microsoft.com/en-us/cli/azure/authenticate-azure-cli?view=azure-cli-latest#sign-in-with-a-service-principal)
* Content Source: [docs-ref-conceptual/authenticate-azure-cli.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/authenticate-azure-cli.md)
* Technology: **azure-cli**
* GitHub Login: @dbradish-microsoft
* Microsoft Alias: **dbradish**

**Comment by kalyankadiyala-Microsoft** [comment]
Following is the link to the comment on Azure-Cli/Issues by yugangw-msft commented on Jul 20, 2019, which helped me fix the error described above in my attempts to setup and sign-in to Azure using SPN + Self-signed Certificate. 

https://github.com/Azure/azure-cli/issues/9970

**Comment by kobulloc-MSFT** [comment]
@kalyankadiyala-Microsoft Thank you for the feedback!  We will assign this to the document author so that they can update the documentation accordingly.

**Comment by dbradish-microsoft** [comment]
I am closing this issue as both [Create an Azure service principal with Azure CLI ](https://docs.microsoft.com/en-us/cli/azure/create-an-azure-service-principal-azure-cli?view=azure-cli-latest) and [Sign in with Azure CLI](https://docs.microsoft.com/en-us/cli/azure/authenticate-azure-cli?view=azure-cli-latest) documents have been updated with additional information to provide better clarity.  These changes will publish on Tuesday, March 20th, 2020.
