### ISSUE TITLE
"Insufficient privileges to complete the operation."

### ISSUE THREAD

**Issue by YanaShetko** [MicrosoftDocs/azure-docs-cli#1772]
can you help me please!
I was invited to some  Azure subscription. And now using and working in this subscription, I want to create  an Azure service principal. But when i try to do it with this command  - az ad sp create-for-rbac, i always get this error - "Insufficient privileges to complete the operation." 
Tell me, please, am I correct in assuming
does this appear because I was invited by a regular user to this subscription?
And in order to expand my privileges do I need to be assigned the administrator role in this subscription?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3f84bdc-9ed0-eb85-f3af-9711e8083a95
* Version Independent ID: 03a47d06-5fbf-4764-0882-99cd8bd41110
* Content: [Use Azure service principals with Azure CLI](https://docs.microsoft.com/en-us/cli/azure/create-an-azure-service-principal-azure-cli?view=azure-cli-latest#feedback)
* Content Source: [docs-ref-conceptual/create-an-azure-service-principal-azure-cli.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/create-an-azure-service-principal-azure-cli.md)
* Technology: **azure-cli**
* GitHub Login: @dbradish-microsoft
* Microsoft Alias: **dbradish**

**Comment by BharathNimmala-MSFT** [comment]
Thank you @YanaShetko for reaching out. We will further look into this and get back to you at the earliest. Thanks

**Comment by MohitVerma-MSFT** [comment]
Hello @YanaShetko ,

Are you the Azure AD administrator or Azure administrator? To create an Azure service principal, the Azure AD administrator or Azure administrator role is required.

If your account doesn't have permission to create a service principal, az ad sp create-for-rbac will return an error message containing "Insufficient privileges to complete the operation." Contact your Azure AD admin to create a service principal.

You can refer [this ](https://docs.microsoft.com/en-us/cli/azure/create-an-azure-service-principal-azure-cli?view=azure-cli-latest)link for more details.

**Comment by MohitVerma-MSFT** [comment]
Hello @YanaShetko ,

Just wanted to check if you got a chance to check my previous response.

**Comment by MohitVerma-MSFT** [comment]
Hello @YanaShetko ,

We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue. Thanks for bringing this to our attention. We will now close
 this issue. If there are further questions regarding this matter, please reopen it and we will gladly continue the discussion. We will close this out, but if you feel you need more information please just let us know.
