### ISSUE TITLE
--output none not documented

### ISSUE THREAD

**Issue by NoNameProvided** [MicrosoftDocs/azure-docs-cli#1774]
The `--output none` flag is not documented on this page. I see there have been an issue for this already which was closed a month ago, but the none option still not visible on the page. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 48273ba7-da5a-95f0-7ffc-8c6d5282313d
* Version Independent ID: 83d348f9-fd1f-1041-0304-d8634e5526d4
* Content: [Output formats for Azure CLI](https://docs.microsoft.com/en-us/cli/azure/format-output-azure-cli?view=azure-cli-latest)
* Content Source: [docs-ref-conceptual/format-output-azure-cli.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/format-output-azure-cli.md)
* Product: **azure**
* Technology: **azure-cli**
* GitHub Login: @dbradish-microsoft
* Microsoft Alias: **dbradish**

**Comment by Mike-Ubezzi-MSFT** [comment]
@NoNameProvided Thank you for bringing this to our attention. I will have this issue investigated and an update will be made as appropriate.

**Comment by BhargaviAnnadevara-MSFT** [comment]
@NoNameProvided Thanks for following up on the change! I've reached out to our internal Teams to approve the pull request for the same.

Also, please know that we welcome public contributions to the Azure CLI documentation from the community! Please feel free to submit a PR as you see fit the next time you stumble upon a bug or an enhancement. :)
