### ISSUE TITLE
Detail how to non-interactively configure settings

### ISSUE THREAD

**Issue by stewartadam** [MicrosoftDocs/azure-docs-cli#1777]
The documentation and help strings are entirely unclear on how to configure defaults non-interactively (i.e. scripting).

The `az configure --help` string shows:

    --defaults -d      : Space-separated 'name=value' pairs for common argument defaults.
    --list-defaults -l : List all applicable defaults.  Allowed values: false, true.

However `az configure -l` doesn't appear to output anything on a default install (as I suspect it is meant to list all *configured* defaults, not all available defaults). Even so, after using `az configure` interactively to set default output to table (`[core]` section setting `output=table`), `az configure -l` still does nothing.

Trying to script that setting with `az configure -d output=table` produces a default entry under the `[defaults]` section of `~/.azure/config`, not `[core]` as required. `az configure -d core.output=table` fails.

So how does one script setting the default output? Telling users to manually script editing a .ini file (#991) is not a very good answer.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 48273ba7-da5a-95f0-7ffc-8c6d5282313d
* Version Independent ID: 83d348f9-fd1f-1041-0304-d8634e5526d4
* Content: [Output formats for Azure CLI](https://docs.microsoft.com/en-us/cli/azure/format-output-azure-cli?view=azure-cli-latest#feedback)
* Content Source: [docs-ref-conceptual/format-output-azure-cli.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/format-output-azure-cli.md)
* Product: **azure**
* Technology: **azure-cli**
* GitHub Login: @dbradish-microsoft
* Microsoft Alias: **dbradish**

**Comment by Mike-Ubezzi-MSFT** [comment]
@stewartadam Thank you for bringing this to our attention. This is being evaluated and any updates and corrections will be made and reflected in the published version of the document as appropriate.

**Comment by MohitVerma-MSFT** [comment]
Hello @stewartadam ,

Thanks for reaching out !!

I tried to reproduce the scenario which you mentioned. For setting up the **`default output`** to **table** , you can try below command:

`az configure --defaults core.output=table`

I tried the same thing and it worked for me , and for getting the defaults entry i tried the below command:

`az configure --list-defaults -l`

Here is the output for the same:

![image](https://user-images.githubusercontent.com/46920446/73438368-f0e41180-4373-11ea-9f4c-75bc892e7fef.png)

Additional reference:
https://docs.microsoft.com/en-us/cli/azure/azure-cli-configuration?view=azure-cli-latest#cli-configuration-with-az-configure
Hope it helps.

**Comment by MohitVerma-MSFT** [comment]
Hello @stewartadam ,

Just wanted to check if you got a chance to check my previous response.

**Comment by stewartadam** [comment]
Hi @MohitVerma-MSFT, perhaps it doesn't behave the same way on Unix-like OS -- here is my current `~/.azure/config`, as configured via the interactive `az configure` command for default table output:

```
[cloud]
name = AzureCloud

[defaults]

[core]
output = table
collect_telemetry = yes
cache_ttl = 10

[logging]
enable_log_file = no
```



`az configure --list-defaults -l` produces no output when I call it, despite `output = table` default being present in the config file.

If I run `az configure --defaults core.output=table`, that results in the following config file (note the command caused an entry to be added as `core.output` under `[default]`, not adjusting the value under `[core]` where it is required/used:
```
[cloud]
name = AzureCloud

[defaults]
core.output = table

[core]
output = table
collect_telemetry = yes
cache_ttl = 10

[logging]
enable_log_file = no
```

Note that after the invalid entry under `[default]` is created, it is now listed in the output of  `az configure --list-defaults`:
```
Name         Source                            Value
-----------  --------------------------------  -------
core.output  /Users/stewartadam/.azure/config  table
```

Although that setting under `[default]` has no real effect, as only the one under `[core]` is used by the Azure CLI. I can verify this by attempting to change the default output back to json using the same command mentioned in your post:
```
$ az configure --defaults core.output=json
$ az account list
Name                           CloudName    SubscriptionId                        State    IsDefault
-----------------------------  -----------  ------------------------------------  -------  -----------
msft-internal                  AzureCloud   <redacted>  Enabled  False
N/A(tenant level account)      AzureCloud   <redacted>  Enabled  False
```
It still uses table output, my config file looks as follows after that:
```
[cloud]
name = AzureCloud

[defaults]
core.output = json

[core]
output = table
collect_telemetry = yes
cache_ttl = 10

[logging]
enable_log_file = no
```

**Comment by jiasli** [comment]
Hi @stewartadam, I am the developer for `az configure`. `az configure --defaults` only works for the ` [defaults]` section in `~/.azure` file, as stated in [CLI configuration with az configure](https://docs.microsoft.com/en-us/cli/azure/azure-cli-configuration?view=azure-cli-latest#cli-configuration-with-az-configure). Currently for other sections, we need manually edit the file.

**Comment by jiasli** [comment]
We are glad to announce a new versatile command group [`az config`](https://docs.microsoft.com/en-us/cli/azure/config?view=azure-cli-latest). Also see our blog [_Azure CLI - az config and the new dynamic extension installer are now live_](https://techcommunity.microsoft.com/t5/azure-tools/azure-cli-az-config-and-the-new-dynamic-extension-installer-are/ba-p/1611913). Please check if this works for your scenario. If anything is not working as expected, please feel free to open an issue at https://github.com/Azure/azure-cli/issues.
