### ISSUE TITLE
Running "az vm list -g QueryDemo --query '[].{Name:name..." causes error

### ISSUE THREAD

**Issue by LyalinDotCom** [MicrosoftDocs/azure-docs-cli#1802]
Running command below leads to error.

Command:
C:\&gt;az vm list -g QueryDemo --query '[].{Name:name, OS:storageProfile.osDisk.osType, Admin:osProfile.adminUsername}' --output table

Error reported back:
az vm list: error: argument --query: invalid jmespath_type value: "'[].{Name:name,"
usage: az vm list [-h] [--verbose] [--debug]
                  [--output {json,jsonc,table,tsv,yaml,none}]
                  [--query JMESPATH] [--subscription _SUBSCRIPTION]
                  [--resource-group RESOURCE_GROUP_NAME] [--show-details]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e60c12ef-d293-5626-c7aa-c7e9241bf975
* Version Independent ID: 7acca1dd-b735-7e1f-afd9-2b5b6ea06b1c
* Content: [Query command results with Azure CLI](https://docs.microsoft.com/en-us/cli/azure/query-azure-cli?view=azure-cli-latest#feedback)
* Content Source: [docs-ref-conceptual/query-azure-cli.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/query-azure-cli.md)
* Product: **azure**
* Technology: **azure-cli**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by LyalinDotCom** [comment]
So a few more comments:

1. Playing more with this I realized that "QueryDemo" is the resource group name, this was very confusing perhaps we should replace this with something that stands out as a value the real query should replace.
2. It seems some of the column names might have changed in Azure causing errors that they cant be found in the path. This makes me think the docs need to be scrubbed for this in general (if im right) as the issue might be more then just this doc.

**Comment by BhargaviAnnadevara-MSFT** [comment]
@LyalinDotCom The exact same command gives me the expected output similar to what is mentioned in the doc.

Few things to note:
- The "-g" switch in the command denotes that the following parameter is the name of the resource group. This is also documented in the `az vm list` command [reference](https://docs.microsoft.com/en-us/cli/azure/vm?view=azure-cli-latest#az-vm-list).
- The az vm list command internally calls the [Virtual Machines - List](https://docs.microsoft.com/en-us/rest/api/compute/virtualmachines/list) API, that gets a list of virtual machines in the response, having the properties listed [here](https://docs.microsoft.com/en-us/rest/api/compute/virtualmachines/list#virtualmachine), and **Name** is definitely one of them.

To troubleshoot this issue further:
- Please let me know the version of Azure CLI that's on your client.
- Try executing the same from the [Azure Cloud Shell](https://shell.azure.com/bash).
- Enable --debug logs on the command as follows:
`az vm list -g QueryDemo --query '[].{Name:name, OS:storageProfile.osDisk.osType, Admin:osProfile.adminUsername}' --output table`

Let me know if you run into issues. Thanks.

**Comment by BhargaviAnnadevara-MSFT** [comment]
@LyalinDotCom Just following up to check if you've had a chance to verufy the above.

**Comment by BhargaviAnnadevara-MSFT** [comment]
@LyalinDotCom Please let us know if you're still blocked and we can troubleshoot further.

We will now proceed to close this thread as resolved, but if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.
