### ISSUE TITLE
Is the repo URL correct?

### ISSUE THREAD

**Issue by jude-chen** [MicrosoftDocs/azure-docs-cli#1812]
The repo URL in this document is "https://packages.microsoft.com/yumrepos/azure-cli" which is for YUM, is this correct? Should it be "https://packages.microsoft.com/opensuse/15/prod"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 26961ab6-af63-1bb9-53d1-566e4acc2896
* Version Independent ID: 2c26a785-ca52-321a-ba33-4622ed9d37a2
* Content: [Install the Azure CLI on Linux with zypper](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-zypper?view=azure-cli-latest#feedback)
* Content Source: [docs-ref-conceptual/install-azure-cli-zypper.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/install-azure-cli-zypper.md)
* Product: **azure**
* Technology: **azure-cli**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by jude-chen** [comment]
looks like the opesuse repo URL is not for azure-cli.

**Comment by KrishnaG-MSFT** [comment]
@jude-chen Thanks for the update. If there are further questions regarding this matter or feedback on the referred Azure documentation, please do let us know and we will gladly continue the discussion.
