### ISSUE TITLE
az <sub-command> list --query  - won't work

### ISSUE THREAD

**Issue by dariuszbz** [MicrosoftDocs/azure-docs-cli#1827]
az group list --query "[].{Name:name}?contains(Name,'EU')"

an error is:
az group list: error: argument --query: invalid jmespath_type value: "[].{Name:name}?contains(Name,'EU'"

in error message, there is no closing bracket - but it is in the command.

**Comment by dariuszbz** [comment]
and the following:
az group list --query "[].{Name:name}[?contains(Name,'EU')]" -o json

] was unexpected at this time.

**Comment by dariuszbz** [comment]
but it works fine from azure cloud shell (Powershell)m and won't work from visual studio code integrated terminal (my laptop)

**Comment by SamaraSoucy-MSFT** [comment]
@dariuszbz thank you for reporting the issue. I will take a look and get back with you shortly.

**Comment by SamaraSoucy-MSFT** [comment]
It's a known issue with Powershell itself unfortunately ([fairly long explanation here](https://stackoverflow.com/questions/562038/escaping-double-quotes-in-batch-script), and [similar issue with the cli here](https://github.com/Azure/azure-cli/issues/11320)). In particular, you'll notice it is stripping out the quotes in the query parameter. This means that when it is passed into the script that handles the JMESPath query it is no longer viewed as a string. My guess as to why it is working on the Cloud Shell is that is a Linux host which handles parameters a bit differently.

By escaping the quotes I was able to get the command to work in both VS Code and the Cloud Shell:
`az group list --query """[].{Name:name}[?contains(Name,'EU')]""" -o json`

I'm going to close the issue as it isn't docs related. If you have any further questions on this issue please tag me.
