### ISSUE TITLE
The script can also be downloaded

### ISSUE THREAD

**Issue by Katja2** [MicrosoftDocs/azure-docs-cli#1829]
A more detailed explanation of how and where to download the script from would be nice. Managed to download it anyhow.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7895b9a-9a6a-cd98-6947-0e4a26eda9a3
* Version Independent ID: a3f27295-3e2e-a36d-02c2-8897295fc443
* Content: [Install the Azure CLI for Linux manually](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-linux?view=azure-cli-latest#feedback)
* Content Source: [docs-ref-conceptual/install-azure-cli-linux.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/install-azure-cli-linux.md)
* Product: **azure**
* Technology: **azure-cli**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by BhargaviAnnadevara-MSFT** [comment]
@Katja2 Thanks for the question. The [install or update](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-linux?view=azure-cli-latest#install-or-update) section of the doc describes this.

Is there anything specific you'd like to see added?

**Comment by BhargaviAnnadevara-MSFT** [comment]
@Katja2 Any update here?

**Comment by BhargaviAnnadevara-MSFT** [comment]
@Katja2 We will now proceed to close this thread as resolved, but if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.
