### ISSUE TITLE
The steps "Update the zypper package index and install" should be updated

### ISSUE THREAD

**Issue by alextuncu** [MicrosoftDocs/azure-docs-cli#1836]
Running the indicated commnad in Suse Enterprise Server 12 fails.
As per the following post https://github.com/Azure/azure-cli/issues/9665#issuecomment-535304323 the new step is:
- Remove the -y option when install:
sudo zypper install --from azure-cli azure-cli
-  then input 2 to continue install.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 26961ab6-af63-1bb9-53d1-566e4acc2896
* Version Independent ID: 2c26a785-ca52-321a-ba33-4622ed9d37a2
* Content: [Install the Azure CLI on Linux with zypper](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-zypper?view=azure-cli-latest#feedback)
* Content Source: [docs-ref-conceptual/install-azure-cli-zypper.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/install-azure-cli-zypper.md)
* Service: **azure-cli**
* GitHub Login: @dbradish-microsoft
* Microsoft Alias: **dbradish**

**Comment by BhargaviAnnadevara-MSFT** [comment]
@alextuncu Thanks for the question! We're investigating this and will get back to you shortly.

**Comment by BhargaviAnnadevara-MSFT** [comment]
@alextuncu Thank you for bringing this to our attention! I have submitted a PR to fix the issue, the change is awaiting review and will reflect once merged.

**Comment by BhargaviAnnadevara-MSFT** [comment]
@alextuncu We will now proceed to close this thread as resolved, but if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.
