### ISSUE TITLE
This works in Ubuntu, but not in Elementary OS

### ISSUE THREAD

**Issue by katlimruiz** [MicrosoftDocs/azure-docs-cli#1842]
If you can add to documentation, would be best, but if not at least this comment will be public.

EOS fails to install azure cli, because lsb_release returns HERA (which is EOS release name, not Ubuntu).

The solution is to fix the file `/etc/apt/sources.list.d/azure-cli.list`  and change from `hera` to `bionic`.

`deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ hera main`

to

`deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ bionic main`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe1526a9-7f22-504e-484c-0f3edc11b178
* Version Independent ID: c5dec108-efcd-aa77-04b5-803b6b894dba
* Content: [Install the Azure CLI on Linux with apt](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-apt?view=azure-cli-latest#feedback)
* Content Source: [docs-ref-conceptual/install-azure-cli-apt.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/install-azure-cli-apt.md)
* Service: **azure-cli**
* GitHub Login: @dbradish-microsoft
* Microsoft Alias: **dbradish**

**Comment by SamaraSoucy-MSFT** [comment]
@katlimruiz I'm going to assign this to the doc author to update the documentation.

**Comment by dbradish-microsoft** [comment]
@katlimruiz , thank you for your feedback on this issue.  Your comments have been added to the article and will publish on Tuesday evening PST, March 31st.
