### ISSUE TITLE
[Feature Request] Add extension install instruction

### ISSUE THREAD

**Issue by Juliehzl** [MicrosoftDocs/azure-docs-cli#1860]
CLI team need install instruction for each extension to provide guidance for users.

Taking `db-up` for example, currently there is no instruction for extensions, as you can see in https://docs.microsoft.com/en-us/cli/azure/ext/db-up/?view=azure-cli-latest.

But to use the commands inside the extension, users have to install the extension with `az extension add` command as shown in https://docs.microsoft.com/en-us/azure/postgresql/quickstart-create-server-up-azure-cli#create-an-azure-database-for-postgresql-server.

CLI team hope you can help add this part for each extenison.

Related issue in CLI is https://github.com/Azure/azure-cli/issues/11629.

**Comment by MarileeTurscak-MSFT** [comment]
@Juliehzl 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by dbradish-microsoft** [comment]
Hello @juliehzl, this information is explained in **Use extensions with Azure CLI** --> https://docs.microsoft.com/en-us/cli/azure/azure-cli-extensions-overview.  I can see how this gets missed, however, so I am going to put this on my list for Reference and Extensions Reference enhancements.  Your suggestion would definitely add value to the Azure CLI reference content.
