### ISSUE TITLE
Make it Clear that Certificates for Service Principals need both Public and Private Key

### ISSUE THREAD

**Issue by pbstrein** [MicrosoftDocs/azure-docs-cli#1867]
There is no clear indication that Certificates uploaded to Azure need a public (certificate) and private key section to them. 

For example, in this [issue](https://github.com/Azure/azure-cli/issues/9970), one of the comments made it clear the format of the cert and how to generate the cert to show the proper format. This should be added to the documentation. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3f84bdc-9ed0-eb85-f3af-9711e8083a95
* Version Independent ID: 03a47d06-5fbf-4764-0882-99cd8bd41110
* Content: [Use Azure service principals with Azure CLI](https://docs.microsoft.com/en-us/cli/azure/create-an-azure-service-principal-azure-cli?view=azure-cli-latest)
* Content Source: [docs-ref-conceptual/create-an-azure-service-principal-azure-cli.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/create-an-azure-service-principal-azure-cli.md)
* Service: **azure-cli**
* GitHub Login: @dbradish-microsoft
* Microsoft Alias: **dbradish**

**Comment by kobulloc-MSFT** [comment]
@pbstrein ty,,

**Comment by dbradish-microsoft** [comment]
Hello @pbstrein , I agree and the updated articles are almost ready for publish.

**Comment by dbradish-microsoft** [comment]
I am closing this issue as both [Create an Azure service principal with Azure CLI ](https://docs.microsoft.com/en-us/cli/azure/create-an-azure-service-principal-azure-cli?view=azure-cli-latest) and [Sign in with Azure CLI](https://docs.microsoft.com/en-us/cli/azure/authenticate-azure-cli?view=azure-cli-latest) documents have been updated with additional information to provide better clarity.  These changes will publish on Tuesday, March 20th, 2020.
