### ISSUE TITLE
az aks browse change missed in the release note: March 10, 2020 

### ISSUE THREAD

**Issue by DreamRivulet** [MicrosoftDocs/azure-docs-cli#1891]
There was an implement change for the az aks browse command in the 2.2.0 release: 
https://github.com/Azure/azure-cli/pull/11804/commits/83397287f5bfb7d79154286ab17b85d77cf7920d#

which changed the az aks browse command to use kube proxy for accessing k8s dashboard. 
We should document this change since it will impact RBAC permissions to login k8s dashboard, as now it requires permissions on "services/proxy" resources, which were not required for port forwarding way.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0e8d9ef-f25b-bb46-7f1a-bd3588be3343
* Version Independent ID: cd392600-a90d-0145-5ea6-6b01ab8f4ab9
* Content: [Azure CLI release notes](https://docs.microsoft.com/en-us/cli/azure/release-notes-azure-cli?view=azure-cli-latest#aks)
* Content Source: [docs-ref-conceptual/release-notes-azure-cli.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/release-notes-azure-cli.md)
* Service: **azure-cli**
* GitHub Login: @dbradish-microsoft
* Microsoft Alias: **dbradish**

**Comment by MonikaReddy-MSFT** [comment]
@DreamRivulet , Thanks for brining this to our attention. We will investigate it further and update you shortly.

**Comment by MonikaReddy-MSFT** [comment]
@DreamRivulet , 
Thanks again for bringing this to our attention. We have created an [Issue](https://dev.azure.com/mseng/TechnicalContent/_workitems/edit/1701872) in our backlog to get it taken care of and it should be added once it is approved. 

So We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
