### ISSUE TITLE
Certificate error

### ISSUE THREAD

**Issue by ussantos** [MicrosoftDocs/azure-docs-cli#1899]
Hi, there is a problem with the certificate used on https://packages.microsoft.com, see bellow (I'm using opensuse leap 15.1 in wsl):

usantos@ussantos-sp3:/mnt/c/Users/uelli&gt; sudo rpm --import https://packages.microsoft.com/keys/microsoft.asc
curl: (60) SSL certificate problem: self signed certificate in certificate chain
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
error: https://packages.microsoft.com/keys/microsoft.asc: import read failed(2).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 26961ab6-af63-1bb9-53d1-566e4acc2896
* Version Independent ID: 2c26a785-ca52-321a-ba33-4622ed9d37a2
* Content: [Install the Azure CLI on Linux with zypper](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-zypper?view=azure-cli-latest)
* Content Source: [docs-ref-conceptual/install-azure-cli-zypper.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/install-azure-cli-zypper.md)
* Service: **azure-cli**
* GitHub Login: @dbradish-microsoft
* Microsoft Alias: **dbradish**

**Comment by ussantos** [comment]
To solve the problem It was necessary run sudo update-ca-certificates before import Microsoft Key, may be this tip could be an observation on documentation.

**Comment by BharathNimmala-MSFT** [comment]
@ussantos Thank you for your question, our team will further look into it and get back to you at the earliest.

**Comment by SamaraSoucy-MSFT** [comment]
@ussantos I'm glad you were able to resolve the issue. I'm going to assign this to the doc author to update appropriately.

**Comment by dbradish-microsoft** [comment]
@ussantos , The [Install Azure CLI with zipper](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-zypper) article has been updated to reflect your findings.  Changes will publish no later than Thursday of this week.  We appreciate your feedback.
