### ISSUE TITLE
additional required info

### ISSUE THREAD

**Issue by uffehellum** [MicrosoftDocs/azure-docs-cli#1900]
In order to manage pipelines, you also need:

`az extension add -n azure-devops`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d09ed623-c83f-6bae-639e-a5f9a31fe3bb
* Version Independent ID: c5d0d722-aacd-47a3-3fcf-982c02c4d0e9
* Content: [Install the Azure CLI for macOS](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-macos?view=azure-cli-latest#feedback)
* Content Source: [docs-ref-conceptual/install-azure-cli-macos.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/install-azure-cli-macos.md)
* Service: **azure-cli**
* GitHub Login: @dbradish-microsoft
* Microsoft Alias: **dbradish**

**Comment by PramodValavala-MSFT** [comment]
@uffehellum Thanks for the feedback! We will review and update accordingly.

**Comment by BhargaviAnnadevara-MSFT** [comment]
@uffehellum This doc details only the installation of Azure CLI on macOS.

Is your feedback to add this information here?

**Comment by BhargaviAnnadevara-MSFT** [comment]
@uffehellum This doc details only the installation of Azure CLI on macOS.

Adding the `azure-devops` extension is better suited and mentioned in [this](https://docs.microsoft.com/en-us/azure/devops/cli/?view=azure-devops) document.

**Comment by BhargaviAnnadevara-MSFT** [comment]
@uffehellum At this point, it appears that there are no edits or updates needed to the document in question. Hence closing this issue for now. If there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.
