### ISSUE TITLE
Webazopsdocs

### ISSUE THREAD

**Issue by WebAzOps** [MicrosoftDocs/azure-docs-cli#1926]

**Comment by RohitMungi-MSFT** [comment]
@WebAzOps It would be great if you could update the issue with more details to help you better.

**Comment by BhargaviAnnadevara-MSFT** [comment]
@WebAzOps Any update here? Please elaborate your issue so we can troubleshoot further.

**Comment by BhargaviAnnadevara-MSFT** [comment]
@WebAzOps We will now proceed to close this thread as resolved, but if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.
