### ISSUE TITLE
I love your documentation!

### ISSUE THREAD

**Issue by roshinirevindranathan** [MicrosoftDocs/azure-docs-cli#1945]
I am a Java developer using Azure for the first time. I have some professional experience using AWS and Openstack. By far, yours is the best documentation I have ever come across in comparison to the other cloud vendors. Well done! Keep up the good work!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d09ed623-c83f-6bae-639e-a5f9a31fe3bb
* Version Independent ID: c5d0d722-aacd-47a3-3fcf-982c02c4d0e9
* Content: [Install the Azure CLI for macOS](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-macos?view=azure-cli-latest#feedback)
* Content Source: [docs-ref-conceptual/install-azure-cli-macos.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/install-azure-cli-macos.md)
* Service: **azure-cli**
* GitHub Login: @dbradish-microsoft
* Microsoft Alias: **dbradish**

**Comment by BhargaviAnnadevara-MSFT** [comment]
@roshinirevindranathan Thank you so much for the feedback!

**Comment by BhargaviAnnadevara-MSFT** [comment]
@roshinirevindranathan Thank you so much for sharing your feedback! We are glad you found the document helpful! :)
