### ISSUE TITLE
Az-cli raises a SyntaxWarning after upgrade to Fedora 32

### ISSUE THREAD

**Issue by zale1983** [MicrosoftDocs/azure-docs-cli#1966]
after upgrade Fedora32, run az command wil raises SynataxWarning

/usr/lib64/az/lib/python3.6/site-packages/jmespath/visitor.py:32: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if x is 0 or x is 1:
/usr/lib64/az/lib/python3.6/site-packages/jmespath/visitor.py:32: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if x is 0 or x is 1:
/usr/lib64/az/lib/python3.6/site-packages/jmespath/visitor.py:34: SyntaxWarning: "is" with a literal. Did you mean "=="?
  elif y is 0 or y is 1:
/usr/lib64/az/lib/python3.6/site-packages/jmespath/visitor.py:34: SyntaxWarning: "is" with a literal. Did you mean "=="?
  elif y is 0 or y is 1:
/usr/lib64/az/lib/python3.6/site-packages/jmespath/visitor.py:260: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if original_result is 0:

this issues is fixed by jmespath 0.9.5
https://github.com/jmespath/jmespath.py/issues/187

Maybe this requirement document should be upgrade
https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/requirements.py3.Linux.txt

**Comment by MonikaReddy-MSFT** [comment]
@zale1983 , Thanks for brining this to our attention. We will investigate it further and update you shortly.

**Comment by MonikaReddy-MSFT** [comment]
@zale1983 -  Raised a PR, Once the PR is approved it should merge the changes. 

Thanks again for bringing this to our attention. We have updated the Doc and We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
