### ISSUE TITLE
Incompatible with Macports?

### ISSUE THREAD

**Issue by ShadSterling** [MicrosoftDocs/azure-docs-cli#1972]
I use macports.  After having to deal with macports and fink I'm not going to get into using macports and homebrew.  Since there's no macports package for azure-cli, I tried the manual install.  The install seemed to work, tho it did warn about chardetect, pyjwt, tabulate, pygmentize, inv, fab, humanfriendly, amd pkginfo being `installed in '/Users/polyergic/Library/Python/3.8/bin' which is not on PATH.` (I assume you included that in the changes you made to my PATH.)  All the `az` command will do is print `/Users/polyergic/lib/azure-cli/bin/python: Error while finding module specification for 'azure.cli' (ModuleNotFoundError: No module named 'azure')`

It looks like your documentation links go to submit issues for the documentation, not for the documented products.  Mostly I think it's the product that's not working.  For the documentation, it would be good if you covered how to install with macports (or just said sorry you can't use our CLI).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d09ed623-c83f-6bae-639e-a5f9a31fe3bb
* Version Independent ID: c5d0d722-aacd-47a3-3fcf-982c02c4d0e9
* Content: [Install the Azure CLI for macOS](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-macos?view=azure-cli-latest)
* Content Source: [docs-ref-conceptual/install-azure-cli-macos.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/install-azure-cli-macos.md)
* Service: **azure-cli**
* GitHub Login: @dbradish-microsoft
* Microsoft Alias: **dbradish**

**Comment by SamaraSoucy-MSFT** [comment]
Thanks for the feedback! We will review and get back to you shortly.

**Comment by BhargaviAnnadevara-MSFT** [comment]
@ShadSterling Thanks for the feedback. I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by dbradish-microsoft** [comment]
Hello, @ShadSterling , 

Azure CLI currently only provides macOS support through Homebrew.  Macports is not supported at this time.

Kindly,

Delora
