### ISSUE TITLE
Invalid "Azure CLI Terms of Use" link

### ISSUE THREAD

**Issue by beatcracker** [MicrosoftDocs/azure-docs-cli#1973]
`Azure CLI Terms of Use` link returns 404: https://aka.ms/AzureCliLegal

Possibly related to https://github.com/Azure/azure-cli/issues/7825

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb42002e-9aa3-233d-9832-353235b7cd0f
* Version Independent ID: e8b320b1-5805-67ba-46b2-48111861facc
* Content: [Azure CLI configuration options](https://docs.microsoft.com/en-us/cli/azure/azure-cli-configuration?view=azure-cli-latest)
* Content Source: [docs-ref-conceptual/azure-cli-configuration.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/azure-cli-configuration.md)
* Service: **azure-cli**
* GitHub Login: @dbradish-microsoft
* Microsoft Alias: **dbradish**

**Comment by SamaraSoucy-MSFT** [comment]
Thanks for the feedback! I have assigned the issue to the doc author to update appropriately.

**Comment by dbradish-microsoft** [comment]
@beatcracker , thank you for bringing this to our attention.  This link is being fixed and will publish on Thursday, May 14th, 2020.
