### ISSUE TITLE
Roles Clarification required.

### ISSUE THREAD

**Issue by porrascarlos802018** [MicrosoftDocs/azure-docs-cli#1979]
For assigning any roles to the service principal
as per this article only owner can do it Because 
the contributor even if it is network contributor 
shouldnt be able to do any other assigment.

Access assigment by design its reserved only to 
Subscription owners.

aks requires aks network contributor role
but who can assign it , someone with the right
access level to deal with permissions, meaning the owner.

If a contributor attempts to deal with access assignment will get this error
"Could not create a role assignment for subnet. Are you an Owner on this subscription?"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21632cd2-aec0-1521-a9b0-f96f69ab15ed
* Version Independent ID: d6ab81e8-1aba-b922-9984-4523386c83cf
* Content: [Manage Azure subscriptions with the Azure CLI](https://docs.microsoft.com/en-us/cli/azure/manage-azure-subscriptions-azure-cli?view=azure-cli-latest)
* Content Source: [docs-ref-conceptual/manage-azure-subscriptions-azure-cli.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/manage-azure-subscriptions-azure-cli.md)
* Service: **azure-cli**
* GitHub Login: @dbradish-microsoft
* Microsoft Alias: **dbradish**

**Comment by kobulloc-MSFT** [comment]
@porrascarlos802018 Thank you for the feedback!  We are investigating this and will get back to you shortly.

**Comment by kobulloc-MSFT** [comment]
@porrascarlos802018 This is a good question but outside of the scope for this document.  I would start off with the AKS documentation:
https://docs.microsoft.com/en-us/azure/aks/kubernetes-service-principal

Additionally, you'll want to check out the Active Directory documentation on service principals:
https://docs.microsoft.com/en-us/azure/active-directory/develop/app-objects-and-service-principals

If you still have questions, we have a forum specifically for Azure Kubernetes Service (AKS) where you can get more detailed answers for your AKS questions:
https://docs.microsoft.com/en-us/answers/topics/azure-kubernetes-service.html

**Comment by kobulloc-MSFT** [comment]
@porrascarlos802018 We are going to close this thread as resolved but if there are any further questions regarding this documentation, please tag me in your reply and we will be happy to continue the conversation.
