### ISSUE TITLE
Obsolete?

### ISSUE THREAD

**Issue by arvidcarlander** [MicrosoftDocs/azure-docs-cli#1987]
Hi, has not the Azure CLI been deprecated and replaced with az? If so, please note that on this page so people don't confuse the two.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d43769b4-5d99-c581-1f13-659bfabaf9ee
* Version Independent ID: a888b71c-7600-2cc6-bd4e-606107205c96
* Content: [What is Azure CLI?](https://docs.microsoft.com/en-us/cli/azure/what-is-azure-cli?view=azure-cli-latest#feedback)
* Content Source: [docs-ref-conceptual/what-is-azure-cli.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/what-is-azure-cli.md)
* Service: **azure-cli**
* GitHub Login: @dbradish-microsoft
* Microsoft Alias: **dbradish**

**Comment by BhargaviAnnadevara-MSFT** [comment]
@arvidcarlander I suppose you have mistaken Azure CLI with the [Az module](https://docs.microsoft.com/en-us/powershell/azure/new-azureps-module-az?view=azps-3.8.0) in PowerShell.
Please note that Azure CLI is still active and being updated regularly. In fact, the latest release happened as latest as a few hours ago. :)

Release notes are [here](https://docs.microsoft.com/en-us/cli/azure/release-notes-azure-cli?view=azure-cli-latest).

Please let me know if you need further information.

**Comment by BhargaviAnnadevara-MSFT** [comment]
@arvidcarlander Any additional questions here?

**Comment by BhargaviAnnadevara-MSFT** [comment]
@arvidcarlander Hope the above response helped. We will now proceed to close this thread as resolved, but if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.
