### ISSUE TITLE
Azure CLI install page information is not correct in zh-cn language.

### ISSUE THREAD

**Issue by Juliehzl** [MicrosoftDocs/azure-docs-cli#1991]
The version in https://docs.microsoft.com/zh-cn/cli/azure/install-azure-cli?view=azure-cli-latest
and https://docs.microsoft.com/en-us/cli/azure/install-azure-cli?view=azure-cli-latest are not the same.

**Comment by BhargaviAnnadevara-MSFT** [comment]
@Juliehzl Thank you very much for bringing this to our attention. I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by dbradish-microsoft** [comment]
@juliehzl, our Microsoft docs language translation team has informed me that this has been corrected.  Thank you very much for bringing this to our attention.
