### ISSUE TITLE
Updating Azure CLI

### ISSUE THREAD

**Issue by munseym** [MicrosoftDocs/azure-docs-cli#1992]
I would like to be able to update to the latest version by typing
az update

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8246b90a-efb1-03ce-f642-d3eb2441fc30
* Version Independent ID: 2fdd20ef-7bd3-57bc-7957-93f4bb5377ce
* Content: [Install the Azure CLI for Windows](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-windows?view=azure-cli-latest)
* Content Source: [docs-ref-conceptual/install-azure-cli-windows.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/install-azure-cli-windows.md)
* Service: **azure-cli**
* GitHub Login: @dbradish-microsoft
* Microsoft Alias: **dbradish**

**Comment by SamaraSoucy-MSFT** [comment]
@munseym Thank you for your feedback! This repository is specifically related to the Azure documentation. The product team is active on their repo and would be the appropriate place to request new features.
