### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by bowlerma** [MicrosoftDocs/azure-docs-cli#2000]
Hi,

I think it would be helpful if the documentation was updated with some details on how errors are reported/handled with Azure CLI, for example exit codes, use of stderr, etc.  There is a brief mention of exit codes https://github.com/Azure/azure-cli#exit-codes but would be useful if this was added to the documentation and expanded upon.

Thanks,

Mark

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c268a98-afcb-d2c2-87c7-880d52900533
* Version Independent ID: 4c835da4-38bc-22a8-67b4-dd522adcc0e3
* Content: [Get started with Azure CLI](https://docs.microsoft.com/en-us/cli/azure/get-started-with-azure-cli?view=azure-cli-latest)
* Content Source: [docs-ref-conceptual/get-started-with-azure-cli.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/get-started-with-azure-cli.md)
* Service: **azure-cli**
* GitHub Login: @dbradish-microsoft
* Microsoft Alias: **dbradish**

**Comment by BhargaviAnnadevara-MSFT** [comment]
@bowlerma Thank you for the feedback! I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by dbradish-microsoft** [comment]
@bowlerma , I think this is a great idea and have created a work item for a conceptual doc that just talks about error handling in the Azure CLI.  Thank you for taking the time to help make the Azure CLI even better.
