### ISSUE TITLE
Invoke-WebRequest Install Method

### ISSUE THREAD

**Issue by pegstr** [MicrosoftDocs/azure-docs-cli#2011]
Powershell needs to be restarted after executing the Invoke-WebRequest command. Docs should maybe mention this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8246b90a-efb1-03ce-f642-d3eb2441fc30
* Version Independent ID: 2fdd20ef-7bd3-57bc-7957-93f4bb5377ce
* Content: [Install the Azure CLI for Windows](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-windows?view=azure-cli-latest)
* Content Source: [docs-ref-conceptual/install-azure-cli-windows.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/install-azure-cli-windows.md)
* Service: **azure-cli**
* GitHub Login: @dbradish-microsoft
* Microsoft Alias: **dbradish**

**Comment by BhargaviAnnadevara-MSFT** [comment]
@pegstr Thanks for the question! We're investigating this and will get back to you shortly.

**Comment by dbradish-microsoft** [comment]
Hello, @pegstr 

There is a statement in the Install doc which reads "After the installation is complete, you will need to reopen PowerShell to use the Azure CLI."  Was there something else you had to do after installing the Azure CLI to get PowerShell to work for you?

https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-windows?view=azure-cli-latest#install-or-update

**Comment by pegstr** [comment]
No sorry my bad, somehow I missed the sentence. I can see it now. Restarting Powershell was the only action I needed to take in order for the Az CLI commands to start working.
