### ISSUE TITLE
Package to download and install azure cli

### ISSUE THREAD

**Issue by swethaps511** [MicrosoftDocs/azure-docs-cli#2019]
Hi, 
I see the link to install azure cli by curl | bash here : https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-linux?view=azure-cli-latest&source=docs

We have a requirement in our setup where we need a versioned downloadable packagee.
Is there is a downloadable package with specific version to download the same in .tar.gz or .zip format?

**Comment by BhargaviAnnadevara-MSFT** [comment]
@swethaps511 Thanks for the question! We're investigating this and will get back to you shortly.

**Comment by BhargaviAnnadevara-MSFT** [comment]
@swethaps511 Depending on the distribution and package manager you're working with, you can get the specific version from https://packages.microsoft.com.

For example, for Linux distributions with yum such as RHEL, Fedora, or CentOS, you can get the required version from https://packages.microsoft.com/yumrepos/azure-cli/ and then install with the `yum install` command.

The same assets in `.zip` and `.tar.gz` can be found on the Releases page of the Azure CLI repo here: https://github.com/Azure/azure-cli/releases

**Comment by BhargaviAnnadevara-MSFT** [comment]
@swethaps511 Hope the above inputs help. Are there any further questions here?

**Comment by BhargaviAnnadevara-MSFT** [comment]
@swethaps511 We will now proceed to close this thread as resolved, but if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.
