### ISSUE TITLE
No Window is prompting after az login 

### ISSUE THREAD

**Issue by cepcruzz** [MicrosoftDocs/azure-docs-cli#2020]
[Team,

No window is prompting after executing az login for me to login interactively on az cli. Using ubuntu 18.04.4]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93174b3a-3e97-8304-83fc-807be75198fe
* Version Independent ID: 1155045b-ce8c-2def-7b0e-043283f8be01
* Content: [Sign in with the Azure CLI](https://docs.microsoft.com/en-us/cli/azure/authenticate-azure-cli?view=azure-cli-latest)
* Content Source: [docs-ref-conceptual/authenticate-azure-cli.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/authenticate-azure-cli.md)
* Service: **azure-cli**
* GitHub Login: @dbradish-microsoft
* Microsoft Alias: **dbradish**

**Comment by BhargaviAnnadevara-MSFT** [comment]
@cepcruzz Thanks for the question! We're investigating this and will get back to you shortly.

**Comment by BhargaviAnnadevara-MSFT** [comment]
@cepcruzz If for some reason the CLI cannot open your default browser, it should still let you login using the old authentication flow based on device code.

You can run the command: `az login --use-device-code` to not default to interactive login. You can then browse to https://aka.ms/devicelogin and enter the authorization code displayed in your terminal.

If it is not a Microsoft account or does not have two-factor authentication enabled, you can even use `az login -u <username> -p <password>`. Other options are detailed [here](https://docs.microsoft.com/en-us/cli/azure/reference-index?view=azure-cli-latest#az-login).

**Comment by BhargaviAnnadevara-MSFT** [comment]
@cepcruzz Hope the above inputs help. Are there any further questions here?

**Comment by BhargaviAnnadevara-MSFT** [comment]
@cepcruzz We will now proceed to close this thread as resolved, but if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.
