### ISSUE TITLE
Download MSI link is broken.  Please fix. 

### ISSUE THREAD

**Issue by kennetherland** [MicrosoftDocs/azure-docs-cli#2028]

**Comment by BhargaviAnnadevara-MSFT** [comment]
@kennetherland Thank you for letting us know. In order to best address your question, could you provide us with the URL of the MS Doc that you were following, if any?

**Comment by BhargaviAnnadevara-MSFT** [comment]
If it is the MSI installer for Azure CLI for Windows, I've verified that both links work on this page: [Install Azure CLI on Windows](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-windows?view=azure-cli-latest)

Please give it another try, and do let us know if you see issues.

**Comment by BhargaviAnnadevara-MSFT** [comment]
@kennetherland We will now proceed to close this thread as resolved, but if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.
