### ISSUE TITLE
Last two links on this page are redirecting to German web pages

### ISSUE THREAD

**Issue by MicheleHope** [MicrosoftDocs/azure-docs-cli#2030]
When I tried to click on the last two links on this page (in the last sentence), they redirected me to German web pages.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93174b3a-3e97-8304-83fc-807be75198fe
* Version Independent ID: 1155045b-ce8c-2def-7b0e-043283f8be01
* Content: [Sign in with the Azure CLI](https://docs.microsoft.com/en-us/cli/azure/authenticate-azure-cli?view=azure-cli-latest)
* Content Source: [docs-ref-conceptual/authenticate-azure-cli.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/authenticate-azure-cli.md)
* Service: **azure-cli**
* GitHub Login: @dbradish-microsoft
* Microsoft Alias: **dbradish**

**Comment by BryanTrach-MSFT** [comment]
@MicheleHope Thanks for the feedback! We are currently investigating and will update you shortly.

**Comment by dbradish-microsoft** [comment]
@MicheleHope , I tested the last two URLs on the [Sign in with the Azure CLI](https://docs.microsoft.com/en-us/cli/azure/authenticate-azure-cli?view=azure-cli-latest):

Note that this URL is specifying /**en-us**/

This is the last sentence in the doc containing two URLS:
"
To learn more about managed identities for Azure resources, see [Configure managed identities for Azure resources](https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/qs-configure-cli-windows-vm) and [Use managed identities for Azure resources for sign in](https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/how-to-use-vm-sign-in).
"

If you are opening [Sign in with the Azure CLI](https://docs.microsoft.com/en-us/cli/azure/authenticate-azure-cli?view=azure-cli-latest) having /**en-us**/ in the URL, the embedded links will take you to docs.microsoft.com/***en-us***/azure/active-directory/managed-identities-azure-resources/qs-configure-cli-windows-vm and docs.microsoft.com/***en-us***/azure/active-directory/managed-identities-azure-resources/how-to-use-vm-sign-in respectively.

Please provide all three URLs (document, link 1 and link 2) for further assistance.

Kindly,

Delora

**Comment by MicheleHope** [comment]
@dbradish-microsoft -- This issue seems to have been transient and has since been resolved upon refresh. Thanks for looking into it. Strange!
