### ISSUE TITLE
after installing azurecli through powershell az command not working

### ISSUE THREAD

**Issue by mohamednazar** [MicrosoftDocs/azure-docs-cli#2039]
[after installing azurecli through powershell az command not working]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8246b90a-efb1-03ce-f642-d3eb2441fc30
* Version Independent ID: 2fdd20ef-7bd3-57bc-7957-93f4bb5377ce
* Content: [Install the Azure CLI for Windows](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-windows?view=azure-cli-latest&tabs=azure-cli)
* Content Source: [docs-ref-conceptual/install-azure-cli-windows.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/install-azure-cli-windows.md)
* Product: **azure**
* Technology: **azure-cli**
* GitHub Login: @dbradish-microsoft
* Microsoft Alias: **dbradish**

**Comment by BhargaviAnnadevara-MSFT** [comment]
@mohamednazar Thanks for the question! We're investigating this and will get back to you shortly.

**Comment by BhargaviAnnadevara-MSFT** [comment]
@mohamednazar Could you please elaborate the steps you've followed and error you see, possibly including a screenshot?

**Comment by BhargaviAnnadevara-MSFT** [comment]
@mohamednazar Any update here?

**Comment by dbradish-microsoft** [comment]
@mohamednazar , after the installation is complete, you will need to reopen PowerShell to use the Azure CLI.  With PowerShell restarted, are you still experiencing the issue?

**Comment by mohamednazar** [comment]
The installation was not success in my earlier approaches. Now all looks good. Thanks, you can close this.
