### ISSUE TITLE
RSS/Atom Feed

### ISSUE THREAD

**Issue by drdamour** [MicrosoftDocs/azure-docs-cli#2054]
Is there an RSS/Atom feed of release WITH the version notes, we like to have them appear in our MS Teams channels.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0e8d9ef-f25b-bb46-7f1a-bd3588be3343
* Version Independent ID: cd392600-a90d-0145-5ea6-6b01ab8f4ab9
* Content: [Azure CLI release notes](https://docs.microsoft.com/en-us/cli/azure/release-notes-azure-cli?view=azure-cli-latest&tabs=azure-cli)
* Content Source: [docs-ref-conceptual/release-notes-azure-cli.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/release-notes-azure-cli.md)
* Service: **azure-cli**
* GitHub Login: @dbradish-microsoft
* Microsoft Alias: **dbradish**

**Comment by BharathNimmala-MSFT** [comment]
@drdamour Thank you for reaching out to us, our team will look into your query and get back to you at the earliest.

**Comment by dbradish-microsoft** [comment]
Hello, @drdamour, I have double-checked with the Azure CLI engineering team and we do not have a RSS feed for our release notes or reference content.  However, they have made a note of your request.
