### ISSUE TITLE
https://azurecliprod.blob.core.windows.net/  bad uri ?

### ISSUE THREAD

**Issue by ehsf973** [MicrosoftDocs/azure-docs-cli#2056]
https://azurecliprod.blob.core.windows.net/ 
the url to download the azure cli package give me that, instead :
[Enter feedback here]
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>InvalidQueryParameterValue</Code>
<Message>Value for one of the query parameters specified in the request URI is invalid. RequestId:ca7583e3-301e-008d-2d19-4ef642000000 Time:2020-06-29T13:33:01.8981173Z</Message>
<QueryParameterName>comp</QueryParameterName>
<QueryParameterValue/>
<Reason/>
</Error>

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8246b90a-efb1-03ce-f642-d3eb2441fc30
* Version Independent ID: 2fdd20ef-7bd3-57bc-7957-93f4bb5377ce
* Content: [Install the Azure CLI for Windows](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-windows?view=azure-cli-latest&tabs=azure-cli)
* Content Source: [docs-ref-conceptual/install-azure-cli-windows.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/install-azure-cli-windows.md)
* Product: **azure**
* Technology: **azure-cli**
* GitHub Login: @dbradish-microsoft
* Microsoft Alias: **dbradish**

**Comment by MonikaReddy-MSFT** [comment]
@ehsf973 ,  Thanks for brining this to our attention. We will investigate it further and update you shortly.

**Comment by dbradish-microsoft** [comment]
Hello, @ehsf973, could you please provide the first URL you are executing? -- "https://azurecliprod.blob.core.windows.net/" is not part of the source code on the Windows Install page, so the URL you provided must be a redirect.  If you are unable to get to the two URLs provided below, something in your ISP, VPN or company Internet rules may be blocking you.

To download the Azure CLI current version, please use https://aka.ms/installazurecliwindows

To download the Azure CLI beta version, please use https://aka.ms/installazurecliwindowsbeta

**Comment by ehsf973** [comment]
i don't know this is a click button in the doc page i do not have an
explicit url before rhe uri below and the xml parsing error.

Le lun. 29 juin 2020 à 18:58, Delora Bradish <notifications@github.com> a
écrit :

**Comment by dbradish-microsoft** [comment]
@ehsf973 , If you are clicking on either Install button in [Install the Azure CLI for Windows](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-windows?view=azure-cli-latest&tabs=azure-cli) article and are receiving an error, the issue is with your ISP, VPN or company Internet rules.  Both links on the page have been tested and provide the intended result.  I suggest navigating to https://aka.ms/installazurecliwindows outside of your company domain or through a different Internet browser.

**Comment by MonikaReddy-MSFT** [comment]
@dbradish-microsoft - Thank you for providing your insights. 
@ehsf973 - Thanks again for bringing this to our attention.  We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
