### ISSUE TITLE
Old Service Principal Credentials can still login after AKS SP is reset

### ISSUE THREAD

**Issue by DreamRivulet** [MicrosoftDocs/azure-docs-cli#2076]
How to reproduce the issue?
- Create an AKS cluster on azure portal(let AKS creates a new SP automatically):
![image](https://user-images.githubusercontent.com/11328236/87306593-d29d5700-c54a-11ea-84ca-e9217c6bc162.png)

-  Follow the document https://docs.microsoft.com/en-us/azure/aks/update-credentials#reset-existing-service-principal-credential to reset the AKS cluster SP:
    $ SP_ID=$(az aks show --resource-group myResourceGroup --name myAKSCluster --query servicePrincipalProfile.clientId -o tsv)
    $ SP_SECRET=$(az ad sp credential reset --name $SP_ID --query password -o tsv) 
    $ az aks update-credentials --resource-group myResourceGroup --name myAKSCluster --reset-service-principal --service-principal $SP_ID --client-secret $SP_SECRET

Then I can still az login with the old SP credentials after the SP was reset successfully, and i can't delete this old password as i can't see this old one from my side.

This will cause security issues since the old SP password still works even after the SP is reset.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3f84bdc-9ed0-eb85-f3af-9711e8083a95
* Version Independent ID: 03a47d06-5fbf-4764-0882-99cd8bd41110
* Content: [Use Azure service principals with Azure CLI](https://docs.microsoft.com/en-us/cli/azure/create-an-azure-service-principal-azure-cli?view=azure-cli-latest#reset-credentials)
* Content Source: [docs-ref-conceptual/create-an-azure-service-principal-azure-cli.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/create-an-azure-service-principal-azure-cli.md)
* Service: **azure-cli**
* GitHub Login: @dbradish-microsoft
* Microsoft Alias: **dbradish**

**Comment by BhargaviAnnadevara-MSFT** [comment]
@DreamRivulet Thanks for the question! We're investigating this and will get back to you shortly.

**Comment by jiasli** [comment]
This is a known issue that `az ad sp credential reset` doesn't take effect immediately because **AAD service needs some time to propagate**.

@DreamRivulet, does the password expire eventually after several seconds (sometimes several minutes)?
