### ISSUE TITLE
device login details need more info

### ISSUE THREAD

**Issue by MarcAir** [MicrosoftDocs/azure-docs-cli#2093]
bash terminal
ProductName:	Mac OS X
ProductVersion:	10.15.6
BuildVersion:	19G73

azure-cli                          2.9.1
command-modules-nspkg              2.0.3
core                               2.9.1
nspkg                              3.0.4
telemetry                          1.0.4

Python location '/usr/local/Cellar/azure-cli/2.9.1/libexec/bin/python'
Extensions directory '/Users/<usrnm>/.azure/cliextensions'

Python (Darwin) 3.8.4 (default, Jul 14 2020, 02:58:48) 
[Clang 11.0.3 (clang-1103.0.32.62)]

no information on page on how to use https://aka.ms/devicelogin
bash on cloudshell shows a device code, but on macos terminal, no info is provided. 
there are no pages on how to use this service either. there should be details on troubleshooting this type of problem when this is the only method for signing in using cli as other methods do not work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93174b3a-3e97-8304-83fc-807be75198fe
* Version Independent ID: 1155045b-ce8c-2def-7b0e-043283f8be01
* Content: [Sign in with the Azure CLI](https://docs.microsoft.com/en-us/cli/azure/authenticate-azure-cli?view=azure-cli-latest)
* Content Source: [docs-ref-conceptual/authenticate-azure-cli.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/authenticate-azure-cli.md)
* Service: **azure-cli**
* GitHub Login: @dbradish-microsoft
* Microsoft Alias: **dbradish**

**Comment by MonikaReddy-MSFT** [comment]
@MarcAir - Thanks for brining this to our attention. We will investigate it further and update you shortly.

**Comment by jiasli** [comment]
On MacOS, `az login` will open the default browser and wait for the login process to finish. 

Previously `az login` will show a message indicating a browser has been opened:

> Note, we have launched a browser for you to login. For old experience with device code, use "az login --use-device-code".

But that warning was removed later in https://github.com/Azure/azure-cli/pull/10851. Perhaps it is not a good idea to remove that warning. 

I am considering perhaps we need to add it back. @achandmsft @chenlomis

**Comment by MonikaReddy-MSFT** [comment]
@MarcAir - 
Thanks again for bringing this to our attention. We have raised a PR and it will be live once its merged.  We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
