### ISSUE TITLE
Tips for using CLI effectively link goes to a page not found

### ISSUE THREAD

**Issue by code2mars** [MicrosoftDocs/azure-docs-cli#2100]
Clicking on **Tips for using CLI effective** takes to a page saying Not found. seems like the link is broken

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e60c12ef-d293-5626-c7aa-c7e9241bf975
* Version Independent ID: 7acca1dd-b735-7e1f-afd9-2b5b6ea06b1c
* Content: [Query command results with Azure CLI](https://docs.microsoft.com/en-au/cli/azure/query-azure-cli?view=azure-cli-latest&viewFallbackFrom=azure-devops)
* Content Source: [docs-ref-conceptual/query-azure-cli.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/query-azure-cli.md)
* Service: **azure-cli**
* GitHub Login: @dbradish-microsoft
* Microsoft Alias: **dbradish**

**Comment by kobulloc-MSFT** [comment]
@code2mars Thank you for the feedback!  We are investigating this and will get back to you shortly.

**Comment by kobulloc-MSFT** [comment]
@code2mars Thank you for bringing this to our attention!  It looks like the page in question was named using underscores instead of dashes.  I'll get this updated but for the time being, you can access the page at:

https://docs.microsoft.com/en-au/cli/azure/use_cli_effectively

**Comment by kobulloc-MSFT** [comment]
@code2mars The fix for the link on the navigation bar should be updated shortly.  Thank you again for bringing this to our attention!

We are going to close this thread as resolved but if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.
