### ISSUE TITLE
Service Principal Association With Resources

### ISSUE THREAD

**Issue by blessedwithsins** [MicrosoftDocs/azure-docs-cli#2116]
[Enter feedback here]

Hi Team,

Is there a way to find associated resources with a Service Principal? 

We're getting several support requests where customer isn't aware where a Service Principal is in use. Please let me know if we have something regarding it.

Please get in touch with me [pigaur@microsoft,com](url). 

Regards,
Piyush Gaur 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3f84bdc-9ed0-eb85-f3af-9711e8083a95
* Version Independent ID: 03a47d06-5fbf-4764-0882-99cd8bd41110
* Content: [Use Azure service principals with Azure CLI](https://docs.microsoft.com/en-us/cli/azure/create-an-azure-service-principal-azure-cli?view=azure-cli-latest)
* Content Source: [docs-ref-conceptual/create-an-azure-service-principal-azure-cli.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/create-an-azure-service-principal-azure-cli.md)
* Service: **azure-cli**
* GitHub Login: @dbradish-microsoft
* Microsoft Alias: **dbradish**

**Comment by BhargaviAnnadevara-MSFT** [comment]
@blessedwithsins Thanks for the question! We're investigating this and will get back to you shortly.

**Comment by BhargaviAnnadevara-MSFT** [comment]
@blessedwithsins That's an interesting question!

As such, resources themselves are not associated to Service Principals (SPs), but the operations performed by SPs are, i.e., when any CUD-like action is performed, it is recorded in the [Administrative category](https://docs.microsoft.com/en-us/azure/azure-monitor/platform/activity-log-schema#administrative-category) under [Azure Activity Logs](https://docs.microsoft.com/en-us/azure/azure-monitor/platform/activity-log).

For example:
The "Event Initiated by" column in the screenshot below shows the name of the Service Principal/user that had performed the operation:
![image](https://user-images.githubusercontent.com/44050820/89445331-9f786d00-d770-11ea-907b-9dea8e3b51ce.png)

However, AFAIK, SP sign-in actions are not being recorded as of today. [Here](https://feedback.azure.com/forums/223579-azure-portal/suggestions/33867259-azure-ad-sign-in-activity-log-should-record-and-sh) is the related feature request on the User Voice Forum.

Hope this helps!

**Comment by BhargaviAnnadevara-MSFT** [comment]
@blessedwithsins We will now proceed to close this thread as resolved, but if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.

Also, on a side note, I'd like to let you know that this channel (the [azure-docs-cli](https://github.com/MicrosoftDocs/azure-docs-cli) repository) is only for driving improvements related to the Azure CLI documentation. The best place for specific answers about implementations is going to be the [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/index.html) platform. We actively look through posts in the forums, and will do our best to get you going in the right direction.

**Comment by jiasli** [comment]
@blessedwithsins, Thank you for reaching Azure CLI team.

The way @BhargaviAnnadevara-MSFT provided is great for checking Activity Logs which contains the operations initiated by a Service Principal.

As for (static) permissions, you may also use `az role assignment list` to check the permissions the Service Principal has.

For example, first create a Service Principal and assign it the **contributor** permission to the selected subscription with `az ad sp create-for-rbac`:

```
> az ad sp create-for-rbac
Creating a role assignment under the scope of "/subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590"
  Retrying role assignment creation: 1/36
{
  "appId": "fe2806ed-379d-43b9-88cc-d23368a87de0",
  "displayName": "azure-cli-2020-08-07-03-23-18",
  "name": "http://azure-cli-2020-08-07-03-23-18",
  "password": "xxx",
  "tenant": "54826b22-38d6-4fb2-bad9-b7b93a3e9c5a"
}
```

Then you may list the permission with `az role assignment list`:

```
> az role assignment list --assignee fe2806ed-379d-43b9-88cc-d23368a87de0 --all
[
  {
    "canDelegate": null,
    "id": "/subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/providers/Microsoft.Authorization/roleAssignments/a7d71d52-c222-4e2f-8ee3-a8ebbfbd8305",
    "name": "a7d71d52-c222-4e2f-8ee3-a8ebbfbd8305",
    "principalId": "9ec9777a-d786-409e-91c4-da25125576e4",
    "principalName": "http://azure-cli-2020-08-07-03-23-18",
    "principalType": "ServicePrincipal",
    "roleDefinitionId": "/subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/providers/Microsoft.Authorization/roleDefinitions/b24988ac-6180-42a0-ab88-20f7382dd24c",
    "roleDefinitionName": "Contributor",
    "scope": "/subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590",
    "type": "Microsoft.Authorization/roleAssignments"
  }
]
```

If you have need any help regarding these commands, please don't hesitate to reply here to let us know.

**Comment by blessedwithsins** [comment]
@jiasli Thank you for sharing the information. However, I were looking more information on how to get a list of resources associated with a Service Principal via Command Line or Azure Portal.

Activity Log details will capture if action is performed via a Service Principal. If it's performed by a person having Owner/Contributor access, it logs the activity with your credential, not for Service Principal. 

as @BhargaviAnnadevara-MSFT mentioned earlier, I will register the issue with Azure AD team if they can get something for me.
