### ISSUE TITLE
Installed .msi, but 'az' is not recognized as the name of a cmdlet, function, script file, or operable program.

### ISSUE THREAD

**Issue by yum-feng** [MicrosoftDocs/azure-docs-cli#2149]
I ran the command as instructed, `Invoke-WebRequest -Uri https://aka.ms/installazurecliwindows -OutFile .\AzureCLI.msi; Start-Process msiexec.exe -Wait -ArgumentList '/I AzureCLI.msi /quiet'; rm .\AzureCLI.msi` and the installation seems to have worked without errors.

I restarted powershell, and tried run "az login" but PowerShell does not recognize this command. Same thing on Command Prompt.

I'm running Windows  10 Pro, version 1909, Os Build 18363.1016 and my powershell version is 5.1.18362.752.

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8246b90a-efb1-03ce-f642-d3eb2441fc30
* Version Independent ID: 2fdd20ef-7bd3-57bc-7957-93f4bb5377ce
* Content: [Install the Azure CLI for Windows](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-windows?view=azure-cli-latest&tabs=azure-powershell)
* Content Source: [docs-ref-conceptual/install-azure-cli-windows.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/install-azure-cli-windows.md)
* Product: **azure**
* Technology: **azure-cli**
* GitHub Login: @dbradish-microsoft
* Microsoft Alias: **dbradish**

**Comment by HarshitaSingh-MSFT** [comment]
@yum-feng , 'az login' is an Azure CLI command. It is not an Azure Powershell command. 

- Yes, you are right, I have validated by running this command and it does not work as expected :
   ```
   Invoke-WebRequest -Uri https://aka.ms/installazurecliwindows -OutFile .\AzureCLI.msi; Start-Process msiexec.exe -Wait -ArgumentList '/I AzureCLI.msi /quiet'; rm .\AzureCLI.msi`
   ```
  I have raised a query about this to the product's team.

  You can meanwhile download Azure CLI .msi file from [here](https://aka.ms/installazurecliwindows) - I have verified and it works and recognizes "Az"

- If you want to use Az in powershell, you will have to install Az Powershell module and then connect to Azure like this :

  ```
  Install-Module -Name Az -AllowClobber
  Connect-AzAccount
  ```

**Comment by HarshitaSingh-MSFT** [comment]
@yum-feng , Just checking in to see if you have had a chance to see the previous response.

**Comment by HarshitaSingh-MSFT** [comment]
@yum-feng , Just checking in to see if you have had a chance to see the previous response.

**Comment by HarshitaSingh-MSFT** [comment]
@yum-feng , since we have not heard back from you we will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply and we will gladly continue the discussion.
