### ISSUE TITLE
Incorrect parameter specified in examples - no url only uri available for az rest

### ISSUE THREAD

**Issue by vairakkumar-vairaperumal** [MicrosoftDocs/azure-docs-cli#2151]
https://docs.microsoft.com/en-us/cli/azure/use-cli-effectively?view=azure-cli-latest#rest-api-command---az-rest
Incorrect parameter specified in examples - no url only uri available for az rest
For example, the following is correct using uri instead of url as documented.

```
az rest --method GET \
 --uri 'https://graph.microsoft.com/v1.0/applications/b4e4d2ab-e2cb-45d5-a31a-98eb3f364001'
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e51daa3-30c5-f449-36a1-9f33c70ca2fc
* Version Independent ID: a21e188b-4ff4-0aca-531b-d4b179665be1
* Content: [Tips for using Azure CLI effectively](https://docs.microsoft.com/en-us/cli/azure/use-cli-effectively?view=azure-cli-latest)
* Content Source: [docs-ref-conceptual/use-cli-effectively.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/use-cli-effectively.md)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by Grace-MacJones-MSFT** [comment]
Hi @vairakkumar-vairaperumal, Thanks for the feedback! We are currently investigating and will update you shortly.

**Comment by MonikaReddy-MSFT** [comment]
@vairakkumar-vairaperumal - 
Thanks again for bringing this to our attention. We have updated the Doc and it will be live once its merged.  We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
