### ISSUE TITLE
What is a tenant? How to configure it?

### ISSUE THREAD

**Issue by olivierpons** [MicrosoftDocs/azure-docs-cli#2154]
You may add a description with the `The following tenants don't contain accessible subscriptions. Use 'az login --allow-no-subscriptions' to have tenant level access.` problem (I guess I'm not the only one who has ever had this).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93174b3a-3e97-8304-83fc-807be75198fe
* Version Independent ID: 1155045b-ce8c-2def-7b0e-043283f8be01
* Content: [Sign in with the Azure CLI](https://docs.microsoft.com/en-us/cli/azure/authenticate-azure-cli?view=azure-cli-latest)
* Content Source: [docs-ref-conceptual/authenticate-azure-cli.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/authenticate-azure-cli.md)
* Service: **azure-cli**
* GitHub Login: @dbradish-microsoft
* Microsoft Alias: **dbradish**

**Comment by kobulloc-MSFT** [comment]
@olivierpons The official answer to those questions ("What is a tenant? How do I configure it?") is in our Active Directory documenation:

https://docs.microsoft.com/en-us/azure/active-directory/develop/quickstart-create-new-tenant

Tenants and subscriptions can be a confusing topic for people who are just starting out with Azure.  I'll update this with a better description but the short answer is that a tenant can contain multiple subscriptions, but a subscription can only be in one tenant.

**Comment by kobulloc-MSFT** [comment]
@olivierpons I would encourage you to look over the links above as they should give you a better understanding of tenants in Azure.  We are going to close this thread as resolved but if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.
