### ISSUE TITLE
Should I use the CLI MSI installer or `Install Modules`

### ISSUE THREAD

**Issue by mikeblakeuk** [MicrosoftDocs/azure-docs-cli#2174]
For Windows 10, PowerShell 7.
As a developer, should I use the CLI msi installer or Install Modules? 
What is the difference?
https://docs.microsoft.com/en-us/powershell/azure/install-az-ps?view=azps-4.6.1#install-the-azure-powershell-module

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8246b90a-efb1-03ce-f642-d3eb2441fc30
* Version Independent ID: 2fdd20ef-7bd3-57bc-7957-93f4bb5377ce
* Content: [Install the Azure CLI for Windows](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-windows?view=azure-cli-latest&tabs=azure-cli)
* Content Source: [docs-ref-conceptual/install-azure-cli-windows.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/install-azure-cli-windows.md)
* Product: **azure**
* Technology: **azure-cli**
* GitHub Login: @dbradish-microsoft
* Microsoft Alias: **dbradish**

**Comment by BhargaviAnnadevara-MSFT** [comment]
@mikeblakeuk Thanks for the question! We're investigating this and will get back to you shortly.

**Comment by BhargaviAnnadevara-MSFT** [comment]
@mikeblakeuk I understand from the [referenced doc](https://docs.microsoft.com/en-us/powershell/azure/install-az-ps?view=azps-4.6.1#install-the-azure-powershell-module) that you intend to install the **Azure PowerShell** module, and not Azure CLI.

However, the recommended way to install Azure PowerShell is with **PowerShellGet**. The MSI installer is provided for environments where the PowerShell Gallery may be blocked by a firewall, or an offline installer is needed.

Also, the MSI installer on Windows is designed to install Azure PowerShell for **PowerShell 5.1 only**. For installation on non-Windows platforms or later versions of PowerShell (PowerShell 7 in your case), please [install with PowerShellGet](https://docs.microsoft.com/en-us/powershell/azure/install-az-ps?view=azps-4.6.1#install-the-azure-powershell-module).

Also, on a side note, I'd like to let you know that this channel (the [Azure Docs CLI](https://github.com/MicrosoftDocs/azure-docs) repository) is only for driving improvements related to the Azure CLI documentation. For further questions on Azure PowerShell docs, please open an issue against the [Azure PowerShell Docs](https://github.com/MicrosoftDocs/azure-docs-powershell) repository.

**Comment by BhargaviAnnadevara-MSFT** [comment]
@mikeblakeuk Hope the above inputs helped.

We will now proceed to close this thread as resolved, but if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.
