### ISSUE TITLE
Tab Completion in Azure CLI does not work

### ISSUE THREAD

**Issue by pratapscil** [MicrosoftDocs/azure-docs-cli#2198]
Tab Completion in Azure CLI does not work as it used to work on Azure PowerShell or PowerShell. Tab completion provides automatic help when you are typing in the command pane and  pressing TAB will automatically complete a command. I am using latest version of Azure CLI on Windows 10. 

azure-cli                         2.12.0
core                              2.12.0
telemetry                          1.0.6

**Comment by BhargaviAnnadevara-MSFT** [comment]
@pratapscil Thanks for the feedback. Azure CLI's Intellisense or auto-complete feature is not supported on Windows. It only works with Linux Bash as of today.

Having said that, you could use auto-complete with Azure CLI commands on [WSL](https://docs.microsoft.com/en-us/windows/wsl/install-win10) or on **VS Code** using [WSL Bash](https://code.visualstudio.com/docs/remote/wsl#_opening-a-terminal-in-wsl) by updating your editor's [settings.json](https://code.visualstudio.com/docs/editor/integrated-terminal#_windows) file:

`"terminal.integrated.shell.windows": "C:\\WINDOWS\\System32\\wsl.exe",`

![wsl_cli](https://user-images.githubusercontent.com/44050820/94046956-fe607700-fdee-11ea-972a-bebfd79c0c5d.gif)

@jiasli Please add any additional inputs you may have.

**Comment by BhargaviAnnadevara-MSFT** [comment]
@pratapscil Hope the above inputs help. Are there any further questions here?

**Comment by jiasli** [comment]
We are currently experimenting with enabling auto-complete in PowerShell (https://github.com/Azure/azure-cli/pull/13576). Fortunately, this is not amongst our high-priority work items and we can't provide a solid ETA.

**Comment by pratapscil** [comment]
Thank you for the update.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by pratapscil** [comment]
Thank you for the quick response.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by BhargaviAnnadevara-MSFT** [comment]
@pratapscil Thanks for the response.

We will now proceed to close this thread as resolved, but if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.
