### ISSUE TITLE
how to config default acr name?

### ISSUE THREAD

**Issue by stliu** [MicrosoftDocs/azure-docs-cli#2206]
[Enter feedback here]

it has "The default container registry name to use for az acr commands." at first of the page but not mention acr in the table at the bottom
and having no idea which section this acr should be
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb42002e-9aa3-233d-9832-353235b7cd0f
* Version Independent ID: e8b320b1-5805-67ba-46b2-48111861facc
* Content: [Azure CLI configuration options](https://docs.microsoft.com/en-us/cli/azure/azure-cli-configuration?view=azure-cli-latest)
* Content Source: [docs-ref-conceptual/azure-cli-configuration.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/azure-cli-configuration.md)
* Service: **azure-cli**
* GitHub Login: @dbradish-microsoft
* Microsoft Alias: **dbradish**

**Comment by BhargaviAnnadevara-MSFT** [comment]
@stliu Thanks for the question. We're investigating this and will get back to you shortly.

**Comment by BhargaviAnnadevara-MSFT** [comment]
@stliu Thanks for bringing this to our attention. I've worked up a PR to add the missing configuration keys to the table. The changes are in review and should reflect soon post the merge.

Meanwhile, please know that `acr` should be added to the `[defaults]` section of the configuration file. You can use the `az configure` command as:

`az configure -d acr=myacr`

after which the config file may look similar to:

```ini
[cloud]
name = AzureCloud

[core]
first_run = yes

[defaults]
location = westus2
group = myResourceGroup
acr = myacr
```

**Comment by BhargaviAnnadevara-MSFT** [comment]
Thanks again for the feedback. The changes have been merged and should reflect in the docs shortly.
