### ISSUE TITLE
azure-cli on ParrotSec4.10

### ISSUE THREAD

**Issue by lorenmaxwellbutler** [MicrosoftDocs/azure-docs-cli#2217]
[404  Not Found [IP: 13.93.152.112 443]
Hit:4 https://mirror.parrot.sh/mirrors/parrot rolling InRelease
Hit:5 https://mirror.parrot.sh/mirrors/parrot rolling-security InRelease
Reading package lists... Done
**E: The repository 'https://packages.microsoft.com/repos/azure-cli n/a Release' does not have a Release file.**
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.]
Currently getting these errors when attempting the "one-shot" install, and  also with the manual-option.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe1526a9-7f22-504e-484c-0f3edc11b178
* Version Independent ID: c5dec108-efcd-aa77-04b5-803b6b894dba
* Content: [Install the Azure CLI on Linux with apt](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-apt?view=azure-cli-latest)
* Content Source: [docs-ref-conceptual/install-azure-cli-apt.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/install-azure-cli-apt.md)
* Service: **azure-cli**
* GitHub Login: @dbradish-microsoft
* Microsoft Alias: **dbradish**

**Comment by BhargaviAnnadevara-MSFT** [comment]
@lorenmaxwellbutler Thanks for the question. We're investigating this and will get back to you shortly.

**Comment by lorenmaxwellbutler** [comment]
Thanks! Its seems something isn't registering with gpg-keys and/or Microsoft Servers. Parrot uses Debian "testing" and its a "rolling" distribution, and I see "testing" isn't yet supported for azure-cli.

**Comment by BhargaviAnnadevara-MSFT** [comment]
@lorenmaxwellbutler As called out in the docs, the one-shot install script is only verified for Ubuntu 16.04+ and Debian 8+, and may not work on other distributions. Let me check with our Product group and circle back on this.

**Comment by BhargaviAnnadevara-MSFT** [comment]
@lorenmaxwellbutler Could you please help me with the contents of the `/etc/apt/sources.list.d/azure-cli.list` file on your machine?

**Comment by lorenmaxwellbutler** [comment]
Certainly,

`deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ n/a main`

So, its trying to find a distro, and can't becuase `testing` isn't supported  at "https://packages.microsoft.com/repos/azure-cli/dists/"

We can call this closed I think.

Thanks much for your time and help @BhargaviAnnadevara-MSFT

**Comment by BhargaviAnnadevara-MSFT** [comment]
@lorenmaxwellbutler Thanks for the details. I suppose you could set the value of `AZ_REPO` manually when [adding the repository](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-apt?view=azure-cli-latest#set-release) as Parrot OS seems to be based on Debian. More on this detailed in the [Troubleshooting](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-apt?view=azure-cli-latest#troubleshooting) section.

Please give it a try and let me know how that goes.

**Comment by lorenmaxwellbutler** [comment]
Well, it never hurts to try the easy thing
`sudo apt install azure-cli`

installs `azure-cli` out of the box 🥇 
Sorry to waste your time-- I'm thankful someone in the community did the hard-work already of setting `AZ_REPO` manually,
but this is something to watch out for using an odd distro, so I appreciate the guidance.


Take care, and thank you again 😅

**Comment by BhargaviAnnadevara-MSFT** [comment]
@lorenmaxwellbutler Sure, thanks for sharing. Glad I could help. :)

If you encounter a distro-specific problem again, please feel free to log an issue with the [Azure/azure-cli](https://github.com/Azure/azure-cli/issues) repo so our Product group can also take a look.
