### ISSUE TITLE
Az CLI Update Instructions should clarify permissions

### ISSUE THREAD

**Issue by mtaylorfsmb** [MicrosoftDocs/azure-docs-cli#2220]
I have version 2.3.1 of the CLI installed from a while back. I needed to use an extension and wanted to ensure everything was up to date. The current instructions do not work for older versions and so I believe some notes should be added.

1. The instructions for MSI with Command where you can copy the IWR command and run it should clarify that you need admin privileges to do so. If you don't have admin privileges then the command runs for a while but nothing happens AND you don't get any error messages. So it looks like it was successful but it wasn't. The only way to know this is to look at the CLI version again.

2. The `az  upgrade` command does not work on older CLI versions. I don't know when it was added but it generated an error on my older version until I finally got it updated. It would be nice if the documentation for this in this section identifies the version you need before it'll work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8246b90a-efb1-03ce-f642-d3eb2441fc30
* Version Independent ID: 2fdd20ef-7bd3-57bc-7957-93f4bb5377ce
* Content: [Install the Azure CLI for Windows](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-windows?tabs=azure-cli)
* Content Source: [docs-ref-conceptual/install-azure-cli-windows.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/install-azure-cli-windows.md)
* Product: **azure**
* Technology: **azure-cli**
* GitHub Login: @dbradish-microsoft
* Microsoft Alias: **dbradish**

**Comment by kobulloc-MSFT** [comment]
@mtaylorfsmb Thank you for the feedback!  We are investigating this and will get back to you shortly.

**Comment by kobulloc-MSFT** [comment]
@mtaylorfsmb To address your first issue, we've got a note requiring admin permissions to run the Invoke-WebRequest command.  In combination with this GitHub issue (which remains visible and will be quite helpful for anyone else who runs into this) I believe other readers will be well equipped to troubleshoot this scenario if need be.

![image](https://user-images.githubusercontent.com/37556655/95497067-9d8c7f00-0956-11eb-9bf0-3e5cef5d81ed.png)

To address your second issue, it looks like version 2.3.1 is the March 31st, 2020 [release](https://docs.microsoft.com/en-us/cli/azure/release-notes-azure-cli).  It appears that az upgrade was added in version 2.11.0 (the August 25th, 2020 update).  I'll do some additional investigation to see how far back the az upgrade command is supposed to work.

**Comment by kobulloc-MSFT** [comment]
@mtaylorfsmb Thank you again for bringing this to our attention.  It looks like the `az upgrade` command was introduced in version 2.11.0 and is intended for use with versions 2.11.0 and later.  We've updated our documentation and the changes should go live shortly.  Thank you for helping to improve our documentation!

We are going to close this thread as resolved but if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.
