### ISSUE TITLE
Still not able to do azlogin after setting environment variable

### ISSUE THREAD

**Issue by Brucius** [MicrosoftDocs/azure-docs-cli#2227]
[Enter feedback here]
Hello, I've been trying to do login using azcli from WSL v2 as per the documentation.

I've verified that the environment variable is set correctly in the terminal.
```
@main bruce% printenv | grep REQUESTS_CA_BUNDLE
REQUESTS_CA_BUNDLE=/opt/az/lib/python3.6/site-packages/certifi/cacert.pem
```

When I tried to login again, same error is observed. Please advise.
```
main bruce% az login
ValidationError: Certificate verification failed. This typically happens when using Azure CLI behind a proxy that intercepts traffic with a self-signed certificate. Please add this certificate to the trusted CA bundle. More info: https://docs.microsoft.com/en-us/cli/azure/use-cli-effectively#work-behind-a-proxy.
```

Below are other useful information.
```
@main bruce% lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.3 LTS
Release:        18.04
Codename:       bionic
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e51daa3-30c5-f449-36a1-9f33c70ca2fc
* Version Independent ID: a21e188b-4ff4-0aca-531b-d4b179665be1
* Content: [Use Azure CLI effectively](https://docs.microsoft.com/en-us/cli/azure/use-cli-effectively#work-behind-a-proxy)
* Content Source: [docs-ref-conceptual/use-cli-effectively.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/use-cli-effectively.md)
* Service: **azure-cli**
* GitHub Login: @dbradish-microsoft
* Microsoft Alias: **dbradish**

**Comment by BhargaviAnnadevara-MSFT** [comment]
@Brucius Thanks for the question. We're investigating this and will get back to you shortly.

**Comment by BhargaviAnnadevara-MSFT** [comment]
@Brucius Could you please confirm if you are trying to use Azure CLI behind a proxy? If yes, please do run through this troubleshooting step: [Proxy blocks connection](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-apt#proxy-blocks-connection), [CLI fails to install or run on Windows Subsystem for Linux](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-apt#cli-fails-to-install-or-run-on-windows-subsystem-for-linux)

If not, the instructions for installing Azure CLI on WSL can be found here: [Install Azure CLI with apt](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-apt)

**Comment by Brucius** [comment]
Thanks @BhargaviAnnadevara-MSFT , I just checked it out again and it seems like it was due to the time drift between WSL 2 container and host windows system. I managed to solved the issue by running the below command to sync the time and updating the cli.
```
sudo hwclock --hctosys
```

**Comment by BhargaviAnnadevara-MSFT** [comment]
@Brucius Glad to know, thanks for sharing what worked for you!
