### ISSUE TITLE
Platform architecture is hard coded in the shell script

### ISSUE THREAD

**Issue by pwehland** [MicrosoftDocs/azure-docs-cli#2230]
The script at https://aka.ms/InstallAzureCLIDeb hard codes the processor platform as amd64.  Although on Raspberry Pi, the install succeeds.  However, when we run "az version", it fails as we need arm64 processor architecture.  Error message is: "
/usr/bin/az: line 2: /opt/az/bin/python3: cannot execute binary file: Exec format error"

The script at https://aka.ms/InstallAzureCLIDeb should check the processor architecture and select the package location accordingly.  The same should go for OS (Eoan, Focal, Buster) 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe1526a9-7f22-504e-484c-0f3edc11b178
* Version Independent ID: c5dec108-efcd-aa77-04b5-803b6b894dba
* Content: [Install the Azure CLI on Linux with apt](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-apt)
* Content Source: [docs-ref-conceptual/install-azure-cli-apt.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/install-azure-cli-apt.md)
* Service: **azure-cli**
* GitHub Login: @dbradish-microsoft
* Microsoft Alias: **dbradish**

**Comment by BhargaviAnnadevara-MSFT** [comment]
@pwehland Thanks for the feedback. We're investigating this and will get back to you shortly.

**Comment by BhargaviAnnadevara-MSFT** [comment]
@pwehland Currently we only build and test the package on **amd64** which covers majority of the package use cases. To support a new architecture, we need to set up corresponding machines and testing in our pipeline besides changing the script.

Our team is tracking this in their backlog and will evaluate it further. The docs will also be updated appropriately once implemented. Please feel free to log any more such related requests here: https://github.com/Azure/azure-cli so our engineering team can also take a look.

We will now proceed to close this thread as resolved, but if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation. Thanks again for reaching out.

**Comment by pwehland** [comment]
@BhargaviAnnadevara-MSFT 
Why do you say that you only build for AMD64?  

Here we can see packages for buster (Debian 10.6) for Arm, Arm64, ArmHF, Armv7HL: https://packages.microsoft.com/repos/azure-cli/dists/buster/

For Eoan, (Ubuntu 19.10) we see Arm64, and ArmHF:
https://packages.microsoft.com/repos/azure-cli/dists/eoan/

And for Focal (Ubuntu 20.04) we see Arm64, and ArmHF:
https://packages.microsoft.com/repos/azure-cli/dists/focal/

**Comment by ham-bo** [comment]
Since this issue is still not resolved, can anyone recommend a workaround for using the script at https://aka.ms/InstallAzureCLIDeb to install on a raspberry pi?
