### ISSUE TITLE
Windows installation process

### ISSUE THREAD

**Issue by exmello** [MicrosoftDocs/azure-docs-cli#2237]
I followed the installation steps for the powershell command on https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-windows?tabs=azure-powershell.

I ran the following command but the azure CLI was not installed: Invoke-WebRequest -Uri https://aka.ms/installazurecliwindows -OutFile .\AzureCLI.msi; Start-Process msiexec.exe -Wait -ArgumentList '/I AzureCLI.msi /quiet'; rm .\AzureCLI.msi

The command ran with no errors.  It took some time to download the installer then ended silently and returned to the prompt with no output.

I tried "az --version" and received a "The term 'az' is not recognized as the name of a cmdlet, function, script file, or operable program." response.  I checked under C:\Program Files (x86)\Microsoft SDKs\Azure and there was no CLI2 folder.  I checked my environment variables and there were no changes.

I ended up manually running the MSI following the instructions on https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-windows?tabs=azure-cli.  This WAS successful.

I am able to use the CLI, but it would be helpful to identify why the powershell command didn't work and document some troubleshooting steps.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8246b90a-efb1-03ce-f642-d3eb2441fc30
* Version Independent ID: 2fdd20ef-7bd3-57bc-7957-93f4bb5377ce
* Content: [Install the Azure CLI for Windows](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-windows?tabs=azure-cli)
* Content Source: [docs-ref-conceptual/install-azure-cli-windows.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/install-azure-cli-windows.md)
* Product: **azure**
* Technology: **azure-cli**
* GitHub Login: @dbradish-microsoft
* Microsoft Alias: **dbradish**

**Comment by Mike-Ubezzi-MSFT** [comment]
@exmello Thank you for bringing this issue to our attention. I am going to have an engineer review this and have the issue addressed.

**Comment by BhargaviAnnadevara-MSFT** [comment]
@exmello Thanks for the feedback. I noticed something similar happen when I tried to run the PowerShell cmdlet without elevated privileges.

Could you please confirm if the following were performed?
- Ensure to Start PowerShell as administrator
- Once the cmdlet finishes execution, you will need to reopen PowerShell to use the Azure CLI.

**Comment by exmello** [comment]
I can confirm that I reopened PowerShell, but I believe I did not start PowerShell as administrator.  I don't have a clean environment to test that this works.  I am already set up by manually installing now.  Thank you.  I didn't notice the /quiet flag.

**Comment by BhargaviAnnadevara-MSFT** [comment]
@exmello Thanks for the quick response. Yes, the execution happens silently because of the `/quiet` argument being passed to the cmdlet. You can run:
```powershell
Invoke-WebRequest -Uri https://aka.ms/installazurecliwindows -OutFile .\AzureCLI.msi; Start-Process msiexec.exe -Wait -ArgumentList '/I AzureCLI.msi'; rm .\AzureCLI.msi
```
if you want to install interactively.

Just to save you some time and trouble, I tested it all by uninstalling the old Azure CLI version that I already had on my machine and verified that the installation happens successfully when PowerShell is run as the administrator vs otherwise. :)

I'm pretty sure it would work for you too. Let me also check how we can improve the documentation to emphasize this, as having elevated privileges to perform the operation is key to the installation process.

Please let me know if you have any other questions.

**Comment by BhargaviAnnadevara-MSFT** [comment]
@exmello Hope the above inputs help.

We will now proceed to close this thread as resolved, but if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.
