### ISSUE TITLE
AZURE CLI Installer never asks which Drive to install

### ISSUE THREAD

**Issue by sjalali123** [MicrosoftDocs/azure-docs-cli#2243]
Hi Azure CLI Team
          [Enter FBack Line]
AZURE CLI Installer never asks which Drive to install, and contributes with other such installers to quickly fill up the C: Drive. It is annoying of many programs to force themselves to go to bed with the OS Drive, and become less manageable for backups and recovery purposes.
Sush
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bdfb5c1b-ba4c-36bb-1e96-271f9deabf58
* Version Independent ID: db0d67b6-4fb8-4596-75d0-376a4ce48efd
* Content: [Install the Azure CLI for Windows](https://docs.microsoft.com/en-us/azure/developer/azure-cli/install-azure-cli-windows)
* Content Source: [articles/azure-cli/install-azure-cli-windows.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/azure-cli/install-azure-cli-windows.md)
* Service: **azure-cli**
* GitHub Login: @dbradish-microsoft
* Microsoft Alias: **dbradish**

**Comment by dbradish-microsoft** [comment]
@sjalali123, that you for contacting the Azure CLI team with your feedback.

@fengzhou-msft , can you please provide insight as to why we must use the C:\ drive for a local Azure CLI install? 

Here are two screen prints of the current installation process:
![image](https://user-images.githubusercontent.com/58762114/96750446-cb26ee80-1380-11eb-8ced-8130ff29acb2.png)

![image](https://user-images.githubusercontent.com/58762114/96750479-d417c000-1380-11eb-9486-866dcfa4a2f2.png)

**Comment by fengzhou-msft** [comment]
The Azure CLI MSI installer currently does not support customized install location. A similar request is tracked here: https://github.com/Azure/azure-cli/issues/14593

**Comment by dbradish-microsoft** [comment]
@sjalali123, please see [Azure/azure-cli#14593](https://github.com/Azure/azure-cli/issues/14593) for continued follow-up from our engineering team.  Thank you.
