### ISSUE TITLE
Command az --version does not work on macOS Catalina 

### ISSUE THREAD

**Issue by mohsinaliayub** [MicrosoftDocs/azure-docs-cli#2245]
[Enter feedback here]

The command **az --version** at the end of second paragraph of main heading does not work. I installed Azure CLI with Homebrew, and when I tried to run the above command it gave me this error: **RequiredArgumentMissingError: the following arguments are required: _command_package**

I think the proper command is **az version**. I tested it on macOS Catalina 10.15.6.

![Screenshot 2020-10-21 at 19 33 58](https://user-images.githubusercontent.com/15940912/96756473-6eedba00-13d4-11eb-9ffa-fdb7e1459349.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d09ed623-c83f-6bae-639e-a5f9a31fe3bb
* Version Independent ID: c5d0d722-aacd-47a3-3fcf-982c02c4d0e9
* Content: [Install the Azure CLI for macOS](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-macos)
* Content Source: [docs-ref-conceptual/install-azure-cli-macos.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/install-azure-cli-macos.md)
* Service: **azure-cli**
* GitHub Login: @dbradish-microsoft
* Microsoft Alias: **dbradish**

**Comment by YutongTie-MSFT** [comment]
Thanks for the feedback! I have assigned the issue to the content author to investigate further and update the document as appropriate.

@dbradish-microsoft Hi Delora, could you please check this issue and update the document if need. Thanks.

**Comment by dbradish-microsoft** [comment]
@mohsinaliayub , **az --version** is not the correct syntax.  Use **az version** instead.  Here is a link to the **az version** command: https://docs.microsoft.com/en-us/cli/azure/reference-index?view=azure-cli-latest#az_version
