### ISSUE TITLE
Incorrect command to remove the Microsoft signing key

### ISSUE THREAD

**Issue by ttmc** [MicrosoftDocs/azure-docs-cli#2251]
Near the bottom of the page, it says, "3. If you use no other packages from Microsoft, remove the signing key:"

`sudo rm /etc/apt/trusted.gpg.d/microsoft.gpg`

but that command doesn't work. It should say:

`sudo rm /etc/apt/trusted.gpg.d/microsoft.asc.gpg`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe1526a9-7f22-504e-484c-0f3edc11b178
* Version Independent ID: c5dec108-efcd-aa77-04b5-803b6b894dba
* Content: [Install the Azure CLI on Linux with apt](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-apt)
* Content Source: [docs-ref-conceptual/install-azure-cli-apt.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/install-azure-cli-apt.md)
* Service: **azure-cli**
* GitHub Login: @dbradish-microsoft
* Microsoft Alias: **dbradish**

**Comment by BhargaviAnnadevara-MSFT** [comment]
@ttmc Thanks for the feedback. We're investigating this and will get back to you shortly.

**Comment by Svijay-msft** [comment]
Hello @ttmc, 

Can you please share more information on the OS and the version you are using this on ? I happen to try it on my Ubuntu 18.04.4 and unfortunately was not able to replicate the issue. 

Also, based on my research, when you are installing the signing key as per below command : 

```
curl -sL https://packages.microsoft.com/keys/microsoft.asc |
    gpg --dearmor |
    sudo tee /etc/apt/trusted.gpg.d/microsoft.gpg > /dev/null
```
You are naming it as "microsoft.gpg"

![image](https://user-images.githubusercontent.com/66949976/97284817-7d6e2280-1867-11eb-9106-df42a06b66f4.png)


Can you please check once when you run the above command what was the name given (sudo tee /etc/apt/trusted.gpg.d/<NAME>.gpg) ?

**Comment by ttmc** [comment]
I was running the latest (updated) Ubuntu 20.04.
It was running under WSL2 on a Windows 10 machine, but that shouldn't matter.

I installed the Azure CLI using this one-liner:

`curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash`

probably on the same day as I posted this issue, or maybe the day before. I got that one-liner from https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-apt#install-with-one-command

**Comment by Svijay-msft** [comment]
Thanks for getting back. I did further check. When I checked the deb_install.sh file (https://aka.ms/InstallAzureCLIDeb)

![image](https://user-images.githubusercontent.com/66949976/97417084-44988100-192d-11eb-8368-74ed95f26dd8.png)

There is a difference i could observe (microsoft.gpg & microsoft.asc.gpg)

```
curl -sL https://packages.microsoft.com/keys/microsoft.asc |
    gpg --dearmor |
    sudo tee /etc/apt/trusted.gpg.d/microsoft.gpg > /dev/null
```

I am further checking with my team on this. I'll keep you posted.

**Comment by Svijay-msft** [comment]
Hello @ttmc 

 Currently, one line installer is installing the signing key as **microsoft.asc.gpg**. The intended name for the signing key **microsoft.gpg**. 

I have got a confirmation from the engineering team there will be fix done in this week to the one line command installer script (https://aka.ms/InstallAzureCLIDeb). 

Having said that, I shall proceed with the closure of this thread if there are no further questions from your end.

**Comment by ttmc** [comment]
Okay thanks for the update, you can go ahead and close this thread.

**Comment by Svijay-msft** [comment]
We will close this out, but if you feel you need more information please just let us know.
