### ISSUE TITLE
AKS deployment

### ISSUE THREAD

**Issue by bkarlen** [MicrosoftDocs/azure-docs-cli#2252]
Running our AKS deployment has created dial out issues to the cluster. 
Our deployment command is a:
kubectl apply -f [FILENAME]

2020-10-23T16:02:25.9375398Z Unable to connect to the server: dial tcp [CLUSTERIP]: i/o timeout
2020-10-23T16:02:25.9494281Z ##[error]Script failed with error: Error: The process '/bin/bash' failed with exit code 1
2020-10-23T16:02:25.9508675Z [command]/usr/bin/az account clear

The only solution that we've come up with is to change the agent from Linux to Windows, then back to Linux. 
After doing this there is no dial timeout.

**Comment by JayaChatterjee-MSFT** [comment]
Thank you for your question! We will review and update as appropriate.

**Comment by BhargaviAnnadevara-MSFT** [comment]
@bkarlen Thank you for the question! In order to best address your question, could you provide us with the URL of the MS Doc that you were following, if any?

**Comment by BhargaviAnnadevara-MSFT** [comment]
@bkarlen Just following up here to check if you have any updates on this.

**Comment by bkarlen** [comment]
https://docs.microsoft.com/en-us/azure/aks/tutorial-kubernetes-deploy-application

I have API server authorized IP ranges on for the cluster I am deploying to as well as RBAC. When I deploy to the cluster, I update the IP ranges with the following command. 
az aks update --resource-group $(aks.RG) \
 --name $(aks.name) \
 --api-server-authorized-ip-ranges "$(THISIP)"

I also get the credentials of the cluster so I can deploy to it with this command. 
az aks get-credentials --resource-group $(aks.RG) --name $(aks.name)

I then build and push an image to the ACR that has already been linked to the cluster in the creation of the cluster.
I then deploy with the Azure CLI task with the command
kubectl apply -f $(System.DefaultWorkingDirectory)/_DockerContainer/drop/$(env).deployment.azure.yaml

I then end the pipeline by removing the authorized IP. 
The only step that Is inconsistent is the kubectl apply step. It is fixed consistently however, when I swap agents, cancel the run, swap agents back and rerun the deployment.

**Comment by BhargaviAnnadevara-MSFT** [comment]
@bkarlen Thanks for the response. I see that this issue relates more to deploying applications on AKS than Azure CLI. I've opened an issue here: MicrosoftDocs/azure-docs#65228 for one of our Engineers to check.

I'd like to let you know that this channel (the [Azure CLI Docs](https://github.com/MicrosoftDocs/azure-docs-cli) repository) is only for driving improvements related to the Azure documentation. The best place for specific answers about implementations is going to be the [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/index.html) platform. We actively look through posts in the forums and will do our best to get you going in the right direction.

We will now proceed to close this thread, but if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.
