### ISSUE TITLE
typo "postgre" instead of postgres used

### ISSUE THREAD

**Issue by AwdotiaRomanowna** [MicrosoftDocs/azure-docs-cli#2273]
in here: "az network private-endpoint-connection: Support mysql, postgre and mariadb types"

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: c0e8d9ef-f25b-bb46-7f1a-bd3588be3343
* Version Independent ID: cd392600-a90d-0145-5ea6-6b01ab8f4ab9
* Content: [Azure CLI release notes](https://docs.microsoft.com/ko-kr/cli/azure/release-notes-azure-cli?tabs=azure-cli-beta&view=azure-cli-latest)
* Content Source: [docs-ref-conceptual/release-notes-azure-cli.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/release-notes-azure-cli.md)
* Service: **azure-cli**
* GitHub Login: @dbradish-microsoft
* Microsoft Alias: **dbradish**

**Comment by BhargaviAnnadevara-MSFT** [comment]
@AwdotiaRomanowna Thanks for the feedback. We shall evaluate and update the document as appropriate.

**Comment by BhargaviAnnadevara-MSFT** [comment]
@AwdotiaRomanowna Thanks for bringing this to our attention. I have submitted a PR to fix the issue that's in review.

**Comment by BhargaviAnnadevara-MSFT** [comment]
@AwdotiaRomanowna Thank you for catching that error in the docs! The change is merged internally and will go-live in the public docs shortly.
