### ISSUE TITLE
use "sudo tee" to create a file, like this

### ISSUE THREAD

**Issue by speculatrix** [MicrosoftDocs/azure-docs-cli#2282]
```
$ sudo tee /etc/yum.repos.d/azure-cli.repo
[azure-cli]
name=Azure CLI
baseurl=https://packages.microsoft.com/yumrepos/azure-cli
enabled=1
gpgcheck=1
gpgkey=https://packages.microsoft.com/keys/microsoft.asc
^D
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9f55d23-7802-e0da-6d12-b71f6da8a1d4
* Version Independent ID: 192846d7-baae-bcba-698b-22bdcdae468a
* Content: [Install the Azure CLI on Linux with yum](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-yum)
* Content Source: [docs-ref-conceptual/install-azure-cli-yum.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/install-azure-cli-yum.md)
* Service: **azure-cli**
* GitHub Login: @dbradish-microsoft
* Microsoft Alias: **dbradish**

**Comment by BhargaviAnnadevara-MSFT** [comment]
@speculatrix Thanks for the feedback. We're investigating this and will get back to you shortly.

**Comment by BhargaviAnnadevara-MSFT** [comment]
@speculatrix Thanks for the feedback. I have submitted a PR to update the command that's in review. The changes should reflect post the merge.

We will now proceed to close this thread, but if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.

**Comment by BhargaviAnnadevara-MSFT** [comment]
@speculatrix Are you seeing an issue with the current command?

```
sudo sh -c 'echo -e "[azure-cli]
name=Azure CLI
baseurl=https://packages.microsoft.com/yumrepos/azure-cli
enabled=1
gpgcheck=1
gpgkey=https://packages.microsoft.com/keys/microsoft.asc" > /etc/yum.repos.d/azure-cli.repo'
```

**Comment by speculatrix** [comment]
Hi,
the command workls but is ugly, and inconsistent with other documentation where you do have sudo tee in use.

**Comment by BhargaviAnnadevara-MSFT** [comment]
@speculatrix Thanks again for the feedback. We've made some changes to the doc in question for it to be consistent with the other  docs. The change is merged internally and will go-live in the public docs shortly.
