### ISSUE TITLE
CentOS CA bundle location for working behind a proxy section

### ISSUE THREAD

**Issue by MartinAbadie** [MicrosoftDocs/azure-docs-cli#2292]
Hi,

At **Work behind a proxy** section, step 1, for CentOS CA bundle location is `/usr/lib64/az/lib/python3.6/site-packages/certifi/cacert.pem` not `/opt/az/lib/python3.6/site-packages/certifi/cacert.pem`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e51daa3-30c5-f449-36a1-9f33c70ca2fc
* Version Independent ID: a21e188b-4ff4-0aca-531b-d4b179665be1
* Content: [Use Azure CLI effectively](https://docs.microsoft.com/en-us/cli/azure/use-cli-effectively)
* Content Source: [docs-ref-conceptual/use-cli-effectively.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/use-cli-effectively.md)
* Service: **azure-cli**
* GitHub Login: @dbradish-microsoft
* Microsoft Alias: **dbradish**

**Comment by BhargaviAnnadevara-MSFT** [comment]
@MartinAbadie Thanks for the feedback. We're investigating this and will get back to you shortly.

**Comment by BhargaviAnnadevara-MSFT** [comment]
@MartinAbadie Thanks for bringing this to our attention. `/opt/az/lib/python3.6/site-packages/certifi/cacert.pem` is actually the location for Ubuntu/Debian. I've updated the doc to reflect the location for other Linux distros as well.

I have submitted a PR to fix the issue that's in review.
