### ISSUE TITLE
Hyperlink leads to 404 - Page not found

### ISSUE THREAD

**Issue by marisaparker** [MicrosoftDocs/azure-docs-cli#2298]
Page: [Overview: Azure CLI references types and status](https://docs.microsoft.com/en-us/cli/azure/reference-types-and-status#feedback)

Section: Referenct Status > Stability > Public Preview
Hyperlink: [Microsoft Azure Previews](https://docs.microsoft.com/en-us/support/legal/preview-supplemental-terms/) leads to a 404 page

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3dd37a62-e248-b1dd-ad17-48e8bcfae21d
* Version Independent ID: a727d676-594e-a19b-cb2c-108c28ae1c9f
* Content: [Azure CLI reference types](https://docs.microsoft.com/en-us/cli/azure/reference-types-and-status)
* Content Source: [docs-ref-conceptual/reference-types-and-status.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/reference-types-and-status.md)
* Service: **azure-cli**
* GitHub Login: @dbradish-microsoft
* Microsoft Alias: **dbradish**

**Comment by BhargaviAnnadevara-MSFT** [comment]
@marisaparker Thanks for the feedback. We shall evaluate and update the document as appropriate.

**Comment by BhargaviAnnadevara-MSFT** [comment]
@marisaparker Thanks for bringing this to our attention. I have submitted a PR to fix the issue that's in review.

Meanwhile, here is the doc you may be looking for: [Microsoft Azure Previews](https://azure.microsoft.com/support/legal/preview-supplemental-terms/). :)

**Comment by BhargaviAnnadevara-MSFT** [comment]
@marisaparker The changes should reflect post the merge.

We will now proceed to close this thread, but if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.
