### ISSUE TITLE
Mistake in the delete command

### ISSUE THREAD

**Issue by oddsrule** [MicrosoftDocs/azure-docs-cli#2307]
[Enter feedback here]
Doc shows this:
az config param-persist delete --name resource_group_name
should be this
az config param-persist delete resource_group_name

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99d3dc67-acbe-08d6-73b3-667aa84002a2
* Version Independent ID: fa911143-aa1e-961f-afa4-6d04c3bf2f30
* Content: [Tutorial on how to use persisted parameters with the Azure CLI](https://docs.microsoft.com/en-us/cli/azure/param-persist-tutorial?tabs=azure-cli)
* Content Source: [docs-ref-conceptual/param-persist-tutorial.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/param-persist-tutorial.md)
* Product: **azure**
* Technology: **azure-cli**
* GitHub Login: @dbradish-microsoft
* Microsoft Alias: **dbradish**

**Comment by BhargaviAnnadevara-MSFT** [comment]
@oddsrule Thanks for the feedback. We shall evaluate and update the document as appropriate.

**Comment by BhargaviAnnadevara-MSFT** [comment]
@oddsrule Thanks for bringing this to our attention. I have submitted a PR to fix the issue that's in review. The changes should reflect post the merge.
