### ISSUE TITLE
Wrong link to privacy

### ISSUE THREAD

**Issue by ItalyPaleAle** [MicrosoftDocs/azure-docs-cli#2311]
In the page https://docs.microsoft.com/en-us/cli/azure/azure-cli-configuration the table lists the various configuration options, including `collect_telemetry`. The explanation for that is:

> Allow Microsoft to collect anonymous data on the usage of the CLI. For privacy information, see the Azure CLI MIT license.

Which links to https://github.com/Azure/azure-cli/blob/dev/LICENSE

The link doesn't seem correct as the page linked to contains only the Azure CLI license and nothing about the privacy policy.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb42002e-9aa3-233d-9832-353235b7cd0f
* Version Independent ID: e8b320b1-5805-67ba-46b2-48111861facc
* Content: [Azure CLI configuration options](https://docs.microsoft.com/en-us/cli/azure/azure-cli-configuration#feedback)
* Content Source: [docs-ref-conceptual/azure-cli-configuration.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/azure-cli-configuration.md)
* Service: **azure-cli**
* GitHub Login: @dbradish-microsoft
* Microsoft Alias: **dbradish**

**Comment by BhargaviAnnadevara-MSFT** [comment]
@ItalyPaleAle Thanks for the feedback. We're investigating this and will get back to you shortly.

**Comment by BhargaviAnnadevara-MSFT** [comment]
@dbradish-microsoft Do we have any other docs to link here?

**Comment by BhargaviAnnadevara-MSFT** [comment]
@ItalyPaleAle Thanks again for the feedback. I have assigned the issue to the content author to evaluate this further and update as appropriate.

**Comment by dbradish-microsoft** [comment]
Hello, @ItalyPaleAle , the Azure CLI uses Microsoft's data privacy statement as described here:

3. DATA. The software may collect information about you and your use of the software, and send that to Microsoft. Microsoft may use this information to provide services and improve our products and services.You may opt-out of many of these scenarios, but not all, as described in the product documentation. There are also some features in the software that may enable you and Microsoft to collect data from users of your applications. If you use these features, you must comply with applicable law, including providing appropriate notices to users of your applications and you should provide a copy of Microsoft’s privacy statement to your users. **The Microsoft privacy statement is located here https://go.microsoft.com/fwlink/?LinkID=824704.** You can learn more about data collection and use in the help documentation and our privacy statement. Your use of the software operates as your consent to these practices.

However, I feel that clarity can be added to our doc so I've created a CLI DevEx work item.  I appreciate your feedback, and if I don't hear from you by end of the day, December 2nd, with additional comments, I'll close this issue.

**Comment by dbradish-microsoft** [comment]
Closing issue per comments given on November 30th.
