### ISSUE TITLE
Wrong syntax

### ISSUE THREAD

**Issue by ITSTord** [MicrosoftDocs/azure-docs-cli#2342]
[Enter feedback here]
@https://docs.microsoft.com/en-us/cli/azure/update-azure-cli
![image](https://user-images.githubusercontent.com/54802153/102078079-a001ce00-3e0a-11eb-8879-d7d5e17a528f.png)
Should be:
"az config set auto-upgrade.all=no"
and
![image](https://user-images.githubusercontent.com/54802153/102084331-4e127580-3e15-11eb-98e2-9da7b6085f08.png)
Should be:
"az config set auto-upgrade.prompt=no"
and
@https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-windows?tabs=azure-cli
Beta links to a way older verison ~2.8,10 which do not include auto upgrade. I would guess beta should contain the latest changes/features. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f3b4caa-fd05-3a1e-d59a-34a5aa6fbbd7
* Version Independent ID: 9b8fdf78-4b2c-5686-6d19-af4c9b3651bd
* Content: [Update the Azure CLI](https://docs.microsoft.com/en-us/cli/azure/update-azure-cli?view=azure-cli-latest)
* Content Source: [docs-ref-conceptual/update-azure-cli.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/update-azure-cli.md)
* Service: **azure-cli**
* GitHub Login: @dbradish-microsoft
* Microsoft Alias: **dbradish**

**Comment by HarshitaSingh-MSFT** [comment]
@ITSTord , thanks for taking time to share your valuable feedback! We are taking a look into this and will get back to you soon.

**Comment by dbradish-microsoft** [comment]
Thank you for bringing this to our attention, @ITSTord.  The doc was indeed incorrect but has been fixed.  You will see the change reflected late afternoon Tuesday, December 15th.
