### ISSUE TITLE
Should add also how to change default subscription

### ISSUE THREAD

**Issue by davidbIQ** [MicrosoftDocs/azure-docs-cli#2350]
whenever I open a new cloudshell it defaults to a sub that I don't want it to default to.  This I think would be a good place to add it.  I found it one day but am struggling to refind it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21632cd2-aec0-1521-a9b0-f96f69ab15ed
* Version Independent ID: d6ab81e8-1aba-b922-9984-4523386c83cf
* Content: [Manage Azure subscriptions with the Azure CLI](https://docs.microsoft.com/en-us/cli/azure/manage-azure-subscriptions-azure-cli)
* Content Source: [docs-ref-conceptual/manage-azure-subscriptions-azure-cli.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/manage-azure-subscriptions-azure-cli.md)
* Service: **azure-cli**
* GitHub Login: @dbradish-microsoft
* Microsoft Alias: **dbradish**

**Comment by BhargaviAnnadevara-MSFT** [comment]
@davidbIQ Thanks for the feedback. We're investigating this and will get back to you shortly.

**Comment by BhargaviAnnadevara-MSFT** [comment]
@davidbIQ The current active subscription can be changed with the [az account set](https://docs.microsoft.com/en-us/cli/azure/account?view=azure-cli-latest#az_account_set) command:
```
az account set --subscription <subscription-name-or-id>
```
which is mentioned as part of the section: [Change the active subscription](https://docs.microsoft.com/en-us/cli/azure/manage-azure-subscriptions-azure-cli#change-the-active-subscription)

Could you please elaborate on the enhancement you are suggesting to this doc?

**Comment by BhargaviAnnadevara-MSFT** [comment]
@davidbIQ Hope the above inputs help. Are there any further questions here?

**Comment by davidbIQ** [comment]
Sure, when I first login I open to beamportal for my subscription.  I’m doing a lot of work in visual studio subscription for exam prep.
Everytime I open the cloud shell though I get put back to beamportal and I need to change it using the az account set command.  If I forget I’m making changes in beam portal.  I know it’s possible to change as I did modify it to beam portal but I don’t recall how currently, but I guess I’m asking how to you change the long running default setting.  It would also change the subscription where your cloud files are saved as they I believe are lost in the transition to a new sub but for me that’s ok.

Thanks
Dave

**Comment by dbradish-microsoft** [comment]
@davidblQ, have you tried using [az configure](https://docs.microsoft.com/en-us/cli/azure/reference-index?view=azure-cli-latest#az_configure) to set your default subscription?

az configure --defaults sbuscription='your-subscription-name'
az configure --list-defaults

**Comment by davidbIQ** [comment]
I just tried it but it didn’t work,
I ran az configure --defaults subscription=’Visual Studio Professional Subscription'
Then ran
Az configure –list-defaults
And it returns Visual Studio Professional Subscription

But if I press cntl-f5 to relaunch my portal.azure.com and then reopen my cloudshell and run
Az account show it will still show beamportal subscription as the default (instead of the Visual Studio Professional one)

If I run az configure --list-defaults (at this point)
it will show the Visual Studio Professional Subscription
But it doesn’t’ seem to be doing what I’m after which is modifying the default for az account show on a fresh session start.

Many Thanks,
David

**Comment by BhargaviAnnadevara-MSFT** [comment]
@davidbIQ Thanks for the details. I believe there isn't an out-of-the-box way to set the default tenant/subscription upon Azure Cloud Shell startup. @dbradish-microsoft Please correct if my understanding is amiss.

One workaround would be to add the `az account set -s "<your-subscription>"` command to the `~/.bashrc` file, so that the default Subscription is selected every time you start Azure Cloud Shell (Please restart Cloud Shell after you make changes using the Power button on the top left).

**Comment by davidbIQ** [comment]
Thanks for looking,
I found the command that I was hunting for, its `cloudshell unmount` this will kill your old session and ask you to create a new one on next login & ask you to choose the subscription, and then the default is that one after.
I thought this doc it would be a good place to mention how to change the default.  I think if you choose your old sub that you were on you get your old files back but I haven’t confirmed.

**Comment by davidbIQ** [comment]
Apologies I ment to say `clouddrive unmount`
Thanks,
David

From: David Bollman
Sent: December 22, 2020 9:50 AM
To: MicrosoftDocs/azure-docs-cli <reply@reply.github.com>; MicrosoftDocs/azure-docs-cli <azure-docs-cli@noreply.github.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [MicrosoftDocs/azure-docs-cli] Should add also how to change default subscription (#2350)

Thanks for looking,
I found the command that I was hunting for, its `cloudshell unmount` this will kill your old session and ask you to create a new one on next login & ask you to choose the subscription, and then the default is that one after.
I thought this doc it would be a good place to mention how to change the default.  I think if you choose your old sub that you were on you get your old files back but I haven’t confirmed.

**Comment by BhargaviAnnadevara-MSFT** [comment]
@davidbIQ Ah ok. Although the `clouddrive unmount` command is primarily used to [unmount a file share](https://docs.microsoft.com/en-us/azure/cloud-shell/persisting-shell-storage#unmount-clouddrive) that's mounted to Cloud Shell, I'll let the content author evaluate the enhancement further. Thanks for the feedback. @dbradish-microsoft FYI.

We will now proceed to close this thread, but if there are any further questions regarding the docs, please tag me in your reply and we will be happy to continue the conversation.
