### ISSUE TITLE
why virtualenv method is not provided as an alternative?

### ISSUE THREAD

**Issue by kunthar** [MicrosoftDocs/azure-docs-cli#2378]
$ python -m venv venv
$ python --version
Python 3.8.6
$ source venv/bin/activate
(venv)$ pip install azure-cli

Successfully installed PyJWT-1.7.1 adal-1.2.5 antlr4-python3-runtime-4.7.2 applicationinsights-0.11.9 argcomplete-1.12.2 azure-appconfiguration-1.1.1 azure-batch-10.0.0 azure-cli-2.17.1 azure-cli-core-2.17.1 azure-cli-telemetry-1.0.6 azure-common-1.1.26 azure-core-1.9.0 azure-cosmos-3.2.0 azure-datalake-store-0.0.51 azure-functions-devops-build-0.0.22 azure-graphrbac-0.60.0 azure-keyvault-1.1.0 azure-keyvault-administration-4.0.0b2 azure-loganalytics-0.1.0 azure-mgmt-advisor-2.0.1 azure-mgmt-apimanagement-0.2.0 azure-mgmt-appconfiguration-0.6.0 azure-mgmt-applicationinsights-0.1.1 azure-mgmt-authorization-0.61.0 azure-mgmt-batch-9.0.0 azure-mgmt-batchai-2.0.0 azure-mgmt-billing-1.0.0 azure-mgmt-botservice-0.2.0 azure-mgmt-cdn-5.2.0 azure-mgmt-cognitiveservices-6.3.0 azure-mgmt-compute-18.0.0 azure-mgmt-consumption-2.0.0 azure-mgmt-containerinstance-1.5.0 azure-mgmt-containerregistry-3.0.0rc16 azure-mgmt-containerservice-9.4.0 azure-mgmt-core-1.2.1 azure-mgmt-cosmosdb-1.0.0 azure-mgmt-databoxedge-0.2.0 azure-mgmt-datalake-analytics-0.2.1 azure-mgmt-datalake-nspkg-3.0.1 azure-mgmt-datalake-store-0.5.0 azure-mgmt-datamigration-0.1.0 azure-mgmt-deploymentmanager-0.2.0 azure-mgmt-devtestlabs-4.0.0 azure-mgmt-dns-2.1.0 azure-mgmt-eventgrid-3.0.0rc7 azure-mgmt-eventhub-4.1.0 azure-mgmt-hdinsight-2.0.0 azure-mgmt-imagebuilder-0.4.0 azure-mgmt-iotcentral-3.0.0 azure-mgmt-iothub-0.12.0 azure-mgmt-iothubprovisioningservices-0.2.0 azure-mgmt-keyvault-8.0.0 azure-mgmt-kusto-0.3.0 azure-mgmt-loganalytics-0.7.0 azure-mgmt-managedservices-1.0.0 azure-mgmt-managementgroups-0.2.0 azure-mgmt-maps-0.1.0 azure-mgmt-marketplaceordering-0.2.1 azure-mgmt-media-2.2.0 azure-mgmt-monitor-0.11.0 azure-mgmt-msi-0.2.0 azure-mgmt-netapp-0.14.0 azure-mgmt-network-17.0.0 azure-mgmt-nspkg-3.0.2 azure-mgmt-policyinsights-0.5.0 azure-mgmt-privatedns-0.1.0 azure-mgmt-rdbms-3.1.0rc1 azure-mgmt-recoveryservices-0.4.0 azure-mgmt-recoveryservicesbackup-0.6.0 azure-mgmt-redhatopenshift-0.1.0 azure-mgmt-redis-7.0.0rc2 azure-mgmt-relay-0.1.0 azure-mgmt-reservations-0.6.0 azure-mgmt-resource-10.3.0 azure-mgmt-search-2.1.0 azure-mgmt-security-0.6.0 azure-mgmt-servicebus-0.6.0 azure-mgmt-servicefabric-0.5.0 azure-mgmt-signalr-0.4.0 azure-mgmt-sql-0.21.0 azure-mgmt-sqlvirtualmachine-0.5.0 azure-mgmt-storage-16.0.0 azure-mgmt-synapse-0.5.0 azure-mgmt-trafficmanager-0.51.0 azure-mgmt-web-0.48.0 azure-multiapi-storage-0.5.2 azure-nspkg-3.0.2 azure-storage-common-1.4.2 azure-synapse-accesscontrol-0.2.0 azure-synapse-artifacts-0.3.0 azure-synapse-spark-0.2.0 bcrypt-3.2.0 certifi-2020.12.5 chardet-4.0.0 colorama-0.4.4 cryptography-2.9.2 fabric-2.5.0 humanfriendly-8.2 idna-2.10 invoke-1.5.0 isodate-0.6.0 javaproperties-0.5.1 jmespath-0.10.0 jsmin-2.2.2 jsondiff-1.2.0 knack-0.7.2 mock-4.0.3 msal-1.0.0 msal-extensions-0.1.3 msrest-0.6.19 msrestazure-0.6.4 oauthlib-3.1.0 paramiko-2.7.2 pkginfo-1.6.1 portalocker-1.7.1 psutil-5.8.0 pygments-2.7.3 pynacl-1.4.0 pyopenssl-19.1.0 python-dateutil-2.8.1 pytz-2019.1 requests-2.25.1 requests-oauthlib-1.3.0 scp-0.13.3 sshtunnel-0.1.5 tabulate-0.8.7 urllib3-1.26.2 vsts-0.1.25 vsts-cd-manager-1.0.2 websocket-client-0.56.0 xmltodict-0.12.0

as it can be seen, no need to have a homebrew.

or 

poetry init 
and add azure-cli when asked 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d09ed623-c83f-6bae-639e-a5f9a31fe3bb
* Version Independent ID: c5d0d722-aacd-47a3-3fcf-982c02c4d0e9
* Content: [Install the Azure CLI for macOS](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-macos)
* Content Source: [docs-ref-conceptual/install-azure-cli-macos.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/install-azure-cli-macos.md)
* Service: **azure-cli**
* GitHub Login: @dbradish-microsoft
* Microsoft Alias: **dbradish**

**Comment by KranthiPakala-MSFT** [comment]
@kunthar  
Thank you for reaching out. At this time we are reviewing the ask and will provide an update as appropriate

**Comment by yungezz** [comment]
hi @fengzhou-msft could you pls help to have a look? thanks

**Comment by fengzhou-msft** [comment]
@kunthar We will plan a new doc for installing `azure-cli` with pip in virtualenv for all platforms.

**Comment by MonikaReddy-MSFT** [comment]
@yungezz - Thank you for providing your insights.
@kunthar - I hope @yungezz has answered your question. 
At this moment, Since there is no doc update required for this particular doc, We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
