### ISSUE TITLE
kubectl Unable to connect to the server Azure Kubernetes Service

### ISSUE THREAD

**Issue by realnikhilkumar** [MicrosoftDocs/azure-docs-cli#2380]
Hi,

I am getting below error when using kubectl with MS AKS. I had followed all Microsoft documentation and Kubernetes documentation.

kubectl get nodes
Unable to connect to the server: x509: certificate signed by unknown authority

Azure CLI 2.17.1

Resolution:

Follow thread at https://github.com/kubernetes/kubectl/issues/1000

Hi,

In my case this error was very misleading. It has nothing to do with actual certificate. Microsoft should have done better job in documentation at their end. The error given is incorrect. Error should actually inform user about not have proper runtime setup. AKS is expecting that the user is using a UNIX/Linux terminal not default Azure-CLI. AKS is expecting user to use AKS CLI from a UNIX/Linux terminal/emulator.

I worked with Microsoft Support on this.

Following is the resolution: (Windows 10 system preferred version 2004 or later)

From Control Panel -> Programs -> Turn Windows Features On or Off
Enable Virtual Machine Platform
Enable Windows Subsystem for Linux
Reboot
From Windows Store Install Ubuntu 18.04 LTS
Launch Ubuntu follow prompt to create user id and password
On Ubuntu prompt run command given in option 1 (curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash)
Install kubectl by running sudo az aks install-cli
login to portal.azure.com and copy the connection instructions for AKS cluster
On Ubuntu prompt run az login
On Ubuntu prompt paste the AKS cluster connection commands (az account set --subscription and az aks get-credentials)
This will create config file with certificates readable through bash shell
Reference links
https://docs.microsoft.com/en-us/cli/azure/install-azure-cli
https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-windows?tabs=azure-cli
https://docs.microsoft.com/en-us/windows/wsl/about
https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=apt

Follow above four links one by one, do not click Next Steps at bottom of the page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b7bd326-07b2-caaa-7155-5852fc2dfa3f
* Version Independent ID: c44d0547-d5cd-8934-00f8-79e2f4df53ac
* Content: [Install the Azure CLI](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli)
* Content Source: [docs-ref-conceptual/install-azure-cli.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/install-azure-cli.md)
* Service: **azure-cli**
* GitHub Login: @dbradish-microsoft
* Microsoft Alias: **dbradish**

**Comment by KranthiPakala-MSFT** [comment]
@realnikhilkumar  
Thank you feedback. At this time we are reviewing the feedback and will provide an update as appropriate.

**Comment by BhargaviAnnadevara-MSFT** [comment]
@realnikhilkumar Thanks for the feedback. I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by dbradish-microsoft** [comment]
@jiasli , @chasewilson , This is an install issue that should have been assigned to engineering or the AKS team.  Reassigning.

**Comment by dbradish-microsoft** [comment]
@realnikhilkumar, Thanks for providing feedback that helps improve our documentation. Our Linux installation articles are being refreshed and your feedback will be considered.
