### ISSUE TITLE
dnf instead of yum?

### ISSUE THREAD

**Issue by AwdotiaRomanowna** [MicrosoftDocs/azure-docs-cli#2384]
hi,
maybe worth to update yum do dnf?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7895b9a-9a6a-cd98-6947-0e4a26eda9a3
* Version Independent ID: a3f27295-3e2e-a36d-02c2-8897295fc443
* Content: [Install the Azure CLI for Linux manually](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=apt&view=azure-cli-latest)
* Content Source: [docs-ref-conceptual/install-azure-cli-linux.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/install-azure-cli-linux.md)
* Service: **azure-cli**
* GitHub Login: @dbradish-microsoft
* Microsoft Alias: **dbradish**

**Comment by BhargaviAnnadevara-MSFT** [comment]
@AwdotiaRomanowna Thanks for the question. We're investigating this and will get back to you shortly.

**Comment by Svijay-msft** [comment]
@AwdotiaRomanowna  I am further checking with my team on this. I'll keep you posted on the updates.

**Comment by Svijay-msft** [comment]
@AwdotiaRomanowna  - 

Thanks for bringing this to our attention.  We are in plans to update the document to reflect dnf as a package manager to install Azure CLI.  There will be considerable time involved to go through internal reviews and finally reflect in the public documentation. Rest assured, there are steps taken towards updating document with **dnf**.

Having said that, we will proceed with the closure of this thread provided you don't have further questions while we continue to work on your feedback at our end.
