### ISSUE TITLE
Make common problems and their workarounds more discoverable

### ISSUE THREAD

**Issue by sicklittlemonkey** [MicrosoftDocs/azure-docs-cli#2390]
Today I spent the whole morning wrestling with the following problem:
![image](https://user-images.githubusercontent.com/4393005/104431724-f3b33300-55d3-11eb-9754-450af76b3694.png)

The code is arbitrary, but the problem is apparently well known: https://github.com/Azure/azure-cli/issues/12084

It's amazing that this gotcha exists, but even more amazing that it's not documented where someone might discover it during their introduction to using azure-cli.

Please consider collecting such information and putting it in the path of new users as they install and learn the tools.

Since the problem I encountered is Windwos specific, I've reported this as a bug in the Windows doc page, but there might be a better place for it, or each platform could have their own section on this topic.

Cheers,
Nick.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8246b90a-efb1-03ce-f642-d3eb2441fc30
* Version Independent ID: 2fdd20ef-7bd3-57bc-7957-93f4bb5377ce
* Content: [Install the Azure CLI for Windows](https://docs.microsoft.com/en-au/cli/azure/install-azure-cli-windows?tabs=azure-cli)
* Content Source: [docs-ref-conceptual/install-azure-cli-windows.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/install-azure-cli-windows.md)
* Product: **azure**
* Technology: **azure-cli**
* GitHub Login: @dbradish-microsoft
* Microsoft Alias: **dbradish**

**Comment by BhargaviAnnadevara-MSFT** [comment]
@sicklittlemonkey Thanks for the feedback. We shall evaluate and update the document as appropriate.

**Comment by BhargaviAnnadevara-MSFT** [comment]
@sicklittlemonkey Thanks for the feedback. I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by dbradish-microsoft** [comment]
This application issue has been fixed by the Azure CLI engineering team, so this doc's issue is being closed.
