### ISSUE TITLE
see also Azure Cloud Shell.

### ISSUE THREAD

**Issue by samsammurphy** [MicrosoftDocs/azure-docs-cli#2403]
In the **See Also** section of this page it would be helpful to include a link to 

- [Azure Cloud Shell](https://azure.microsoft.com/en-gb/features/cloud-shell/)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b7bd326-07b2-caaa-7155-5852fc2dfa3f
* Version Independent ID: c44d0547-d5cd-8934-00f8-79e2f4df53ac
* Content: [Install the Azure CLI](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli)
* Content Source: [docs-ref-conceptual/install-azure-cli.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/install-azure-cli.md)
* Service: **azure-cli**
* GitHub Login: @dbradish-microsoft
* Microsoft Alias: **dbradish**

**Comment by BhargaviAnnadevara-MSFT** [comment]
@samsammurphy Thanks for the feedback. We shall evaluate and update the document as appropriate.

**Comment by dbradish-microsoft** [comment]
Hello, @samsammurphy , Did you see the [Run in Azure Cloud Shell](https://docs.microsoft.com/en-us/azure/cloud-shell/quickstart) link?

![image](https://user-images.githubusercontent.com/58762114/105107936-2d2de780-5a87-11eb-81b4-98a08aafd3bb.png)

Were you looking for something other than this?  We try not to duplicate links on a page.

**Comment by BhargaviAnnadevara-MSFT** [comment]
@samsammurphy Agree with @dbradish-microsoft on not duplicating links. Please let us know if you were looking for something more than this.

**Comment by BhargaviAnnadevara-MSFT** [comment]
@samsammurphy We will now proceed to close this thread as resolved, but if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.
