### ISSUE TITLE
Suggest restarting Windows Terminal after installing CLI

### ISSUE THREAD

**Issue by vboctor** [MicrosoftDocs/azure-docs-cli#2461]
After installing Azure CLI, the "AZ" command won't be found if the terminal / console is already open. Opening a new tab won't help, the whole app needs to be closed and re-opened. It may be a good to add a reminder to do so in the Azure CLI install instructions page.

**Comment by kobulloc-MSFT** [comment]
@vboctor Thank you for the feedback!  We are investigating this and will get back to you shortly.

**Comment by kobulloc-MSFT** [comment]
@vboctor Is this the documentation that you were following?
https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-windows?tabs=azure-powershell

You are correct, if you try to use AZ commands before closing and reopening PowerShell they won't be recognized.

![image](https://user-images.githubusercontent.com/37556655/109908451-26cf8580-7c59-11eb-89ea-d257f7b81046.png)

![image](https://user-images.githubusercontent.com/37556655/109908635-7dd55a80-7c59-11eb-8856-e5bf997ea3a4.png)

**Comment by vboctor** [comment]
This is the page that I was referring to:
https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-windows?tabs=azure-cli

(Same as you shared, but I was using the regular command console and not powershell)

I expect the comment to apply to case of running "az" after install from PowerShell or Command prompt. In both cases, user has to completely close the console/terminal app and re-run it to pick up the new PATH.

**Comment by kobulloc-MSFT** [comment]
@vboctor Thank you for the clarification!  I'll go through the documentation and see where we can make this more clear.

**Comment by kobulloc-MSFT** [comment]
@vboctor Thank you for calling this out.  If the command console is open when the Microsoft Installer is run, it will need to be restarted before you can use az commands.  I'm going to add a reminder which should go live in a day or two.

![image](https://user-images.githubusercontent.com/37556655/110070003-e5f57080-7d2d-11eb-9ade-b9812819870d.png)

![image](https://user-images.githubusercontent.com/37556655/110070030-ee4dab80-7d2d-11eb-877f-178c5453519c.png)

**Comment by kobulloc-MSFT** [comment]
@vboctor The PR has been merged and the changes should go live shortly.  Thank you again for bringing this to our attention!  We are going to close this thread as resolved but if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.
