### ISSUE TITLE
`az config` is no longer a valid command

### ISSUE THREAD

**Issue by bennage** [MicrosoftDocs/azure-docs-cli#2465]
I'm using 2.2.0 and `az config` is not recognized.

```
az: 'config' is not in the 'az' command group. See 'az --help'. If the command is from an extension, please make sure the corresponding extension is installed. To learn more about extensions, please visit https://docs.microsoft.com/en-us/cli/azure/azure-cli-extensions-overview

The most similar choice to 'config' is:
        configure
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba27fa77-7839-ce9c-862a-96f72b01ee87
* Version Independent ID: e3f2fc59-4dd6-5016-967e-657319f749b6
* Content: [Azure CLI Extensions](https://docs.microsoft.com/en-us/cli/azure/azure-cli-extensions-overview)
* Content Source: [docs-ref-conceptual/azure-cli-extensions-overview.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/azure-cli-extensions-overview.md)
* Service: **azure-cli**
* GitHub Login: @dbradish-microsoft
* Microsoft Alias: **dbradish**

**Comment by bennage** [comment]
:-P
I was using an older version.

**Comment by kobulloc-MSFT** [comment]
@bennage Happy to hear that you were able to resolve this :)  If you have any other questions about the documentation, just open a new issue and we would be happy to help you.
