### ISSUE TITLE
Issue with either documentation or the command for az cli

### ISSUE THREAD

**Issue by cjmakwana** [MicrosoftDocs/azure-docs-cli#2469]
Just verified this to upgrade az cli. To set the flag, I followed as per this page. There is no command called 'config'. However, there is a command 'configure' which doesn't allow me to set auto upgrade flag!

![image](https://user-images.githubusercontent.com/23075550/110417768-1cc7df80-80bc-11eb-806c-a3b98c2405b3.png)

Looks like Microsoft releases and documentations are not in tune.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f3b4caa-fd05-3a1e-d59a-34a5aa6fbbd7
* Version Independent ID: 9b8fdf78-4b2c-5686-6d19-af4c9b3651bd
* Content: [Update the Azure CLI](https://docs.microsoft.com/en-us/cli/azure/update-azure-cli)
* Content Source: [docs-ref-conceptual/update-azure-cli.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/update-azure-cli.md)
* Service: **azure-cli**
* GitHub Login: @dbradish-microsoft
* Microsoft Alias: **dbradish**

**Comment by kobulloc-MSFT** [comment]
@cjmakwana Thank you for pointing this out.  The documentation notes that `az upgrade` requires version 2.11.0 or later and it looks like the assumption is made that version 2.11.0 or later is being used for the rest of the page.

`az config` was added [August 4th, 2020 in version 2.10.0](https://docs.microsoft.com/en-us/cli/azure/release-notes-azure-cli?tabs=azure-cli#august-04-2020) however we're missing instructions here for people with older versions which are under [Install or Update](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-windows?tabs=azure-cli#install-or-update) under the Install documentation.

**With CLI version 2.1.0:**

![image](https://user-images.githubusercontent.com/37556655/110429580-01c78200-8060-11eb-8b9f-b0985f647f02.png)


**With CLI version 2.20.0 (updated by running the [MSI installer](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-windows?tabs=azure-cli#install-or-update)):**

![image](https://user-images.githubusercontent.com/37556655/110429863-61259200-8060-11eb-8095-8d7f428b843a.png)

**Comment by kobulloc-MSFT** [comment]
@cjmakwana Thank you again for pointing this out.  Anyone using a version of CLI prior to 2.11.0 can use the [MSI installer](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-windows?tabs=azure-cli#install-or-update).  We are working to make this clearer moving forward and this is being tracked in [GitHub Issue 17261](https://github.com/Azure/azure-cli/issues/17261).  We're going to close this issue but if you have any additional questions, please tag me in your reply and we'd be happy to continue the conversation.
