### ISSUE TITLE
Remove command recommendation with side effects

### ISSUE THREAD

**Issue by edernucci** [MicrosoftDocs/azure-docs-cli#2475]
Please never encourage a user to run the command `sudo apt remove azure-cli -y && sudo apt autoremove -y`.

When describing this command, the author assumes that the user does not have any pending removal packages. If he has any pending packages that he did not remove for personal reasons, when executing the recommended command he will have all pending removal packages on his system removed, and not just `azure-cli`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7895b9a-9a6a-cd98-6947-0e4a26eda9a3
* Version Independent ID: a3f27295-3e2e-a36d-02c2-8897295fc443
* Content: [Install the Azure CLI for Linux manually](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-linux)
* Content Source: [docs-ref-conceptual/install-azure-cli-linux.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/install-azure-cli-linux.md)
* Service: **azure-cli**
* GitHub Login: @dbradish-microsoft
* Microsoft Alias: **dbradish**

**Comment by kobulloc-MSFT** [comment]
@edernucci Thank you for bringing this to our attention.  We are investigating this and will get back to you shortly.

**Comment by dbradish-microsoft** [comment]
@edernucci, Thanks for providing feedback that helps improve our documentation.  We are refreshing our install doc for Linux and your feedback is being considered.
