### ISSUE TITLE
possibility of having multiple config file

### ISSUE THREAD

**Issue by minnieshi** [MicrosoftDocs/azure-docs-cli#2497]
[can multiple configuration file be used. example if one has multiple resource group(hence multiple storage account, 1 each under each resource group), it would be possible to switch environment dev/prod]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb42002e-9aa3-233d-9832-353235b7cd0f
* Version Independent ID: e8b320b1-5805-67ba-46b2-48111861facc
* Content: [Azure CLI configuration options](https://docs.microsoft.com/en-us/cli/azure/azure-cli-configuration)
* Content Source: [docs-ref-conceptual/azure-cli-configuration.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/azure-cli-configuration.md)
* Service: **azure-cli**
* GitHub Login: @dbradish-microsoft
* Microsoft Alias: **dbradish**

**Comment by MonikaReddy-MSFT** [comment]
@minnieshi - 
Thanks for brining this to our attention. We will investigate it further and update you shortly.

**Comment by dbradish-microsoft** [comment]
@minnieshi, Thank you for this suggestion.  Regardless of the active subscription, the CLI configuration information is located at $AZURE_CONFIG_DIR/config. The default value of AZURE_CONFIG_DIR is $HOME/.azure on Linux and macOS, and %USERPROFILE%\.azure on Windows.  So when switching between environments with `az account set --subscription mySubName`, the stored values in the config file and locally stored environment variables don't change.  

If I am interpreting your ask correctly, you are looking for behavior in tools like Terraform where every environment can have its own config information to toggle easily between DEV, STG and PROD.  In speaking with the Azure CLI engineering team this evening, if you would be willing to share some basic background and current contact information with me, they would like to hear more detail from you.  You can send me your information at dbradish@microsoft.com.  I look forward to hearing from you.

Kindly,

Delora J Bradish
Senior Content Developer for the Azure CLI
C+AI Developer Relations

**Comment by MonikaReddy-MSFT** [comment]
@dbradish-microsoft - Thank you for providing your insights.
@minnieshi - I hope @dbradish-microsoft has answered your question. 
At this moment, Since there is no doc update required, We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
