### ISSUE TITLE
how to upgrade versions prior to 2.11.0

### ISSUE THREAD

**Issue by ForrestTrepte** [MicrosoftDocs/azure-docs-cli#2498]
This note was very helpful to me: `The az upgrade command was added in version 2.11.0 and will not work with versions prior to 2.11.0.`

However, at first I was unsure what to do. I had the older version and had no idea how to get to the new version. I eventually decided to run the install at https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-windows?tabs=azure-cli and that worked for me. Worth adding that to the note?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f3b4caa-fd05-3a1e-d59a-34a5aa6fbbd7
* Version Independent ID: 9b8fdf78-4b2c-5686-6d19-af4c9b3651bd
* Content: [Update the Azure CLI](https://docs.microsoft.com/en-us/cli/azure/update-azure-cli)
* Content Source: [docs-ref-conceptual/update-azure-cli.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/update-azure-cli.md)
* Service: **azure-cli**
* GitHub Login: @dbradish-microsoft
* Microsoft Alias: **dbradish**

**Comment by kobulloc-MSFT** [comment]
@ForrestTrepte Thank you for reaching out!

> This note was very helpful to me: The az upgrade command was added in version 2.11.0 and will not work with versions prior to 2.11.0.

This is a recent addition. I'm happy to hear that it is helpful!

> However, at first I was unsure what to do. I had the older version and had no idea how to get to the new version.

I'm looking at the note right now and I agree, update instructions would be really useful here.  I'll submit a PR to address this.

**Comment by ForrestTrepte** [comment]
I just submitted a PR with my suggestion for addressing it: #2499. Feel free to use this or close it if you want to take a different approach.
