### ISSUE TITLE
GPG BADSIG for Ubuntu Cosmic packages.microsoft.com repo

### ISSUE THREAD

**Issue by philtweir** [MicrosoftDocs/azure-docs-cli#2510]
Ahead of fetching the azure-cli package from https://packages.microsoft.com/ubuntu/18.10/prod/dists/cosmic/, `apt update` complains that the signature is bad.

```
W: GPG error: https://packages.microsoft.com/ubuntu/18.10/prod cosmic Release: The following signatures were invalid: BADSIG EB3E94ADBE1229CF Microsoft (Release signing) <gpgsecurity@microso
ft.com>                                                                                        
E: The repository 'https://packages.microsoft.com/ubuntu/18.10/prod cosmic Release' is not signed.
```

This occurred today in a stable, fairly regularly run build-script that first runs:

```
    wget -q https://packages.microsoft.com/config/ubuntu/18.10/packages-microsoft-prod.deb
    curl -sL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > /etc/apt/trusted.gpg.d/microsoft.gpg
    dpkg -i packages-microsoft-prod.deb
```

before an apt clean and update.

To isolate the issue, I have imported the `microsoft.gpg` key locally, downloaded the Release* files from the repository and run `gpg --verify Release.gpg Release`, which gives:

```
gpg: Signature made Thu 01 Apr 2021 18:04:13 BST
gpg:                using RSA key EB3E94ADBE1229CF
gpg: BAD signature from "Microsoft (Release signing) <gpgsecurity@microsoft.com>" [unknown]
```

**Comment by ram-msft** [comment]
@philtweir Thanks for the question. We are investigating the issue and will update you shortly.

**Comment by BhargaviAnnadevara-MSFT** [comment]
@philtweir Thanks for reaching out. I've reached out to our Product group about this issue and will keep you posted as I have more details.

**Comment by BhargaviAnnadevara-MSFT** [comment]
@philtweir Cosmic has reached its end-of-life on July 18, 2019 (See https://wiki.ubuntu.com/Releases). We no longer support it with newer versions of CLI.

Please consider using one of the following tested distros for Ubuntu:

![image](https://user-images.githubusercontent.com/44050820/113805912-04acb400-977f-11eb-953d-7cd975ff449a.png)

**Comment by BhargaviAnnadevara-MSFT** [comment]
@philtweir Hope the above inputs help. We will now proceed to close this thread as resolved, but if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.
