### ISSUE TITLE
Azure-CLI Installation using Powershell is not working 

### ISSUE THREAD

**Issue by kgopi1** [MicrosoftDocs/azure-docs-cli#2512]
Hi, 

I tried installing the Azure CLI using PowerShell command as per the below link and it is not working. 

https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-windows?tabs=azure-powershell#install-or-update 

Command used: Start-Process msiexec.exe -Wait '/i /lv log.txt AzureCLI.msi /quiet '

Log file for installation failure : 

=== Verbose logging started: 03/04/2021  16:14:24  Build type: SHIP UNICODE 5.00.10011.00  Calling process: C:\WINDOWS\system32\msiexec.exe ===
MSI (c) (38:80) [16:14:24:165]: Resetting cached policy values
MSI (c) (38:80) [16:14:24:165]: Machine policy value 'Debug' is 0
MSI (c) (38:80) [16:14:24:165]: ******* RunEngine:
           ******* Product: AzureCLI.msi
           ******* Action: 
           ******* CommandLine: **********
MSI (c) (38:80) [16:14:24:165]: Client-side and UI is none or basic: Running entire install on the server.
MSI (c) (38:80) [16:14:24:165]: Grabbed execution mutex.
MSI (c) (38:80) [16:14:24:179]: Cloaking enabled.
MSI (c) (38:80) [16:14:24:179]: Attempting to enable all disabled privileges before calling Install on Server
MSI (c) (38:80) [16:14:24:187]: Incrementing counter to disable shutdown. Counter after increment: 0
MSI (s) (88:3C) [16:14:24:197]: Running installation inside multi-package transaction C:\AzureCLI.msi
MSI (s) (88:3C) [16:14:24:197]: Grabbed execution mutex.
MSI (s) (88:38) [16:14:24:201]: Resetting cached policy values
MSI (s) (88:38) [16:14:24:201]: Machine policy value 'Debug' is 0
MSI (s) (88:38) [16:14:24:201]: ******* RunEngine:
           ******* Product: C:\AzureCLI.msi
           ******* Action: 
           ******* CommandLine: **********
MSI (s) (88:38) [16:14:24:202]: Note: 1: 2203 2: c:\AzureCLI.msi 3: -2147286960 
MSI (s) (88:38) [16:14:24:202]: MainEngineThread is returning 1620
MSI (s) (88:3C) [16:14:24:204]: User policy value 'DisableRollback' is 0
MSI (s) (88:3C) [16:14:24:204]: Machine policy value 'DisableRollback' is 0
MSI (s) (88:3C) [16:14:24:204]: Incrementing counter to disable shutdown. Counter after increment: 0
MSI (s) (88:3C) [16:14:24:205]: Note: 1: 1402 2: HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Installer\Rollback\Scripts 3: 2 
MSI (s) (88:3C) [16:14:24:205]: Note: 1: 1402 2: HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Installer\Rollback\Scripts 3: 2 
MSI (s) (88:3C) [16:14:24:205]: Decrementing counter to disable shutdown. If counter >= 0, shutdown will be denied.  Counter after decrement: -1
MSI (c) (38:80) [16:14:24:207]: Decrementing counter to disable shutdown. If counter >= 0, shutdown will be denied.  Counter after decrement: -1
MSI (c) (38:80) [16:14:24:208]: MainEngineThread is returning 1620
=== Verbose logging stopped: 03/04/2021  16:14:24 ===

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8246b90a-efb1-03ce-f642-d3eb2441fc30
* Version Independent ID: 2fdd20ef-7bd3-57bc-7957-93f4bb5377ce
* Content: [Install the Azure CLI for Windows](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-windows?tabs=azure-powershell)
* Content Source: [docs-ref-conceptual/install-azure-cli-windows.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/install-azure-cli-windows.md)
* Product: **azure**
* Technology: **azure-cli**
* GitHub Login: @dbradish-microsoft
* Microsoft Alias: **dbradish**

**Comment by MartinJaffer-MSFT** [comment]
Thank you for your detailed feedback.  We are looking into the issue, and we will respond when we have more information.

**Comment by Svijay-msft** [comment]
Can you please confirm the size of the download AzureCLI.msi file and existence of the AzureCLI.msi file ?  This error usually when the file/package is not present or corrupt - or simply when the package AzureCLI.msi is un-openable. 

If the file is already present, remove it manually or using the command `rm .\AzureCLI.msi` , run the below command  : 
 
    Invoke-WebRequest -Uri https://aka.ms/installazurecliwindows -OutFile .\AzureCLI.msi

This downloads the AzureCLI Package. This may take few minutes .The size should be around 47 MB (while writing this comment) 
`(Get-ChildItem -Path .\ -File AzureCli.msi).Length`  gives the size in Bytes

Once you confirm this, you could run the below command as mentioned in the document  :
 `Start-Process msiexec.exe -Wait -ArgumentList '/i AzureCLI_2.msi /lv outputlog.txt  /quiet'`

**Comment by Svijay-msft** [comment]
Just checking in to see if you have had a chance to see the previous response. Kindly let us know if you need further assistance on this issue or is good to be closed.

**Comment by Svijay-msft** [comment]
Since we have not heard back from you we will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply and we will gladly continue the discussion.
