### ISSUE TITLE
Incorrect parameter value in az login command example

### ISSUE THREAD

**Issue by Sumtin** [MicrosoftDocs/azure-docs-cli#2569]
az login command when using Service Principal is asking for "app-url" instead of ClientID as per https://docs.microsoft.com/en-us/cli/azure/create-an-azure-service-principal-azure-cli.  

This page shows:
az login --service-principal -u **app-url** -p password-or-cert --tenant tenant

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93174b3a-3e97-8304-83fc-807be75198fe
* Version Independent ID: 1155045b-ce8c-2def-7b0e-043283f8be01
* Content: [Sign in with the Azure CLI](https://docs.microsoft.com/en-us/cli/azure/authenticate-azure-cli)
* Content Source: [docs-ref-conceptual/authenticate-azure-cli.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/authenticate-azure-cli.md)
* Service: **azure-cli**
* GitHub Login: @dbradish-microsoft
* Microsoft Alias: **dbradish**

**Comment by SaurabhSharma-MSFT** [comment]
@Sumtin Thanks for your feedback! We will investigate and update as appropriate.

**Comment by dbradish-microsoft** [comment]
@Sumtin, @SaurabhSharma-MSFT , This article has been corrected in PR [2640](https://github.com/MicrosoftDocs/azure-docs-cli/pull/2640)
