### ISSUE TITLE
Installation for Leap 15.2 not working

### ISSUE THREAD

**Issue by grisu48** [MicrosoftDocs/azure-docs-cli#2572]
Hi,

the current installation Instructions don't work on Leap 15.2. I've been following the recommended steps as follows:

    rpm --import https://packages.microsoft.com/keys/microsoft.asc
    zypper addrepo --name 'Azure CLI' --check https://packages.microsoft.com/yumrepos/azure-cli azure-cli
    zypper install --from azure-cli azure-cli

Then even a simple `az login` already fails:

    az login
    /usr/bin/python3: No module named azure.cli.__main__; 'azure.cli' is a package and cannot be directly executed

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: e7895b9a-9a6a-cd98-6947-0e4a26eda9a3
* Version Independent ID: a3f27295-3e2e-a36d-02c2-8897295fc443
* Content: [Manuelles Installieren der Azure CLI für Linux](https://docs.microsoft.com/de-de/cli/azure/install-azure-cli-linux?pivots=yum)
* Content Source: [docs-ref-conceptual/install-azure-cli-linux.md](https://github.com/MicrosoftDocs/azure-docs-cli.de-de/blob/live/docs-ref-conceptual/install-azure-cli-linux.md)
* Service: **azure-cli**
* GitHub Login: @dbradish-microsoft
* Microsoft Alias: **dbradish**

**Comment by grisu48** [comment]
Hmmm, I've tried to reproduce the issue in a clean environment where it looks like it is not occurring. Could be that there were some remnants of a previous installation which caused this issue. If anyone can confirm that we could close this issue.

**Comment by JayaChatterjee-MSFT** [comment]
@grisu48  Thank you for the question. We will review and get back to you.

**Comment by Svijay-msft** [comment]
@grisu48 I tested it at my end.  Unfortunately, I was not able to reproduce the issue at my end. I was able to install and run the az commands by following the steps in the document.

![image](https://user-images.githubusercontent.com/66949976/116879603-75d86d80-ac3e-11eb-9da6-f56fd1d8393b.png)

**Comment by grisu48** [comment]
Thank you for looking into it. Then it must be indeed some remnants from a previous install. Guess we can close the issue then.

**Comment by grisu48** [comment]
Closing as invalid.
