### ISSUE TITLE
The slowest download on the internet

### ISSUE THREAD

**Issue by cornelhuman** [MicrosoftDocs/azure-docs-cli#2577]
There is noting on the internet that downloads more slowly than this azurecli msi. It would be faster driving 1000km with a memory stick and copy it from someone that has it, drive back and install it. btw I have a 1gig internet line...

https://azcliprod.blob.core.windows.net/msi/azure-cli-2.23.0.msi

Is blob storage on vacation, or hosted on mars?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8246b90a-efb1-03ce-f642-d3eb2441fc30
* Version Independent ID: 2fdd20ef-7bd3-57bc-7957-93f4bb5377ce
* Content: [Install the Azure CLI for Windows](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-windows?tabs=azure-cli)
* Content Source: [docs-ref-conceptual/install-azure-cli-windows.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/install-azure-cli-windows.md)
* Product: **azure**
* Technology: **azure-cli**
* GitHub Login: @dbradish-microsoft
* Microsoft Alias: **dbradish**

**Comment by MarileeTurscak-MSFT** [comment]
@cornelhuman thank you for the feedback and I am sorry that the download is so slow for you! 

If you would like to make an official feature request around this you can do so here: https://feedback.azure.com/forums/34192--general-feedback
