### ISSUE TITLE
Better to download installers to temp folder instead of current folder 

### ISSUE THREAD

**Issue by archerzz** [MicrosoftDocs/azure-docs-cli#2603]
Normally there should be `temp` environment variable which points to the temp folder of the current user. So it would be better if the installation script can be changed to use `temp`, like below:

```powershell
Invoke-WebRequest -Uri https://aka.ms/installazurecliwindows -OutFile "$env:temp\AzureCLI.msi"; Start-Process msiexec.exe -Wait -ArgumentList "/I $env:temp\AzureCLI.msi /quiet"; rm "$env:temp\AzureCLI.msi"
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8246b90a-efb1-03ce-f642-d3eb2441fc30
* Version Independent ID: 2fdd20ef-7bd3-57bc-7957-93f4bb5377ce
* Content: [Install the Azure CLI for Windows](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-windows?tabs=azure-cli)
* Content Source: [docs-ref-conceptual/install-azure-cli-windows.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/install-azure-cli-windows.md)
* Product: **azure**
* Technology: **azure-cli**
* GitHub Login: @dbradish-microsoft
* Microsoft Alias: **dbradish**

**Comment by HarshitaSingh-MSFT** [comment]
Hello @archerzz , thanks for taking time to share your valuable feedback! We are taking a look into this and will get back to you soon.

**Comment by HarshitaSingh-MSFT** [comment]
This issue has been moved to Engineering repo as a Feature request. 
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
