### ISSUE TITLE
YAML is machine readable?

### ISSUE THREAD

**Issue by lostmygithubaccount** [MicrosoftDocs/azure-docs-cli#2630]
from this page: "YAML, a machine-readable alternative to JSON" - isn't JSON also machine-readable? should this say human-readable or friendly?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 48273ba7-da5a-95f0-7ffc-8c6d5282313d
* Version Independent ID: 83d348f9-fd1f-1041-0304-d8634e5526d4
* Content: [Output formats for Azure CLI](https://docs.microsoft.com/en-us/cli/azure/format-output-azure-cli)
* Content Source: [docs-ref-conceptual/format-output-azure-cli.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/format-output-azure-cli.md)
* Service: **azure-cli**
* GitHub Login: @dbradish-microsoft
* Microsoft Alias: **dbradish**

**Comment by kobulloc-MSFT** [comment]
@lostmygithubaccount Yeah, I would agree.  YAML is definitely human-readable (as hinted at in the name, YAML Ain't Markup Language).  I think the intention was to describe it as human-readable as is often used in the description of YAML.  I'll get that updated.

**Comment by kobulloc-MSFT** [comment]
@lostmygithubaccount Those changes have been merged and should go live soon.  Thank you again for helping us improve the documentation!  We are going to close this thread as resolved but if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.
