### ISSUE TITLE
"zypper rm -y --clean-deps azure-cli"

### ISSUE THREAD

**Issue by GlennWOW** [MicrosoftDocs/azure-docs-cli#2651]
The fix for older version removal on SLES "zypper rm -y --clean-deps azure-cli", breaks sap scs/ers cluster deployments as removes libraries required for crm sap cluster support on azure namely  python3-azure-mgmt-compute.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7895b9a-9a6a-cd98-6947-0e4a26eda9a3
* Version Independent ID: a3f27295-3e2e-a36d-02c2-8897295fc443
* Content: [Install the Azure CLI for Linux manually](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=zypper#install)
* Content Source: [docs-ref-conceptual/install-azure-cli-linux.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/install-azure-cli-linux.md)
* Service: **azure-cli**
* GitHub Login: @dbradish-microsoft
* Microsoft Alias: **dbradish**

**Comment by kobulloc-MSFT** [comment]
@GlennWOW Thank you for bringing this to our attention!  We've assigned this to the document author for review.

**Comment by dbradish-microsoft** [comment]
@GlennWOW. Thanks for providing feedback that helps improve our documentation. This issue is being taken under consideration for our December refresh of [Install the Azure CLI on Linux](https://learn.microsoft.com/en-us/cli/azure/install-azure-cli-linux?view=azure-cli-latest&pivots=apt).
