### ISSUE TITLE
AZ CLI downloading very slow 64kpbs 

### ISSUE THREAD

**Issue by PradeeDevananth** [MicrosoftDocs/azure-docs-cli#2663]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8246b90a-efb1-03ce-f642-d3eb2441fc30
* Version Independent ID: 2fdd20ef-7bd3-57bc-7957-93f4bb5377ce
* Content: [Install the Azure CLI for Windows](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-windows?tabs=azure-cli)
* Content Source: [docs-ref-conceptual/install-azure-cli-windows.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/install-azure-cli-windows.md)
* Product: **azure**
* Technology: **azure-cli**
* GitHub Login: @dbradish-microsoft
* Microsoft Alias: **dbradish**

**Comment by AshokPeddakotla-MSFT** [comment]
@PradeeDevananth Thanks for the feedback! We are currently investigating and will update you shortly.

**Comment by HarshitaSingh-MSFT** [comment]
@PradeeDevananth, can you please tell me what is the ask?

**Comment by HarshitaSingh-MSFT** [comment]
Hello!
Just checking to see if you have had a chance to see the previous response. Kindly let us know if it answers your question and if you need further assistance on this issue.

**Comment by HarshitaSingh-MSFT** [comment]
Hello!
Just checking to see if you have had a chance to see the previous response. Kindly let us know if it answers your question and if you need further assistance on this issue.

**Comment by HarshitaSingh-MSFT** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
