### ISSUE TITLE
login when company uses third party

### ISSUE THREAD

**Issue by edgreenberg** [MicrosoftDocs/azure-docs-cli#2679]
My company requires me to log into azure by means of okta. In other words, azure portal opens okta and then we return to azure portal. 

When following the instructions for az login, I got errors at the browser level. I decided it couldn't launch okta. Not sure of this. 

So I entered portal.azure.com, logged in, then did az login at the command line and got success. 

Perhaps a suggestion should be added to the page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c268a98-afcb-d2c2-87c7-880d52900533
* Version Independent ID: 4c835da4-38bc-22a8-67b4-dd522adcc0e3
* Content: [Get started with Azure CLI](https://docs.microsoft.com/en-us/cli/azure/get-started-with-azure-cli)
* Content Source: [docs-ref-conceptual/get-started-with-azure-cli.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/get-started-with-azure-cli.md)
* Service: **azure-cli**
* GitHub Login: @dbradish-microsoft
* Microsoft Alias: **dbradish**

**Comment by kobulloc-MSFT** [comment]
@edgreenberg Thank you for bringing this to our attention!  We'll look into this and get back to you shortly.

**Comment by kobulloc-MSFT** [comment]
@edgreenberg It looks like Okta uses the same command in their documentation with a reference to this page:
https://help.okta.com/oag/en-us/Content/Topics/Access-Gateway/deploy-msa-cli.htm

![image](https://user-images.githubusercontent.com/37556655/128105190-af4aa41c-79d6-4588-b162-3e849563d9c8.png)

There's also another reference on their developer blog:
https://developer.okta.com/blog/2020/09/02/10x-development-azure-cli-dotnet

It's possible the error you are encountering is related to how Okta has been configured for your environment.

**Comment by edgreenberg** [comment]
In my case, I believe I am squared away since I can just log into portal
via okta before using CLI commands.

I think that will work for me.

I was reporting this more so you could consider putting some sort of
warning in the documentation for others who use third party authentication.

Thanks for your attention.

**Comment by kobulloc-MSFT** [comment]
@edgreenberg Good to hear!  Third party documentation is a bit tricky because there are extra criteria for verification and it's easier for information to become outdated (making it less frequent as a result).  This thread is viewable for all readers of the documentation, however, and serves as a great resource for others who may run into this issue.  Thank you for helping to improve the docs!

**Comment by kobulloc-MSFT** [comment]
@edgreenberg Thank you again for helping to improve the docs.  We are going to close this thread as resolved but if there are any further questions or comments regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.
