### ISSUE TITLE
Azure CLI - RHEL install, Yum repos is not accessible, generating 404

### ISSUE THREAD

**Issue by krishnaprabhat** [MicrosoftDocs/azure-docs-cli#2691]
https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=dnf

The Yum repos is not accessible, generating 404.

![Screen Shot 2021-08-10 at 6 35 09 PM](https://user-images.githubusercontent.com/50242680/128943614-0899753f-3bd3-4334-ae17-22e0db0c7889.png)
![Screen Shot 2021-08-10 at 6 34 45 PM](https://user-images.githubusercontent.com/50242680/128943615-acd29945-c937-47b8-a503-136d17e2795b.png)

**Comment by BhargaviAnnadevara-MSFT** [comment]
@krishnaprabhat Thanks for bringing this to our attention. Do you still see this happening?

I'm able to access https://packages.microsoft.com/yumrepos/azure-cli without any issues:

![image](https://user-images.githubusercontent.com/44050820/128999908-d46df397-d7b1-44a6-8109-7f782ae04fe1.png)

Please check and let me know.

**Comment by krishnaprabhat** [comment]
I am able to access it now. Do we have any RCA for this issue.

**Comment by BhargaviAnnadevara-MSFT** [comment]
@krishnaprabhat AFAIK, there wasn't a known incident for the noticed behavior on our side. That said, if you run into this issue again, please file an issue with [Azure/azure-cli](https://github.com/Azure/azure-cli/issues) repository so our Engineering Team can take a look.

Also, on a side note, I'd like to let you know that this channel (the [Azure CLI Docs](https://github.com/MicrosoftDocs/azure-docs-cli) repository) is only for driving improvements related to the [Azure CLI documentation](https://docs.microsoft.com/en-us/cli/azure/). At this point, it appears that there are no edits or updates needed to the document in question. Hence closing this issue for now. If there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.
