### ISSUE TITLE
"Try it!" login is convoluted

### ISSUE THREAD

**Issue by jenellea** [MicrosoftDocs/azure-docs-cli#2699]
Using the "try it!" launched 3 windows, 3 login attempts, and multiple questions which account I was using to login. All that AFTER providing the one time use "code" generated in the CLI window.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8246b90a-efb1-03ce-f642-d3eb2441fc30
* Version Independent ID: 2fdd20ef-7bd3-57bc-7957-93f4bb5377ce
* Content: [Install the Azure CLI for Windows](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-windows?tabs=azure-cli)
* Content Source: [docs-ref-conceptual/install-azure-cli-windows.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/install-azure-cli-windows.md)
* Product: **azure**
* Technology: **azure-cli**
* GitHub Login: @dbradish-microsoft
* Microsoft Alias: **dbradish**

**Comment by CHEEKATLAPRADEEP-MSFT** [comment]
@jenellea  Thanks for the question! We are investigating and will update you shortly.

**Comment by HarshitaSingh-MSFT** [comment]
@jenellea, this did not happen to me. After providing code like in below line:

> To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code H4***P to authenticate.

After providing code, I got login screen with my default login method screen and it successfully logged in. I would recommend you to "Try this!" in InPrivate/Incognito mode again. Also, if it still does not work, let me know other specifics with screenshots.

**Comment by kobulloc-MSFT** [comment]
@jenellea Hopefully you are not still running into issues with the "try it" feature of the documentation.  I suspect that there was a delay which caused 3 attempts to connect and that may have been responsible for the behavior you saw.  If you are still running into this issue, please tag @HarshitaSingh-MSFT in your reply and we will reopen this issue for further investigation.
