### ISSUE TITLE
Consider a name change for "Azure PowerShell"

### ISSUE THREAD

**Issue by rsbuckles** [MicrosoftDocs/azure-docs-cli#2713]
That name is rather unfortunate and confusing, IMO.  It leads one to believe it is a shell for Azure when in fact it is a set of cmdlets, i.e., a module callable from a shell, i.e., PowerShell, not a shell itself.  Two different concepts.

> Windows PowerShell, PowerShell, Cmd, and Bash **are shell environments**. Your shell environment not only determines which tools you can use but also changes your command-line experience.

> Azure PowerShell is **set of cmdlets** packaged as a PowerShell module named Az; not an executable. Windows PowerShell or PowerShell must be used to install the Az module.

Something like "Azure PS Cmdlets" or "Azure PSC" (like Azure CLI ) or really *anything* without the full word "PowerShell" in it would be helpful for disambiguation and clarity.

Also, this sentence, while mentioning the confusion, contributes to it by conflating the concepts of a command and a shell, IMO:

> Azure CLI, Azure PowerShell, and Azure Cloud Shell have overlapping functionality. Each operates differently, and the language is sometimes confused with the environment. Use this guide to determine which is the right tool for you.

The implication of the wording is that Azure CLI, Azure PowerShell, and Azure Cloud Shell are of the same type.  They are not.  The first two are the commands callable from a shell.  The last is a shell, albeit an online one.

Lastly, here is an example of a sentence that is practically nonsensical IMO because of the naming of Azure PowerShell:

> Cloud Shell provides two shell environments: Bash (with Azure CLI preinstalled) and PowerShell (with Azure PowerShell preinstalled). A dropdown list at the top of the Cloud Shell window allows you to easily switch between the two environments.

PowerShell with Azure PowerShell preinstalled?  What does that mean?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 385d1790-0cf8-3759-aefe-8044acaf6df7
* Version Independent ID: 333d9ead-ae04-1cd9-e57b-fa9710e4238e
* Content: [Choose the right Azure command-line tool - Azure CLI](https://docs.microsoft.com/en-us/cli/azure/choose-the-right-azure-command-line-tool#feedback)
* Content Source: [docs-ref-conceptual/choose-the-right-azure-command-line-tool.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/choose-the-right-azure-command-line-tool.md)
* Service: **azure**
* GitHub Login: @Duffney
* Microsoft Alias: **jduffney**

**Comment by MarileeTurscak-MSFT** [comment]
@rsbuckles Thanks for your feedback! I see your point and we have passed your message along to the product team.

CC @Duffney
