### ISSUE TITLE
[Feature Request] Show experimental/preview/deprecation info in docs

### ISSUE THREAD

**Issue by jiasli** [MicrosoftDocs/azure-docs-cli#2720]
Status tags like **experimental**/**preview**/**deprecation** should be shown in docs as CLI does (https://github.com/Azure/azure-cli/issues/12549).
 
Status tags can be applied to **command group**/**command**/**argument** levels.

- **Deprecation** tells the user that it is deprecated and it should redirect them to use the alternatives.
- **Experimental**/**Preview** tells the user that it is under experimental/preview and it might change someday.

For example (https://github.com/MicrosoftDocs/azure-docs-cli/pull/2602), `az vm image accept-terms` is deprecated:

```
> az vm image accept-terms -h

Command
    az vm image accept-terms : Accept Azure Marketplace term so that the image can be used to create
    VMs.
        This command has been deprecated and will be removed in version '3.0.0'. Use 'az vm
        image terms accept' instead.
```

but the document for `az vm image accept-terms` doesn't reflect this:

https://docs.microsoft.com/en-us/cli/azure/vm/image?view=azure-cli-latest#az_vm_image_accept_terms

![image](https://user-images.githubusercontent.com/4003950/130890555-e3adb24b-8e9c-4b75-983c-2dca231dbea8.png)

Email: _Add additional information to Azure CLI Docs_

**Comment by dbradish-microsoft** [comment]
@Jiasli, This issue is being closed to accommodate SLA requirements.  Adding reference type, status (includes isDeprecated) and minimum CLI version is set to publish CYQ1.  Please see @matrilby for more detail.

**Comment by jiasli** [comment]
@dbradish-microsoft, can we keep this issue open as this feature request hasn't been implemented yet. We are still seeing users asking for this feature: https://github.com/Azure/azure-cli/issues/25316.
