### ISSUE TITLE
Install Azure CLI from cmd does not work

### ISSUE THREAD

**Issue by D3m1urg3** [MicrosoftDocs/azure-docs-cli#2727]
The instructions to install azure cli from command line does not work. The command provided in the official documentation:

$ powershell -Command "Invoke-WebRequest -Uri https://aka.ms/installazurecliwindows -OutFile .\AzureCLI.msi; Start-Process msiexec.exe -Wait -ArgumentList '/I AzureCLI.msi /quiet'; rm .\AzureCLI.msi"

Installs azure but does not adds it to registry making the installation worthless.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b7bd326-07b2-caaa-7155-5852fc2dfa3f
* Version Independent ID: c44d0547-d5cd-8934-00f8-79e2f4df53ac
* Content: [How to install the Azure CLI](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli)
* Content Source: [docs-ref-conceptual/install-azure-cli.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/install-azure-cli.md)
* Service: **azure-cli**
* GitHub Login: @dbradish-microsoft
* Microsoft Alias: **dbradish**

**Comment by HarshitaSingh-MSFT** [comment]
Hello @D3m1urg3 , thanks for taking time to share your valuable feedback! We are taking a look into this and will get back to you soon.

**Comment by D3m1urg3** [comment]
> Hello @D3m1urg3 , thanks for taking time to share your valuable feedback! Can you pls explain, what do you mean by "registry"?

After installation the az command is not recognized. Does not matter that one opens a fresh cmd or powershell.

Mimicking the path entry when the az cli is installed by using ui instead of command line does not help either.

**Comment by HarshitaSingh-MSFT** [comment]
@D3m1urg3 , thanks for the information. I have verified this behavior and will reach out to the PG to rectify this. Thanks for reporting!

**Comment by D3m1urg3** [comment]
Thanks!

**Comment by D3m1urg3** [comment]
I'm testing this in a vm.

- This is my path before installing azure cli:

PS C:\Users\IEUser> echo $env:PATH  C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\ProgramData\chocolatey\bin;C:\Program Files\Puppet Labs\Puppet\bin;C:\Program 
Files\Perforce\;C:\Users\IEUser\AppData\Local\Microsoft\WindowsApps;

- Run the installer from a powershell using the provided command in doc, it does not work properly:

PS C:\Users\IEUser> Invoke-WebRequest -Uri https://aka.ms/installazurecliwindows -OutFile .\AzureCLI.msi; Start-Process msiexec.exe -Wait -ArgumentList '/I AzureCLI.msi /quiet'; rm .\AzureCLI.msi
PS C:\Users\IEUser> az
az : The term 'az' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the
spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ az
+ ~~
    + CategoryInfo          : ObjectNotFound: (az:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

- Path after install:

PS C:\Users\IEUser> echo $env:PATH
C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\ProgramData\chocolatey\bin;C:\Program Files\Puppet Labs\Puppet\bin;C:\Program Files\Perforce\;C:\Users\IEUser\AppData\Local\Microsoft\WindowsApps;

- Apparently Installation failed as the azure cli folder does not exists.

PS C:\Program Files (x86)> ls


    Directory: C:\Program Files (x86)


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        8/26/2021   1:18 PM                BraveSoftware
d-----        9/15/2018  12:42 AM                Common Files
d-----        3/19/2019   6:19 AM                Internet Explorer
d-----        3/19/2019   6:03 AM                Microsoft Silverlight
d-----        9/15/2018  12:33 AM                Microsoft.NET
d-----         9/2/2021  12:05 AM                Vim
d-----        9/15/2018   2:07 AM                Windows Defender
d-----        9/15/2018  12:33 AM                Windows Mail
d-----        3/19/2019   6:19 AM                Windows Media Player
d-----        9/15/2018   2:10 AM                Windows Multimedia Platform
d-----        9/15/2018  12:42 AM                windows nt
d-----        3/19/2019   6:19 AM                Windows Photo Viewer
d-----        9/15/2018   2:10 AM                Windows Portable Devices
d-----        9/15/2018  12:33 AM                WindowsPowerShell

- If I remove the /quiet from the command then the usual window is open and the installation succeeds.

I hope that provides more context on the issue.

**Comment by jiasli** [comment]
It is not that the `PATH` is not configured correct. The installation didn't happen at all. 

I tested on Azure VM but couldn't repro. Could you double confirm if the PowerShell terminal is run as Administrator?

![image](https://user-images.githubusercontent.com/4003950/131985283-8c448e76-ecda-4cb2-8d4c-32f7ca6e6a6f.png)

**Comment by D3m1urg3** [comment]
I just tried it as administrator with the same result :/

**Comment by jiasli** [comment]
I can repro. Tested on Windows Server 2019 VM. CLI's path is indeed added, but `PATH` doesn't take it:

![image](https://user-images.githubusercontent.com/4003950/132009689-01ef12b1-21c0-4b95-9731-3734f80381e1.png)

CMD meanwhile works fine:

![image](https://user-images.githubusercontent.com/4003950/132010076-6a0ca488-9916-4828-83b0-c1b5ddcab458.png)

I will investigate on this.

**Comment by jiasli** [comment]
Actually in Windows Server, the PowerShell terminal is run as administrator by default. @D3m1urg3, what is the system you use in the VM?

The document says:

https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-windows?tabs=azure-powershell#powershell-command

> After the installation is complete, you will need to reopen PowerShell to use the Azure CLI.

Does it work if you reopen the PowerShell terminal?

---

On Windows Server, there seems to be a bug with PowerShell when opened with **Tasks -> Run as Administrator**:

- https://github.com/PowerShell/PowerShell/issues/16057

Opening PowerShell with **More -> Run as administrator** will take the environment variable change.

![image](https://user-images.githubusercontent.com/4003950/132166000-126d8549-4177-4f41-9a69-8c331931789f.png)

**Comment by D3m1urg3** [comment]
I´m using the vmware vm provided by microsoft: https://developer.microsoft.com/en-us/windows/downloads/virtual-machines/

In my case az cli is not added to path neither in ps or cmd.

**Comment by jiasli** [comment]
The MSI will indeed add CLI to `PATH`:

https://github.com/azure/azure-cli/blob/c803a548ef820bd840eb08fec46d638eae27672a/build_scripts/windows/Product.wxs#L96-L102

```xml
        <Environment Id="AzureCliAddedToPATH"
                     Name="PATH"
                     Value="[DynamicCliDir]wbin"
                     Permanent="no"
                     Part="first"
                     Action="set"
                     System="yes" />
```

Could you check the environment variable after installation in GUI? **Start -> Edit the system environment variables -> Environment Variables...**

**Comment by D3m1urg3** [comment]
Path before install:

![image](https://user-images.githubusercontent.com/10133797/132173914-3c80e8d6-f625-469c-b6d2-0112aed7410b.png)

Path after install using GUI:
![image](https://user-images.githubusercontent.com/10133797/132174265-36a20d4c-a5d8-4e95-b77a-7b703b7909d0.png)

![image](https://user-images.githubusercontent.com/10133797/132174479-a17608e2-fbbe-4930-b520-8869a3a74819.png)

**Comment by jiasli** [comment]
Apparently the environment variable `PATH` is modified correctly:

![](https://user-images.githubusercontent.com/10133797/132174479-a17608e2-fbbe-4930-b520-8869a3a74819.png)

I tested with the image https://developer.microsoft.com/en-us/windows/downloads/virtual-machines/ in Hyper-V. Here are my steps:

- Open PowerShell as administator
- Install Azure CLI with
    ```
    $ProgressPreference = 'SilentlyContinue' ; Invoke-WebRequest -Uri https://aka.ms/installazurecliwindows -OutFile .\AzureCLI.msi; Start-Process msiexec.exe -Wait -ArgumentList '/I AzureCLI.msi /quiet'; rm .\AzureCLI.msi
    ```
- Run `az --version` -> ❌
  ```
  > az --version
  az : The term 'az' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the
  spelling of the name, or if a path was included, verify that the path is correct and try again.
  ```
- Close PowerShell
- Reopen PowerShell with normal user permission
- Run `az --version`: 
   ![image](https://user-images.githubusercontent.com/4003950/132175503-66992fb3-b1e8-42dc-8f23-400b86356039.png)

Therefore, you only need to close all PowerShell terminals and restart one for the change on `PATH` to take effect.

**Comment by D3m1urg3** [comment]
Indeed it works now. I presume some changes in the scripts have been done as it was not working before.

**Comment by jiasli** [comment]
We didn't change anything recently. You only need to reopen the PowerShell terminal, nothing more.

**Comment by jiasli** [comment]
We didn't change anything recently. You only need to reopen the PowerShell terminal, nothing more. 

Anyway, let me update the doc to make those steps more visible: https://github.com/MicrosoftDocs/azure-docs-cli/pull/2738

**Comment by HarshitaSingh-MSFT** [comment]
Thanks a lot @jiasli for helping out here.
