### ISSUE TITLE
Repositories for Debian 11 aka bullseye is missing.

### ISSUE THREAD

**Issue by pkruesi** [MicrosoftDocs/azure-docs-cli#2728]
Repositories for Debian 11 aka bullseye is missing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7895b9a-9a6a-cd98-6947-0e4a26eda9a3
* Version Independent ID: a3f27295-3e2e-a36d-02c2-8897295fc443
* Content: [Install the Azure CLI on Linux](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=apt)
* Content Source: [docs-ref-conceptual/install-azure-cli-linux.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/install-azure-cli-linux.md)
* Service: **azure-cli**
* GitHub Login: @dbradish-microsoft
* Microsoft Alias: **dbradish**

**Comment by kobulloc-MSFT** [comment]
@pkruesi Thank you for the feedback!  We've assigned this to the document author for review.

**Comment by jiasli** [comment]
Please see https://github.com/Azure/azure-cli/pull/19370
