### ISSUE TITLE
As a Linux Mint user, We need to find the base ubuntu image

### ISSUE THREAD

**Issue by samuraifox1** [MicrosoftDocs/azure-docs-cli#2737]
[As a Linux Mint user, We need to find the base ubuntu image. using `cat /etc/upstream-release/lsb-release` ]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7895b9a-9a6a-cd98-6947-0e4a26eda9a3
* Version Independent ID: a3f27295-3e2e-a36d-02c2-8897295fc443
* Content: [Install the Azure CLI on Linux](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=apt)
* Content Source: [docs-ref-conceptual/install-azure-cli-linux.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/install-azure-cli-linux.md)
* Service: **azure-cli**
* GitHub Login: @dbradish-microsoft
* Microsoft Alias: **dbradish**

**Comment by BhargaviAnnadevara-MSFT** [comment]
@samuraifox1 Thanks for the feedback. We're investigating this and will get back to you shortly.

**Comment by samuraifox1** [comment]
Please close this ticket, as the documentation mentions this step already. Thanks !
