### ISSUE TITLE
Unable to create management group as of 2.27.1

### ISSUE THREAD

**Issue by mdtro** [MicrosoftDocs/azure-docs-cli#2746]
```
$ az account management-group create --name "test123" --parent "MyTestMG"
```

In version 2.27.0, creating a child management group. As of 2.27.1, the same command is failing with the error message:

> (AuthorizationFailed) The client '<spn id>' with object id '<spn id>' does not have authorization to perform action 'Microsoft.Management/register/action' over scope '/subscriptions/<subscription id' or the scope is invalid. If access was recently granted, please refresh your credentials.

To recreate this issue, you'll need the following:

- A management group, for example named "MyTestMG".
- A subscription (does not need to be a member of the above management group).
- A SPN with the following roles assigned:
  - _Reader_ at the subscription scope.
  - _Management Group Contributor_ at the "MyTestMG" management group scope.
- An AzureCLI (version >=2.27.1) shell logged in as your SPN.
- An Azure PowerShell instance logged in as your SPN.

Running the following will fail with an error message.
```
$ az account management-group create --name "test123" --parent "MyTestMG"

(AuthorizationFailed) The client '<spn id>' with object id '<spn id>' does not have authorization to perform action 'Microsoft.Management/register/action' over scope '/subscriptions/<subscription id' or the scope is invalid. If access was recently granted, please refresh your credentials.
```

In Azure PowerShell (I tested with version 6.4.0.34709), the equivalent command with the same SPN and assigned roles will complete successfully and create the child management group.

```
$parentGroup = Get-AzManagementGroup -GroupName MyTestMG
New-AzManagementGroup -GroupName 'test123' -ParentId $parentGroup.id
```

**Comment by mdtro** [comment]
Closing issue. I realize I'm on the docs repo. Sorry!

**Comment by AjayKumar-MSFT** [comment]
Apologies for the delay!  

No worries, Thanks for leveraging Azure docs feedback channel to raise this question and follow-up/closure. 

As a side note, this channel is reserved for ‘Azure docs’ feedback- for sharing doc feedback and suggesting content improvements.
