### ISSUE TITLE
"invalid jmespath_type value" with boolean query

### ISSUE THREAD

**Issue by mdelarosab** [MicrosoftDocs/azure-docs-cli#2777]
The following command returns an error with the message: "invalid jmespath_type value":
``` sh
   az account list --query "[?isDefault == \`false\`]"
```
It works with double ticks:
``` sh
   az account list --query "[?isDefault == ``false``]"
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e60c12ef-d293-5626-c7aa-c7e9241bf975
* Version Independent ID: 7acca1dd-b735-7e1f-afd9-2b5b6ea06b1c
* Content: [JMESPath query command results with Azure CLI](https://docs.microsoft.com/en-us/cli/azure/query-azure-cli)
* Content Source: [docs-ref-conceptual/query-azure-cli.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/query-azure-cli.md)
* Service: **azure-cli**
* GitHub Login: @dbradish-microsoft
* Microsoft Alias: **dbradish**

**Comment by MonikaReddy-MSFT** [comment]
@mdelarosab - Thanks again for bringing this to our attention. We have updated the Doc and it will be live once its merged.  We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
