### ISSUE TITLE
Scope defined for this API configured by default to "http://appname/user_impersonation"

### ISSUE THREAD

**Issue by vaacuavi-MSFT** [MicrosoftDocs/azure-docs-cli#2781]
Hello team,

I would like to understand why when we are creating a Service Principal using the command "az ad sp create-for-rbac -n svcpname --skip-assignment" the scope defined for the API is set by default to "http://appname/user_impersonation". 

![image](https://user-images.githubusercontent.com/92326587/136831418-bc123f54-b65a-4549-824b-3c1f8ef5d900.png)

Thanks

**Comment by MonikaReddy-MSFT** [comment]
@vaacuavi-MSFT Thank you for your query. 

Also please note that we scope issues on this repo to feedback related to the docs. If you are following through any documentation and came across this issue, it would be great if you could share the doc link. That would help us to guide you accordingly.
