### ISSUE TITLE
Add release cadence information

### ISSUE THREAD

**Issue by chasewilson** [MicrosoftDocs/azure-docs-cli#2792]
Would it be good to add release cadence information to this page at the [Current Version Section](https://docs.microsoft.com/en-us/cli/azure/what-is-azure-cli#current-version)? 

In my mind it will give the customer an expectatation of service. 

If this is added, the scope of update should be noted. E.g. this doesn't include extensions and modules not owned by the team. 

@dbradish-microsoft, @yonzhan do either of you see any issues with this addition? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d43769b4-5d99-c581-1f13-659bfabaf9ee
* Version Independent ID: a888b71c-7600-2cc6-bd4e-606107205c96
* Content: [What is the Azure CLI?](https://docs.microsoft.com/en-us/cli/azure/what-is-azure-cli)
* Content Source: [docs-ref-conceptual/what-is-azure-cli.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/what-is-azure-cli.md)
* Service: **azure-cli**
* GitHub Login: @dbradish-microsoft
* Microsoft Alias: **dbradish**

**Comment by SwathiDhanwada-MSFT** [comment]
@chasewilson Thanks for your feedback.

Assigning to content author @dbradish-microsoft   for review.

**Comment by dbradish-microsoft** [comment]
@chasewilson, Release information is being published in [24451](https://github.com/Azure/azure-cli/pull/24451), and once merged, portions will be brought into conceptual content.  This issue is being closed in accordance with MSFT SLA requirements for GitHub issues.
