### ISSUE TITLE
Homebrew warning when upgrading: "Warning: Calling bottle :unneeded is deprecated!"

### ISSUE THREAD

**Issue by nathanlindorff** [MicrosoftDocs/azure-docs-cli#2804]
Running az upgrade on macos now gives a homebrew warning:

```
Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the azure/functions tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/azure/homebrew-functions/Formula/azure-functions-core-tools-v3-preview.rb:10
```

Based on the timeframe of search results for `Warning: Calling bottle :unneeded is deprecated! `, It looks like there has been a change to homebrew that will require a change the the homebrew formula.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d09ed623-c83f-6bae-639e-a5f9a31fe3bb
* Version Independent ID: c5d0d722-aacd-47a3-3fcf-982c02c4d0e9
* Content: [Install the Azure CLI on macOS](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-macos)
* Content Source: [docs-ref-conceptual/install-azure-cli-macos.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/install-azure-cli-macos.md)
* Service: **azure-cli**
* GitHub Login: @dbradish-microsoft
* Microsoft Alias: **dbradish**

**Comment by jiasli** [comment]
This doesn't seem to be Azure CLI issue, judging by the formula `azure-functions-core-tools-v3-preview.rb`. Could you share the steps you followed?

**Comment by nathanlindorff** [comment]
I honestly can't remember, I think I just ran az upgrade.

**Comment by dbradish-microsoft** [comment]
@nathanlindorff , Thanks for providing feedback that helps improve our documentation.  This feedback has been passed to the appropriate team at Microsoft and as there has been no continued discussion since January, 2022, this GitHub issue is being closed.
