### ISSUE TITLE
Could you add release notes for the Azure CLI extensions (and not only for Azure CLI itself)?

### ISSUE THREAD

**Issue by gro1m** [MicrosoftDocs/azure-docs-cli#2818]
Could you add release notes for the Azure CLI extensions (and not only for Azure CLI itself)? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0e8d9ef-f25b-bb46-7f1a-bd3588be3343
* Version Independent ID: cd392600-a90d-0145-5ea6-6b01ab8f4ab9
* Content: [Release notes & updates – Azure CLI](https://docs.microsoft.com/en-us/cli/azure/release-notes-azure-cli?toc=%2Fcli%2Fazure%2Ftoc.json&bc=%2Fcli%2Fazure%2Fbreadcrumb%2Ftoc.json&view=azure-cli-latest)
* Content Source: [docs-ref-conceptual/release-notes-azure-cli.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/release-notes-azure-cli.md)
* Service: **azure-cli**
* GitHub Login: @dbradish-microsoft
* Microsoft Alias: **dbradish**

**Comment by BhargaviAnnadevara-MSFT** [comment]
@gro1m Thanks for the feedback. We're investigating this and will get back to you shortly.

**Comment by dbradish-microsoft** [comment]
@gro1m, Release notes for Azure CLI extensions are available from the [List of available Azure CLI extensions](https://docs.microsoft.com/en-us/cli/azure/azure-cli-extensions-list?view=azure-cli-latest) page.  I appreciate your suggestion to have the release notes combined, and will pass your suggestion to the engineering team.

**Comment by gro1m** [comment]
Thanks @dbradish-microsoft. Not all links seem to work, e.g. subscription and ml: Should I open a separate feedback for this?

**Comment by dbradish-microsoft** [comment]
Hello, @gro1m, I have opened an issue in the Azure/azure-cli-extensions repo.  It is issue #[4090](https://github.com/Azure/azure-cli-extensions/issues/4090).  Thank you for bringing this to our attention.
