### ISSUE TITLE
yamlc output format not documented

### ISSUE THREAD

**Issue by adriancuadrado** [MicrosoftDocs/azure-docs-cli#2820]
Running `az webapp list --help` shows this help:

```
Command
    az webapp list : List web apps.

Arguments
    --resource-group -g             : Name of resource group. You can configure the default group
                                      using `az configure --defaults group=<name>`.

Global Arguments
    --debug                         : Increase logging verbosity to show all debug logs.
    --help -h                       : Show this help message and exit.
    --only-show-errors              : Only show errors, suppressing warnings.
    --output -o                     : Output format.  Allowed values: json, jsonc, none, table, tsv,
                                      yaml, yamlc.  Default: json.
    --query                         : JMESPath query string. See http://jmespath.org/ for more
                                      information and examples.
    --query-examples [Experimental] : Recommend JMESPath string for you. You can copy one
                                      of the query and paste it after --query parameter within
                                      double quotation marks to see the results. You can add one or
                                      more positional keywords so that we can give suggestions based
                                      on these key words.
        This parameter is experimental and under development. Reference and support levels:
        https://aka.ms/CLI_refstatus
    --subscription                  : Name or ID of subscription. You can configure the default
                                      subscription using `az account set -s NAME_OR_ID`.
    --verbose                       : Increase logging verbosity. Use --debug for full debug logs.

Examples
    List default host name and state for all web apps.
        az webapp list --query ".{hostName: defaultHostName, state: state}"


To search AI knowledge base for examples, use: az find "az webapp list"
```

As you can see, one of the valid output formats is yamlc, but I can't find any information about that format anywhere and after running the command with that option I can't understand the difference between it and normal yaml.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 48273ba7-da5a-95f0-7ffc-8c6d5282313d
* Version Independent ID: 83d348f9-fd1f-1041-0304-d8634e5526d4
* Content: [Output formats - Azure CLI](https://docs.microsoft.com/en-us/cli/azure/format-output-azure-cli)
* Content Source: [docs-ref-conceptual/format-output-azure-cli.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/format-output-azure-cli.md)
* Service: **azure-cli**
* GitHub Login: @dbradish-microsoft
* Microsoft Alias: **dbradish**

**Comment by BhargaviAnnadevara-MSFT** [comment]
@adriancuadrado Thank you very much for bringing this to our attention. Just like how `json` has a colorized counterpart `jsonc`, `yamlc` is used to produce **colored YAML** formatted output. Note the differences in color in the snip below:

![image](https://user-images.githubusercontent.com/44050820/141268656-619155d0-f812-4683-b15a-881cdbc24f4a.png)

I've submitted a PR to add `yamlc` to the list of output formats. The changes should reflect post the merge.

**Comment by BhargaviAnnadevara-MSFT** [comment]
@dbradish-microsoft FYI.

**Comment by BhargaviAnnadevara-MSFT** [comment]
@adriancuadrado Thanks again for the feedback. The change is merged internally and will go-live in the public docs shortly.
