### ISSUE TITLE
Is the search space for JMESPath queries via `--query` implicitly limited, or does it search across the entire collection of items?

### ISSUE THREAD

**Issue by tknerr** [MicrosoftDocs/azure-docs-cli#2825]
Hi @dbradish-microsoft ,

great documentation! 

I was looking for one specific detail, which is not entirely clear to me. The docs say:

> Queries are executed on the JSON output before any display formatting.

Does that mean that the query is executed on client side, after **all** data has been fetched?

I'm asking, because my intuitive expectation was that the JMESPath queries were evaluated on server side, and then would only return the filtered / queried json results to the az cli. 

However, I'm seeing that `--top` seems to narrow down the search space over which the query is executed, i.e. the `--top` seems to be applied **before** the query is run. This is surprising, because `--top` seems to have a default at around 1000, which essentially means "your query is run over the last 1000 items only, but not over the entire search space", so once the overall amount of items to be searched surpasses 1000, you may no longer find them with that very same query. I was hitting this, and managed to temporarily work around this by increasing the limit to 5000 -- but this is the maximum, so i can't query more than the last 5000 items.

In my case this was a query was for azure devops pipeline runs:
```
$ az pipelines runs list --only-show-errors --organization https://dev.azure.com/MyOrg --project MyProject --query '[? definition.name==`my-pipeline` && sourceBranch==`refs/tags/0.1.0` && result==`succeeded` ].id'
```

At some point in time, it no longer returned a result, even though the pipeline run still existed. I could make it work again by adding `--top 5000`, but this won't last forever either (and 5000 is the maximum allowed in this case):
```
$ az pipelines runs list --only-show-errors --organization https://dev.azure.com/MyOrg --project MyProject --query '[? definition.name==`my-pipeline` && sourceBranch==`refs/tags/0.1.0` && result==`succeeded` ].id' --top 5000
```

Is it expected that the search space for JMESPath queries is narrowed down to a subset of the available items, or am I hitting a bug here?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e60c12ef-d293-5626-c7aa-c7e9241bf975
* Version Independent ID: 7acca1dd-b735-7e1f-afd9-2b5b6ea06b1c
* Content: [JMESPath query command results with Azure CLI](https://docs.microsoft.com/en-us/cli/azure/query-azure-cli)
* Content Source: [docs-ref-conceptual/query-azure-cli.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/query-azure-cli.md)
* Service: **azure-cli**
* GitHub Login: @dbradish-microsoft
* Microsoft Alias: **dbradish**

**Comment by tknerr** [comment]
This seems to have been reported in https://developercommunity.visualstudio.com/t/az-pipelines-build-list-does-not-properl/1513703 already -- cross-linking both for reference here

**Comment by tknerr** [comment]
Hi @dbradish-microsoft , @BhargaviAnnadevara-MSFT , any update on this so far?

**Comment by dbradish-microsoft** [comment]
@jiasli , can you please review and comment?

**Comment by jiasli** [comment]
> Does that mean that the query is executed on client side, after all data has been fetched?

Yes. Global argument `--query` which uses JMESPath is totally executed on the client-side: 

https://github.com/microsoft/knack/blob/cd590312b9b4ea1402d7a0a76814f6ca4da7fab8/knack/query.py#L43-L47

```py
            def filter_output(cli_ctx, **kwargs):
                from jmespath import Options
                kwargs['event_data']['result'] = query_expression.search(
                    kwargs['event_data']['result'], Options(collections.OrderedDict))
                cli_ctx.unregister_event(EVENT_INVOKER_FILTER_RESULT, filter_output)
```

On the other hand, `--top` is an implementation of `azure-devops` extension. You may report your problem at https://github.com/Azure/azure-devops-cli-extension.

**Comment by tknerr** [comment]
Thanks @jiasli for clarification!
