### ISSUE TITLE
Add Clarity to msal-based-azure-cli

### ISSUE THREAD

**Issue by chasewilson** [MicrosoftDocs/azure-docs-cli#2831]
- The current doc isn't clear that the migration is tool based and the customer doesn't need to migrate anything. 
- Alternatives currently look like they are required when they are only if you are working with other versions
- Clarity on no backwards compatibility. Has been an issue for pipeline users. 
- Updates for markdown formatting requirements.

**Comment by BhargaviAnnadevara-MSFT** [comment]
@chasewilson Thank you for the updates! I see https://github.com/MicrosoftDocs/azure-docs-cli/pull/2832 is awaiting review.

**Comment by BhargaviAnnadevara-MSFT** [comment]
@chasewilson We will now proceed to close this thread, but if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.
