### ISSUE TITLE
Homebrew is not necessarily a good way to install on Mac

### ISSUE THREAD

**Issue by AronT-TLV** [MicrosoftDocs/azure-docs-cli#2835]
Today I ran into an issue with `az aks nodepool add` See [this issue](https://github.com/Azure/azure-cli/issues/20461). Apparently the problem is `brew` automatically upgraded to Python 3.10 because of some other dependancy. This is not the first time I have run into CLI issues on the Mac because of Python incompatibilities. Hence I suggest the documentation note the option of using `conda` with a pinned version of Python and switch environments before running `az`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d09ed623-c83f-6bae-639e-a5f9a31fe3bb
* Version Independent ID: c5d0d722-aacd-47a3-3fcf-982c02c4d0e9
* Content: [Install the Azure CLI on macOS](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-macos)
* Content Source: [docs-ref-conceptual/install-azure-cli-macos.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/install-azure-cli-macos.md)
* Service: **azure-cli**
* GitHub Login: @dbradish-microsoft
* Microsoft Alias: **dbradish**

**Comment by Grace-MacJones-MSFT** [comment]
thanks for bringing this to our attention. Your feedback has been shared with the content owner for further review.

**Comment by jiasli** [comment]
> This is not the first time I have run into CLI issues on the Mac because of Python incompatibilities.

I have to admit Homebrew is indeed not very user-friendly to developers 🙁 (https://github.com/Homebrew/discussions/discussions/155).

> Hence I suggest the documentation note the option of using `conda` with a pinned version of Python and switch environments before running `az`

We don't officially support `conda` either, but we do support Python's built-in module `venv`. You are welcome to create a `venv` and install Azure CLI with `pip`.

See https://github.com/Azure/azure-cli/issues/20476.
