### ISSUE TITLE
Set configuration file name as the environment var value

### ISSUE THREAD

**Issue by wujiangxingzhe** [MicrosoftDocs/azure-docs-cli#2845]
Whether we set configuration file name as the environment var value and then az pares the configuration file by the environment var
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb42002e-9aa3-233d-9832-353235b7cd0f
* Version Independent ID: e8b320b1-5805-67ba-46b2-48111861facc
* Content: [Azure CLI configuration options](https://docs.microsoft.com/en-us/cli/azure/azure-cli-configuration#feedback)
* Content Source: [docs-ref-conceptual/azure-cli-configuration.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/docs-ref-conceptual/azure-cli-configuration.md)
* Service: **azure-cli**
* GitHub Login: @dbradish-microsoft
* Microsoft Alias: **dbradish**

**Comment by BhargaviAnnadevara-MSFT** [comment]
@wujiangxingzhe Thanks for reaching out. I'm not quite sure if I understand your requirement completely. Could you please elaborate the feedback you wish to provide?

**Comment by BhargaviAnnadevara-MSFT** [comment]
@wujiangxingzhe Please elaborate your feedback so we can help you better.

**Comment by BhargaviAnnadevara-MSFT** [comment]
@wujiangxingzhe We will now proceed to close this thread, but if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.
