### ISSUE TITLE
Releases notes missing for version 2.31.0

### ISSUE THREAD

**Issue by BzSpi** [MicrosoftDocs/azure-docs-cli#2862]
The release notes for version 2.31.0 is missing on docs.microsoft.com and in the docs-ref-conceptual/release-notes-azure-cli.md file.

**Comment by AjayKumar-MSFT** [comment]
@BzSpi, Thanks for leveraging Azure docs to share this feedback. 

Just to confirm, I believe you're referring to this doc: https://docs.microsoft.com/cli/azure/release-notes-azure-cli 
and  [Azure CLI release notes](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/docs-ref-conceptual/release-notes-azure-cli.md)?

**Comment by BzSpi** [comment]
@AjayKumar-MSFT yes, that's the two documents I'm talking about.

**Comment by AjayKumar-MSFT** [comment]
BzSpi, Thanks for the confirmation. We're checking on this and will get back to you shortly.

**Comment by AjayKumar-MSFT** [comment]
@dbradish-microsoft, Requesting your comments on this. Thank you.

**Comment by dbradish-microsoft** [comment]
@AjayKumar-MSFT , please reach out to @jiasli as this is an engineering issue.

**Comment by jiasli** [comment]
Issue has been fixed.
