### ISSUE TITLE
"The JSON may have been parsed by the shell" unable to use JSON file

### ISSUE THREAD

**Issue by dejan-shuki** [MicrosoftDocs/azure-docs-cli#2869]
[Enter feedback here]
I was sent to this page after I tried to create Azure Synapse Linked Service using .json file from Azure CLI:
az synapse linked-service create --name LS_dakeyvault --file "C:\Project\SynGitTest0\linkedService\LS_dakeyvault.json" --workspace-name edap-d-syn

Unfortunately, I was not able to figure out how should I deal with quotes.
Should I change the reference to the file? I tried putting single quotes.
Should I change content of .json file? That does not make sense to me.

I tried using different shells (Windows, powershell, bash). I am getting same result.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e51daa3-30c5-f449-36a1-9f33c70ca2fc
* Version Independent ID: a21e188b-4ff4-0aca-531b-d4b179665be1
* Content: [Use Azure CLI effectively](https://docs.microsoft.com/en-us/cli/azure/use-cli-effectively#quoting-issues)
* Content Source: [docs-ref-conceptual/use-cli-effectively.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/docs-ref-conceptual/use-cli-effectively.md)
* Service: **azure-cli**
* GitHub Login: @dbradish-microsoft
* Microsoft Alias: **dbradish**

**Comment by MonikaReddy-MSFT** [comment]
@dejan-shuki - Thanks for bringing this to our attention. We will investigate it further and update you shortly.

**Comment by dbradish-microsoft** [comment]
CCing @wonner for input

**Comment by wonner** [comment]
hi @dejan-shuki  , could you please add "@" at the front of the path?
for example: --file @"C:\Project\SynGitTest0\linkedService\LS_dakeyvault.json"
Here is the related doc: https://github.com/Azure/azure-cli/blob/dev/doc/quoting-issues-with-powershell.md#best-practice-use-file-input-for-json

**Comment by MonikaReddy-MSFT** [comment]
@wonner  - Thank you for providing your insights.
@dejan-shuki  - I hope @wonner has answered your question. 
At this moment, Since there is no doc update required, We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
