### ISSUE TITLE
Required permission changed to the newly created microsoft.asc.gpg file

### ISSUE THREAD

**Issue by njaiswal27** [MicrosoftDocs/azure-docs-cli#2884]
Please include steps to change the permission of microsoft.asc.gpg file else apt-get fails with public key error

The following signatures couldn't be verified because the public key is not available: NO_PUBKEY EB3E94ADBE1229CF
Reading package lists...

 chmod 666 /etc/apt/trusted.gpg.d/microsoft.asc.gpg

Also copy pasting steps from the documents ends up with error message

The key(s) in the keyring /etc/apt/trusted.gpg.d/microsoft.gpg are ignored as the file is not readable by user '_apt' executing apt-key.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7895b9a-9a6a-cd98-6947-0e4a26eda9a3
* Version Independent ID: a3f27295-3e2e-a36d-02c2-8897295fc443
* Content: [Install the Azure CLI on Linux](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=apt&view=azure-cli-latest)
* Content Source: [docs-ref-conceptual/install-azure-cli-linux.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/docs-ref-conceptual/install-azure-cli-linux.md)
* Service: **azure-cli**
* GitHub Login: @dbradish-microsoft
* Microsoft Alias: **dbradish**

**Comment by JamesTran-MSFT** [comment]
@njaiswal27 
Thanks for your feedback! I've assigned this issue to the author who will investigate and update as appropriate.

**Comment by jiasli** [comment]
@njaiswal27, we are not able to repro by following the current doc.

Could you share the steps you followed and the full error message? Thanks.

**Comment by njaiswal27** [comment]
Using Option #2
--------------------
sudo apt-get update
Hit:1 http:// repo-domainname.com /archive.ubuntu.com/ubuntu bionic InRelease
Hit:2  repo-domainname.com/archive.ubuntu.com/ubuntu bionic-updates InRelease
Hit:3 http:// repo-domainname.com /archive.ubuntu.com/ubuntu bionic-backports InRelease
Hit:4 http:// repo-domainname.com/archive.ubuntu.com/ubuntu bionic-security InRelease
Reading package lists... Done
myuser@server1:~/tools$ sudo apt-get install ca-certificates curl apt-transport-https lsb-release gnupg
Reading package lists... Done
Building dependency tree
Reading state information... Done
lsb-release is already the newest version (9.20170808ubuntu1).
ca-certificates is already the newest version (20210119~18.04.2).
curl is already the newest version (7.58.0-2ubuntu3.16).
gnupg is already the newest version (2.2.4-1ubuntu1.4).
apt-transport-https is already the newest version (1.6.14).
0 upgraded, 0 newly installed, 0 to remove and 140 not upgraded.


myuser@server1:~/tools$ curl -sL https://packages.microsoft.com/keys/microsoft.asc |
> gpg --dearmor |
> sudo tee /etc/apt/trusted.gpg.d/microsoft.gpg > /dev/null

myuser@server1:~/tools$ AZ_REPO=$(lsb_release -cs)
myuser@server1:~/tools$ echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" |
> sudo tee /etc/apt/sources.list.d/azure-cli.list
deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ bionic main

myuser@server1:~/tools$ sudo apt-get update
Hit:1 http://repo-domainname.com/archive.ubuntu.com/ubuntu bionic InRelease
Hit:2 http:// repo-domainname.com /archive.ubuntu.com/ubuntu bionic-updates InRelease
Get:3 https://packages.microsoft.com/repos/azure-cli bionic InRelease [3,964 B]
Hit:4 http:// repo-domainname.com /archive.ubuntu.com/ubuntu bionic-backports InRelease
Hit:5 http:// repo-domainname.com /archive.ubuntu.com/ubuntu bionic-security InRelease
Err:3 https://packages.microsoft.com/repos/azure-cli bionic InRelease
The following signatures couldn't be verified because the public key is not available: NO_PUBKEY EB3E94ADBE1229CF
Reading package lists... Done
W: http:// repo-domainname.com/archive.ubuntu.com/ubuntu/dists/bionic/InRelease: The key(s) in the keyring /etc/apt/trusted.gpg.d/microsoft.gpg are ignored as the file is not readable by user '_apt' executing apt-key.
W: http:// repo-domainname.com/ubuntu/dists/bionic-updates/InRelease: The key(s) in the keyring /etc/apt/trusted.gpg.d/microsoft.gpg are ignored as the file is not readable by user '_apt' executing apt-key.
W: https://packages.microsoft.com/repos/azure-cli/dists/bionic/InRelease: The key(s) in the keyring /etc/apt/trusted.gpg.d/microsoft.gpg are ignored as the file is not readable by user '_apt' executing apt-key.
W: GPG error: https://packages.microsoft.com/repos/azure-cli bionic InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY EB3E94ADBE1229CF
E: The repository 'https://packages.microsoft.com/repos/azure-cli bionic InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: http:// repo-domainname.com /archive.ubuntu.com/ubuntu/dists/bionic-backports/InRelease: The key(s) in the keyring /etc/apt/trusted.gpg.d/microsoft.gpg are ignored as the file is not readable by user '_apt' executing apt-key.
W: http:// repo-domainname.com/archive.ubuntu.com/ubuntu/dists/bionic-security/InRelease: The key(s) in the keyring /etc/apt/trusted.gpg.d/microsoft.gpg are ignored as the file is not readable by user '_apt' executing apt-key.
myuser@server1:~/tools$ sudo apt-get install azure-cli
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package azure-cli

**Comment by jiasli** [comment]
We have seen this error before:

```
The key(s) in the keyring /etc/apt/trusted.gpg.d/microsoft.gpg are ignored as the file is not readable by user '_apt' executing apt-key.
```

Could you check https://github.com/Azure/azure-cli/issues/18199?

**Comment by njaiswal27** [comment]
Surprisingly using automated script, I saw the same issue, so ideally the script should apply permission change before executing other steps as well as option2 step by step should also include permission change in the document as a side note.

**Comment by jiasli** [comment]
On a default Ubuntu installation, our doc works perfectly. 

If `uname` is changed, it changes the default file permission for new files, so it corrupts the `apt-key` command. This is not related to Azure CLI, so should not be covered by us. Thanks for understanding.
