### ISSUE TITLE
dont recommend

### ISSUE THREAD

**Issue by maliaga-pantoja** [MicrosoftDocs/azure-docs-cli#2890]
[Enter feedback here]
web page dont give any response at question: "how to use azure cli in docker" . I mean .. what env vars are required, best practices .. any options, but give nothing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d884a3fe-07cf-e518-085d-602425fe2480
* Version Independent ID: 1636994b-e193-74e2-9936-a07e43913326
* Content: [How to run Azure CLI in a Docker Container](https://docs.microsoft.com/en-us/cli/azure/run-azure-cli-docker)
* Content Source: [docs-ref-conceptual/run-azure-cli-docker.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/docs-ref-conceptual/run-azure-cli-docker.md)
* Service: **azure-cli**
* GitHub Login: @dbradish-microsoft
* Microsoft Alias: **dbradish**

**Comment by GitaraniSharma-MSFT** [comment]
@maliaga-pantoja , Thanks for your feedback.

We have assigned this to the content owner/author @dbradish-microsoft for review.

**Comment by jiasli** [comment]
> I mean .. what env vars are required, best practices .. any options, but give nothing.

I think this belongs more to the topic of docker usage. You may check docker manual https://docs.docker.com/desktop/ instead.

**Comment by chasewilson** [comment]
@maliaga-pantoja, is there something specific to Azure CLI, not docker that should be included in the doc?

**Comment by adriancuadrado** [comment]
Maybe what volumes should be mapped to have the Azure CLI configuration or login information persisted, for instance.

**Comment by dbradish-microsoft** [comment]
[adriancuadrado](https://github.com/adriancuadrado), Thanks for providing feedback that helps improve our documentation.  This feedback has been passed to the appropriate team at Microsoft and as there has been no continued discussion since March, 2022, this GitHub issue is being closed.
