### ISSUE TITLE
Azure CLI is using AAD Graph, which is being deprecated soon

### ISSUE THREAD

**Issue by RayGHeld** [MicrosoftDocs/azure-docs-cli#2903]
This library is using the AAD Graph API ( graph.windows.net ) and that service is scheduled for deprecation in June of this year.  Consequently, users cannot add permissions for the AAD Graph api anymore.  Is there any plan to update the CLI to use the Microsoft Graph API instead?  https://docs.microsoft.com/en-us/graph/migrate-azure-ad-graph-faq#:~:text=For%20this%20reason%2C%20Azure%20AD%20Graph%20has%20been,to%20Microsoft%20Graph%20to%20avoid%20loss%20of%20functionality.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed09ee6c-d023-f470-a976-03536112d556
* Version Independent ID: e14c213e-70d4-f6d7-c19b-7fab474b102b
* Content: [Differences between Azure CLI products](https://docs.microsoft.com/en-us/cli/azure/cli-versioning-identifiers)
* Content Source: [docs-ref-conceptual/cli-versioning-identifiers.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/docs-ref-conceptual/cli-versioning-identifiers.md)
* Service: **azure-cli**
* GitHub Login: @dbradish-microsoft
* Microsoft Alias: **dbradish**

**Comment by MonikaReddy-MSFT** [comment]
Thanks for bringing this to our attention. We will investigate it further and update you shortly.

**Comment by chasewilson** [comment]
Hi @RayGHeld, 

Great question and thanks for reaching out. The CLI team is currently working on updating the CLI to use MS Graph. You can see the full timeline in [this blog post](https://techcommunity.microsoft.com/t5/azure-tools-blog/azure-ad-to-microsoft-graph-migration-for-azure-command-line/ba-p/2836666), but the expected timeline is to have a MS Graph using CLI by the end of March. 

Feel free to respond here if you have any more questions but I believe we can close this issue. :)

**Comment by MonikaReddy-MSFT** [comment]
@chasewilson  - Thank you for providing your insights.
@RayGHeld  - I hope @chasewilson has answered your question. 
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
