### ISSUE TITLE
Images are not crosscompiled

### ISSUE THREAD

**Issue by RiRa12621** [MicrosoftDocs/azure-docs-cli#2906]
The referenced image is erroring on Apple Silion

```
$ uname -a
Darwin 21.2.0 Darwin Kernel Version 21.2.0: Sun Nov 28 20:29:10 PST 2021; root:xnu-8019.61.5~1/RELEASE_ARM64_T8101 arm64

$ docker version
Client:
 Cloud integration: v1.0.22
 Version:           20.10.11
 API version:       1.41
 Go version:        go1.16.10
 Git commit:        dea9396
 Built:             Thu Nov 18 00:36:09 2021
 OS/Arch:           darwin/arm64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.11
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.9
  Git commit:       847da18
  Built:            Thu Nov 18 00:34:44 2021
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.4.12
  GitCommit:        7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

```

```
$ docker run --rm -it mcr.microsoft.com/azure-cli
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requ

```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d884a3fe-07cf-e518-085d-602425fe2480
* Version Independent ID: 1636994b-e193-74e2-9936-a07e43913326
* Content: [How to run Azure CLI in a Docker Container](https://docs.microsoft.com/en-us/cli/azure/run-azure-cli-docker?view=azure-cli-latest)
* Content Source: [docs-ref-conceptual/run-azure-cli-docker.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/docs-ref-conceptual/run-azure-cli-docker.md)
* Service: **azure-cli**
* GitHub Login: @dbradish-microsoft
* Microsoft Alias: **dbradish**

**Comment by MonikaReddy-MSFT** [comment]
Thanks for bringing this to our attention. We will investigate it further and update you shortly.

**Comment by chasewilson** [comment]
Hey @RiRa12621 , thanks for reaching out about this. Do you mind clarifying if you believe there is an issue with Docker, CLI, or the specified document?

**Comment by RiRa12621** [comment]
I think the image just wasn't built for all platforms/architectures and since it's an official image, you folks would need to rebuild it.

**Comment by chasewilson** [comment]
Hey @RiRa12621, 

Thanks for your patience here. I've tested the doc myself in an M1 apple silicon env. It appears everything works aside from the warning. I don't think a change to the doc is needed but want to verify before we move this issue. 

@yonzhan, the warning does exist when running the docs suggested command on an M1 mac. Hoever, the docker image appears to run the cli fine. Does there need to be a change to the doc or do we need to create an issue in the azure cli repo?

**Comment by RiRa12621** [comment]
Yeah it does work, just thought a small note about the behavior on apple silicon might be nice.

**Comment by chasewilson** [comment]
> Yeah it does work, just thought a small note about the behavior on apple silicon might be nice.

A good suggestion. I think if this behavior is going to be expected for M1 macs, we'll add a note, but if not then we will work towards resolving it on the technical side and refer to this, and the cli issue if it comes up here again. 

Does that seem like a good way forward from your perspective?

**Comment by RiRa12621** [comment]
Sgtm

**Comment by jiasli** [comment]
The warning indicates the docker image is built for `linux/amd64`, but the host machine is `linux/arm64/v8`. This will lead to low performance as docker needs to translate the instruction set.

However, we can keep track of this issue in Azure CLI repo for `linux/arm64/v8` docker image release: #20989.

**Comment by MonikaReddy-MSFT** [comment]
@jiasli - Thanks for raising the PR and providing your insights.
@RiRa12621 - Thanks again for bringing this to our attention. We have updated the Doc and it will be live once its merged.  We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
