### ISSUE TITLE
Array flattenning needs double quotes actually 

### ISSUE THREAD

**Issue by mishal153** [MicrosoftDocs/azure-docs-cli#2912]
Hi,
Despite what I understood from the document, I had to use double quotes to make array query work. 

`az account list-locations --query "[].{n:name , dispName:displayName}"
`

single quotes causes error. I found my answer [here](https://stackoverflow.com/questions/68762521/azure-ad-cli-how-to-query-multiple-parameter-from-output). 

--
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e60c12ef-d293-5626-c7aa-c7e9241bf975
* Version Independent ID: 7acca1dd-b735-7e1f-afd9-2b5b6ea06b1c
* Content: [JMESPath query command results with Azure CLI](https://docs.microsoft.com/en-us/cli/azure/query-azure-cli)
* Content Source: [docs-ref-conceptual/query-azure-cli.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/docs-ref-conceptual/query-azure-cli.md)
* Service: **azure-cli**
* GitHub Login: @dbradish-microsoft
* Microsoft Alias: **dbradish**

**Comment by MonikaReddy-MSFT** [comment]
@mishal153 - Thanks for bringing this to our attention. Can you please share with us in which particular command in the above document you referenced are you having issues with?

**Comment by MonikaReddy-MSFT** [comment]
@mishal153 - Thanks for bringing this to our attention. Can you please share with us in which particular command in the above document you referenced are you having issues with?

**Comment by dbradish-microsoft** [comment]
Hello, @mishal153, I was able to replicate your results by running the following two commands:
    `az account list-locations --query "[].{n:name , dispName:displayName}"`
   `az account list-locations --query [].{n:name , dispName:displayName}`
    
![image](https://user-images.githubusercontent.com/58762114/149372139-7556c374-6c08-4e0e-91b1-77afe48ad61e.png)

Thanks for bringing this to our attention.  I'll speak with the engineering team to understand the cause and we'll update [Get properties in an array](https://docs.microsoft.com/en-us/cli/azure/query-azure-cli#get-properties-in-an-array).

**Comment by chasewilson** [comment]
Just an addition to this, the query works with single and double in a PowerShell terminal in Windows but not CMD. It also works in bash and powershell on mac but not zsh. I'm assuming it will work with Bash and Pwsh on linux since it does in both of those on Mac.

All of that being said, my suggestion is that since it works with double quotes regardless the shell, we should have that reflect in the docs and make that the standard for similar examples unless there is an environement specific reason for using single quotes.

**Comment by mishal153** [comment]
> Just an addition to this, the query works with single and double in a PowerShell terminal in Windows but not CMD. It also works in bash and powershell on mac but not zsh. I'm assuming it will work with Bash and Pwsh on linux since it does in both of those on Mac.
> 
> All of that being said, my suggestion is that since it works with double quotes regardless the shell, we should have that reflect in the docs and make that the standard for similar examples unless there is an environement specific reason for using single quotes.

Okay. Yes an update to the 'Note' on the page could help I guess. Something that indicates that double quote might work instead of single quote based on the environment in use. 

Thanks !
