### ISSUE TITLE
More detailed documentation for `--query`

### ISSUE THREAD

**Issue by jiasli** [MicrosoftDocs/azure-docs-cli#2914]
The grammar of JMESPATH is not that easy to learn. We need to provide more detailed documentation and examples for `--query`.

**Comment by shashishailaj** [comment]
-- Adding Github Metadata . 

The grammar of JMESPATH is not that easy to learn. We need to provide more detailed documentation and examples for --query.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e60c12ef-d293-5626-c7aa-c7e9241bf975
* Version Independent ID: 7acca1dd-b735-7e1f-afd9-2b5b6ea06b1c
* Content: [JMESPath query command results with Azure CLI](https://docs.microsoft.com/en-us/cli/azure/query-azure-cli)
* Content Source: [docs-ref-conceptual/query-azure-cli.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/docs-ref-conceptual/query-azure-cli.md)
* Service: **azure-cli**
* GitHub Login: @dbradish-microsoft
* Microsoft Alias: **dbradish**

**Comment by shashishailaj** [comment]
@jiasli Thank you for bringing this to notice. We have engaged the content team to see how best the documentation can be improved. In case you are referring to any other document than https://docs.microsoft.com/en-us/cli/azure/query-azure-cli please feel free to share the information.

**Comment by dbradish-microsoft** [comment]
@shashishailaj / @jiasli , There is also JMESPath query information in [How to use Azure CLI effectively](https://docs.microsoft.com/en-us/cli/azure/use-cli-effectively#pass-values-to-another-command), [Table output format](https://docs.microsoft.com/en-us/cli/azure/format-output-azure-cli#table-output-format), and a brief mention in [Using variables](https://docs.microsoft.com/en-us/cli/azure/azure-cli-variables).

**Comment by carlosporter** [comment]
I agree with the initial statement,

Personally, I have two issues with this document:

1. There are no examples to explain the use of the Boolean operators.
2. There is no mention about how to search or filter JSON attributes with numerical values.

For example I needed to build a query that would filter the virtual machine SKU's by size of their resource disk and the number of processors.

It took me a good amount of "searching" to find out the correct JMESPath query, like the one below:

```
optech@vm1001caimd1001:~/today_1400$ az vm list-sizes --location eastus2 \
>   --query "[?resourceDiskSizeInMb<=\`512\` && numberOfCores<=\`2\`]" -o table
Name              NumberOfCores    OsDiskSizeInMb    ResourceDiskSizeInMb    MemoryInMb    MaxDataDiskCount
----------------  ---------------  ----------------  ----------------------  ------------  ------------------
Standard_E2_v4    2                1047552           0                       16384         4
Standard_E2s_v4   2                1047552           0                       16384         4
Standard_D2_v4    2                1047552           0                       8192          4
Standard_D2s_v4   2                1047552           0                       8192          4
Standard_D2s_v5   2                1047552           0                       8192          4
Standard_D2_v5    2                1047552           0                       8192          4
Standard_E2s_v5   2                1047552           0                       16384         4
Standard_E2_v5    2                1047552           0                       16384         4
Standard_DC1s_v3  1                1047552           0                       8192          4
Standard_DC2s_v3  2                1047552           0                       16384         8
optech@vm1001caimd1001:~/today_1400$
```

**Comment by dbradish-microsoft** [comment]
@shashishailaj / @jiasli / @carlosporter , [JMESPath query command results with Azure CLI](https://docs.microsoft.com/en-us/cli/azure/query-azure-cli) is currently being improved by a technical writer at Microsoft.  I anticipate seeing the improvements published in March.  The feedback here has been very helpful.

**Comment by dbradish-microsoft** [comment]
@jiasli, this is currently [PR draft 2986](https://github.com/MicrosoftDocs/azure-docs-cli/pull/2986)

**Comment by dbradish-microsoft** [comment]
@jiasli , @shashishailaj , @carlosporter , The [How to query Azure CLI command output using a JMESPath query](https://docs.microsoft.com/en-us/cli/azure/query-azure-cli?view=azure-cli-latest&tabs=concepts%2Cpowershell) article was updated significantly in April, 2022.  The update includes examples for Bash, PowerShell and CMD as shown here --> 

![image](https://user-images.githubusercontent.com/58762114/174087776-09683cd4-8f11-4b2e-973b-4e5b7ef404e6.png)

If you would like additional updates to this article, please open a new Issue or PR.  

Kindly,

@dbradish-microsoft

**Comment by carlosporter** [comment]
Thanks @dbradish-microsoft

The document looks great now and the addition of the PowerShell and CMD tabs is a big plus!
