### ISSUE TITLE
Need an example YAML file for az ml datastore create

### ISSUE THREAD

**Issue by moneygit** [MicrosoftDocs/azure-docs-cli#2926]
`az ml datastore create `needs a `--file` parameter that points to a YAML file containing the Azure ML datastore specification.
I need an example of how that specification is setup,  an example file in the documentation would be useful.

**Comment by BryanTrach-MSFT** [comment]
@moneygit Thank you for your question. Can you please share with us the URL of the doc that closest aligns with your ask?

**Comment by moneygit** [comment]
This is the section that needs to be updated
https://docs.microsoft.com/en-us/cli/azure/ml/datastore?view=azure-cli-latest#az-ml-datastore-create

**Comment by BryanTrach-MSFT** [comment]
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27bfd14b-bddd-771f-1364-c52a991b75f0
* Version Independent ID: e0750d23-f2a0-7364-e6dc-34ffa51503d4
* Content: [az ml datastore](https://docs.microsoft.com/en-us/cli/azure/ml/datastore?view=azure-cli-latest#az-ml-datastore-create)
* Content Source: [latest/docs-ref-autogen/ml/datastore.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/ml/datastore.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by moneygit** [comment]
Any update on this?
We are going to need YAML reference files for all the az ml commands that require it

**Comment by moneygit** [comment]
I managed to create one successfully with a YAML file containing the data like this
I am unsure if I am missing some fields that are optional or required for a different endpoint.

```
  "account_name": "<storage_account_name>"
  "endpoint": "core.windows.net"
  "filesystem": "<folder_name>"
  "name": "<name_of_the_datastore>"
  "protocol": "https"
  "type": "azure_data_lake_gen2"
```

**Comment by dbradish-microsoft** [comment]
[moneygit](https://github.com/moneygit), Thanks for providing feedback that helps improve our reference documentation.  Instructions for using `az ml datastore` can be found in [How Azure Machine Learning works: resources and assets](https://learn.microsoft.com/en-us/azure/machine-learning/concept-azure-machine-learning-v2?tabs=cli#create-a-workspace) and [Create datastores](https://learn.microsoft.com/en-us/azure/machine-learning/how-to-datastore).
