### ISSUE TITLE
Add Third URL to Proxy Allow Paragraph

### ISSUE THREAD

**Issue by iokevins** [MicrosoftDocs/azure-docs-cli#2927]
Please add a third and fourth URL under paragraph "In order to get the MSI, your proxy needs to allow HTTPS connections to the following addresses":
https://azcliextensionsync.blob.core.windows.net/
https://objects.githubusercontent.com/

Reference:
Third URL: https://github.com/Azure/azure-cli/issues/17938#issuecomment-853011210
Fourth URL: Personal experience

Thank you,

Kevin

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8246b90a-efb1-03ce-f642-d3eb2441fc30
* Version Independent ID: 2fdd20ef-7bd3-57bc-7957-93f4bb5377ce
* Content: [Install the Azure CLI for Windows](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-windows?tabs=azure-cli#proxy-blocks-connection)
* Content Source: [docs-ref-conceptual/install-azure-cli-windows.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/docs-ref-conceptual/install-azure-cli-windows.md)
* Product: **azure**
* Technology: **azure-cli**
* GitHub Login: @dbradish-microsoft
* Microsoft Alias: **dbradish**

**Comment by BryanTrach-MSFT** [comment]
@iokevins Thanks for the feedback! I have assigned the issue to the content author to investigate further and update the document as appropriate.

**Comment by chasewilson** [comment]
Hey @iokevins thanks for the feedback here!

@yonzhan or @jiasli, can I get a confirmation for these URLs? I can make changes as necessary.

**Comment by iokevins** [comment]
After 45 days with no response, it seems maintainers have given up on or forgotten about this documentation request (?) 🤔

**Comment by jiasli** [comment]
The complete list of URLs Azure CLI requires is currently tracked by https://github.com/Azure/azure-cli/issues/21052 .

**Comment by dbradish-microsoft** [comment]
@iokevins, In response to your issue, the article [Azure CLI endpoints for proxy bypass](https://learn.microsoft.com/en-us/cli/azure/azure-cli-endpoints?view=azure-cli-latest&tabs=azure-cloud) was published.  Thank you for helping to make Azure CLI documentation better.
