### ISSUE TITLE
Links in azure documentation using underscore instead of minus to reference subsection anchors

### ISSUE THREAD

**Issue by mks-sky** [MicrosoftDocs/azure-docs-cli#2934]
### Prerequisites

- [X] Write a descriptive title.
- [X] Search the existing issues.
- [X] I am reporting the documentation problem for the current version of Azure CLI.

### Azure CLI version being used

Docs for `azure-cli-latest`

### Link to affected document

https://docs.microsoft.com/en-us/cli/azure/create-an-azure-service-principal-azure-cli#2-get-an-existing-service-principal

### Description of the documentation error

In the section `2. Get an existing service principal` the link in the first line to `az ad sp list.` is :
 https://docs.microsoft.com/en-us/cli/azure/ad/sp?view=azure-cli-latest#az_ad_sp_list

...But should be (minuses instead of underscores to represent spaces) : 
 https://docs.microsoft.com/en-us/cli/azure/ad/sp?view=azure-cli-latest#az-ad-sp-list

...And therefore it doesn't jump to the correct section of the page.

### Suggested fix

Replace _ with - where using #anchors in doc URLs.

**Comment by chasewilson** [comment]
@mks-sky, thanks for noticing and creating the issue for the fix! 

The issue was corrected in #2937 

Have a good one!
