### ISSUE TITLE
az network firewall create command is still Experimental on the document

### ISSUE THREAD

**Issue by mayoneka** [MicrosoftDocs/azure-docs-cli#2942]
### Prerequisites

- [X] Write a descriptive title.
- [X] Search the existing issues.
- [X] I am reporting the documentation problem for the current version of Azure CLI.

### Azure CLI version being used

N/A

### Link to affected document

https://docs.microsoft.com/en-US/cli/azure/reference-types-and-status?view=azure-cli-latest#what-is-reference-status

### Description of the documentation error

![image](https://user-images.githubusercontent.com/46919687/151628083-f5c19621-8e86-441a-a313-6663f2ace464.png)
"az network firewall create" command is still Experimental. But this is GA now.
It should be "No".

**Comment by AjayKumar-MSFT** [comment]
Adding doc metadata info: 



---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3dd37a62-e248-b1dd-ad17-48e8bcfae21d
* Version Independent ID: a727d676-594e-a19b-cb2c-108c28ae1c9f
* Content: [Reference types, status and support levels – Azure CLI](https://docs.microsoft.com/en-US/cli/azure/reference-types-and-status?view=azure-cli-latest#what-is-reference-status)
* Content Source: [docs-ref-conceptual/reference-types-and-status.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/docs-ref-conceptual/reference-types-and-status.md)
* Service: **azure-cli**
* GitHub Login: @dbradish-microsoft
* Microsoft Alias: **dbradish**

**Comment by ShaikMaheer-MSFT** [comment]
@dbradish-microsoft Could you please validate feedback and update document as appropriate. Thank you
