### ISSUE TITLE
Installation documentation is wrong

### ISSUE THREAD

**Issue by ihategithubsomuch** [MicrosoftDocs/azure-docs-cli#2946]
### Prerequisites

- [X] Write a descriptive title.
- [X] Search the existing issues.
- [X] I am reporting the documentation problem for the current version of Azure CLI.

### Azure CLI version being used

irrelevant

### Link to affected document

https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-macos

### Description of the documentation error

The instructions are wrong and the azure cli is never properly installed as the shell's path isnt updated and you have to manually search for where your package manager installs the product (~/homebrew/Cellar/azure-cli/2.32.0/bin) and update the shell path manually. This documentation is also incredibly out of date as it still references the bash shell. The bash shell became depreciated back in 2019 in Mac OS 10.15 when it was replaced by zsh as the default shell. For reference the current version of Mac OS is 12.1

### Suggested fix

Update the zsh path, and update your change management process so as to verify your documentation is accurate after every major release of Mac OS.

**Comment by chasewilson** [comment]
Hi @ihategithubsomuch , 

Thanks for the feedback here. 

I can't repro the install problem for shell path. Following the example, I get a good installation and immediate access to the `az`  CLI tool. 

Az for the reference to bash, I agree there are some references that could be updated. The code blocks can't be updated currently to `zsh` as it's not currently supported in Microsoft's docs platform. We can update the completion and proxy bash references though.

@jiasli could I get some info on the proxy guidance? The completion info will be a minor update linking to the same documentation but will need verification on the proxy.

**Comment by dbradish-microsoft** [comment]
@ihategithubsomuch, Thanks for your dedication to our documentation. According to [Homebrew issue 938](https://github.com/orgs/Homebrew/discussions/938) you may need to add Homebrew to your PATH.  I have forwarded your comments about the Bash shell to our engineering team.  We are closing this issue for now, but feel free to comment here as necessary.
