### ISSUE TITLE
Release Notes change under ACS instead of AKS

### ISSUE THREAD

**Issue by krsche** [MicrosoftDocs/azure-docs-cli#2950]
### Prerequisites

- [X] Write a descriptive title.
- [X] Search the existing issues.
- [X] I am reporting the documentation problem for the current version of Azure CLI.

### Azure CLI version being used

irrelevant

### Link to affected document

https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/docs-ref-conceptual/release-notes-azure-cli.md#acs

### Description of the documentation error

The command `az aks nodepool upgrade` is clearly a AKS command, why is it listed under ACS?

Also the documentation [here](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/docs-ref-conceptual/release-notes-azure-cli.md#acs) does not respect the breaking change. It shows a now broken command.
Please also provide some reason why this change was introduced, like an issue ID or similar. 

I'm not happy that I need to now manually change the max-surge of the nodepool before executing an os-image upgrade, and change it back to the original value afterwards.

### Suggested fix

1. Please consider reverting the braking change to the old behaviour - This would then not be a breaking change again.  

__If thats not possible:__
1. Fix [release notes](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/docs-ref-conceptual/release-notes-azure-cli.md#acs)
2. Fix [documentation](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/docs-ref-conceptual/release-notes-azure-cli.md#acs)

**Comment by shashishailaj** [comment]
Thank you for your inputs. We will have the team look into this and revert . 

Adding docs metadata for discoverability . 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0e8d9ef-f25b-bb46-7f1a-bd3588be3343
* Version Independent ID: cd392600-a90d-0145-5ea6-6b01ab8f4ab9
* Content: [Release notes & updates – Azure CLI](https://docs.microsoft.com/en-us/cli/azure/release-notes-azure-cli)
* Content Source: [docs-ref-conceptual/release-notes-azure-cli.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/docs-ref-conceptual/release-notes-azure-cli.md)
* Service: **azure-cli**
* GitHub Login: @dbradish-microsoft
* Microsoft Alias: **dbradish**

**Comment by AnuragSingh-MSFT** [comment]
@krsche, thank you for the query. I am assigning it to our content author for further comment. 

@dbradish, could you review and update your thoughts here. 
Thank you

**Comment by chasewilson** [comment]
Hey @krsche, thanks for the feedback here. 

I'm not sure why the release notes were formatted that way and I will update. 
Just a couple of things: 
1. The link you reference: "Also the documentation [here](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/docs-ref-conceptual/release-notes-azure-cli.md#acs) does not respect the breaking change." links to the release notes again. Would you mind sharing the correct link if you were meaning something else? 
2. These updates to Azure CLI are generally requested by the Azure Service team meaning AKS requested the change to line up with their service. This being the case we will work to update the documentation 

Thanks again when I get that other link I will create a PR that will be linked to this issue. 

Best,
Chase
