### ISSUE TITLE
The install documentation is slightly misleading on what is needed to enable the az command

### ISSUE THREAD

**Issue by johnmreynolds** [MicrosoftDocs/azure-docs-cli#2992]
### Prerequisites

- [X] Write a descriptive title.
- [X] Search the existing issues.
- [X] I am reporting the documentation problem for the current version of Azure CLI.

### Azure CLI version being used

2.33.1

### Link to affected document

https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-windows?tabs=azure-cli

### Description of the documentation error

The documentation says:

"After the installation is complete, you will need to close and reopen any active Windows Command Prompt or PowerShell windows to use the Azure CLI."

However, I found that that was not sufficient to get the az command to work - it still wasn't found even after opening a new shell.

A reboot did fix it (and I suspect signing out and back in again might have).

The only thing which is unusual about my setup is that for the UAC I need to provide separate admin credentials rather than just clicking yes, which might have an affect on how the installer works.

### Suggested fix

Either note that a reboot might be needed, or investigate exactly what the steps required are.

**Comment by SaurabhSharma-MSFT** [comment]
@johnmreynolds Thanks for the feedback !  I have assigned this issue to content author to investigate and update the document as appropriate.

**Comment by jiasli** [comment]
I think this is more of a Windows problem. We do call win32 API to broadcast the environment variable `PATH` change in `propagate_env_change.exe`:

https://github.com/Azure/azure-cli/blob/13d2f3ec69a62ea45882f1c004d211824cffdd23/build_scripts/windows/propagate_env_change/main.cpp#L1-L14

```c
#include "windows.h"

int main(int argc, LPCWSTR argv[])
{
    LRESULT dwResult = SendMessageTimeout(HWND_BROADCAST,
        WM_SETTINGCHANGE,
        0,
        (LPARAM)L"Environment",
        SMTO_ABORTIFHUNG,
        5000,
        NULL);

    return (dwResult) ? 0 : 1;
}
```

It sends `WM_SETTINGCHANGE` with `Environment` as `lParam` which notifies Windows system we have changed the `PATH` **system** environment variable.

![image](https://user-images.githubusercontent.com/4003950/174519910-c0bb3c25-67d6-4207-ac22-2f8aab886dbf.png)

On my test machine, `az` can be found immediately after installing MSI on my machine. A troubleshooting direction is to investigate why your Windows system is not responding to the `WM_SETTINGCHANGE` message.

**Comment by dbradish-microsoft** [comment]
[johnmreynolds](https://github.com/johnmreynolds), Thanks for providing feedback that helps improve our documentation.  As there has been no further conversation in this Issue since June, 2022, I am closing this thread.  If you have additional feedback, please open a new issue.
