### ISSUE TITLE
Include how to change the TLS version used by Invoke-WebRequest 

### ISSUE THREAD

**Issue by JUUTC** [MicrosoftDocs/azure-docs-cli#3028]
### Prerequisites

- [X] Write a descriptive title.
- [X] Search the existing issues.
- [X] I am reporting the documentation problem for the current version of Azure CLI.

### Azure CLI version being used

2.34.1

### Link to affected document

https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-windows?tabs=azure-powershell

### Description of the documentation error

The documentation doesn't explain that the minimum required TLS for the storage account distributing the Azure-cli is TLS1.2.   When using an Azure virtual machine running windows 2016 datacenter I wasn't able to download the CLI following the example powershell command on this page.

### Suggested fix

Include a powershell command to change the security protocol as a potental fix if a user encourters the error:

> Invoke-WebRequest : <?xml version="1.0" encoding="utf-8"?><Error><Code>TlsVersionNotPermitted</Code><Message>The TLS  version of the connection is not permitted on this storage account. 

Powershell command that fixed my issue:
`[Net.ServicePointManager]::SecurityProtocol =[Net.SecurityProtocolType]::Tls12`

**Comment by femsulu** [comment]
Thanks for bringing this to our attention. We are actively investigating and will get back to you soon.

**Comment by chasewilson** [comment]
Hey @JUUTC thanks for the feedback and the PR :) I just want to check with the eng team to make sure that this is something that should be and not something we need to implement.

@jiasli ,Can you confirm that this should be the case?

**Comment by jiasli** [comment]
I think this is more of a question regarding `Invoke-WebRequest` and out of the scope of Azure CLI.
