### ISSUE TITLE
az login  when PIM enabled 

### ISSUE THREAD

**Issue by technoidnostress** [MicrosoftDocs/azure-docs-cli#3034]
### Prerequisites

- [X] Write a descriptive title.
- [X] Search the existing issues.

### Summary of the new document or enhancement

When a user try to log in with the help of Az cli , it goes to the portal.microsoftonline.com and if the user assigned with assigned with any of the subscription, user will be able to see those subscription, 
However many corporate denies direct access to the portal by having ssl and proxies in middle which is as per in line security practices , in my case i need to activate PIM role to be able to access the subscriptions, once approved i can see those subscriptions as usual. however there is no guidance how to  access when PIM is enabled 

### Proposed title

AZ LOGIN PIM

### Proposed location in the TOC

AZ LOGIN

### List of related articles to link to

https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=apt

**Comment by navba-MSFT** [comment]
@technoidnostress Apologies for the late reply. Thanks for reaching out to us and sharing your feedback. I am looking into this ask. Tagging the 2 github issue threads from Az CLI Repo related to the CLI with PIM support Azure/azure-cli#13064 Azure/azure-cli#17712 . I will update this github thread once I have more details on this.

**Comment by navba-MSFT** [comment]
@technoidnostress Could you please elaborate on the ask ? Are you asking to [document](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=apt) the steps to be followed to run `az login `(CLI command) when the PIM is enabled for your account ? Awaiting your reply.

**Comment by technoidnostress** [comment]
@navba-MSFT  Thank you for your reply, yes i am looking for a way to access the portal when PIM is enabled through Az cli cmdlet  `az login`  i am able to reach to the portal.microsoftonline.com .   but it says "add this  to ca cert bundle"
The steps: i looged in the portal, activated my PIM role, tried to login with `az login` but could not see any of the subscriptions, so i am looking for a way to to access my subscription in either case. i saw of the article that says it s not supported yet,

**Comment by navba-MSFT** [comment]
@technoidnostress Thanks for getting back. Could you please share the article which you had referred ?

**Comment by jiasli** [comment]
> but it says "add this to ca cert bundle"

Could also share the full error message and screenshot?

**Comment by technoidnostress** [comment]
@jiasli  thank you, 

i activated PIM manually and then tried login through Az CLI & got the below response

`Certificate verification failed. This typically happens when using Azure CLI behind a proxy that intercepts traffic with a self-signed certificate. Please add this certificate to the trusted CA bundle: https://github.com/Azure/azure-cli/blob/dev/doc/use_cli_effectively.md#working-behind-a-proxy. Error detail: HTTPSConnectionPool(host='login.microsoftonline.com', port=443): Max retries exceeded with url: /common/oauth2/token (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))`

**Comment by navba-MSFT** [comment]
@technoidnostress Thanks for getting back. Apologies for the late reply. Is there a proxy in your environment ? Could you please try to run the command on another machine which is on a different network and check if that works fine ? If this is not feasible, you can append your corporate proxy certificate(s) to the end of the certifi library's cacert.pem file. Sharing the location of this on Windows: C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages\certifi\cacert.pem

Please let me know if you face any issue while testing this. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@technoidnostress Could you please let me know if you had a chance to follow the above action plan. Awaiting your reply.

**Comment by technoidnostress** [comment]
Sorry for being late, yes  i am behind the corporate proxy, i did tried to convert to cacert.crt to .PEM but i had an error , the ca.crt is in DER format, when i try to view the ca.crt i see all gibberish characters which confirms that this in DER format.
 The cacert.crt is /java/jre folder,  i am using wsl, Pls guide on proxy cert how tos, thank you

**Comment by navba-MSFT** [comment]
@technoidnostress Thanks for getting back. The step by step procedure to append the proxy's cert to the **cacert.pem** has been explained here. https://jiasli.github.io/azure-notes/cli/cli-proxy.html

The above article explains how to use Azure CLI behind a proxy. Hope this helps.

**Comment by technoidnostress** [comment]
thanks i will take a look

**Comment by navba-MSFT** [comment]
@technoidnostress Please let me know if you have any update on this. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@technoidnostress Could you please let me know if you had a chance to follow the action plan suggested in my [above](https://github.com/MicrosoftDocs/azure-docs-cli/issues/3034#issuecomment-1089808779) comment ? Awaiting your reply.

**Comment by navba-MSFT** [comment]
@technoidnostress We will now proceed with closure of this github issue. Once you have an update and need any further assistance on this issue, please feel free to reopen this thread. We would be happy to help.

**Comment by technoidnostress** [comment]
@navba-MSFT can you pls post the link : https://jiasli.github.io/azure-notes/cli/cli-proxy.html the page not found

**Comment by navba-MSFT** [comment]
@technoidnostress It is moved to new location where you can find "How to use CLi with Proxy"?

For Windows, refer [this](https://github.com/jiasli/azure-notes/blob/master/cli/proxy-cert-win.md).
For Linux, refer [this](https://github.com/jiasli/azure-notes/blob/master/cli/proxy-cert-linux.md).
