### ISSUE TITLE
Please add that Option 1: Install with one command can take an hour or two to complete

### ISSUE THREAD

**Issue by spacecat** [MicrosoftDocs/azure-docs-cli#3038]
### Prerequisites

- [X] Write a descriptive title.
- [X] Search the existing issues.
- [X] I am reporting the documentation problem for the current version of Azure CLI.

### Azure CLI version being used

2.34.1

### Link to affected document

https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=apt

### Description of the documentation error

This command takes way too long to execute.
Please add an info text in the script output to inform the user that this could take a couple of hours to complete.

Related:
https://github.com/microsoft/WSL/issues/2775

### Suggested fix

This command takes way too long to execute.
Please add an info text in the script output to inform the user that this could take a couple of hours to complete.

**Comment by GiftA-MSFT** [comment]
@spacecat we'll review your feedback and get back to you shortly. Thanks.

**Comment by chasewilson** [comment]
Hey @spacecat, thanks for the feedback here. 

@jiasli or @yonzhan, is this commopn behavior? Is this something we should document or is this not the normal behavior or something we should improve?

**Comment by jiasli** [comment]
"Take an hour or two" is definitely unexpected. It should finish with in minutes. You may check you network connection.
