### ISSUE TITLE
command fails

### ISSUE THREAD

**Issue by carlrab** [MicrosoftDocs/azure-docs-cli#3058]
should be:
az account list --query "[?isDefault == \`false\`]"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e60c12ef-d293-5626-c7aa-c7e9241bf975
* Version Independent ID: 7acca1dd-b735-7e1f-afd9-2b5b6ea06b1c
* Content: [JMESPath query command results with Azure CLI](https://docs.microsoft.com/en-us/cli/azure/query-azure-cli)
* Content Source: [docs-ref-conceptual/query-azure-cli.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/docs-ref-conceptual/query-azure-cli.md)
* Service: **azure-cli**
* GitHub Login: @dbradish-microsoft
* Microsoft Alias: **dbradish**

**Comment by shashishailaj** [comment]
@carlrab Thank you for your feedback . We will investigate and update the thread.

**Comment by shashishailaj** [comment]
@carlrab Thank you for reporting this . We have initiated a change request for the content team to review. Once approved the change would be live. 

Thank you .
