### ISSUE TITLE
python version should not be hardcoded

### ISSUE THREAD

**Issue by ebioux-btig** [MicrosoftDocs/azure-docs-cli#3067]
### Prerequisites

- [X] Write a descriptive title.
- [X] Search the existing issues.
- [X] I am reporting the documentation problem for the current version of Azure CLI.

### Azure CLI version being used

az login

### Link to affected document

https://docs.microsoft.com/cli/azure/use-cli-effectively#work-behind-a-proxy

### Description of the documentation error

<html>
<body>

Ubuntu/Debian Linux | /opt/az/lib/python3.6/site-packages/certifi/cacert.pem
-- | --

</body>
</html>

### Suggested fix

The document makes the assumption that the `az cli` is using python 3.6 - it is probably a good idea to run `az --version` first in order to find out which is the actual version of python in use

**Comment by KranthiPakala-MSFT** [comment]
Thank you for reaching out. At this time we are reviewing the ask and will provide an update as appropriate

**Comment by chasewilson** [comment]
You make a good point here @ebioux-btig. I've [created a PR](https://github.com/MicrosoftDocs/azure-docs-cli/pull/3083) to fix this. Would you mind taking a look and providing any feedback you have?
