### ISSUE TITLE
Supported certificate format for Azure CLI login is not clearly described

### ISSUE THREAD

**Issue by AAdamCCox** [MicrosoftDocs/azure-docs-cli#3091]
### Prerequisites

- [X] Write a descriptive title.
- [X] Search the existing issues.
- [X] I am reporting the documentation problem for the current version of Azure CLI.

### Azure CLI version being used

2.35.0

### Link to affected document

https://docs.microsoft.com/en-us/cli/azure/authenticate-azure-cli#sign-in-with-a-service-principal

### Description of the documentation error

Certificates are the recommended authentication method (per [this article](https://docs.microsoft.com/en-us/azure/active-directory/fundamentals/service-accounts-principal#service-principal-authentication)). For on-premises devices needing to authenticate to Azure, certificates represent the best-practice approach.

However the certificate format required by CLI is not fully described, and no example command is provided showing how to use a certificate. The note included in this section links to another [article](https://docs.microsoft.com/en-us/cli/azure/create-an-azure-service-principal-azure-cli#certificate-based-authentication). However this only shows examples for using a pre-existing .PEM file already in the required format (and the example is for Linux only), and another example when generating a self-signed certificate during Service Principal creation. This doesn't cover Windows use cases (with no mention of certificate store support or PFX files), and doesn't explain usage of CA certificates or pre-existing or externally generated self-signed certificates.

### Suggested fix

[This article](https://docs.microsoft.com/en-us/azure/container-registry/container-registry-auth-service-principal#use-with-certificate) about Container Registry mentions how to get a PEM certificate with the necessary format:

> "...the certificate must be in PEM format and include the private key. If your certificate isn't in the required format, use a tool such as openssl to convert it"

This still doesn't describe how to do the conversion, which a user has explained in detail in [this bug comment](https://github.com/MicrosoftDocs/azure-docs/issues/39687#issuecomment-537639468).

> If you have a PKCS#12 file, you can convert it to PEM format using (assuming no password, otherwise omit/change the passin argument):
> openssl pkcs12 -in acme-cert.p12 -clcerts -nodes -out acme-cert.pem -passin pass:

It would be helpful for this level of detail to be included in both articles.

**Comment by himanshusinha-msft** [comment]
We have assigned the issue to the content author . They will evaluate & update the document as appropriate

**Comment by dbradish-microsoft** [comment]
@AAdamCCox , We appreciate your suggestions and have added PKCS12 to PEM conversion information to [Working with service principals](https://learn.microsoft.com/en-us/cli/azure/create-an-azure-service-principal-azure-cli#certificate-based-authentication) in PR [3658](https://github.com/MicrosoftDocs/azure-docs-cli/pull/3658/files).. We are closing this issue for now, but feel free to comment here as necessary.
