### ISSUE TITLE
Removal of data impacts Azure PowerShell

### ISSUE THREAD

**Issue by dcaro** [MicrosoftDocs/azure-docs-cli#3101]
### Prerequisites

- [X] Write a descriptive title.
- [X] Search the existing issues.
- [X] I am reporting the documentation problem for the current version of Azure CLI.

### Azure CLI version being used

n/a

### Link to affected document

https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-windows?tabs=azure-cli#remove-data

### Description of the documentation error

The steps indicated in *Remove data* section will also impact Azure PowerShell if both are installed on the same machine.

### Suggested fix

The content should be more specific about the files to remove or provide a script that helps with the cleanup.

**Comment by RyanHill-MSFT** [comment]
Hi @dcaro, the files to removed are those in the `C:\Users\<username>\.azure` folder. You no longer need this folder if you don't intend to reinstall the CLI per instructed, as it contains any extensions you've installed, any profile details like your defaults, etc.

**Comment by dcaro** [comment]
The folder `C:\Users\<username>\.azure` is also used by Azure PowerShell.
The article needs to list explicitly the files and precise that deleting the folder will impact other tools like Azure PowerSell.

**Comment by RyanHill-MSFT** [comment]
I see, I'll reach out to the product group to find out any details regarding this matter.

**Comment by BryanTrach-MSFT** [comment]
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8246b90a-efb1-03ce-f642-d3eb2441fc30
* Version Independent ID: 2fdd20ef-7bd3-57bc-7957-93f4bb5377ce
* Content: [Install the Azure CLI for Windows](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-windows?tabs=azure-cli#remove-data)
* Content Source: [docs-ref-conceptual/install-azure-cli-windows.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/docs-ref-conceptual/install-azure-cli-windows.md)
* Product: **azure**
* Technology: **azure-cli**
* GitHub Login: @jiasli
* Microsoft Alias: **jiasli**

**Comment by RyanHill-MSFT** [comment]
I have assigned the issue to the content author to investigate further and update the document as appropriate.

**Comment by RyanHill-MSFT** [comment]
I have a pending PR to better clarify which folder can be removed @dcaro.
