### ISSUE TITLE
The link for ml extension is unavailable

### ISSUE THREAD

**Issue by slowlyswimming** [MicrosoftDocs/azure-docs-cli#3135]
### Prerequisites

- [X] Write a descriptive title.
- [X] Search the existing issues.
- [X] I am reporting the documentation problem for the current version of Azure CLI.

### Azure CLI version being used

 2.36.0

### Link to affected document

https://docs.microsoft.com/en-us/cli/azure/azure-cli-extensions-list

### Description of the documentation error

The link for ml extension is unavailable in https://docs.microsoft.com/en-us/cli/azure/azure-cli-extensions-list:
<html>
<body>

ml | 2.15.0 | Microsoft Azure Command-Line Tools AzureMachineLearningWorkspaces Extension | Preview | 2.3.1
-- | -- | -- | -- | --

</body>
</html>[ml](https://github.com/Azure/azure-cli-extensions/tree/master/src/machinelearningservices)	2.15.0	Microsoft Azure Command-Line Tools AzureMachineLearningWorkspaces Extension	Preview	[2.3.1](https://github.com/Azure/azure-cli-extensions/tree/master/src/machinelearningservices/HISTORY.rst)

**Comment by DerekHerman-MSFT** [comment]
Thanks for reporting this. I have assigned the issue to the content author to investigate further and update the document as appropriate.

**Comment by dbradish-microsoft** [comment]
[slowlyswimming](https://github.com/slowlyswimming),  Thanks for providing feedback that helps improve our documentation.  This issue has been corrected.
