### ISSUE TITLE
openssl instruction produces invalid .pem file on macOS

### ISSUE THREAD

**Issue by fardarter** [MicrosoftDocs/azure-docs-cli#3138]
### Prerequisites

- [X] Write a descriptive title.
- [X] Search the existing issues.
- [X] I am reporting the documentation problem for the current version of Azure CLI.

### Azure CLI version being used

azure-cli                         2.36.0  core                              2.36.0 telemetry                          1.0.6  Dependencies: msal                              1.17.0 azure-mgmt-resource               20.0.0  Python location '/opt/homebrew/Cellar/azure-cli/2.36.0/libexec/bin/python' Extensions directory '/Users/<redacted>/.azure/cliextensions'  Python (Darwin) 3.10.4 (main, Apr 26 2022, 19:36:29) [Clang 13.1.6 (clang-1316.0.21.2)]

### Link to affected document

https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/docs-ref-conceptual/create-an-azure-service-principal-azure-cli.md#certificate-based-authentication

### Description of the documentation error

OK, so first off, I'm not 100% sure this is only a macOS issue, but I have too many hurdles to jump through on my side to make another machine valid for `az login`, so I hope you'll forgive me for not testing on other setups. 

I am setting up a terraform project, so it's possible that there is an issue there. Anyway.

I used the following command to produce a Service Principal with a cert: `az ad sp create-for-rbac --create-cert --cert acert -n automation-global --role Contributor --keyvault automation-global --scopes /subscriptions/<redacted>`

Then this to download:

`az keyvault secret download --file ./.certs/acert.pfx --vault-name automation-global --name acert --encoding base64`

And this to convert `openssl pkcs12 -info -in ./.certs/acert.pfx -passin pass: -out ./.certs/acert.pem -nodes`

I set up an Azure Devops Service Connection with this output and it verified correctly.

However, it doesn't actually work. On the local `terraform init` I get:

```sh
2022-05-19T12:25:16.677+0200 [INFO]  Terraform version: 1.1.9
2022-05-19T12:25:16.677+0200 [INFO]  Go runtime version: go1.17.2
2022-05-19T12:25:16.677+0200 [INFO]  CLI args: []string{"terraform", "init"}
2022-05-19T12:25:16.677+0200 [DEBUG] Attempting to open CLI config file: /Users/<redacted>/.terraformrc
2022-05-19T12:25:16.678+0200 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2022-05-19T12:25:16.678+0200 [DEBUG] ignoring non-existing provider search directory terraform.d/plugins
2022-05-19T12:25:16.678+0200 [DEBUG] ignoring non-existing provider search directory /Users/<redacted>/.terraform.d/plugins
2022-05-19T12:25:16.678+0200 [DEBUG] ignoring non-existing provider search directory /Users<redacted>/Library/Application Support/io.terraform/plugins
2022-05-19T12:25:16.678+0200 [DEBUG] ignoring non-existing provider search directory /Library/Application Support/io.terraform/plugins
2022-05-19T12:25:16.679+0200 [INFO]  CLI command args: []string{"init"}

Initializing the backend...
2022-05-19T12:25:16.695+0200 [INFO]  Testing if Service Principal / Client Certificate is applicable for Authentication..
2022-05-19T12:25:16.695+0200 [INFO]  Using Service Principal / Client Certificate for Authentication
╷
│ Error: Error building ARM Config: 1 error occurred:
│       * the Client Certificate Path is not a valid pfx file: pkcs12: error reading P12 data: asn1: structure error: tags don't match (16 vs {class:1 tag:2 length:97 isCompound:false}) {optional:false explicit:false application:false private:false defaultValue:<nil> tag:<nil> stringType:0 timeType:0 set:false omitEmpty:false} pfxPdu @2
```

I thought at first that perhaps there was something wrong locally. However, I was getting the following output on the CI:

```sh
│ Error: Error building ARM Config: obtain subscription(<redacted>) from Azure CLI: parsing json result from the Azure CLI: waiting for the Azure CLI: exit status 1: ERROR: Please run 'az login' to setup account.
│ 
│ 
╵

##[error]Terraform command 'init' failed with exit code '1'.
##[error]╷
│ Error: Error building ARM Config: obtain subscription(<redacted>) from Azure CLI: parsing json result from the Azure CLI: waiting for the Azure CLI: exit status 1: ERROR: Please run 'az login' to setup account.
│ 
```

I then followed the steps in the terraform guide and set up the service connection  with the `.pfx` output from the guide (the service connection now had both cert in the certificates tab): https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/service_principal_client_certificate

This connected fine locally.

However, if I tried to run the conversion command (`openssl pkcs12 -info -in ./.certs/input.pfx -passin pass: -out ./.certs/output.pem -nodes`) on _this_ cert and use the outputed cert for the service connection, it also fails, and fails locally as well.

So I think maybe the command doesn't work properly on macOS, or maybe it will never work for anyone.

**Comment by DerekHerman-MSFT** [comment]
I'd recommend posting your question in https://github.com/Azure/azure-cli/issues since it's not directly related to the documentation. We'll follow up there. We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.

**Comment by fardarter** [comment]
@DerekHerman-MSFT Hi, thanks for the response.

I'll follow your advice is you reaffirm it, but my sense is that there either an error in the instructions for using openssl for the use case or there is a need to issue macOS specific instructions. It does seem to me like something that should be covered in process docs rather than a specific cli issue. 

I suspect if I post this there it'll get closed as not relevant to them.

What do you think?
