### ISSUE TITLE
add PowerShell examples

### ISSUE THREAD

**Issue by spottedmahn** [MicrosoftDocs/azure-docs-cli#3149]
### Prerequisites

- [X] Write a descriptive title.
- [X] Search the existing issues.
- [X] I am reporting the documentation problem for the current version of Azure CLI.

### Azure CLI version being used

2.37.0

### Link to affected document

https://docs.microsoft.com/en-us/cli/azure/use-cli-effectively

### Description of the documentation error

The page assumes bash

>Azure CLI commands run in a shell. This article uses Bash, but there are other options

### Suggested fix

add PowerShell examples

**Comment by shwetamathur7** [comment]
@spottedmahn Thanks for your feedback. We will investigate and update the thread.
