### ISSUE TITLE
feedback on this page not working as intended

### ISSUE THREAD

**Issue by spottedmahn** [MicrosoftDocs/azure-docs-cli#3150]
### Prerequisites

- [X] Write a descriptive title.
- [X] Search the existing issues.
- [X] I am reporting the documentation problem for the current version of Azure CLI.

### Azure CLI version being used

2.37

### Link to affected document

https://github.com/MicrosoftDocs/azure-docs-cli/issues

### Description of the documentation error

when reporting a doc issue:

![image](https://user-images.githubusercontent.com/14079228/170290500-3c79f7c7-5863-4f31-8d0a-0ff448f58fb0.png)

![image](https://user-images.githubusercontent.com/14079228/170290583-f630783e-aeca-469f-8bdd-f6dfef93b32c.png)

it is not doing it's normal thing:

![image](https://user-images.githubusercontent.com/14079228/170290784-bc77c65d-b18b-4ec0-a46e-f7dfcdbdc3cd.png)

that breaks features like this:
![image](https://user-images.githubusercontent.com/14079228/170290993-805067bc-db35-4e27-8dc7-1473fde0fa60.png)
https://github.com/MicrosoftDocs/azure-docs-cli/issues?utf8=%E2%9C%93&q=%22a21e188b-4ff4-0aca-531b-d4b179665be1%22&in=body

### Suggested fix

no clue

**Comment by shwetamathur7** [comment]
@spottedmahn Thanks for your feedback. We will investigate and update the thread.

**Comment by dbradish-microsoft** [comment]
[spottedmahn](https://github.com/spottedmahn),  Thanks for providing feedback that helps improve our documentation.  This issue has been corrected.
