### ISSUE TITLE
breaking changes to az ad app update are not documented

### ISSUE THREAD

**Issue by grzn** [MicrosoftDocs/azure-docs-cli#3171]
### Prerequisites

- [X] Write a descriptive title.
- [X] Search the existing issues.
- [X] I am reporting the documentation problem for the current version of Azure CLI.

### Azure CLI version being used

2.37.0

### Link to affected document

https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/docs-ref-conceptual/microsoft-graph-migration.md

### Description of the documentation error

This article lists the breaking changes to az cli.

Breaking changes are documented for `az ad app create` but not for `az ad app update`, specifically the change to `--available-to-other-tenants`

**Comment by JamesTran-MSFT** [comment]
@grzn 
Thanks for your feedback! I've assigned this issue to the author who will investigate and update as appropriate.
