### ISSUE TITLE
[MacOS] Azure CLI behind a proxy

### ISSUE THREAD

**Issue by rumstead** [MicrosoftDocs/azure-docs-cli#3184]
### Prerequisites

- [X] Write a descriptive title.
- [X] Search the existing issues.
- [X] I am reporting the documentation problem for the current version of Azure CLI.

### Azure CLI version being used

az login

### Link to affected document

https://docs.microsoft.com/en-us/cli/azure/use-cli-effectively#work-behind-a-proxy

### Description of the documentation error

macOS | /usr/local/Cellar/azure-cli//libexec/lib/python/site-packages/certifi/cacert.pem
-- | --

There are two slashes between azure-cli and libexec. It is missing the version of az cli. 

### Suggested fix

macOS | /usr/local/Cellar/azure-cli/<azure cli version>/libexec/lib/python/site-packages/certifi/cacert.pem
-- | --

```
az version | jq '."azure-cli"' | sed -e 's/"//g'
2.37.0
```

**Comment by AjayKumar-MSFT** [comment]
Added doc metadata info



---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e51daa3-30c5-f449-36a1-9f33c70ca2fc
* Version Independent ID: a21e188b-4ff4-0aca-531b-d4b179665be1
* Content: [Use Azure CLI effectively](https://docs.microsoft.com/en-us/cli/azure/use-cli-effectively#work-behind-a-proxy)
* Content Source: [docs-ref-conceptual/use-cli-effectively.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/docs-ref-conceptual/use-cli-effectively.md)
* Service: **azure-cli**
* GitHub Login: @dbradish-microsoft
* Microsoft Alias: **dbradish**

**Comment by rumstead** [comment]
LMK if you are good with that PR.

**Comment by jiasli** [comment]
@rumstead, your markdown is not rendered correctly either! 🤣 ![image](https://user-images.githubusercontent.com/4003950/174057618-7f4e5d76-7a3e-4727-92a7-10ebb707837e.png)

**Comment by wsmelton** [comment]
That path is no longer accurate, not sure if this should be reopened or a new issue created.

The path of the `cacert.pem` is based on the Python installation on Mac and not Azure CLI. On my M1 (Monteray) the path listed in the doc does not exist at all. Only place I find a `cacert.pem` is under the Python install folder.
