### ISSUE TITLE
Typo latest az cli release notes - "stroage"

### ISSUE THREAD

**Issue by dkars-csl** [MicrosoftDocs/azure-docs-cli#3186]
### Prerequisites

- [X] Write a descriptive title.
- [X] Search the existing issues.
- [X] I am reporting the documentation problem for the current version of Azure CLI.

### Azure CLI version being used

2.32.0

### Link to affected document

https://docs.microsoft.com/en-gb/cli/azure/release-notes-azure-cli#storage

### Description of the documentation error

Typo of az storage command in bullet point 11

### Suggested fix

correct to "stroage" to "storage"

**Comment by AjayKumar-MSFT** [comment]
@dkars-csl, Thanks for the feedback! We are taking a look into this and will get back to you soon.

**Comment by dbradish-microsoft** [comment]
This has been fixed in PR [22912](https://github.com/Azure/azure-cli/pull/22912)
