### ISSUE TITLE
Typo in data-export CLI doc

### ISSUE THREAD

**Issue by scschneider** [MicrosoftDocs/azure-docs-cli#3231]
### Prerequisites

- [X] Write a descriptive title.
- [X] Search the existing issues.
- [X] I am reporting the documentation problem for the current version of Azure CLI.

### Azure CLI version being used

2.38.0

### Link to affected document

https://github.com/MicrosoftDocs/azure-docs-cli/blob/08aa73acd8ed7be5deb88e0a701e663eeacb5be0/latest/docs-ref-autogen/monitor/log-analytics/workspace/data-export.yml#L4 AND https://github.com/MicrosoftDocs/azure-docs-cli/blob/08aa73acd8ed7be5deb88e0a701e663eeacb5be0/latest/docs-ref-autogen/monitor/log-analytics/workspace/data-export.yml#L204

### Description of the documentation error

Typo in the word ruls.

### Suggested fix

Manage data export rules for log analytics workspace.

**Comment by SaurabhSharma-MSFT** [comment]
@scschneider Thanks for the feedback !  I have assigned this issue to content author to investigate and update the document as appropriate.

**Comment by dbradish-microsoft** [comment]
@SaurabhSharma-MSFT , This is an autogenerated document.  The change must be made in the source code.  Please refer this issue to the appropriate service team.

**Comment by dbradish-microsoft** [comment]
[scschneider](https://github.com/scschneider),  Thanks for providing feedback that helps improve our documentation.  Your comments have been passed to the ML engineering team who controls the Azure CLI source code for [Log Analytics](https://learn.microsoft.com/en-us/azure/azure-monitor/logs/log-analytics-overview)
