### ISSUE TITLE
Typo in table CLI doc

### ISSUE THREAD

**Issue by scschneider** [MicrosoftDocs/azure-docs-cli#3232]
### Prerequisites

- [X] Write a descriptive title.
- [X] Search the existing issues.
- [X] I am reporting the documentation problem for the current version of Azure CLI.

### Azure CLI version being used

2.38.0

### Link to affected document

https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/monitor/log-analytics/workspace/table.yml

### Description of the documentation error

Typo in the word colunm

### Suggested fix

Should be column

**Comment by SaurabhSharma-MSFT** [comment]
@scschneider Thanks for the feedback !  I have assigned this issue to content author to investigate and update the document as appropriate.

**Comment by dbradish-microsoft** [comment]
@SaurabhSharma-MSFT , This is an autogenerated document.  This issue needs to be referred to the service team.   See [Modules Owned by CLI Team](https://github.com/Azure/azure-cli/blob/dev/doc/modules_owned_by_cli_team.md).

**Comment by dbradish-microsoft** [comment]
[scschneider](https://github.com/scschneider),  Thanks for providing feedback that helps improve our documentation.  I have forwarded your comment to the Azure service team that is responsible for this content.
