### ISSUE TITLE
Installing azure-cli 2.39 on RHEL 8 fails if python39 is not found.

### ISSUE THREAD

**Issue by ghost** [MicrosoftDocs/azure-docs-cli#3253]
### Prerequisites

- [X] Write a descriptive title.
- [X] Search the existing issues.
- [X] I am reporting the documentation problem for the current version of Azure CLI.

### Azure CLI version being used

2.39.0

### Link to affected document

https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-linux

### Description of the documentation error

`Error: 
 Problem: cannot install the best candidate for the job
  - nothing provides python39 needed by azure-cli-2.39.0-1.el8.x86_64
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)`

### Suggested fix

Options.
1. Current doc says required python is 3.6, so change it properly reflect python 3.9 as a dependency.
2. Fix the dependency in the package to 3.6, as is documented.

**Comment by KranthiPakala-MSFT** [comment]
Thanks for the feedback! We have assigned the issue to the content author to further review this and update the document as appropriate.

**Comment by ChaseCrum** [comment]
This has been moved toto Azure/azure-cli source code repository issue [#26341](https://github.com/Azure/azure-cli/issues/26341)
