### ISSUE TITLE
Advice for Enabling Autocompletions Does Not Work on macOS 12.5 using zsh

### ISSUE THREAD

**Issue by jscottarmstrong** [MicrosoftDocs/azure-docs-cli#3257]
### Prerequisites

- [X] Write a descriptive title.
- [X] Search the existing issues.
- [X] I am reporting the documentation problem for the current version of Azure CLI.

### Azure CLI version being used

2.39.0

### Link to affected document

https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-macos

### Description of the documentation error

Under the section `Completion is not working`, the advice fails to load correctly, using the link for Home-brew provided in that section also does not work.

### Suggested fix

What I found to work was adding the following two lines at the bottom of my `.zshrc` file:

```
autoload bashcompinit && bashcompinit
source $(brew --prefix)/etc/bash_completion.d/az
```

Credit goes to this [blog post](https://alastairchristian.com/setting-up-bash-completions-for-azure-cli-on-a-mac-with-zsh-e410a7081416) for shedding light on part of the issue.

**Comment by AnuragSharma-MSFT** [comment]
@jscottarmstrong Thank you for the feedback. This is being assigned to the content author to evaluate and update as appropriate.

**Comment by dbradish-microsoft** [comment]
Thank you for your feedback, @jscottarmstrong .  Your suggestion has been added to the macOS installation doc in PR [3678](https://github.com/MicrosoftDocs/azure-docs-cli/pull/3678).
