### ISSUE TITLE
A Little More Clarity, Please

### ISSUE THREAD

**Issue by buzzwick** [MicrosoftDocs/azure-docs-cli#3281]
### Prerequisites

- [X] Write a descriptive title.
- [X] Search the existing issues.
- [X] I am reporting the documentation problem for the current version of Azure CLI.

### Azure CLI version being used

N/A

### Link to affected document

https://docs.microsoft.com/en-us/cli/azure/create-an-azure-service-principal-azure-cli

### Description of the documentation error

It really would be enormously helpful if this page included examples of the output of the various credential-generating commands. Including examples of how those examples are used in consuming applications, if this affects formatting. It's more challenging to make a great cup of espresso if you have no idea what a great cup of espresso looks like.

**Comment by RohitMungi-MSFT** [comment]
@buzzwick Thanks for the feedback. I have assigned the issue to the content author to review and update accordingly.

**Comment by dbradish-microsoft** [comment]
@buzzwick, Thanks for your dedication to our documentation. We sincerely apologize for the delayed response. Your feedback has resulted in a current effort to improve this article with more examples and troubleshooting tips.  We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again.

**Comment by dbradish-microsoft** [comment]
@buzzwick, This is a follow-up comment to let you know that in response to your GitHub issue, we have reworked the [Work with service principals](https://learn.microsoft.com/en-us/cli/azure/azure-cli-sp-tutorial-1?view=azure-cli-latest&tabs=bash) tutorial. Thank you again for your feedback.
