### ISSUE TITLE
Linux install instructions hard-coded to amd64

### ISSUE THREAD

**Issue by tom-haines** [MicrosoftDocs/azure-docs-cli#3317]
### Prerequisites

- [X] Write a descriptive title.
- [X] Search the existing issues.
- [X] I am reporting the documentation problem for the current version of Azure CLI.

### Azure CLI version being used

n/a

### Link to affected document

https://learn.microsoft.com/en-us/cli/azure/install-azure-cli-linux

### Description of the documentation error

Under: Option 2 (step by step), part 3, "add the Azure CLI software repository": 

Issue: the bash script assumes the architecture is amd64, which leads to installing incorrect/useless software without error.

Currently:

```shell
AZ_REPO=$(lsb_release -cs)
echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" |
    sudo tee /etc/apt/sources.list.d/azure-cli.list
```

### Suggested fix

you could use `dpkg  --print-architecture` to fix (at least it will have error if arch not supported by azure cli)

```shell
AZ_REPO=$(lsb_release -cs)
echo "deb [arch=`dpkg --print-architecture`] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" |
    sudo tee /etc/apt/sources.list.d/azure-cli.list
```

This will then print 
```text
deb [arch=arm64] https://packages.......
or
deb [arch=amd64] https://packages.......
```

**Comment by RamanathanChinnappan-MSFT** [comment]
@tom-haines

Thanks for your feedback! We will investigate and update as appropriate.

It would be great if you could add a link to the documentation you are following for these steps? This would help us redirect the issue to the appropriate team. Thanks!!

**Comment by tom-haines** [comment]
It is in the description under "Link to affected document":
https://learn.microsoft.com/en-us/cli/azure/install-azure-cli-linux

Also, the embedded version of python installed is incorrect under arm64; I had to manually replace python3 binaries.  Why not just depends on python3 instead, and allow the package manager itself to find the correct version, as you do for libc for example.

**Comment by RamanathanChinnappan-MSFT** [comment]
@KranthiPakala-MSFT

Please check this case

**Comment by RamanathanChinnappan-MSFT** [comment]
@tom-haines 

Thanks for your feedback! We have assigned the issue to author and will provide further updates.

**Comment by ChaseCrum** [comment]
Agree with @Tom-Haines : submitted pull request to change arch to current arch as submitted. will close when pull request is approved

**Comment by ChaseCrum** [comment]
This was resolved per suggestion
