### ISSUE TITLE
Azure CLI Allowlist Information

### ISSUE THREAD

**Issue by dbradish-microsoft** [MicrosoftDocs/azure-docs-cli#3335]
### Prerequisites

- [X] Write a descriptive title.
- [X] Search the existing issues.

### Summary of the new document or enhancement

**Information Needed:**

1. Where to show the information
2. What UI style is needed
3. Which pages need to show the information
4. Where to get the list

**Original Request:**
We have a CX whose environment is completely behind a firewall and they whitelist endpoints on a need basis. They’re trying to install our CLI extension – connectedk8s but are failing to do so. Is there a place where network requirements (a list of endpoints) to install CLI extensions are documented? I could find this [link](https://nam06.safelinks.protection.outlook.com/?url=https:%2f%2fdocs.microsoft.com%2fen-us%2fcli%2fazure%2fuse-cli-effectively?tabs%3Dbash%252Cbash2%23work-behind-a-proxy&data=05%7c01%7cmatrilby%40microsoft.com%7c13839da1ae7e4bb0ef0208da922093f4%7c72f988bf86f141af91ab2d7cd011db47%7c1%7c0%7c637982965878526854%7cUnknown%7cTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7c3000%7c%7c%7c&sdata=4G2DzsonUNibFGNrP7WRArXMefaayI5msJ0%2BuzBUQbQ%3D&reserved=0) where there is guidance on setting env var for firewall certificate but couldn’t find the endpoint list. Can you please share it so that CX can whitelist them in their env?

 These are the ones I have gathered so far:

pypi.org
files.pythonhosted.org

**Related work item** [Customer suggestion 705760](https://dev.azure.com/ceapex/Engineering/_workitems/edit/705760)
**Potentially related GitHub** [issues](https://github.com/MicrosoftDocs/azure-docs-cli/issues?q=firewall+in%3Atitle%2Cbody+)
**Azure CLI backlog work item** [2003166](https://dev.azure.com/mseng/TechnicalContent/_workitems/edit/2003166)

CCing @chasewilson  and @jiasli  for awareness

### Proposed title

Tips for using the Azure CLI successfully

### Proposed location in the TOC

How-to

### List of related articles to link to

Add this information to our existing [Use the Azure CLI successfully](https://learn.microsoft.com/en-us/cli/azure/use-cli-effectively?view=azure-cli-latest&tabs=bash%2Cbash2) article

**Comment by ManoharLakkoju-MSFT** [comment]
@dbradish-microsoft 
Thanks for your feedback! We will investigate and update as appropriate.

It would be great if you could add a link to the documentation you are following for these steps? This would help us redirect the issue to the appropriate team. Thanks!

**Comment by dbradish-microsoft** [comment]
@ManoharLakkoju-MSFT , The purpose of this Issue is to create visibility that customers are asking for this information from engineering that I can then add to the existing article referenced in the description.

**Comment by dbradish-microsoft** [comment]
PR #[3412](https://github.com/MicrosoftDocs/azure-docs-cli/pull/3412) has been merged so this issue is being closed
