### ISSUE TITLE
Linux installation page doesn't mention architecture

### ISSUE THREAD

**Issue by howardjones** [MicrosoftDocs/azure-docs-cli#3399]
### Prerequisites

- [X] Write a descriptive title.
- [X] Search the existing issues.
- [X] I am reporting the documentation problem for the current version of Azure CLI.

### Azure CLI version being used

none yet

### Link to affected document

https://learn.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=apt

### Description of the documentation error

The page doesn't mention specific processor requirements, and the "one line install" bash script sets the architecture in the APT source list to amd64, even when the architecture ISN'T amd64 (just tried on a raspberry pi400, since the page didn't say it was intel specific)

### Suggested fix

Have the script check for supported architectures. Have the page mention what the supported architectures are.

**Comment by Naveenommi-MSFT** [comment]
@howardjones 
Thank you for bringing this to our attention. I've assigned this issue to the author who will investigate and update as appropriate.

**Comment by mikkoi** [comment]
A possible fix in [PR](https://github.com/MicrosoftDocs/azure-docs-cli/pull/3434/files)

"Use dpkg --print-architecture to get the current architecture instead of hardcoded 'amd64'."

**Comment by ChaseCrum** [comment]
OK - changes have been made in code block and merged into public view. I need to change the same command in the downloadable script and then we can close this out
