### ISSUE TITLE
Unable to install azure-cli-2.43 because the repo listed on this page does not contain the latest version

### ISSUE THREAD

**Issue by tuttipazzo** [MicrosoftDocs/azure-docs-cli#3455]
### Prerequisites

- [X] Write a descriptive title.
- [X] Search the existing issues.
- [X] I am reporting the documentation problem for the current version of Azure CLI.

### Azure CLI version being used

azure-cli                         2.38.0 

### Link to affected document

https://github.com/Azure/azure-cli

### Description of the documentation error

This page:
https://learn.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=zypper#update

says to update azure-cli by running 'zypper update azure-cli' and it's 
not finding it because azure-cli-2.43 rpm pkg is not in 

https://packages.microsoft.com/yumrepos/azure-cli/

repo.  And running 'az upgrade' doesn't work either.  

Can you please update the MS yumrepos repo to include latest MS pkgs.
Details below...

superdude@cafe:~> az --version |& egrep azure-cli
azure-cli                         2.38.0 *

superdude@cafe:~> zypper -n lr -s azure-cli
Alias          : azure-cli
Name           : Azure CLI
URI            : https://packages.microsoft.com/yumrepos/azure-cli
Enabled        : Yes
GPG Check      : (r ) Yes
Priority       : 50 (raised priority)
Autorefresh    : On
Keep Packages  : Off
Type           : rpm-md
GPG Key URI    : https://packages.microsoft.com/keys/microsoft.asc
Path Prefix    : 
Parent Service : 
Keywords       : ---
Repo Info Path : /etc/zypp/repos.d/azure-cli.repo
MD Cache Path  : /var/cache/zypp/raw/azure-cl

superdude@cafe:~> zypper update azure-cli
Loading repository data...
Reading installed packages...
No update candidate for 'azure-cli-2.38.0-1.el7.x86_64'. The highest available version is already installed.
Resolving package dependencies...
Nothing to do.

# The pkg is NOT in the repo that page specified
superdude@cafe:~> zypper se -s azure-cli | egrep 2-43
superdude@cafe:~>

# Let's try using 'az upgrade'
superdude@cafe:~> az upgrade
This command is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
Your current Azure CLI version is 2.38.0. Latest version available is 2.43.0.
Please check the release notes first: https://docs.microsoft.com/cli/azure/release-notes-azure-cli
Do you want to continue? (Y/n): y
<snip>                                                                                              
Repository 'Azure CLI' is up to date.                                                                                                                                        
<snip>                                                                             
All repositories have been refreshed.
Loading repository data...
Reading installed packages...
No update candidate for 'azure-cli-2.38.0-1.el7.x86_64'. The highest available version is already installed.
Resolving package dependencies...
Nothing to do.
CLI upgrade failed or aborted.

### Suggested fix

Can you please update the MS yumrepos repo to include latest MS pkgs.

**Comment by SaibabaBalapur-MSFT** [comment]
Unable to add meta data above .

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e7895b9a-9a6a-cd98-6947-0e4a26eda9a3
* Version Independent ID: a3f27295-3e2e-a36d-02c2-8897295fc443
* Content: [Install the Azure CLI on Linux](https://learn.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=zypper#update)
* Content Source: [docs-ref-conceptual/install-azure-cli-linux.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/docs-ref-conceptual/install-azure-cli-linux.md)
* Service: **azure-cli**
* GitHub Login: @ChaseCrum
* Microsoft Alias: **chasecrum**

**Comment by ChaseCrum** [comment]
@tuttipazzo was this resolved with the version/maintenance language that was recently updated? I don't want to mark this closed if you still have outlying concerns. Please find my contact info in my profile to discuss

**Comment by ChaseCrum** [comment]
@tuttipazzo, thank you for making Azure CLI better. Please note the shift in recent documentation changes where the binary packages are no longer maintained by Microsoft. On my test SLES servers, I am able to install, and upgrade Azure CLI - but only to the latest version maintained by SUSE. While it is not the most current version available - it is the most current version offered by SUSE. If you would like to use the most recent version available, please uninstall the SUSE version (zypper remove package and zypper rm package, etc.) and install Azure CLI from the Linux install script found [here](https://learn.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=script).
