### ISSUE TITLE
Typo in CLI command name: 'az volumes qouta-rule'

### ISSUE THREAD

**Issue by netapp-juliec** [MicrosoftDocs/azure-docs-cli#3517]
### Prerequisites

- [X] Write a descriptive title.
- [X] Search the existing issues.
- [X] I am reporting the documentation problem for the current version of Azure CLI.

### Azure CLI version being used

2.44.0

### Link to affected document

https://learn.microsoft.com/en-us/cli/azure/release-notes-azure-cli#netappfiles 

### Description of the documentation error

'qouta' in command names should be 'quota'.

**Comment by Naveenommi-MSFT** [comment]
@netapp-juliec 
Thanks for your contribution.
It would be great if you could add a link to the Proper documentation you are following for these steps? This would help us redirect the issue to the appropriate team. Thanks!

**Comment by ManoharLakkoju-MSFT** [comment]
@netapp-juliec 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by dbradish-microsoft** [comment]
@netapp-juliec , This typo, along with the Azure CLI command name, has been fixed in the source file located in Azure/azure-cli.  Please see PR #[25618](https://github.com/Azure/azure-cli/pull/25618).  Thank you for helping to improve the Azure CLI Release Notes.
