### ISSUE TITLE
Focal release is no longer signed

### ISSUE THREAD

**Issue by akshaybabloo** [MicrosoftDocs/azure-docs-cli#3539]
### Prerequisites

- [X] Write a descriptive title.
- [X] Search the existing issues.
- [X] I am reporting the documentation problem for the current version of Azure CLI.

### Azure CLI version being used

N/A

### Link to affected document

https://learn.microsoft.com/en-us/cli/azure/install-azure-cli-linux

### Description of the documentation error

I tried these steps on Ubuntu 20.04 and I get this error:

```
E: The repository 'https://packages.microsoft.com/repos/azure-cli focal Release' is no longer signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

**Comment by AjayBathini-MSFT** [comment]
@akshaybabloo 
Thanks for bringing this to our attention.
I'm going to assign this to the document author so they can take a look at it accordingly.

**Comment by ChaseCrum** [comment]
@akshaybabloo Thank you for making Azure CLI better. I have tested the installation on Ubuntu 20.04, and could not replicate the focal error that you received. As you can see below - my focal was successfully pulled down and the installation completed. It is possible that there is a certificate issue on your local machine, but further troubleshooting would be required to verify this on your end. 
[screenshot]
![image](https://user-images.githubusercontent.com/14236969/236296499-de568c88-bd97-4f03-b935-c2bedc01c0f0.png)

**Comment by akshaybabloo** [comment]
Hi just tried it today. It seems to be working fine on my system too. Thanks for your help.
