### ISSUE TITLE
serial-console - Incorrect link to documentation

### ISSUE THREAD

**Issue by fabienmazieres** [MicrosoftDocs/azure-docs-cli#3557]
### Prerequisites

- [X] Write a descriptive title.
- [X] Search the existing issues.
- [X] I am reporting the documentation problem for the current version of Azure CLI.

### Azure CLI version being used

2.46.0

### Link to affected document

https://learn.microsoft.com/en-us/cli/azure/azure-cli-extensions-list

#### Bad link to extension folder in GitHub

Link to serial console release note is currently:
https://github.com/Azure/azure-cli-extensions/tree/main/src/serialconsole

This leads to a 404 error page with message: The 'Azure/azure-cli-extensions' repository doesn't contain the 'src/serialconsole' path in 'main'.  

#### Bad link to release note in GitHub

Link to serial console release note is currently:
https://github.com/Azure/azure-cli-extensions/tree/main/src/serialconsole

This leads to a 404 error page with message: The 'Azure/azure-cli-extensions' repository doesn't contain the 'src/serialconsole' path in 'main'.  

### Suggested fix

Use this link for extension files: https://github.com/Azure/azure-cli-extensions/tree/main/src/serial-console
Use this link for release notes: https://github.com/Azure/azure-cli-extensions/tree/main/src/serial-console/HISTORY.rst

**Comment by fabienmazieres** [comment]
@SaibabaBalapur-MSFT 
https://learn.microsoft.com/en-us/cli/azure/azure-cli-extensions-list

**Comment by SaibabaBalapur-MSFT** [comment]
Document Details
⚠ Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.

ID: 4067dde0-6db0-4e37-1a8e-fe5bb9324c62
Version Independent ID: 8ba50218-429b-2c2a-eda6-8b1cfc62615f
Content: [Available extensions for the Azure CLI](https://docs.microsoft.com/en-us/cli/azure/azure-cli-extensions-list?view=azure-cli-latest)
Content Source: [docs-ref-conceptual/azure-cli-extensions-list.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/azure-cli-extensions-list.md)
Product: azure
Technology: azure-cli
GitHub Login: @haroldrandom
Microsoft Alias: jianzen

**Comment by SaibabaBalapur-MSFT** [comment]
@fabienmazieres 
Thanks for bringing this to our attention.
I'm going to assign this to the document author so they can take a look at it accordingly.

@RakeshMohanMSFT 
please review it.

**Comment by fabienmazieres** [comment]
Thanks,
Please be aware that I also raised this request on the Azure Extension repo side: https://github.com/Azure/azure-cli-extensions/pull/5970
I let you guys coordinate

**Comment by dbradish-microsoft** [comment]
@fabienmazieres, Thank you for helping to make Azure CLI documentation better.  This is an autogenerated doc from the extensions repo where you kindly created issue 5970.  The resolution of this issue was merged on March 14th, so I am closing this issue.
