### ISSUE TITLE
[Install] winget installation instructions don't add az to path

### ISSUE THREAD

**Issue by citelao** [MicrosoftDocs/azure-docs-cli#3568]
### Prerequisites

- [X] Write a descriptive title.
- [X] Search the existing issues.
- [X] I am reporting the documentation problem for the current version of Azure CLI.

### Azure CLI version being used

n/a

### Link to affected document

https://learn.microsoft.com/en-us/cli/azure/install-azure-cli-windows?tabs=powershell

### Description of the documentation error

I followed the winget installation instructions:

```
winget install -e --id Microsoft.AzureCLI
```

But this did not add `az` to my path. I am unable to run the `az` command bare; I have to run it:

```ps
& "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin\az.cmd"
```

### Suggested fix

2 possible fixes:

1. Fix the winget recipe to include adding `az` to the path.
2. Tell folks to add the directory to their path manually: `C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin`

**Comment by SaibabaBalapur-MSFT** [comment]
@citelao 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by bebound** [comment]
> After the installation is complete, you will need to close and reopen any active terminal window to use the Azure CLI.

Kindly restart terminal and it should work.

**Comment by dbradish-microsoft** [comment]
@citelao, Did you restart PowerShell before you tried to run `az`?  That should fix the problem.

**Comment by dbradish-microsoft** [comment]
@citelao, We are closing this issue for now, but feel free to comment here as necessary.  Thank you for your feedback.

**Comment by wheniuseoddjoy** [comment]
Found this page during a websearch. A terminal restart is indeed the answer.

**Comment by thedomeffm** [comment]
I've installed the az yesterday via winget and restarting the windows powershell and even reboot the system does not help. The installation does not add it to the path.

**Comment by dbradish-microsoft** [comment]
@thedomeffm, What version of Windows are you running?  winget is only available by default in Windows 11 and modern versions of Windows 10.

**Comment by thedomeffm** [comment]
> @thedomeffm, What version of Windows are you running? winget is only available by default in Windows 11 and modern versions of Windows 10.

Windows 11 Enterprise 23H2

**Comment by thedomeffm** [comment]
@dbradish-microsoft 

I've solved it by adding the following path to the `$profile.CurrentUserCurrentHost`:
```
$env:Path += ';C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin'
```

But from my expecation the installation of azure cli should have done it!
