### ISSUE TITLE
Add default values to optional parameters

### ISSUE THREAD

**Issue by bryanidsts** [MicrosoftDocs/azure-docs-cli#3577]
### Prerequisites

- [X] Write a descriptive title.
- [X] Search the existing issues.

### Summary of the new document or enhancement

Will it be zone-redundant or not when I run "az sql db create" without the zone-redundant option specified?

Nobody knows, and no one ever will

### Proposed title

Add default values to optional parameters

### List of related articles to link to

https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/sql/db.yml

**Comment by AjayBathini-MSFT** [comment]
@bryanidsts 
Thanks for your feedback! I've assigned this issue to the author who will investigate and update as appropriate.

**Comment by dbradish-microsoft** [comment]
@bryanidsts, I have moved this issue to the Github repository where the source code for `az sql` is located, and have requested clarification on the `--zone-redundant` parameter.  You can track your issue in [26317](https://github.com/Azure/azure-cli/issues/26317).  Thank you for bringing this to our attention.
