### ISSUE TITLE
Add env:path after installation of az cli. 

### ISSUE THREAD

**Issue by Mihaly7** [MicrosoftDocs/azure-docs-cli#3581]
### Prerequisites

- [X] Write a descriptive title.
- [X] Search the existing issues.
- [X] I am reporting the documentation problem for the current version of Azure CLI.

### Azure CLI version being used

2.46.0

### Link to affected document

https://learn.microsoft.com/en-us/cli/azure/install-azure-cli-windows?tabs=powershell

### Description of the documentation error

When customers install az cli as described : 
$ProgressPreference = 'SilentlyContinue'; Invoke-WebRequest -Uri https://aka.ms/installazurecliwindows -OutFile .\AzureCLI.msi; Start-Process msiexec.exe -Wait -ArgumentList '/I AzureCLI.msi /quiet'; Remove-Item .\AzureCLI.msi

It will miss the path from the environmental variables on windows core os like Azure Stack HCI OS. Therefore customers cannot run az commands and open support cases.

### Suggested fix

Add the az cli's installation path to the environmental variables.:
$env:Path += ";C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin"

**Comment by ManoharLakkoju-MSFT** [comment]
@Mihaly7 
Since we have not heard back from you, we will now proceed to close this thread.
If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.

**Comment by jiasli** [comment]
Please see the explanation at https://github.com/MicrosoftDocs/azure-docs-cli/issues/4625#issuecomment-2410655449.
