### ISSUE TITLE
Include Intune guidance in documentation

### ISSUE THREAD

**Issue by wUEZRs** [MicrosoftDocs/azure-docs-cli#3584]
### Prerequisites

- [X] Write a descriptive title.
- [X] Search the existing issues.

### Summary of the new document or enhancement

One wants to control all installations with Intune. For Microsoft native apps, this should always be on the forefront of documentation.

Use case:
Install and always upgrade AzureCLI on machines

### Proposed title

Include Intune guidance in documentation

**Comment by ManoharLakkoju-MSFT** [comment]
@wUEZRs 
It would be great if you could add a link to the documentation you are following for these steps? This would help us redirect the issue to the appropriate team. Thanks!

**Comment by ManoharLakkoju-MSFT** [comment]
@wUEZRs 
Since we have not heard back from you, we will now proceed to close this thread.
If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
