### ISSUE TITLE
Debian 12 support is not mentioned on the installation doc

### ISSUE THREAD

**Issue by akirayamamoto** [MicrosoftDocs/azure-docs-cli#3719]
### Prerequisites

- [X] Write a descriptive title.
- [X] Search the existing issues.
- [X] I am reporting the documentation problem for the current version of Azure CLI.

### Azure CLI version being used

N/A

### Link to affected document

https://learn.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=apt

### Description of the documentation error

The linked document does not mention support for Debian 12, could you add that to the doc since it is now supported?

**Comment by AjayBathini-MSFT** [comment]
@akirayamamoto 
Thanks for your feedback! I've assigned this issue to the author who will investigate and update as appropriate.

**Comment by dbradish-microsoft** [comment]
@akirayamamoto, the Azure CLI has been tested on the following distributions:  
![image](https://github.com/MicrosoftDocs/azure-docs-cli/assets/58762114/0fd30019-f8b3-445b-91c8-cdf5877a4448)

Is this the information you are seeking?

**Comment by dbradish-microsoft** [comment]
@akirayamamoto, I am closing this GitHub issue as I believe it is resolved.  if you feel that it's still a concern, please respond and let us know.
