### ISSUE TITLE
Debian one command install script is broken

### ISSUE THREAD

**Issue by chanster** [MicrosoftDocs/azure-docs-cli#3747]
### Prerequisites

- [X] Write a descriptive title.
- [X] Search the existing issues.
- [X] I am reporting the documentation problem for the current version of Azure CLI.

### Azure CLI version being used

n/a

### Link to affected document

https://learn.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=apt#option-1-install-with-one-command

### Description of the documentation error

When calling `curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash`, script exits without downloading and installing script.

in verbose mode, I see the domain that holds the blob has an invalid certificate.
```
* Connection #0 to host aka.ms left intact
* Issue another request to this URL: 'https://azurecliprod.blob.core.windows.net/$root/deb_install.sh'
*   Trying 52.239.228.4:443...
* Connected to azurecliprod.blob.core.windows.net (52.239.228.4) port 443 (#1)
* ALPN, offering h2
* ALPN, offering http/1.1
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
...
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: CN=*.blob.core.windows.net
*  start date: Mar 20 00:57:24 2023 GMT
*  expire date: Mar 20 00:57:24 2024 GMT
*  subjectAltName does not match azurecliprod.blob.core.windows.net
* SSL: no alternative certificate subject name matches target host name 'azurecliprod.blob.core.windows.net'
* Closing connection 1
* TLSv1.2 (OUT), TLS header, Unknown (21):
* TLSv1.2 (OUT), TLS alert, close notify (256):
```

### Suggested fix

update certificate

**Comment by AjayBathini-MSFT** [comment]
@chanster 
Thanks for your feedback! I've assigned this issue to the author who will investigate and update as appropriate.

**Comment by dbradish-microsoft** [comment]
Closing as there is a corresponding Issue https://github.com/Azure/azure-cli/issues/26939 which is resolved.
