### ISSUE TITLE
First part of the sentence "to the service principal, giving you control over which resources can be accessed and at which level." is missing

### ISSUE THREAD

**Issue by QueryCoordinator** [MicrosoftDocs/azure-docs-cli#3800]
### Prerequisites

- [X] Write a descriptive title.
- [X] Search the existing issues.
- [X] I am reporting the documentation problem for the current version of Azure CLI.

### Azure CLI version being used

I don't know how to check this value.

### Link to affected document

https://learn.microsoft.com/en-us/cli/azure/create-an-azure-service-principal-azure-cli

### Description of the documentation error

First part of the sentence "to the service principal, giving you control over which resources can be accessed and at which level." is missing. I guess it should read "**Access to resources is restricted by the roles assigned** to the service principal, giving you control over which resources can be accessed and at which level." instead, based on this page: https://learn.microsoft.com/en-us/azure/active-directory/develop/howto-create-service-principal-portal. 

### Suggested fix

"Access to resources is restricted by the roles assigned** to the service principal, giving you control over which resources can be accessed and at which level."

**Comment by ManoharLakkoju-MSFT** [comment]
@QueryCoordinator 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by AjayBathini-MSFT** [comment]
@QueryCoordinator 
Thanks for reporting this! We have created a PR for this issue and the changes should go live soon.
https://github.com/AjayBathini-MSFT/azure-docs-cli/pull/1
