### ISSUE TITLE
Version not correct

### ISSUE THREAD

**Issue by Z0dal** [MicrosoftDocs/azure-docs-cli#3826]
### Prerequisites

- [X] Write a descriptive title.
- [X] Search the existing issues.
- [X] I am reporting the documentation problem for the current version of Azure CLI.

### Azure CLI version being used

2.50.0_1

### Link to affected document

https://learn.microsoft.com/en-us/cli/azure/install-azure-cli-macos

### Description of the documentation error

The URL states that the latest version of Azure CLI is 2.51.0 (also in the release notes) but for Mac OS it is possible to install 2.50.0_1 (using homebrew) and still complains that latest version is 2.51.0.

**Comment by Z0dal** [comment]
$ az --version
azure-cli                         2.50.0 *

core                              2.50.0 *
telemetry                          1.0.8 *

Extensions:
aks-preview                      0.5.118
log-analytics                      0.2.2

Dependencies:
msal                              1.22.0
azure-mgmt-resource             23.1.0b2

Python location '/usr/local/Cellar/azure-cli/2.50.0_1/libexec/bin/python'
Extensions directory '/Users/tfidler/.azure/cliextensions'

Python (Darwin) 3.10.12 (main, Jun 20 2023, 16:51:59) [Clang 13.0.0 (clang-1300.0.29.30)]

Legal docs and information: aka.ms/AzureCliLegal
You have 3 update(s) available. Consider updating your CLI installation with 'az upgrade'

$ az upgrade
This command is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
Your current Azure CLI version is 2.50.0. Latest version available is 2.51.0.
Please check the release notes first: https://docs.microsoft.com/cli/azure/release-notes-azure-cli
Do you want to continue? (Y/n): Y
Already up-to-date.
Warning: azure-cli 2.50.0_1 already installed
CLI upgrade failed or aborted.

**Comment by RamanathanChinnappan-MSFT** [comment]
> ### Prerequisites
> * [x]  Write a descriptive title.
> * [x]  Search the existing issues.
> * [x]  I am reporting the documentation problem for the current version of Azure CLI.
> 
> ### Azure CLI version being used
> 2.50.0_1
> 
> ### Link to affected document
> https://learn.microsoft.com/en-us/cli/azure/install-azure-cli-macos
> 
> ### Description of the documentation error
> The URL states that the latest version of Azure CLI is 2.51.0 (also in the release notes) but for Mac OS it is possible to install 2.50.0_1 (using homebrew) and still complains that latest version is 2.51.0.
> 
> ### Suggested fix
> _No response_



---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d09ed623-c83f-6bae-639e-a5f9a31fe3bb
* Version Independent ID: c5d0d722-aacd-47a3-3fcf-982c02c4d0e9
* Content: [Install the Azure CLI on macOS](https://learn.microsoft.com/en-us/cli/azure/install-azure-cli-macos)
* Content Source: [docs-ref-conceptual/install-azure-cli-macos.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/docs-ref-conceptual/install-azure-cli-macos.md)
* Service: **azure-cli**
* GitHub Login: @jiasli
* Microsoft Alias: **jiasli**

**Comment by RamanathanChinnappan-MSFT** [comment]
@Z0dal 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by bebound** [comment]
Known issue, see https://github.com/Azure/azure-cli/issues/27047
Fixed in 2.52
