### ISSUE TITLE
[AFD] The custom domain name requires dash instead of dot

### ISSUE THREAD

**Issue by progxaker** [MicrosoftDocs/azure-docs-cli#3838]
### Prerequisites

- [X] Write a descriptive title.
- [X] Search the existing issues.
- [X] I am reporting the documentation problem for the current version of Azure CLI.

### Azure CLI version being used

2.51.1

### Link to affected document

https://learn.microsoft.com/en-us/cli/azure/afd/custom-domain?view=azure-cli-latest#az-afd-custom-domain-create

### Description of the documentation error

Hello. I used the following command to create a custom domain in Azure Front Door:
```
az afd custom-domain create --certificate-type CustomerCertificate
                            --custom-domain-name dev.project.org.example.com
                            --host-name dev.project.org.example.com
                            --minimum-tls-version TLS12
                            --profile-name example-profile-name
                            --resource-group example-resource-group
                            --secret example-secret-name
```

but got an error:
```
Command group `afd` is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
(BadRequest) Property 'AfdDomainEntry.AfdDomainName' cannot be set to 'dev.project.org.example.com'.
Code: BadRequest
Message: Property 'AfdDomainEntry.AfdDomainName' cannot be set to 'dev.project.org.example.com'.
```

I obtained a REST API request from Azure Portal and according to it, the custom domain name should use `-` as delimiter, but there is no mention of this in the documentations.
<details>
<summary>REST API</summary>

```
curl 'https://management.azure.com/subscriptions/<subscription-id>/resourceGroups/<resource-group>/providers/Microsoft.Cdn/profiles/<profile>/customdomains/dev-project-org-example-com?api-version=2023-05-01' \
    -X PUT \
    --data-raw '{
                    "id": "/subscriptions/<subscription-id>/resourceGroups/<resource-group>/providers/Microsoft.Cdn/profiles/<profile>/customdomains/dev-project-org-example-com",
                    "name": "dev-project-org-example-com",
                    "properties": {
                        "hostName": "dev.project.org.example.com",
                        "tlsSettings": {
                            "certificateType": "CustomerCertificate",
                            "minimumTlsVersion": "TLS12",
                            "secret": { 
                                "id":"/subscriptions/<subscription-id>/resourceGroups/<resource-group>/providers/Microsoft.Cdn/profiles/<profile>/secrets/<secret-name>"
                            }
                        }
                    }
                }'
```

</details>

```
--custom-domain-name
Name of the custom domain.
```

After changing the delimiter for `--custom-domain-name`, I successfully created the domain.
```
az afd custom-domain create --certificate-type CustomerCertificate
                            --custom-domain-name dev-project-org-example-com
                            --host-name dev.project.org.example.com
                            --minimum-tls-version TLS12
                            --profile-name example-profile-name
                            --resource-group example-resource-group
                            --secret example-secret-name
```

<details>
<summary>az-afd response</summary>

```json
{
  "azureDnsZone": null,
  "deploymentStatus": "Succeeded",
  "domainValidationState": "Approved",
  "hostName": "dev.project.org.example.com",
  "name": "dev-project-org-example-com",
  "preValidatedCustomDomainResourceId": null,
  "profileName": null,
  "provisioningState": "Succeeded",
  "resourceGroup": "example-resource-group",
  "systemData": null,
  "tlsSettings": {
    "certificateType": "CustomerCertificate",
    "minimumTlsCertificate": "TLS12",
    "secret": {
      "id": "/subscriptions/<subscription-id>/resourceGroups/<resource-group>/providers/Microsoft.Cdn/profiles/<profile>/secrets/<secret-name>",
      "resourceGroup": "example-resource-group"
    }
  },
  "type": "Microsoft.Cdn/profiles/customdomains",
  "validationProperties": {
    "expirationDate": "0001-01-01T00:00:00.0000000",
    "validationToken": null
  }
}
```

</details>

**Comment by SaibabaBalapur-MSFT** [comment]
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 79c5f236-82b3-f9ff-05dc-2649dfd7cb35
* Version Independent ID: cea7c44c-f653-4ce5-6623-379d1ca52463
* Content: [az afd custom-domain](https://learn.microsoft.com/en-us/cli/azure/afd/custom-domain?view=azure-cli-latest#az-afd-custom-domain-create)
* Content Source: [latest/docs-ref-autogen/afd/custom-domain.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/afd/custom-domain.yml)
* GitHub Login: @dbradish-microsoft
* Microsoft Alias: **dbradish**

**Comment by SaibabaBalapur-MSFT** [comment]
@progxaker 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by dbradish-microsoft** [comment]
@progxaker , Thank you for bringing this to our attention.  Because the reference content in MicrosoftDocs/azure-docs-cli is autogenerated from in-line help, I have moved this GitHub issue to the Azure/azure-cli GitHub repository in new Issue [27309](https://github.com/Azure/azure-cli/issues/27309).  This is the repo where the actual content resides, and it will be routed to the AFD team from there.

I am closing this issue as I cannot fix the problem from here, but you can continue to comment here as needed.
