### ISSUE TITLE
Typo in Azure CLI onboarding cheat sheet

### ISSUE THREAD

**Issue by Prakash4844** [MicrosoftDocs/azure-docs-cli#3840]
### Prerequisites

- [X] Write a descriptive title.
- [X] Search the existing issues.
- [X] I am reporting the documentation problem for the current version of Azure CLI.

### Azure CLI version being used

2.51.0

### Link to affected document

https://learn.microsoft.com/en-us/cli/azure/cheat-sheet-onboarding#common-usage-questions

### Description of the documentation error

In Common Usage Question Table: in 2nd Column and 5th Row

it lists command as `az account list --ouput table`

which results in error: `unrecognized arguments: --ouput table`

### Suggested fix

Change command listed from `az account list --ouput table` to `az account list --output table`

**Comment by SaibabaBalapur-MSFT** [comment]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/V-SAIB~1/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/V-SAIB~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#467886" vlink="#96607D">



S.No | Name | Count
-- | -- | --
1 | Naveen | 21
2 | Ajay | 22
3 | Rama | 20
4 | Manohar | 22
5 | Saibaba | 21



</body>

</html>

**Comment by SaibabaBalapur-MSFT** [comment]
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7e619320-8638-7beb-48ce-fa00a5d67779
* Version Independent ID: e5d2a07f-afd9-e985-abda-0840ac5f59b0
* Content: [Azure CLI onboarding cheat sheet](https://learn.microsoft.com/en-us/cli/azure/cheat-sheet-onboarding#common-usage-questions)
* Content Source: [docs-ref-conceptual/cheat-sheet-onboarding.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/docs-ref-conceptual/cheat-sheet-onboarding.md)
* Service: **azure-cli**
* GitHub Login: @dbradish-microsoft
* Microsoft Alias: **dbradish**

**Comment by SaibabaBalapur-MSFT** [comment]
@Prakash4844 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by dbradish-microsoft** [comment]
@Prakash4844 , Thank you for brining this to our attention.  This typo has been fixed in PR https://github.com/MicrosoftDocs/azure-docs-cli/pull/3842.
