### ISSUE TITLE
incorrect/misleading command to install specific version of azure-cli 

### ISSUE THREAD

**Issue by chrnel** [MicrosoftDocs/azure-docs-cli#3863]
### Prerequisites

- [X] Write a descriptive title.
- [X] Search the existing issues.
- [X] I am reporting the documentation problem for the current version of Azure CLI.

### Azure CLI version being used

2.52.0 (but applicable to any version)

### Link to affected document

https://learn.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=apt

### Description of the documentation error

the page states that the command you should use to install a specific version of azure-cli on ubuntu is:

sudo apt-get install azure-cli=<version>-1~bullseye

However, the word "bullseye" refers to a specific ubuntu distribution version - this command is only correct if you happen to be installing onto that particular version of ubuntu.

### Suggested fix

It would be better if the page mentioned that you should amend the ubuntu distribution name to match the version that you are trying to install on e.g.

sudo apt-get install azure-cli=<version>-1~<ubuntu distribution name>

Perhaps mention that the distribution name can be obtained by running this:

lsb_release -cs

**Comment by chrnel** [comment]
The form has mangled my feedback input by sanitizing the angle brackets away.

The bad command was:
sudo apt-get install azure-cli=[version]-1~bullseye

the suggested fix was:
sudo apt-get install azure-cli=[version]-1~[ubuntu distribution version]

**Comment by Naveenommi-MSFT** [comment]
@chrnel
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by Naveenommi-MSFT** [comment]
@chrnel 
Thank you for bringing this to our attention.
I've delegated this to content author @dbradish-microsoft, who will review it and offer their insightful opinions.

**Comment by Naveenommi-MSFT** [comment]
@dbradish-microsoft 
Could you please review add comments on this, update as appropriate.

**Comment by dbradish-microsoft** [comment]
@chrnel, Thank you for your suggestions.  We have added clarity to the [Install specific version](https://learn.microsoft.com/en-us/cli/azure/install-azure-cli-linux?view=azure-cli-latest&pivots=apt#install-specific-version) section of the article per your feedback.  You can view the update in [PR 3872](https://github.com/MicrosoftDocs/azure-docs-cli/pull/3872).
