### ISSUE TITLE
Typo in the page https://learn.microsoft.com/en-us/cli/azure/manage-azure-subscriptions-azure-cli

### ISSUE THREAD

**Issue by msteel9999** [MicrosoftDocs/azure-docs-cli#3916]
### Prerequisites

- [X] Write a descriptive title.
- [X] Search the existing issues.
- [X] I am reporting the documentation problem for the current version of Azure CLI.

### Azure CLI version being used

NA

### Link to affected document

https://learn.microsoft.com/en-us/cli/azure/manage-azure-subscriptions-azure-cli

### Description of the documentation error

I believe this code extract has a typo and the password parameter should be "--password <Your password>" that is double dash not single dash as in the page:

`# sign in as a different user
az login --user <myAlias@myCompany.com> **-password** <myPassword>

# sign in with a different tenant
az login --tenant <myTenantID>`

### Suggested fix

Add another dash

**Comment by AjayBathini-MSFT** [comment]
@msteel9999 
Thanks for your feedback! I've assigned this issue to the author who will investigate and update as appropriate.

**Comment by dbradish-microsoft** [comment]
@msteel9999, thanks so much for letting me know about this!  This typo has been fixed in PR [3917](https://github.com/MicrosoftDocs/azure-docs-cli/pull/3917).
