### ISSUE TITLE
Python@3.11 instead of Python@3.10 as min requirement

### ISSUE THREAD

**Issue by jaypee1990** [MicrosoftDocs/azure-docs-cli#4035]
### Prerequisites

- [X] Write a descriptive title.
- [X] Search the existing issues.
- [X] I am reporting the documentation problem for the current version of Azure CLI.

### Azure CLI version being used

2.55

### Link to affected document

https://learn.microsoft.com/en-us/cli/azure/install-azure-cli-macos#install-with-homebrew

### Description of the documentation error

Now it requires Python@3.11 as min requirement to install via Homebrew, doc says 3.10.

### Suggested fix

update the documentation to reflect changes.

**Comment by RamanathanChinnappan-MSFT** [comment]
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d09ed623-c83f-6bae-639e-a5f9a31fe3bb
* Version Independent ID: c5d0d722-aacd-47a3-3fcf-982c02c4d0e9
* Content: [Install the Azure CLI on macOS](https://learn.microsoft.com/en-us/cli/azure/install-azure-cli-macos#install-with-homebrew)
* Content Source: [docs-ref-conceptual/install-azure-cli-macos.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/docs-ref-conceptual/install-azure-cli-macos.md)
* Service: **azure-cli**
* GitHub Login: @jiasli
* Microsoft Alias: **jiasli**

> ### Prerequisites
> * [x]  Write a descriptive title.
> * [x]  Search the existing issues.
> * [x]  I am reporting the documentation problem for the current version of Azure CLI.
> 
> ### Azure CLI version being used
> 2.55
> 
> ### Link to affected document
> https://learn.microsoft.com/en-us/cli/azure/install-azure-cli-macos#install-with-homebrew
> 
> ### Description of the documentation error
> Now it requires Python@3.11 as min requirement to install via Homebrew, doc says 3.10.
> 
> ### Suggested fix
> update the documentation to reflect changes.
