### ISSUE TITLE
"resourcegroup name must be globally unique"

### ISSUE THREAD

**Issue by thebeautiful** [MicrosoftDocs/azure-docs-cli#4054]
### Prerequisites

- [X] Write a descriptive title.
- [X] Search the existing issues.
- [X] I am reporting the documentation problem for the current version of Azure CLI.

### Azure CLI version being used

2.53.1

### Link to affected document

https://learn.microsoft.com/en-us/cli/azure/get-started-tutorial-1-prepare-environment?tabs=bash#create-a-resource-group

### Description of the documentation error

It says "resourcegroup name must be globally unique".
This is simply not true

### Suggested fix

the resource group needs a unique name in the subscription scope.
thank you

**Comment by SaibabaBalapur-MSFT** [comment]
@thebeautiful 
Could you please elaborate the query for better understanding. So, we can assist you further.

**Comment by SaibabaBalapur-MSFT** [comment]
@dbradish-microsoft 
Please review it.

**Comment by dbradish-microsoft** [comment]
Thank you for bringing this to my attention, @thebeautiful.  This has been corrected in PR [4074](https://github.com/MicrosoftDocs/azure-docs-cli/pull/4074).
