### ISSUE TITLE
reference to command line tools vague and unclear

### ISSUE THREAD

**Issue by sandokanfirst** [MicrosoftDocs/azure-docs-cli#4116]
### Prerequisites

- [X] Write a descriptive title.
- [X] Search the existing issues.
- [X] I am reporting the documentation problem for the current version of Azure CLI.

### Azure CLI version being used

NA

### Link to affected document

https://learn.microsoft.com/en-us/cli/azure/use-cli-effectively?tabs=bash%2Cbash2

### Description of the documentation error

![CLI](https://github.com/MicrosoftDocs/azure-docs-cli/assets/36963445/659731e1-4c2d-49fe-8e49-264488c3a39b)

The text can be rather confusing for those not familar with (the Azure) CLI! The text says: "Azure CLI is a COMMAND-LINE TOOL (my emphasis) that allows you to configure and manage Azure resources from many shell environments. First choose the right COMMAND-LINE TOOL (my emphasis) and install the Azure CLI. Then use this article to discover useful tips on how to avoid common pitfalls and use the Azure CLI successfully." 

So Azure CLI is a **command-line tool**, but you first have to select the right **command-line tool** to use it?!! How does that work? This use of the same term for different concepts is confusing and wrong.

### Suggested fix

I would propose to use the term 'shell environment' for bash, PowerShell, Cmd and the like. This is also borne out by information on https://learn.microsoft.com/en-us/cli/azure/choose-the-right-azure-command-line-tool Then the term 'command line tool' can be reserved for the tools installed with (or in) their respective shell environments.

**Comment by AjayBathini-MSFT** [comment]
@sandokanfirst 
Thanks for bringing this to our attention.
I'm going to assign this to the document author so they can take a look at it accordingly.

**Comment by dbradish-microsoft** [comment]
@sandokanfirst, Thank you for your feedback.  I like your suggestion!  This has been implemented in PR #4120 .
