### ISSUE TITLE
allow_broker config is deprecated and replaced with enable_broker_on_windows in 2.58.0

### ISSUE THREAD

**Issue by chunderbolt** [MicrosoftDocs/azure-docs-cli#4202]
### Prerequisites

- [X] Write a descriptive title.
- [X] Search the existing issues.
- [X] I am reporting the documentation problem for the current version of Azure CLI.

### Azure CLI version being used

2.58.0

### Link to affected document

https://learn.microsoft.com/en-us/cli/azure/authenticate-azure-cli-web-account-manager

### Description of the documentation error

Documentation suggests doing the following to enable WAM:

```
az config set core.allow_broker=true
az account clear
az login
```

As of [2.58.0, allow_broker has been deprecated and replaced with enable_broker_on_windows](https://learn.microsoft.com/en-us/cli/azure/release-notes-azure-cli#core).

### Suggested fix

The documentation should suggest using enable_broker_on_windows instead, and probably have a note regarding the breaking change and versions involved.

**Comment by SaibabaBalapur-MSFT** [comment]
@chunderbolt 
I'm going to assign this to the document author so they can take a look at it accordingly.

**Comment by dbradish-microsoft** [comment]
@chunderbolt, This update has been completed in the [March 2024 release](https://learn.microsoft.com/en-us/cli/azure/release-notes-azure-cli#core-2) of the Azure CLI.
