### ISSUE TITLE
No mention of refreshing login for account with multi-factor authentication

### ISSUE THREAD

**Issue by FrankDeGroot** [MicrosoftDocs/azure-docs-cli#4213]
### Prerequisites

- [X] Write a descriptive title.
- [X] Search the existing issues.
- [X] I am reporting the documentation problem for the current version of Azure CLI.

### Azure CLI version being used

2.58.0

### Link to affected document

https://learn.microsoft.com/en-us/cli/azure/authenticate-azure-cli-interactively

### Description of the documentation error

This document does not mention the option to refresh the login for an account using multi-factor authentication.

### Suggested fix

After repeated attempts the az cli presents the following command line which solves the issue: `az login --scope https://management.core.windows.net//.default`

**Comment by Naveenommi-MSFT** [comment]
@FrankDeGroot 
Thank you for bringing this to our attention.
I've delegated this to content author @jiasli, who will review it and offer their insightful opinions.

**Comment by dbradish-microsoft** [comment]
@FrankDeGroot, Did you try [az logout](https://learn.microsoft.com/en-us/cli/azure/reference-index?view=azure-cli-latest#az-logout)?

**Comment by FrankDeGroot** [comment]
Thanks for the reply. I was able to resolve the issue but I thought it would be useful if the documentation would mention the suggested fix that's put at the bottom of the post.

**Comment by dbradish-microsoft** [comment]
@frankDeGroot, I would like to add your suggestion to the doc, but I need more context. How might I replicate the problem? For example, was there some sort of permissions change in Azure, and this update was not recognized by the Azure CLI?

**Comment by dbradish-microsoft** [comment]
I am closing this GitHub issue as adequate time has been given for discussion.  If further action is needed, please open a new GitHub issue.
