### ISSUE TITLE
Install azure-cli on sonoma apple silicon

### ISSUE THREAD

**Issue by yingding** [MicrosoftDocs/azure-docs-cli#4220]
### Prerequisites

- [X] Write a descriptive title.
- [X] Search the existing issues.
- [X] I am reporting the documentation problem for the current version of Azure CLI.

### Azure CLI version being used

2.58.0

### Link to affected document

https://learn.microsoft.com/en-us/cli/azure/install-azure-cli-macos

### Description of the documentation error

For the section **completion isn't working**
https://learn.microsoft.com/en-us/cli/azure/install-azure-cli-macos#completion-isnt-working

For the apple silicon mac, you need to add the following to the .zshrc
```
autoload -U +X compinit && compinit
autoload -U +X bashcompinit && bashcompinit
source $(brew --prefix)/etc/bash_completion.d/az
```
otherwise you will get an error: `complete:13: command not found: compdef`

## Completion isn't working
The Homebrew formula of Azure CLI installs a completion file named az in the Homebrew-managed completions directory (default location is /usr/local/etc/bash_completion.d/). To enable completion, follow Homebrew's instructions [here](https://docs.brew.sh/Shell-Completion).

For Zsh on mac(< ventura) , add the following two lines to the bottom of your .zshrc file, then save and reload your zsh profile.
```
autoload bashcompinit && bashcompinit
source $(brew --prefix)/etc/bash_completion.d/az
````

For Zsh on mac(>= ventura), add the following three lines to the bottom of your .zshrc file, then save and reload your zsh profile.
```
autoload -U +X compinit && compinit
autoload -U +X bashcompinit && bashcompinit
source $(brew --prefix)/etc/bash_completion.d/az
```

**Comment by ManoharLakkoju-MSFT** [comment]
@yingding 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by dbradish-microsoft** [comment]
@jiasli, Can you kindly verify this information so it can be added to the install doc for macOS?

**Comment by dbradish-microsoft** [comment]
Thanks for your dedication to our documentation. As there has been no further discussion, we are closing this issue for now.
