### ISSUE TITLE
examples do not work as-is with copy/paste as is apparently intended

### ISSUE THREAD

**Issue by lmamakos** [MicrosoftDocs/azure-docs-cli#4335]
### Prerequisites

- [X] Write a descriptive title.
- [X] Search the existing issues.
- [X] I am reporting the documentation problem for the current version of Azure CLI.

### Azure CLI version being used

2.58.0

### Link to affected document

https://learn.microsoft.com/en-us/cli/azure/get-started-tutorial-4-delete-resources?tabs=bash

### Description of the documentation error

This is a commonly repeated error across multiple pages in this section of the documentation.   The problem is that having, e.g., a resource group named, literally,  `<msdocs-tutorial-rg-0000000>` is problematic with shell command line processing.  Using the redirect operators just doesn't work without quoting, and none of the examples do so.  For example, on this page we see

```bash
# Set your resource group variable
rgName=<msdocs-tutorial-rg-0000000>
```

which doesn't work.   On other pages, the literal `<msdocs-tutorial-rg-0000000>` string is passed as a command-line parameter to the `az` command and also fails.

It seems the intent is that someone should be able to press the "Copy" button on those text boxes and paste the result into their shell window as-is, but that's not working.

I suspect this could be a formatting problem?  Not sure.

A less serious issue is that neither bash or zsh on at least macOS take `#` as a comment introducer for interactive input, which is what happens when doing the copy/paste thing to try out the examples.   Perhaps using `:` instead could be considered?  Otherwise, people will just ignore the spurious `#: command not found` errors that pop out.

**Comment by TPavanBalaji** [comment]
@lmamakos 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by AjayBathini-MSFT** [comment]
@lmamakos 
Thanks for bringing this to our attention.
I'm going to assign this to the document author so they can take a look at it accordingly.

**Comment by dbradish-microsoft** [comment]
@lmamakos, When you see a parameter value in angled bracets `<>`, it is an indicator to replace what is inside of the brackets with an actual value from your own environment. This particular tutorial has prerequisite steps to create a resouce group with a random ID, thus the parameter value `msdocs-rg-00000000` vs something like `myResourceGroupName`.

I do see your point in the docs within this tutorial assuming a customer knows to also quote their parameter value, so I've updated the instance you brought to our attention plus several others in [PR #4347](https://github.com/MicrosoftDocs/azure-docs-cli/pull/4347).

I appreciate your comments about our `Copy` button as well.  Some scripts can run as-is, like this one:
```
for rgList in $(az group list --query "[?starts_with(name, 'msdocs') == \`true\`].name" -o tsv); 
do
    az group delete --name $rgList --yes --no-wait
done
```
However, most Azure CLI commands require an actual resource group name or subscription ID like this example:
```
rgName="myResourceGroupName"

# Delete storage accounts without a confirmation prompt.
for saList in $(az storage account list --resource-group $rgName \
    --query "[?starts_with(name, 'msdocs') == \`true\`].id" \
    --output tsv); do
    echo "deleting storage account $saList"
    az storage account delete --ids $saList --yes
done
```

I hear your point about the comment character, and here is a good discussion on this topic in StackExchange: [zsh comment character](https://apple.stackexchange.com/questions/405246/zsh-comment-character). As the Azure CLI can be run in many environments, we have chosen to standardize on the `#` character for comments.

Thank you for your feedback and for helping us improve Azure CLI docs.
