### ISSUE TITLE
az login --service-principal

### ISSUE THREAD

**Issue by abirhasan132** [MicrosoftDocs/azure-docs-cli#4340]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d884a3fe-07cf-e518-085d-602425fe2480
* Version Independent ID: 1636994b-e193-74e2-9936-a07e43913326
* Content: [How to run Azure CLI in a Docker Container](https://learn.microsoft.com/en-us/cli/azure/run-azure-cli-docker)
* Content Source: [docs-ref-conceptual/run-azure-cli-docker.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/docs-ref-conceptual/run-azure-cli-docker.md)
* Service: **azure-cli**
* GitHub Login: @jiasli
* Microsoft Alias: **jiasli**

**Comment by PesalaPavan** [comment]
@abirhasan132 
It would be great if you could add more about issue you are following for these steps? This would help us redirect the issue to the appropriate team. Thanks!!

**Comment by dbradish-microsoft** [comment]
@abirhasan132, I'm closing this GitHub issue as it doesn't contain sufficient information for us to provide assistance. Please open a new GitHub issue to suggest documentation updates for this article. We always appreciate customer feedback that asists us to improve the Azure CLI content.

**Comment by abirhasan132** [comment]
#4340
