### ISSUE TITLE
Remove the redundant AAD login section. 

### ISSUE THREAD

**Issue by sivagudivadaz** [MicrosoftDocs/azure-docs-cli#4397]
### Type of issue

Other (describe below)

### Feedback

AAD login is documented twice 
![image](https://github.com/MicrosoftDocs/azure-docs-cli/assets/98360053/af2d7cfb-465f-4330-b641-68716ef91c86)
 

### Page URL

https://learn.microsoft.com/en-us/cli/azure/network/bastion?view=azure-cli-latest

### Content source URL

https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/network/bastion.yml

### Author

@dbradish-microsoft

### Document Id

399a501c-b96d-8867-078f-73dd9b8b3da2

**Comment by AjayBathini-MSFT** [comment]
@sivagudivadaz 
Thanks for bringing this to our attention.
I'm going to assign this to the document author so they can take a look at it accordingly.

**Comment by dbradish-microsoft** [comment]
The content of this document must be fixed by the engineering team.  Consequently, this issue has been moved to azure/azure-cli [issue #29219](https://github.com/Azure/azure-cli/issues/29219). Please post any additional comments in the engineering GitHub issue.
