### ISSUE TITLE
Clarify the expected values for 'identity'

### ISSUE THREAD

**Issue by gabesmsft** [MicrosoftDocs/azure-docs-cli#4408]
### Type of issue

Missing information

### Feedback

For [az containerapp secret set](https://learn.microsoft.com/cli/azure/containerapp/secret?view=azure-cli-latest#az-containerapp-secret-set), need to clarify that when using a system-assigned managed identity, the value of 'identity' is system, as indicated in [this doc](https://learn.microsoft.com/azure/container-apps/manage-secrets?tabs=azure-cli#reference-secret-from-key-vault) ("for system assigned identity, use system instead of the resource ID").

Could we update the CLI doc to reflect this? E.g::
Change from the following...:
A list of secret(s) for the container app. Space-separated values in 'key=value' or 'key=keyvaultref:keyvaulturl,identityref:identity' format (where 'key' cannot be longer than 20 characters).

...to the following:
A list of secret(s) for the container app. Space-separated values in 'key=value' or 'key=keyvaultref:keyvaulturl,identityref:identity' format (where 'key' cannot be longer than 20 characters, and where 'identity' is either **system** or the resource id of the user-assigned managed identity).

### Page URL

https://learn.microsoft.com/en-us/cli/azure/containerapp/secret?view=azure-cli-latest#az-containerapp-secret-set

### Content source URL

https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/containerapp/secret.yml

### Author

@dbradish-microsoft

### Document Id

dc8c1147-dd84-6ef3-2744-63853b1a1d20

**Comment by PesalaPavan** [comment]
@gabesmsft 
Thanks for your feedback! I've assigned this issue to the author who will investigate and update as appropriate.

**Comment by dbradish-microsoft** [comment]
@gabesmsft , thank you for your feedback. This doc is autogenerated from source code, so I am moving this GitHub issue to Azure/azure-cli so the engineering team can respond.  Please see new GitHub issue [#29238](https://github.com/Azure/azure-cli/issues/29238).
