### ISSUE TITLE
Typo "a Azure"→""an Azure"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/azure-docs-cli#4412]
### Type of issue

Typo

### Feedback

https://learn.microsoft.com/en-us/cli/azure/pipelines?view=azure-cli-latest
#PingMSFTDocs

![image](https://github.com/MicrosoftDocs/azure-docs-cli/assets/40815708/ab69bdc1-c5f5-4bc7-89be-eff551581cbb)

![image](https://github.com/MicrosoftDocs/azure-docs-cli/assets/40815708/c97c8c0e-2604-49d3-b0aa-fa2ebdf76aa1)

### Page URL

https://learn.microsoft.com/en-us/cli/azure/pipelines?view=azure-cli-latest

### Content source URL

https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/pipelines.yml

### Author

@dbradish-microsoft

### Document Id

e79f2bc9-543d-9a14-a08c-911d037e108a

**Comment by PesalaPavan** [comment]
@hyoshioka0128 
Thanks for your feedback! I've assigned this issue to the author who will investigate and update as appropriate.

**Comment by dbradish-microsoft** [comment]
@hyoshioka0128, Thank you for bringing this typo to our attention. As all changes to this article need to be completed in Azure/azure-cli, I am moving this GitHub issue so the appropriate engineering team can respond.  Please see the new GitHub issue [#29239](https://github.com/Azure/azure-cli/issues/29239).
