### ISSUE TITLE
AppGW  rules command has priority rules but redirect-config doesnt have priority

### ISSUE THREAD

**Issue by xzrians** [MicrosoftDocs/azure-docs-cli#4421]
### Type of issue

Missing information

### Feedback

Hi. I saw in portal that you require priority to be set either backend pool and redirection.
but on Azure CLI command for redirect-config doesnt include --priority

![image](https://github.com/MicrosoftDocs/azure-docs-cli/assets/47202302/693ecf9f-14b0-4222-b473-d5dda7c76f67)
This command for rules
![image](https://github.com/MicrosoftDocs/azure-docs-cli/assets/47202302/96f319b7-03e8-4f32-b85e-bbed37968db6)
This is for redirect-config
![image](https://github.com/MicrosoftDocs/azure-docs-cli/assets/47202302/8c5076e2-9bbe-40b8-b5c0-f19ca0b9574e)

Error when you run with priority(due to there is no option to set --priority)
![image](https://github.com/MicrosoftDocs/azure-docs-cli/assets/47202302/60fe2b47-e8a2-405c-b2dd-ea1f97049354)

### Page URL

https://learn.microsoft.com/en-us/cli/azure/network/application-gateway/redirect-config?view=azure-cli-latest

### Content source URL

https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/network/application-gateway/redirect-config.yml

### Author

@dbradish-microsoft

### Document Id

1e7ce1d8-d680-0b93-d402-2b561587fcb4

**Comment by dbradish-microsoft** [comment]
@xzrians, Thank you for your taking the time to provide feedback, and add great screen prints (!). Unfortunately I am unable to make this change in this doc's repo, so I've moved your feedback to Azure/azure-cli [Issue #29255](https://github.com/Azure/azure-cli/issues/29255) where the engineering team can respond to it.
