### ISSUE TITLE
az functionapp config appsettings set does not work like documented

### ISSUE THREAD

**Issue by ulluoink** [MicrosoftDocs/azure-docs-cli#4425]
### Type of issue

Code doesn't work

### Feedback

https://learn.microsoft.com/en-us/cli/azure/functionapp/config/appsettings?view=azure-cli-latest#az-functionapp-config-appsettings-set

see example AND parameters description:

example: 
az functionapp config appsettings set --name MyFunctionApp --resource-group MyResourceGroup --settings foo=bar AzureWebJobsStorage=$storageConnectionString

Parameters description:
"--settings
Space-separated appsettings in KEY=VALUE format. Use @{file} to load from a file."

this is not true.

it does not work that way. the settings are just put in one Environmetnvariable like so:
wehn using the documented example:

Name: "foo"
Value: "bar AzureWebJobsStorage=$storageConnectionString"

### Page URL

https://learn.microsoft.com/en-us/cli/azure/functionapp/config/appsettings?view=azure-cli-latest#az-functionapp-config-appsettings-set

### Content source URL

https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/functionapp/config/appsettings.yml

### Author

@dbradish-microsoft

### Document Id

ad86610e-e20d-2c96-80fd-61c3d6e7f9ff

**Comment by dbradish-microsoft** [comment]
@ulluoink, Can you please look at [Quoting differences in scripting languages - Space-separated values](https://learn.microsoft.com/en-us/cli/azure/use-azure-cli-successfully-quoting?view=azure-cli-latest&tabs=bash1%2Cbash2#space-separated-values) and wrap your space-seperated values as suggested?
