### ISSUE TITLE
The optional parameter `--with-source` for `az bicep publish` is not in preview anymore.

### ISSUE THREAD

**Issue by Cezus** [MicrosoftDocs/azure-docs-cli#4437]
### Type of issue

Outdated article

### Feedback

The optional parameter `--with-source` for `az bicep publish` is not in preview anymore.

https://github.com/Azure/bicep/releases/tag/v0.27.1#:~:text=%22publishSource%22%20is%20now%20GA!

### Page URL

https://learn.microsoft.com/en-us//cli/azure/bicep?view=azure-cli-latest#az-bicep-publish-optional-parameters

### Content source URL

https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/bicep.yml

### Author

@dbradish-microsoft

### Document Id

60edc003-8f74-62af-e9fd-79efb5a77d9f

**Comment by TPavanBalaji** [comment]
@Cezus 
Thank you for bringing this to our attention.
I've delegated this to content author, who will review it and offer their insightful opinions.

**Comment by dbradish-microsoft** [comment]
@Cezus, I am moving this GitHub issue to the source code repo where it can be corrected by the bicep engineering team. Please continue to comment and followup in [Azure/azurecli issue #29337](https://github.com/Azure/azure-cli/issues/29337).
