### ISSUE TITLE
Add steps to install Azure CLI for Windows ARM based devices

### ISSUE THREAD

**Issue by Jiihaa** [MicrosoftDocs/azure-docs-cli#4439]
### Type of issue

Missing information

### Feedback

Now that Microsoft is selling Surface Laptop 7 with Windows ARM, please consider documenting how to install Az modules as they are very key on productivity for developers, as the current packages don't work.

### Page URL

https://learn.microsoft.com/en-us/cli/azure/install-azure-cli-windows?tabs=azure-cli

### Content source URL

https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/docs-ref-conceptual/install-azure-cli-windows.md

### Author

@jiasli

### Document Id

2fdd20ef-7bd3-57bc-7957-93f4bb5377ce

**Comment by TPavanBalaji** [comment]
@Jiihaa 
Thank you for bringing this to our attention.
I've delegated this to content author, who will review it and offer their insightful opinions.

**Comment by dbradish-microsoft** [comment]
@Jiihaa, What errors are you receiving? I have a Surface 7 and Surface Pro 9, and run Azure CLI locally on both. As you mentioned `az modules`, I'm wondering if you are thinking of [Azure PowerShell](https://learn.microsoft.com/en-us/powershell/scripting/install/installing-powershell?view=powershell-7.4)?  The Azure CLI has core commands and [extensions](https://learn.microsoft.com/en-us/cli/azure/azure-cli-extensions-list).

**Comment by dbradish-microsoft** [comment]
Thanks for your dedication to our documentation. As there has been no further discussion, we are closing this issue for now.
