### ISSUE TITLE
AZ CLI workaround section missing

### ISSUE THREAD

**Issue by bandwiches** [MicrosoftDocs/azure-docs-cli#4441]
### Type of issue

Missing information

### Feedback

AZ CLI refers to this document in one of its error messages, but the section does not exist.

```PowerShell
> az network bastion rdp --name "yyy" --resource-group "zzz" --target-resource-id "xxx" --configure

HTTPSConnectionPool(host='...bastion.azure.com', port=443): Max retries exceeded with url: ... '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)')))
Certificate verification failed. This typically happens when using Azure CLI behind a proxy that intercepts traffic with a self-signed certificate. Please add this certificate to the trusted CA bundle.

More info: https://docs.microsoft.com/cli/azure/use-cli-effectively#work-behind-a-proxy.
```

### Page URL

https://learn.microsoft.com/en-us/cli/azure/use-azure-cli-successfully-tips?tabs=bash%2Cbash2#work-behind-a-proxy.

### Content source URL

https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/docs-ref-conceptual/use-azure-cli-successfully-tips.md

### Author

@dbradish-microsoft

### Document Id

101838d8-0477-a82a-d390-c0bba6aa6076

**Comment by TPavanBalaji** [comment]
@bandwiches 
Thank you for bringing this to our attention.
I've delegated this to content author, who will review it and offer their insightful opinions.

**Comment by dbradish-microsoft** [comment]
@Bandwiches, We recently published a troubleshooting article that contains this information and we are in the process of updating links found in reference source code.  You can see this source code update in [Azure/azure-cli PR #29299](https://github.com/Azure/azure-cli/pull/29299) and the supporting conceptual doc change in [MicrosoftDocs/azure-docs-cli PR #4451](https://github.com/MicrosoftDocs/azure-docs-cli/pull/4451). Thank you for helping to make the Azure CLI documentation more accurate.
