### ISSUE TITLE
Soft-delete should not be appearing here

### ISSUE THREAD

**Issue by clmendes-MSFT** [MicrosoftDocs/azure-docs-cli#4447]
### Type of issue

Other (describe below)

### Feedback

--soft-delete should not yet being appearing as customers need to register for the feature and it is not yet in preview.

### Page URL

https://learn.microsoft.com/en-us/cli/azure/sig?view=azure-cli-latest#az-sig-create

### Content source URL

https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/sig.yml

### Author

@dbradish-microsoft

### Document Id

90421467-30f0-75b6-d171-02b8e37e7d07

**Comment by sandeepraichura** [comment]
We should hide this instead of removing it, as the feature is still in private preview.

**Comment by dbradish-microsoft** [comment]
@clmendes-MSFT, Can this GitHub issue be moved to the source code repo where it can be resolved?

**Comment by clmendes-MSFT** [comment]
@dbradish-microsoft  as long as we follow up on it, I'm 100% okay

**Comment by dbradish-microsoft** [comment]
@clmendes-MSFT, Unfortunately, I am unable to permanently update reference content in this repo, and this repo has GitHub issue SLAs that cannot wait for reference content release schedules, I've moved this GitHub issue to Azure/azure-cli [#29358](https://github.com/Azure/azure-cli/issues/29358) where it can receive the proper response from engineering. Kindly continue the discussion there. Thank you.
