### ISSUE TITLE
Warning about behavior of job start

### ISSUE THREAD

**Issue by fleed** [MicrosoftDocs/azure-docs-cli#4456]
### Type of issue

Missing information

### Feedback

The documentation should be enhanced by including a cautionary note regarding the start of a new job and overridden configuration. In particular, based on my examinations:

- Emphasize that options such as `--command`, `--args`, `--env-vars`, etc., are functional only when used in conjunction with `--image`
- Referring to the [documentation](https://learn.microsoft.com/en-us/azure/container-apps/jobs?tabs=azure-cli#start-a-job-execution-on-demand), note that *"When overriding the configuration, the job's entire template configuration is replaced with the new configuration. Ensure that the new configuration includes all required settings."*. Therefore, the statement *"Empty string to clear existing values"* on certain parameters may be misleading, as in my assessments, the environment variables specified by the container are cleared even in the absence of the `--env-vars` parameter.

### Page URL

https://learn.microsoft.com/en-us/cli/azure/containerapp/job?view=azure-cli-latest

### Content source URL

https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/containerapp/job.yml

### Author

@dbradish-microsoft

### Document Id

82b112a1-eba3-d9bd-072b-1cfda2403013

**Comment by dbradish-microsoft** [comment]
@fleed, Thank you for your feedback. Because this article's source is the reference command's in-line help, I am moving your feedback to Azure/azure-cli [GitHub issue #29356](https://github.com/Azure/azure-cli/issues/29356) so that the engineering team can respond and make the needed update. Please continue this discussion in the new location.
