### ISSUE TITLE
`az ml workspace create` is not working. Getting error- Missing dependent resources in workspace json

### ISSUE THREAD

**Issue by Aswinsb** [MicrosoftDocs/azure-docs-cli#4467]
### Type of issue

Code doesn't work

### Feedback

`az ml workspace create` is not working. When I tried this to create ml workspace, I am getting error. I am attaching screenshot. ![](https://i.imgur.com/3msM3XQ.png).

### Page URL

https://learn.microsoft.com/en-us/cli/azure/ml/workspace?view=azure-cli-latest

### Content source URL

https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/ml/workspace.yml

### Author

@dbradish-microsoft

### Document Id

a20a657c-aeaa-d122-0714-1aa2cfecd966

**Comment by sanpietro** [comment]
Hey @Naveenommi-MSFT, I am a Microsoft Technical Trainer and we are experiencing this issue across our course labs related to the DP-100 parent Azure ML course. Rather than opening up a separate issue for you folks, I'm happy to follow it here. Thanks, @Aswinsb for bringing this important issue to light. It is apparently a recurring issue and had been fixed up until this past week.

**Comment by Naveenommi-MSFT** [comment]
Hi @Aswinsb 
Thanks for reaching us. 
As Per Azure Documentaion, we need to declare all variables related to the ml workspace. 
<img width="451" alt="image" src="https://github.com/user-attachments/assets/82cef245-6dc7-45b8-ade8-a4c7a0713a8c">


Or we can clearly be mentioned in yaml file and then we can use this below command: **az ml workspace create --file workspace.yml --resource-group my-resource-group**

File schema ref: https://learn.microsoft.com/en-us/azure/machine-learning/reference-yaml-workspace?view=azureml-api-2

**Comment by Naveenommi-MSFT** [comment]
@Aswinsb 
We are going to close this thread as resolved but if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.

Thanks for your feedback and your contribution to Azure docs.
Feedback for this repository is moving away from GitHub to a system specific to the Microsoft Learn platform. Issues for this repository will soon be disabled, and additional comments from GitHub will no longer be possible. However, we are now tracking and triaging this issue in the new feedback system.
To learn more about our feedback systems, please see [Provide feedback for Microsoft Learn content](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2Fcontentuserfeedback&data=05%7C02%7Cv-ommikumar%40microsoft.com%7C2469fb0ee4e14243d7ff08dcaa6acfb0%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638572622992825118%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=kC5WOp10fV1oVhsLEFTHEzjLo6HeVUbxU%2Fe%2F5z8TTU8%3D&reserved=0).
