### ISSUE TITLE
fabric-name required but documentation says not required

### ISSUE THREAD

**Issue by mcdonamw** [MicrosoftDocs/azure-docs-cli#4470]
### Type of issue

Other (describe below)

### Feedback

Latest Az CLI documentation states that for `az site-recovery protectable-item show`,  `[--fabric-name]` is an optional field, but when attempt to run without it, I get an error citing that it is actually required.

![image](https://github.com/user-attachments/assets/08fb3cc5-b06d-4b80-a326-4a100a8ef080)
![image](https://github.com/user-attachments/assets/7569fb5f-d258-417c-91d7-25ca66eb2b5b)

### Page URL

https://learn.microsoft.com/en-us/cli/azure/site-recovery/protectable-item?view=azure-cli-latest

### Content source URL

https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/site-recovery/protectable-item.yml

### Author

@dbradish-microsoft

### Document Id

a9008605-3f2b-abe6-c84f-24d6f2714eb0

**Comment by TPavanBalaji** [comment]
@mcdonamw 
Thank you for bringing this to our attention.
I've delegated this to content author, who will review it and offer their insightful opinions.

**Comment by dbradish-microsoft** [comment]
@mcdonamw , I've moved your feedback to Azure\azure-cli issue [29459](https://github.com/Azure/azure-cli/issues/29459) which will cause this information to be routed to the `az site recovery` engineering team who can update the article contents. Kindly provide additional comments in the new issue.
