### ISSUE TITLE
Information related to certificate validation points to non-existent link 

### ISSUE THREAD

**Issue by fl1bbl3** [MicrosoftDocs/azure-docs-cli#4471]
### Type of issue

Missing information

### Feedback

The error message az cli provides when exhibiting CERTIFICATE_VERIFY_FAILED points you to this doc with a tag of work-behind-a-proxy, but this section has been removed. 

The original working information is available here https://web.archive.org/web/20230322203740/https:/learn.microsoft.com/en-us/cli/azure/use-cli-effectively?tabs=bash%2Cbash2

### Page URL

https://learn.microsoft.com/en-gb/cli/azure/use-azure-cli-successfully-tips?tabs=bash%2Cbash2#work-behind-a-proxy

### Content source URL

https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/docs-ref-conceptual/use-azure-cli-successfully-tips.md

### Author

@dbradish-microsoft

### Document Id

101838d8-0477-a82a-d390-c0bba6aa6076

**Comment by TPavanBalaji** [comment]
@fl1bbl3 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by TPavanBalaji** [comment]
@fl1bbl3 
Thank you for bringing this to our attention.
I've delegated this to content author, who will review it and offer their insightful opinions.

**Comment by dbradish-microsoft** [comment]
@fl1bbl3 , This issue has been fixed in PR [4451](https://github.com/MicrosoftDocs/azure-docs-cli/pull/4451). Thank you for your feedback.
