### ISSUE TITLE
No output example in documentation

### ISSUE THREAD

**Issue by ltouro** [MicrosoftDocs/azure-docs-cli#4475]
### Type of issue

Missing information

### Feedback

Articles like [this ](https://learn.microsoft.com/en-us/cli/azure/storage/queue?view=azure-cli-latest#az-storage-queue-list)shows all inputs but does not provide any example output, making it hard for developers to understand which information is provided by each command.

### Page URL

https://learn.microsoft.com/en-us/cli/azure/storage/queue?view=azure-cli-latest

### Content source URL

https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/storage/queue.yml

### Author

@dbradish-microsoft

### Document Id

95cdc341-ac11-4709-ee41-0323e07e8750

**Comment by ltouro** [comment]
[This ](https://commandmasters.com/commands/az-storage-queue-common/)article provides example output, which is useful to understand the capabilities of each endpoint. 

Notwithstanding, it would be better if output be documented the same way the paremeters (inputs), with an explanation of each attribute

**Comment by PesalaPavan** [comment]
@ltouro 
Thanks for your feedback! I've assigned this issue to the author who will investigate and update as appropriate.

**Comment by dbradish-microsoft** [comment]
@ltouro, I understand your viewpoint, and agree that output code blocks would be extrememly helpful. Right now, only some of our _conceptual docs_ have output, like you see in [Populate variables for use in scripts](https://learn.microsoft.com/en-us/cli/azure/get-started-tutorial-3-use-variables?view=azure-cli-latest&tabs=bash).

I've fowarded your feedback to the project manager for the Azure CLI, and although you might not see an immediate result, _your suggestion has impact_ and will be further considered. Please continue to send us suggestions that will help you to use the Azure CLI successfully.
