### ISSUE TITLE
Customer feedback | authenticate-azure-cli-service-principal | avoid displaying password in console

### ISSUE THREAD

**Issue by dbradish-microsoft** [MicrosoftDocs/azure-docs-cli#4488]
### Type of issue

Other (describe below)

### Feedback category
Alternative method

### Doc link:
https://learn.microsoft.com/cli/azure/authenticate-azure-cli-service-principal

### Customer verbatim:
"
> If you want to avoid displaying your password on console and are using az login interactively, use the read -s command under bash.

this is not enough as the password will still be displayed on the process table.
A suggested way to do that better would be to run the secret in a file, or a pipe fd, and do 
az login -p @<(echo $P)
which would prevent the password on the command line. 

A user following the documentation today will leak its password in the process table, visible in clear to every other logged-in user on the system. The password is also logged by Crowdstrike/Stackrox or other auditing tools.
"

### Page URL

https://learn.microsoft.com/en-us/cli/azure/authenticate-azure-cli-service-principal

### Content source URL

https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/docs-ref-conceptual/authenticate-azure-cli-service-principal.md

### Author

@dbradish-microsoft

### Document Id

da99513c-6137-108d-6a0f-d8cf495672c4

**Comment by TPavanBalaji** [comment]
@dbradish-microsoft 
Thank you for bringing this to our attention.
I've delegated this to content author, who will review it and offer their insightful opinions.

**Comment by dbradish-microsoft** [comment]
Signing into the Azure CLI using a password on the command line is not recommended.  It is best to use a certificate stored in Azure Key Vault.  If you must pass secrets in your code, there is a good discussion on StackOverflow with subject [How to get a password from a shell script without echoing](https://stackoverflow.com/questions/3980668/how-to-get-a-password-from-a-shell-script-without-echoing).
