### ISSUE TITLE
Customer feedback | get-started-tutorial-2-environment-syntax | missing prerequisite

### ISSUE THREAD

**Issue by dbradish-microsoft** [MicrosoftDocs/azure-docs-cli#4489]
### Type of issue

Missing information

### Artocle URL with H2 location
https://learn.microsoft.com/en-us/cli/azure/get-started-tutorial-2-environment-syntax?tabs=Bash#create-a-storage-account-to-apply-what-youve-learned

### Customer verbatim
"
There is a missing prerequisite missing for the Create Storage Account section. A valid provider for Microsoft.Storage must be registered prior to creating a storage account.
"

### Page URL

https://learn.microsoft.com/en-us/cli/azure/get-started-tutorial-2-environment-syntax?tabs=Bash

### Content source URL

https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/docs-ref-conceptual/get-started-tutorial-2-environment-syntax.md

### Author

@dbradish-microsoft

### Document Id

d2cf746e-7edf-05bb-f938-a8c531b60f27

**Comment by TPavanBalaji** [comment]
@dbradish-microsoft 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by dbradish-microsoft** [comment]
This is fixed in PR https://github.com/MicrosoftDocs/azure-docs-cli/pull/4490
