### ISSUE TITLE
az load test create | `--test-plan` does not work as expected

### ISSUE THREAD

**Issue by ademirmochi** [MicrosoftDocs/azure-docs-cli#4518]
### Type of issue

Code doesn't work

### Feedback

The documentation clearly states that in the command for: az load test-run create, we can use test-plan for setting up the JMX file and the engine-instances to set up the number of engines for the test run, however, in the azure CLI, latest version, which was 2.62.0 as of this writing, and the latest load extension, which is 1.0.1, it does not support said parameters, these are the documentation notes for the parameters:

az load test create --load-test-resource
                    --test-id
                    [--certificate]
                    [--description]
                    [--display-name]
                    [--engine-instances]
                    [--env]
                    [--keyvault-reference-id]
                    [--load-test-config-file]
                    [--no-wait]
                    [--resource-group]
                    [--secret]
                    [--split-csv]
                    [--subnet-id]
                    [--test-plan]
                    
This is the response from az load test create --help

Command
    az load test-run create : Create a new load test run.
        Create a new load test run for a given test. If an existing test run is specified, then the
        test run will be rerun. By default this command will wait for the test run to complete. Use
        --no-wait to skip this wait.
        Command group 'load test-run' is in preview and under development. Reference and
        support levels: https://aka.ms/CLI_refstatus

Arguments
    --load-test-resource --name -n [Required] : Name or ARM resource ID of the Load Testing
                                                resource.
    --test-id -t                   [Required] : Test ID of the load test.
    --test-run-id -r               [Required] : Test run ID of the load test run.
    --certificate                             : A single certificate in 'key[=value]' format. The
                                                certificate should be stored in Azure Key Vault in
                                                PFX format, and the certificate identifier should be
                                                provided as the value.Use "" to clear existing
                                                certificate.
    --description                             : Description of the load test run.
    --display-name                            : Display name of the load test run.
    --env                                     : Space-separated environment variables: key[=value]
                                                [key[=value] ...]. Use "" to clear existing
                                                environment variables.
    --existing-test-run-id                    : Test run ID of an existing load test run which
                                                should be rerun.
    --no-wait                                 : Do not wait for the long-running operation to
                                                finish.
    --resource-group -g                       : Name of resource group. You can configure the
                                                default group using `az configure --defaults
                                                group=<name>`.
    --secret                                  : Space-separated secrets: key[=value] [key[=value]
                                                ...]. Secrets should be stored in Azure Key Vault,
                                                and the secret identifier should be provided as the
                                                value.Use "" to clear existing secrets.
                                                
                                                
 I tried using in various ways as it is described in the documentation online, however, it won't work, why?

### Page URL

https://learn.microsoft.com/en-us/cli/azure/load/test?view=azure-cli-latest

### Content source URL

https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/load/test.yml

### Author

@dbradish-microsoft

### Document Id

ea435ca4-b971-aa3c-0781-dfab3a3365e5

**Comment by TPavanBalaji** [comment]
@ademirmochi 
Thank you for bringing this to our attention.
I've delegated this to content author, who will review it and offer their insightful opinions.

**Comment by dbradish-microsoft** [comment]
@ademirmochi, Can you please provide more error information?  If you run the Azure CLI reference command with the [--debug](https://learn.microsoft.com/en-us/cli/azure/use-azure-cli-successfully-troubleshooting?view=azure-cli-latest#the---debug-parameter) parameter, we'll be able to better understand what's happening.

**Comment by dbradish-microsoft** [comment]
Hello, @ademirmochi, as we haven't heard back from you in a couple of weeks, I'm closing this GitHub issue.  If you can supply the `--debug` output of your command, we can revisit your feedback.
