### ISSUE TITLE
Service Principal in Azure cannot create DevBox in azure portals

### ISSUE THREAD

**Issue by dasra** [MicrosoftDocs/azure-docs-cli#4519]
### Type of issue

Missing information

### Feedback

service principal account cannot use az cli to create a devbox. ERROR: (DevBoxCreationByApplicationNotSupported) Dev Box creation is only supported for users. anyone have any solution to this my code is using az cli commands and the service principal is owner for the subscription.

az login --service-principal -u $ACCESS_KEY -p $SECRET_KEY --tenant var{tenant_id}
# Check if Dev Box exists
DEV_BOX_EXISTS=$(az devcenter dev dev-box list --dev-center-name $DEV_CENTER_NAME --query "[?name=='$DEV_BOX_NAME'] | length(@)")
# Create Dev Box
if [ "$DEV_BOX_EXISTS" -eq 0 ]; then
    echo "Dev Box $DEV_BOX_NAME does not exist. Creating Dev Box..."
    az devcenter dev dev-box create  \
  --pool-name $POOL_NAME \
  --name $DEV_BOX_NAME \
  --dev-center-name $DEV_CENTER_NAME \
  --project-name $PROJECT_NAME 

### Page URL

https://learn.microsoft.com/en-us/cli/azure/service-page/microsoft%20dev%20box%20and%20azure%20deployment%20environments?view=azure-cli-latest

### Content source URL

https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/service-page/Microsoft Dev Box and Azure Deployment Environments.yml

### Author

@dbradish-microsoft

### Document Id

4db6c891-eb21-daed-0904-965e9d765e97

**Comment by TPavanBalaji** [comment]
@dasra 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by dbradish-microsoft** [comment]
Hello, @dasra. The [service principal object](https://learn.microsoft.com/en-us/entra/identity-platform/app-objects-and-service-principals?tabs=browser#service-principal-object) is intended for resource access. In looking at the prerequisites in [Quickstart: Create and connect to a dev box by using the Microsoft Dev Box developer portal](https://learn.microsoft.com/en-us/azure/dev-box/quickstart-create-dev-box#prerequisites), "You must have permissions as a [Dev Box User](https://learn.microsoft.com/en-us/azure/dev-box/quickstart-configure-dev-box-service#provide-access-to-a-dev-box-project) for a project that has an available dev box pool."

**Comment by dbradish-microsoft** [comment]
@dasra, One more follow-up. I reached out to the author of [Spin up a new dev box](https://learn.microsoft.com/en-us/azure/dev-box/quickstart-create-dev-box) and she said "Dev Box doesn't support using a Service Principal to create multiple dev boxes through scripting". 

If you want to make a product improvement suggestion directly to the DevBox engineering team, you can create a [feature request](https://github.com/Azure/azure-cli/issues/new?assignees=&labels=&projects=&template=Feature_request.md&title=).
