### ISSUE TITLE
Missing Premium SKU reference

### ISSUE THREAD

**Issue by johnwildes** [MicrosoftDocs/azure-docs-cli#4521]
### Type of issue

Missing information

### Feedback

The `--sku` selection reference for this extension only shows `Basic`, and `Standard` as the only values.  `Premium` should also be a value.  
It shows in the lastet revision of code as an acceptable value.   

`https://github.com/Azure/azure-cli-extensions/blob/5a62f9ad1f8120fa9c054babc3a131439f930226/src/bastion/azext_bastion/BastionServiceConstants.py#L14`

### Page URL

https://learn.microsoft.com/en-us/cli/azure/network/bastion?view=azure-cli-latest

### Content source URL

https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/network/bastion.yml

### Author

@dbradish-microsoft

### Document Id

399a501c-b96d-8867-078f-73dd9b8b3da2

**Comment by TPavanBalaji** [comment]
@johnwildes 
Thanks for your feedback! We will investigate and update as appropriate.
