### ISSUE TITLE
Provide alternative way without email ID as input for fetching the azure user object ID

### ISSUE THREAD

**Issue by praharshith** [MicrosoftDocs/azure-docs-cli#4547]
### Type of issue

Missing information

### Feedback

We were able to fetch the azure user object ID by logging in with service principal and then using the user email id we were able to fetch the user object ID. below is the sample commands used.

az login --service-principal -u clientID -p clientsecret --tenant tenantID

az ad user show --id **emailID** --query id --output tsv

We do not want to prompt the email ID for our application, is there any other way through which we can fetch the user object without providing the email ID? we would like to know how the other applications are authenticating the users Azure AD group membership without any email ID prompt.

Note: The main goal is to authenticate the end user whether he/she is a member of a Azure AD group or not, for this we need the Azure user Object ID

### Page URL

https://learn.microsoft.com/en-us/cli/azure/authenticate-azure-cli

### Content source URL

https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/docs-ref-conceptual/authenticate-azure-cli.md

### Author

@jiasli

### Document Id

1155045b-ce8c-2def-7b0e-043283f8be01

**Comment by TPavanBalaji** [comment]
@praharshith 
Thank you for bringing this to our attention.
I've delegated this to content author, who will review it and offer their insightful opinions.

**Comment by dbradish-microsoft** [comment]
@praharshith, The output for `show` has these properties:

```output
{
  "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#users/$entity",
  "businessPhones": [],
  "displayName": "myDisplayName",
  "givenName": "myGivenName",
  "id": "000000...00000",
  "jobTitle": "",
  "mail": "myName@contoso.com",
  "mobilePhone": null,
  "officeLocation": "Home Office",
  "preferredLanguage": null,
  "surname": "mySurname",
  "userPrincipalName": "myName@contoso.com"
}
```

The `--id` parameter of the `az ad user show` command currently accepts these values:
* id
* userPrincipalName

What unique property of an authenticated Azure user do you want to use? If you have a suggestion for improvement, please create a [new feature request](https://github.com/Azure/azure-cli/issues/new?assignees=&labels=&projects=&template=Feature_request.md&title=).

**Comment by dbradish-microsoft** [comment]
Thanks for your dedication to our documentation. As there has been no further discussion, we are closing this issue for now.
