### ISSUE TITLE
Cannot specify both -n and -s or -d in create policy command.

### ISSUE THREAD

**Issue by harrchen88** [MicrosoftDocs/azure-docs-cli#4551]
### Type of issue

Code doesn't work

### Feedback

This command (following the example from the documentation) doesn't work:
az storage account or-policy create -g rgadflab -n harrchenmsdnsasource1 -d harrchenmsdnsatarget1 -s harrchenmsdnsasource1 --destinatio
n-container targetor1 --source-container sourceor1
It produces the error below:
ValueError: Please specify --policy-id with auto-generated policy id value on destination account.

However, if I remove the -d parameter, it works, the working command:
az storage account or-policy create -g rgadflab -n harrchenmsdnsatarget1 -s harrchenmsdnsasource1 --destination-container targetor1 --s
ource-container sourceor1

### Page URL

https://learn.microsoft.com/en-us/cli/azure/storage/account/or-policy?view=azure-cli-latest

### Content source URL

https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/storage/account/or-policy.yml

### Author

@dbradish-microsoft

### Document Id

c82c8430-4981-bf90-548f-3e975d7f8878

**Comment by TPavanBalaji** [comment]
@harrchen88 
Thank you for bringing this to our attention.
I've delegated this to content author, who will review it and offer their insightful opinions.

**Comment by dbradish-microsoft** [comment]
[harrchen88](https://github.com/harrchen88), can you please attached the output from running your command with the `--debug` parameter?  You can read more about debugging in [Troubleshooting Azure CLI](https://learn.microsoft.com/en-us/cli/azure/use-azure-cli-successfully-troubleshooting#the---debug-parameter)

**Comment by dbradish-microsoft** [comment]
Thanks for your dedication to our documentation. As there has been no further discussion, we are closing this issue for now. If  you feel that it's still a concern, please respond and let us know.
