### ISSUE TITLE
Hi, can you please explicitly address on the Documentation that EXR or VPN GW should not be longer than 64 caracters!

### ISSUE THREAD

**Issue by PabloG-MSsupport** [MicrosoftDocs/azure-docs-cli#4564]
### Type of issue

Other (describe below)

### Feedback

HI, I recently file an ICM to address an issue in which a EXR GW on a VHUB was going along with it`s connections to a Failed Status: https://portal.microsofticm.com/imp/v5/incidents/details/533601064/summary

The product group confirmed that a name larger than that will cause several issues on the backend, and will lead to the GW and it`s connections to a failed status. 

Can you please indicate on the command "az network express-route gateway create" that as NOTE name shouldnt be larger than 64 caracters? 

### Page URL

https://learn.microsoft.com/en-us/cli/azure/network/express-route/gateway?view=azure-cli-latest#az-network-express-route-gateway-create

### Content source URL

https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/network/express-route/gateway.yml

### Author

@dbradish-microsoft

### Document Id

1af51475-88d9-aed7-04c9-9782c5018833

**Comment by dbradish-microsoft** [comment]
@PabloG-MSsupport, **good suggestion**!  I'm moving this request to Azure/azure-cli repo where the engineering team can respond. The content in MicrosoftDocs/azure-docs-cli is autogenerated from Azure CLI source code, so this comment will need to be made at the source.  Please see the new GitHub issue [29762](https://github.com/Azure/azure-cli/issues/29762) and make any additional comments there.
