### ISSUE TITLE
az artifacts universal command does not work

### ISSUE THREAD

**Issue by sambroy** [MicrosoftDocs/azure-docs-cli#4583]
### Type of issue

Typo

### Feedback

This is what I get when I run the command. 
```
$ az artifacts universal
'artifacts' is misspelled or not recognized by the system.

Examples from AI knowledge base:
az extension add --name anextension
Add extension by name

https://docs.microsoft.com/en-US/cli/azure/extension#az_extension_add
Read more about the command in reference docs
```

### Page URL

https://learn.microsoft.com/en-us/cli/azure/artifacts?view=azure-cli-latest

### Content source URL

https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/artifacts.yml

### Author

@dbradish-microsoft

### Document Id

17c90c22-ff22-487a-5c33-ce4ef92d38f4

**Comment by dbradish-microsoft** [comment]
@sambroy, you were not prompted to install the extension as shown here?
![image](https://github.com/user-attachments/assets/df46bb8b-d391-4a21-a545-0f5c4c3e046c)

Can you please try to install the extension manually?
```
az extension add --name "azure-devops"
```

**Comment by sambroy** [comment]
Hi @dbradish-microsoft No, I was not prompted to install the extension. 

This is what I see when I install the extension: 
```
$ az extension add --name "azure-devops"
Default enabled including preview versions for extension installation now. Disabled in May 2024. Use '--allow-preview true' to enable it specifically if needed. Use '--allow-preview false' to install stable version only.
```

and then 
```
$ az artifacts universal
the following arguments are required: _subcommand

Examples from AI knowledge base:
https://aka.ms/cli_ref
Read more about the command in reference docs
```

**Comment by dbradish-microsoft** [comment]
@sambroy, all Azure CLI reference commands that are not "core" belong to an extension. You can see the extension name at the top of the reference page

https://learn.microsoft.com/en-us/cli/azure/artifacts
![image](https://github.com/user-attachments/assets/b2bb1407-4789-4928-8d34-eaeb208f7924)

In your screen print, `az artifacts universal` is a command subgroup.  You need to specify a command with any required parameters.  
![image](https://github.com/user-attachments/assets/28a934ca-a00a-4124-9dd4-7dcf8e94b9bf)

For an overview of Azure CLI command syntax, please see [Azure CLI terminology and support levels](https://learn.microsoft.com/en-us/cli/azure/reference-types-and-status?view=azure-cli-latest).

**Comment by dbradish-microsoft** [comment]
This PR is being closed as the customer feedback has been answered.
