### ISSUE TITLE
CLI example incorrect

### ISSUE THREAD

**Issue by linkhuo-fha** [MicrosoftDocs/azure-docs-cli#4596]
### Type of issue

Typo

### Feedback

The example in this document is incorrect. There should be a "/" in front of the "subscriptions/SubID..."
`az aks create -g MyResourceGroup -n MyMC --kubernetes-version 1.20.9 --node-vm-size VMSize --assign-identity "subscriptions/SubID/resourceGroups/RGName/providers/Microsoft.ManagedIdentity/userAssignedIdentities/myID" --enable-managed-identity --crg-id "subscriptions/SubID/resourceGroups/RGName/providers/Microsoft.ContainerService/CapacityReservationGroups/MyCRGID"`

### Page URL

https://learn.microsoft.com/en-us/cli/azure/aks?view=azure-cli-latest

### Content source URL

https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/aks.yml

### Author

@dbradish-microsoft

### Document Id

75b0c352-762e-16ae-5cc6-d807ffc1dc3f

**Comment by dbradish-microsoft** [comment]
@linkhuo-fha, Thank you for bringing this to our attention. I'm moving your feedback to Azure/azure-cli where the engineering team can respond and make the needed update. (This code block example comes from source code.)  Please see new GitHub issue [29842](https://github.com/Azure/azure-cli/issues/29842) and make additional comments there.
