### ISSUE TITLE
List Deployed OpenAI models

### ISSUE THREAD

**Issue by mwarqee** [MicrosoftDocs/azure-docs-cli#4600]
### Type of issue

Other (describe below)

### Feedback

I find the information for the command a bit misleading, since the command:

`az cognitiveservices account list-models -n NAME -g RG` lists the AVAILABLE open ai models, and not the deployed models for the specific resource as it would be expected.

It would be far more useful if this command would also have a flag for deployed models only, and would work on subcription level - i.e. I want to see all OpenAI endpoints and their respective deployed models in subscription 99999999999999999.

Is this on the roadmap?

### Page URL

https://learn.microsoft.com/en-us/cli/azure/cognitiveservices/account?view=azure-cli-latest#az-cognitiveservices-account-list

### Content source URL

https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/cognitiveservices/account.yml

### Author

@dbradish-microsoft

### Document Id

baffbf17-2f5d-44a6-de77-7ecb320f35ed

**Comment by ManoharLakkoju-MSFT** [comment]
@mwarqee 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by dbradish-microsoft** [comment]
Hello @mwarqee. I have moved your feedback to Azure/azure-cli where the engineering team can respond.  Please see new GitHub issue [29883](https://github.com/Azure/azure-cli/issues/29883) and continue the discussion there. Thank you.
