### ISSUE TITLE
my powershell does not recognize the AZ cmedlets, help please

### ISSUE THREAD

**Issue by hossamhussein6055** [MicrosoftDocs/azure-docs-cli#4612]
### Type of issue

Code doesn't work

### Feedback

PS C: \WINDOWS\system32> az ad user update -- id hunkyhouse0260@gmail.com -- display-name hossam. hussein@andalusia. innovatio
net
az : The term 'az' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the
spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ az ad user update -- id hunkyhouse0260@gmail.com -- display-name hossam

+ CategoryInfo
+ FullyQualifiedErrorId : CommandNotFoundException

PS C:\WINDOWS\system32>

..

: ObjectNotFound: (az:String) [], CommandNotFoundException

### Page URL

https://learn.microsoft.com/en-us/cli/azure/ad/user?view=azure-cli-latest#code-try-9

### Content source URL

https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/ad/user.yml

### Author

@dbradish-microsoft

### Document Id

39842113-e499-d863-0f61-795089d844d9

**Comment by dbradish-microsoft** [comment]
Hello, @hossamhussein6055. This reference group is part of our Core components, so I'm wondering if you are running into a PowerShell scripting language issue. Please take a look at [Considerations for running the Azure CLI in a PowerShell scripting language](https://learn.microsoft.com/en-us/cli/azure/use-azure-cli-successfully-powershell?view=azure-cli-latest&tabs=read%2CBash1%2CBash2).

I also suggest running `az ad user update` with the `--debug` parameter. This will expose the API calls and parameter values as parsed by the PowerShell tool.

**Comment by dbradish-microsoft** [comment]
@hossamhussein6055, were you able to get the `az ad user update` reference command working? What did you do to handle the error message? (I'd like to add information to our [troubleshooting guide](https://learn.microsoft.com/en-us/cli/azure/use-azure-cli-successfully-troubleshooting?view=azure-cli-latest) if needed.)

**Comment by dbradish-microsoft** [comment]
Thanks for your dedication to our documentation. If  you feel that it's still a concern, please respond and let us know.
