### ISSUE TITLE
az image copy --cleanup needs a better warning

### ISSUE THREAD

**Issue by marweet** [MicrosoftDocs/azure-docs-cli#4619]
### Type of issue

Missing information

### Feedback

if you use az image copy with the "--cleanup" and "--temporary-resource-group-name" parameters and reference an existing resource group, that resource group and all of its content will be deleted. 

I guess a note of warning would be nice.

### Page URL

https://learn.microsoft.com/en-us/cli/azure/image?view=azure-cli-latest

### Content source URL

https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/image.yml

### Author

@dbradish-microsoft

### Document Id

2a24cd5b-8798-a175-5bde-7d2850bf9015

**Comment by dbradish-microsoft** [comment]
@marweet, I appreciate your suggestion, and am going to pass your comment to the engineering team for `az image`. To do this, I need to move your feedback to Azure/azure-cli. Please see new GitHub issue [29918](https://github.com/Azure/azure-cli/issues/29918) and continue the conversation there.
