### ISSUE TITLE
az stack sub validate -- Validate how?

### ISSUE THREAD

**Issue by mrkesu** [MicrosoftDocs/azure-docs-cli#4639]
### Type of issue

Missing information

### Feedback

https://learn.microsoft.com/en-us/cli/azure/stack/sub?view=azure-cli-latest#az-stack-sub-validate

Here it says "Validate a deployment stack at subscription scope.", which sounds nice, but what are you validating? I don't understand what this command is doing at all.

If I change something in my bicep file or parameter file it just says "looks cool 👍" with a list of "validatedResources" (including resources that don't exist yet or that I modified)

_I had hoped it would give me a list of what would change (but sadly, this doesn't seem to exist at all for deployment stacks?)..._

### Page URL

https://learn.microsoft.com/en-us/cli/azure/stack/sub?view=azure-cli-latest

### Content source URL

https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/stack/sub.yml

### Author

@dbradish-microsoft

### Document Id

7fcc1262-84b2-dcba-975b-f59ebd5b67e7

**Comment by ManoharLakkoju-MSFT** [comment]
@mrkesu 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by dbradish-microsoft** [comment]
@sijuman, @sarathys, @bganapa, @rakku-ms, Can you please answer the customer's question and provide more detail on the `az stack sub validate` command?

**Comment by dbradish-microsoft** [comment]
Please continue the conversation with the `az stack` engineering team in Azure/azure-cli GitHub issue [30019](https://github.com/Azure/azure-cli/issues/30019).
