### ISSUE TITLE
`az apim api import` - What are the options for `--soap-api-type`?

### ISSUE THREAD

**Issue by QuickScoP3s** [MicrosoftDocs/azure-docs-cli#4645]
### Type of issue

Missing information

### Feedback

As the title says, it's unclear from the CLI documentation which values(s) are expected for the parameter `--soap-api-type`.
It's definitely not a boolean flag, because I get this error:
```
ERROR: argument --soap-api-type: expected one argument
```

Anywhere else I could find what is the options are?

### Page URL

https://learn.microsoft.com/en-us/cli/azure/apim/api?view=azure-cli-latest

### Content source URL

https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/apim/api.yml

### Author

@dbradish-microsoft

### Document Id

d1a421eb-807c-c0bd-cee3-a5aed7335625

**Comment by TPavanBalaji** [comment]
@QuickScoP3s 
Thank you for bringing this to our attention.
I've delegated this to content author, who will review it and offer their insightful opinions.

**Comment by dbradish-microsoft** [comment]
@QuickScoP3s , I've copied your question to Azure/azure-cli issue [30082](https://github.com/Azure/azure-cli/issues/30082) where the engineering team for `az apim api` can respond. Please continue to follow the discussion in this new location. Thank you.
