### ISSUE TITLE
the version information in LTS version Table is not correct

### ISSUE THREAD

**Issue by yiwasaki** [MicrosoftDocs/azure-docs-cli#4646]
### Type of issue

Missing information

### Feedback

From below diagram, the LTS version is v2.66.x and v2.78.x.
![image](https://github.com/user-attachments/assets/47d5989c-08d7-4f33-935f-6f5caee1b6fd)

But, this table on same document, it seems that LTS version is v2.79.x
![image](https://github.com/user-attachments/assets/ff92983a-6a63-4b8f-9e11-51890ce66913)

I guess that the table is incorrect. would you, please, confirm and fix this information? 

### Page URL

https://learn.microsoft.com/en-us/cli/azure/azure-cli-support-lifecycle

### Content source URL

https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/docs-ref-conceptual/azure-cli-support-lifecycle.md

### Author

@dbradish-microsoft

### Document Id

3235c619-d901-d6f7-fc2e-f9c443e29cc2

**Comment by dbradish-microsoft** [comment]
@yiwasaki, Thank you for bringing this to our attention. I'm taking a look and will update as needed.

**Comment by dbradish-microsoft** [comment]
This issue is fixed in PR [4699](https://github.com/MicrosoftDocs/azure-docs-cli/pull/4699).
