### ISSUE TITLE
"Tips for using the Azure CLI successfully" script examples are written in CMD, not BASH

### ISSUE THREAD

**Issue by fsilvani92** [MicrosoftDocs/azure-docs-cli#4647]
### Type of issue

Typo

### Feedback

On the page "Tips for using the Azure CLI successfully" under "Script Examples" there are 2 examples with tabs called "Bash" and "PowerShell". However, the examples provided for "Bash" are written with cmd commands. 

In short, the following lines
https://github.com/MicrosoftDocs/azure-docs-cli/blob/f21ee674f2326fc5c3f24cfff80ed1dd1fc61f3d/docs-ref-conceptual/use-azure-cli-successfully-tips.md?plain=1#L180
https://github.com/MicrosoftDocs/azure-docs-cli/blob/f21ee674f2326fc5c3f24cfff80ed1dd1fc61f3d/docs-ref-conceptual/use-azure-cli-successfully-tips.md?plain=1#L204

should be the same as

https://github.com/MicrosoftDocs/azure-docs-cli/blob/f21ee674f2326fc5c3f24cfff80ed1dd1fc61f3d/docs-ref-conceptual/use-azure-cli-successfully-tips.md?plain=1#L142

### Page URL

https://learn.microsoft.com/en-us/cli/azure/use-azure-cli-successfully-tips?tabs=bash%2Cbash2

### Content source URL

https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/docs-ref-conceptual/use-azure-cli-successfully-tips.md

### Author

@dbradish-microsoft

### Document Id

101838d8-0477-a82a-d390-c0bba6aa6076

**Comment by dbradish-microsoft** [comment]
@fsilvani92, Thank you for your feedback. I tested those scripts and they need to be refreshed as well as placed on the correct conceptual tab, so you are correct. We appreciate your helping us to improve Azure CLI documents. I'll follow up on this GitHub issue once this has been corrected.

**Comment by dbradish-microsoft** [comment]
This issue has been corrected in PR [4693](https://github.com/MicrosoftDocs/azure-docs-cli/pull/4693).
