### ISSUE TITLE
service principal is no longer the default identity type

### ISSUE THREAD

**Issue by bessalahAmar** [MicrosoftDocs/azure-docs-cli#4659]
### Type of issue

Outdated article

### Feedback

regarding the parameter "--service-principal" the doc says that "If not specified, a new service principal is created and cached at $HOME/.azure/aksServicePrincipal.json to be used by subsequent az aks commands."

this is no longer the case if we create an aks cluster without specifying the parameter  "--service-principal" it will use system managed identity instead of creating a SP and make cluster use it.

![image](https://github.com/user-attachments/assets/1764ca27-8b84-4b6f-be3b-fd254784c866)

### Page URL

https://learn.microsoft.com/en-us/cli/azure/aks?view=azure-cli-latest

### Content source URL

https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/aks.yml

### Author

@dbradish-microsoft

### Document Id

75b0c352-762e-16ae-5cc6-d807ffc1dc3f

**Comment by PesalaPavan** [comment]
@bessalahAmar 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by PesalaPavan** [comment]
@bessalahAmar 
Thanks for your feedback! I've assigned this issue to the author who will investigate and update as appropriate.

**Comment by dbradish-microsoft** [comment]
Hello, @bessalahAmar. 

Service principals can be `application` or `managed identity` as described in [Service principal object](https://learn.microsoft.com/en-us/entra/identity-platform/app-objects-and-service-principals?tabs=browser#service-principal-object), and a [system assigned managed identity](https://learn.microsoft.com/en-us/entra/identity/managed-identities-azure-resources/overview#managed-identity-types) is a service principal of a special type.

This can be somewhat confusing!  Therefore, I've moved your feedback to Azure/azure-cli GitHub issue [#30056](https://github.com/Azure/azure-cli/issues/30056), and have requested the engineering team to provide additional information in the `--service-principal` parameter description.
