### ISSUE TITLE
Azure CLI is not Azure Cloud

### ISSUE THREAD

**Issue by skrabbe001** [MicrosoftDocs/azure-docs-cli#4664]
### Type of issue

Other (describe below)

### Feedback

When documenting Azure CLI you MUST separate the cloud based from the local command based stuff.

That means that the first authentication method is NOT Azure CLI - it is Azure Cloud:

>Azure Cloud Shell - Azure Cloud Shell automatically logs you in and is the easiest way to get started.

Almost all of your documentation confuses the two methods of doing stuff, ie locally (az) vs using the cloud (browser + powershell syntax).

What I do not understand, is why you can not implement the same syntax for both cloud and local usage AND why you in most articles refer to the the cloud based (Azure Cloud Powershell) as Azure CLI - it makes it extremely time consuming to find the right article OR to figure out which `Azuyre CLI az` command that corresponds with which `Azure Cloud PowerShell` command.

As I see it, your entire documentation needs a rewrite.

### Page URL

https://learn.microsoft.com/en-us/cli/azure/authenticate-azure-cli

### Content source URL

https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/docs-ref-conceptual/authenticate-azure-cli.md

### Author

@dbradish-microsoft

### Document Id

1155045b-ce8c-2def-7b0e-043283f8be01

**Comment by skrabbe001** [comment]
If you look at this page, it lists some of the commands. We need a page containing all commands for all extensions:

https://learn.microsoft.com/en-us/cli/azure/choose-the-right-azure-command-line-tool

**Comment by dbradish-microsoft** [comment]
Hello @skrabbe001. I hear your frustration.  The Azure CLI can be run in many environments / scripting languages. This impacts [installation](https://learn.microsoft.com/en-us/cli/azure/install-azure-cli?view=azure-cli-latest), [authentication method](https://learn.microsoft.com/en-us/cli/azure/authenticate-azure-cli?view=azure-cli-latest) and [syntax of Azure CLI parameter values](https://learn.microsoft.com/en-us/cli/azure/use-azure-cli-successfully-quoting?view=azure-cli-latest&tabs=bash1%2Cbash2%2Cbash3).

This can be especially challenging for PowerShell users as PowerShell is both an [app](https://learn.microsoft.com/en-us/powershell/), and as you know, hosts the [Azure PowerShell](https://learn.microsoft.com/en-us/powershell/azure/?view=azps-12.3.0) tool. 

I would like to provide you with a 1:1 comparison between the Azure CLI and Azure PowerShell as you requested. In fact, this is something I've talked about with the Azure PowerShell doc's lead and project manager.  However, we don't have anything to share with you at this moment.

If you haven't already, please consider the tutorial [Learn to use the Azure CLI](https://learn.microsoft.com/en-us/cli/azure/get-started-tutorial-0-before-you-begin?view=azure-cli-latest).

Kindly,

@dbradish-microsoft

**Comment by dbradish-microsoft** [comment]
Hello, @skrabbe001, I haven't heard from you in a couple of days.

1. Can you kindly provide me with an article link that `refer to the the cloud based (Azure Cloud Powershell) as Azure CLI`?
1. Were you able to review the [Learn the Azure CLI](https://learn.microsoft.com/en-us/cli/azure/get-started-tutorial-0-before-you-begin?view=azure-cli-latest) article, specifically [step 3](https://learn.microsoft.com/en-us/cli/azure/get-started-tutorial-2-environment-syntax?view=azure-cli-latest&tabs=Bash) that talks about syntax differences between Cmd, Bash and PowerShell environments?

**Comment by dbradish-microsoft** [comment]
I am closing this GitHub request as a reply has been supplied by Microsoft. For additional discussion, you can continue to add comments to this issue thread.
