### ISSUE TITLE
Updating nginx document from cli-extension

### ISSUE THREAD

**Issue by zaowang-ms** [MicrosoftDocs/azure-docs-cli#4676]
### Prerequisites

- [X] Write a descriptive title.
- [X] Search the existing issues.

### Summary of the new feature or changed behavior

Hi folks,

Our team would like to update a text here in this [document](https://github.com/MicrosoftDocs/azure-docs-cli/blob/40613f083e49261c01561a3308b947a33d43b402/latest/docs-ref-autogen/nginx/deployment.yml) (Specifically, change `standard_Monthly`  to `standardv2_Monthly`).
From the readme looks like it's based on [azure/azure-cli](https://github.com/azure/azure-cli) automatically. But we didn't see the change even though we've updated our notes [here](https://github.com/Azure/azure-cli-extensions/blob/main/src/nginx/azext_nginx/aaz/latest/nginx/deployment/_create.py) in the azure-cli-extensions (no related code piece found for our nginx service in azure-cli repo.
Is it because we update them in a wrong place, or we need to trigger the document generate somehow?
Thanks in advance for any help!

### List of articles that need to be updated

https://github.com/MicrosoftDocs/azure-docs-cli/blob/40613f083e49261c01561a3308b947a33d43b402/latest/docs-ref-autogen/nginx/deployment.yml

### Link to related PR in Azure/azure-cli repo

None because of it's auto one

### Link to related Issues in Azure/azure-cli repo

None

**Comment by dbradish-microsoft** [comment]
Hello, @zaowant-ms. Please see the conversation I've started with you in Teams.
