### ISSUE TITLE
Mustafacco

### ISSUE THREAD

**Issue by mustafacco7** [MicrosoftDocs/azure-docs-cli#4694]
### Type of issue

Typo

### Feedback

#

### Page URL

https://learn.microsoft.com/en-us/cli/azure/ad/user?view=azure-cli-latest#az-ad-user-get-member-groups

### Content source URL

https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/ad/user.yml

### Author

@dbradish-microsoft

### Document Id

39842113-e499-d863-0f61-795089d844d9

**Comment by dbradish-microsoft** [comment]
Hello, @mustafacco7, I see your PR [9696](https://github.com/MicrosoftDocs/azure-docs-cli/pull/4696) and I've replied there.

**Comment by jiasli** [comment]
Spam.
