### ISSUE TITLE
Missing schema for artifacts file format

### ISSUE THREAD

**Issue by cnovel** [MicrosoftDocs/azure-docs-cli#4701]
### Type of issue

Missing information

### Feedback

When using `az lab vm` commands, it's possible to use in some cases the `--artifacts` argument. However, the schema expected for this argument is specified nowhere. I tried extracting it from the ARM template of the formula in the portal, it does not work. There are no links to documentation regarding this file.

### Page URL

https://learn.microsoft.com/en-us/cli/azure/lab/vm?view=azure-cli-latest

### Content source URL

https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/lab/vm.yml

### Author

@dbradish-microsoft

### Document Id

ef65acdc-464a-08c7-b013-d9e3f1560977

**Comment by TPavanBalaji** [comment]
@cnovel 
Thank you for bringing this to our attention.
I've delegated this to content author, who will review it and offer their insightful opinions.

**Comment by dbradish-microsoft** [comment]
Helo, @cnovel. I hear your frustration and have moved your feedback to the Azure/azure-cli engineering GitHub repository where it will receive attention from the `az lab vm` engineering team. Please continue this conversation in [30134](https://github.com/Azure/azure-cli/issues/30134).
