### ISSUE TITLE
az aksarc appears not to work in UK south

### ISSUE THREAD

**Issue by milesbarnard** [MicrosoftDocs/azure-docs-cli#4715]
### Type of issue

Missing information

### Feedback

Running commands such as az aksarc get-credentials in uksouth causes the following error:
2024-10-23 14:04:12.874753+00:00 Error: NoRegisteredProviderFound
Detail: No registered resource provider found for location 'uksouth' and API version '2024-01-01' for type 'provisionedClusterInstances'. The supported api-versions are '2023-11-15-preview, 2024-01-01'. The supported locations are 'eastus, westus3, southcentralus, westeurope, southeastasia, australiaeast, centralindia, canadacentral, japaneast'.

Alternatives running az aksarc list produces an empty list even if clusters exist - this is not stated in the documentation anywhere

### Page URL

https://learn.microsoft.com/en-us/cli/azure/aksarc?view=azure-cli-latest

### Content source URL

https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/aksarc.yml

### Author

@dbradish-microsoft

### Document Id

76c0d7d5-1413-a9f3-64de-6bf8a841395b

**Comment by PesalaPavan** [comment]
@milesbarnard 
Thanks for your feedback and your contribution to Azure docs.
Feedback for this repository is moving away from GitHub to a system specific to the Microsoft Learn platform. Issues for this repository will soon be disabled, and additional comments from GitHub will no longer be possible. However, we are now tracking and triaging this issue in the new feedback system.
To learn more about our feedback systems, please see [Provide feedback for Microsoft Learn content](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2Fcontentuserfeedback&data=05%7C02%7Cv-ommikumar%40microsoft.com%7C2469fb0ee4e14243d7ff08dcaa6acfb0%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638572622992825118%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=kC5WOp10fV1oVhsLEFTHEzjLo6HeVUbxU%2Fe%2F5z8TTU8%3D&reserved=0).

**Comment by dbradish-microsoft** [comment]
@milesbarnard , Is AKS a registered resouce in your subscription? Please see [Register a resource provider](https://learn.microsoft.com/en-us/azure/azure-resource-manager/management/resource-providers-and-types#register-resource-provider) for more information.

**Comment by milesbarnard** [comment]
@dbradish-microsoft Yes it is registered in my subscription

**Comment by dbradish-microsoft** [comment]
@milesbarnard, here is the response I received from the `az aksarc` engineering team -->

"
Actually "az aksarc" only works for the AKS enabled by Azure Arc: [Azure Kubernetes Service (AKS) enabled by Azure Arc documentation | Microsoft Learn](https://learn.microsoft.com/en-us/azure/aks/hybrid/), it only supports running on Azure Stack HCI as the platform for today. and we do have limited list of the supported regions: [System requirements for Azure Stack HCI, version 23H2 - Azure Stack HCI | Microsoft Learn](https://learn.microsoft.com/en-us/azure-stack/hci/concepts/system-requirements-23h2#azure-requirements). basically only the following regions are available: 

- East US
- West Europe
- Australia East
- Southeast Asia
- India Central
- Canada Central
- Japan East
- South Central US

as there is no other ways to create an AKS Arc cluster out of these regions,  It sounds like the customer might be usnig the wrong Azure CLI command?
"

**Comment by dbradish-microsoft** [comment]
> Thanks for your feedback and your contribution to Azure docs. Feedback for this repository is moving away from GitHub to a system specific to the Microsoft Learn platform. Issues for this repository will soon be disabled, and additional comments from GitHub will no longer be possible. However, we are now tracking and triaging this issue in the new feedback system. To learn more about our feedback systems, please see [Provide feedback for Microsoft Learn content](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2Fcontentuserfeedback&data=05%7C02%7Cv-ommikumar%40microsoft.com%7C2469fb0ee4e14243d7ff08dcaa6acfb0%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638572622992825118%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=kC5WOp10fV1oVhsLEFTHEzjLo6HeVUbxU%2Fe%2F5z8TTU8%3D&reserved=0).

@PesalaPavan, this information is not correct. Please message me on Teams. Thank you.

**Comment by dbradish-microsoft** [comment]
This GitHub issue is being closed as a response has been received from the engineering team. For additional suggestions, please open a [new GitHub issue in Azure/azure-cli](https://github.com/Azure/azure-cli/issues).
