### ISSUE TITLE
TLS 1.0 still used in example code

### ISSUE THREAD

**Issue by zyadamec** [MicrosoftDocs/azure-docs-cli#4729]
### Type of issue

Outdated article

### Feedback

TLS 1.0 is being deprecated and the sample code for the App gateway still specifies TLS 1.0

### Page URL

https://learn.microsoft.com/en-us/cli/azure/network/application-gateway?view=azure-cli-latest&source=docs

### Content source URL

https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/network/application-gateway.yml

### Author

@dbradish-microsoft

### Document Id

2573afce-d2fa-6f5f-3647-ea8696b8d0e2

**Comment by dbradish-microsoft** [comment]
Thank you, @zyadamec, for bringing this to our attention. As the source of this documentation is written by the engineering team for `az network application-gateway`, I've moved your feedback to Azure/azure-cli GitHub issue [30233](https://github.com/Azure/azure-cli/issues/30233) so the engineering team can be advised and make this update. Please follow up  and make additional comments in this new location.
