### ISSUE TITLE
Article for service creation principal has misleading guidance for --cert

### ISSUE THREAD

**Issue by jikuja** [MicrosoftDocs/azure-docs-cli#4734]
### Type of issue

Other (describe below)

### Feedback

`When you use a PEM file, the CERTIFICATE must be appended to the PRIVATE KEY within the file.` on linked page is wrong:

* The AZ CLI example after that sentence is clearly using only certificate
* Implementation for local --cert is assuming that only certificate is present on the input: https://github.com/Azure/azure-cli/blob/b976aa4280016c33f9fda00307ba24d6670f1624/src/azure-cli/azure/cli/command_modules/role/custom.py#L1521-L1528

----

TBH this might be even security issue if MS Graph API logs contents of the `keyCredential.key` and documentation suggests sening private key into API.

### Page URL

https://learn.microsoft.com/en-us/cli/azure/azure-cli-sp-tutorial-3

### Content source URL

https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/docs-ref-conceptual/azure-cli-sp-tutorial-3.md

### Author

@dbradish-microsoft

### Document Id

0fbbbebc-427f-0df1-3bfa-447fbafab071

**Comment by TPavanBalaji** [comment]
@jikuja 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by TPavanBalaji** [comment]
@jikuja 
Thank you for bringing this to our attention.
I've delegated this to content author, who will review it and offer their insightful opinions.

**Comment by jiasli** [comment]
It is true that the document is incorrect. Private key is not needed for `--cert`. However, even if you include private key in the value of `--cert`, it won't be used, as only the public certificate is dumpped:

https://github.com/Azure/azure-cli/blob/6bbf23a39da7d6029ae7acf0393f3c00289a90c9/src/azure-cli/azure/cli/command_modules/role/custom.py#L1523

```py
def _get_public(x509):
    import OpenSSL.crypto
    pem = OpenSSL.crypto.dump_certificate(OpenSSL.crypto.FILETYPE_PEM, x509)
```

> TBH this might be even security issue if MS Graph API logs contents of the `keyCredential.key` and documentation suggests sening private key into API.

So this cannot a security issue.

**Comment by jikuja** [comment]
> So this cannot be a security issue.

True. Missed some parts of the logic (mostly: validator changing argument types)

Couple of questions:

----

Because `az ad sp create-for-rbac --create-cert` [creates](https://github.com/Azure/azure-cli/blob/b976aa4280016c33f9fda00307ba24d6670f1624/src/azure-cli/azure/cli/command_modules/role/custom.py#L1433-L1438) file containing private key and certificate, should Az CLI support using file with same format as input for `--cert` and make that official?

----

Interoperatibility with `az login`:

* `az logic --service-principal --certificate`  does not require @{file} notation, only direct reference to file containing certificate and private key.
* Old/current(?) az logic --service-principal --certificate {file}
  * Internally checks if `{file}` exists, otherwise use parameter as input
 
----

**Is re-usable certificate creation on scope for CLI or should the guidance by provided by Entra ID team?** ATM there is no documentation how to create keys and certificates for Entra ID service principals, only the command that does the local creation and service principal creation or update.

Use case: third party user creates their own private key and certificate, mails sertitiface to Entra ID admin and admin adds sertificate into their service principal
