### ISSUE TITLE
help missing for "az search service update --ip-rules"

### ISSUE THREAD

**Issue by chylek** [MicrosoftDocs/azure-docs-cli#4745]
### Type of issue

Missing information

### Feedback

Meaningful help text is missing for "az search service update" flag "--ip-rules".
![image](https://github.com/user-attachments/assets/1c93fbd2-31bb-4a7c-bfff-88331d41a1ac)

### Page URL

https://learn.microsoft.com/en-us/cli/azure/search/service?view=azure-cli-latest#az-search-service-update

### Content source URL

https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/search/service.yml

### Author

@dbradish-microsoft

### Document Id

63e76088-2537-b337-c130-20dcad6d772c

**Comment by TPavanBalaji** [comment]
@chylek 
Thanks for your feedback! We will investigate and update as appropriate.
