### ISSUE TITLE
Unclear how to define  instant recovery resource group name

### ISSUE THREAD

**Issue by V4A001** [MicrosoftDocs/azure-docs-cli#4751]
### Type of issue

Missing information

### Feedback

It is unclear how to define the instant recovery resource group name through CLI.

### Page URL

https://learn.microsoft.com/en-us/cli/azure/backup/policy?view=azure-cli-latest

### Content source URL

https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/backup/policy.yml

### Author

@dbradish-microsoft

### Document Id

8b695b10-a26d-caac-5206-38edeb1859c1

**Comment by ManoharLakkoju-MSFT** [comment]
@V4A001 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by dbradish-microsoft** [comment]
@V4A001, can you please provide more information about your reference to "instant recovery resource group name"? The link in your feedback takes me to [az backup policy create](https://learn.microsoft.com/en-us/cli/azure/backup/policy?view=azure-cli-latest) which has a `--resource-group` parameter.

**Comment by dbradish-microsoft** [comment]
This GitHub issues is being closed as there have been no further conversation since November 7th. Please reopen a new issue in [Azure/azure-cli](https://github.com/Azure/azure-cli/issues) if you feel there is an error in the product source code.
