### ISSUE TITLE
Unclear how to Enable vault immutability through azure cli

### ISSUE THREAD

**Issue by V4A001** [MicrosoftDocs/azure-docs-cli#4758]
### Type of issue

Missing information

### Feedback

![image](https://github.com/user-attachments/assets/cc648a42-cd84-472c-93f9-dc85b59b7755)

### Page URL

https://learn.microsoft.com/en-us/cli/azure/backup/vault?view=azure-cli-latest

### Content source URL

https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/backup/vault.yml

### Author

@dbradish-microsoft

### Document Id

f5d969a6-e8ef-90eb-5679-b6734612be76

**Comment by TPavanBalaji** [comment]
@V4A001 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by dbradish-microsoft** [comment]
Hello, @V4A001. The `--immutability-state` parameter accepts three options:
* Disabled
* Locked
* Unlocked

This covers the `Enable vault immutability` checkbox, and the "lock immutability" on/off switch.

For more examples of `az backup vault`, see [Azure CLI article list A to Z](https://learn.microsoft.com/en-us/cli/azure/reference-docs-index?view=azure-cli-latest#az-backup) and use `CTRL + F` to jump quickly to the `az backup vault` article list.

**Comment by V4A001** [comment]
I found out that after creation it is locked. But by first unlock it and then enable it again that sets all flats.

Can be closed or shall I provide scripts for reference to others?
