### ISSUE TITLE
Unclear how to enable system managed identity through azure cli for automation account

### ISSUE THREAD

**Issue by V4A001** [MicrosoftDocs/azure-docs-cli#4759]
### Type of issue

Missing information

### Feedback

Unclear how to enable system managed identity through azure cli for automation account

I try:
az automation account identity assign \
  --resource-group $resourceGroupNameToAutomate \
  --name $automationAccountName

but not luck. I want to turn on:

![image](https://github.com/user-attachments/assets/9f723f44-55f2-48b3-bcfb-72d6c1ac4c7b)

### Page URL

https://learn.microsoft.com/en-us/cli/azure/automation/account?view=azure-cli-latest

### Content source URL

https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/automation/account.yml

### Author

@dbradish-microsoft

### Document Id

c74ff008-a7d5-bf7c-e8ba-e9dcbad654be

**Comment by dbradish-microsoft** [comment]
Hello @V4A001. There isn't always a 1:1 relationship between the Azure portal UI and Azure CLI commands and/or parameter availability. I have an inquiry into the `az automation account` engineering team to confirm that I'm not overlooking something, and I've also created an Azure/azure-cli-extensions GitHub request [8273](https://github.com/Azure/azure-cli-extensions/issues/8273) to add this capability to the command group.

**Comment by V4A001** [comment]
I understand. I only want to use bash with azure cli as it roles out consistent without marking documentation

**Comment by dbradish-microsoft** [comment]
This GitHub issue is being closed as a new GitHub issue [8273](https://github.com/Azure/azure-cli-extensions/issues/8273) has been created in Azure/azure-cli where the engineering team can respond directly. Please post any new comments in the engineering repo. Thank you.
