### ISSUE TITLE
Unclear how to add an advanced weekly schedule with only for instance monday and wednesday

### ISSUE THREAD

**Issue by V4A001** [MicrosoftDocs/azure-docs-cli#4760]
### Type of issue

Missing information

### Feedback

  Unclear how to create a schedule of a few days:

    "advancedSchedule": {
      "monthDays": null,
      "monthlyOccurrences": null,
      "weekDays": [
        "Monday",
        "Tuesday",
        "Wednesday",
        "Thursday",
        "Friday"
      ]
    },

### Page URL

https://learn.microsoft.com/en-us/cli/azure/automation/schedule?view=azure-cli-latest

### Content source URL

https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/automation/schedule.yml

### Author

@dbradish-microsoft

### Document Id

be41ebb1-ee13-9eba-6a41-0c5cda23f18d

**Comment by PesalaPavan** [comment]
@V4A001 
Thanks for your feedback! I've assigned this issue to the author who will investigate and update as appropriate.

**Comment by dbradish-microsoft** [comment]
Hello @V4A001. I have sent a request to the `az automation schedule` engineering team for examples of the `--frequency` and `--interval` parameters. I will provide them here once received.

I've also created Azure/azure-cli-extensions GitHub issue [8272](https://github.com/Azure/azure-cli-extensions/issues/8272) requesting the engineering team to add more examples in the reference documentation.
