### ISSUE TITLE
Creation of backup-instance for Blob Storage Containers needs clarification

### ISSUE THREAD

**Issue by Salazander** [MicrosoftDocs/azure-docs-cli#4763]
### Type of issue

Missing information

### Feedback

The issues mentioned in https://github.com/Azure/azure-cli-extensions/issues/7499 can be avoided in the future by providing guidance on how to chain the commands `az dataprotection backup-instance initialize-backupconfig` and `az dataprotection backup-instance initialize` when setting up vaulted backups for blob storage containers.

The current docs mention
```
--backup-configuration
Backup configuration for backup. Use this parameter to configure protection for AzureKubernetesService.
```

The docs could mention how to generate the backup-configuration for blob containers. The fact that AzureKubernetesService are mentioned explicitly suggests to the reader that this parameter is not relevant for other use-cases. 

### Page URL

https://learn.microsoft.com/en-us/cli/azure/dataprotection/backup-instance?view=azure-cli-latest#az-dataprotection-backup-instance-initialize-backupconfig

### Content source URL

https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/dataprotection/backup-instance.yml

### Author

@dbradish-microsoft

### Document Id

463aa6af-5d08-2929-b244-6abfc9baf3b2

**Comment by PesalaPavan** [comment]
@Salazander 
Thanks for your feedback! I've assigned this issue to the author who will investigate and update as appropriate.

**Comment by dbradish-microsoft** [comment]
@AbhishekMallick-MS, In looking for `az dataprotection backup-instance%`, it looks like you have written the following conceptual articles that use this command prefix:

- https://github.com/microsoftdocs/azure-docs-pr/blob/main/articles/backup/azure-kubernetes-service-cluster-backup-using-cli.md
- https://github.com/microsoftdocs/azure-docs-pr/blob/main/articles/backup/azure-kubernetes-service-cluster-restore-using-cli.md
- https://github.com/microsoftdocs/azure-docs-pr/blob/main/articles/backup/backup-blobs-storage-account-cli.md
- https://github.com/microsoftdocs/azure-docs-pr/blob/main/articles/backup/backup-managed-disks-cli.md
- https://github.com/microsoftdocs/azure-docs-pr/blob/main/articles/backup/backup-postgresql-cli.md
- https://github.com/microsoftdocs/azure-docs-pr/blob/main/includes/blob-backup-prepare-request-cli.md

The only doc that uses `az dataprotection backup-instance initialize-backupconfig` is for AKS. Can you please implement the customer request for one of the Azure Blob articles?

**Comment by dbradish-microsoft** [comment]
@Salazander, your request has been passed to the PM group for `az dataprotection backup-instance`. I've also created a GitHub issue in Azure/azure-cli [30499](https://github.com/Azure/azure-cli/issues/30499) requesting more reference examples, specifically for blob containers. Please place additional comments in this new GitHub issue so the engineering team can be automatically notificed.
