### ISSUE TITLE
Code sample issue

### ISSUE THREAD

**Issue by jamesyao-msft** [MicrosoftDocs/azure-docs-cli#4766]
### Type of issue

Code doesn't work

### Feedback

Code sample: 
`az bicep publish --file {bicep_file} --target "br:{registry}/{module_path}:{tag} --force"`

`--force` shall be out side of ""

### Page URL

https://learn.microsoft.com/en-us/cli/azure/bicep?view=azure-cli-latest

### Content source URL

https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/bicep.yml

### Author

@dbradish-microsoft

### Document Id

60edc003-8f74-62af-e9fd-79efb5a77d9f

**Comment by PesalaPavan** [comment]
@jamesyao-msft 
Thanks for your feedback! I've assigned this issue to the author who will investigate and update as appropriate.

**Comment by dbradish-microsoft** [comment]
@jamesyao-msft, as this is generated content from source code `--help`, I am passing your observation to the Bicep team for correction. Please follow up in Azure/azure-cli [issue 30335](https://github.com/Azure/azure-cli/issues/30335). Thank you for helping to improve our reference content.
