### ISSUE TITLE
az servicebus namespace authorization-rule keys renew `--key-value` parameter description illegible

### ISSUE THREAD

**Issue by kiweezi** [MicrosoftDocs/azure-docs-cli#4779]
### Type of issue

Typo

### Feedback

Seen in the `az servicebus namespace authorization-rule keys renew` section of the page.
The `--key-value` parameter description is very confusing. I've been trying, but personally I cannot make out a legible sentence from what it is trying to say. Maybe it has been incorrectly copy+pasted into?
> Optional, if the key value provided, is reset for KeyType value or autogenerate Key value set for keyType.

It is not possible to understand how to use the parameter from this description, and there is no example using it either.
Please can this description be corrected?

### Page URL

https://learn.microsoft.com/en-us/cli/azure/servicebus/namespace/authorization-rule/keys?view=azure-cli-latest

### Content source URL

https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/servicebus/namespace/authorization-rule/keys.yml

### Author

@dbradish-microsoft

### Document Id

78a5f641-bea0-83d7-c328-b708c5d6f490

**Comment by PesalaPavan** [comment]
@kiweezi 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by PesalaPavan** [comment]
@kiweezi 
Thanks for your feedback! I've assigned this issue to the author who will investigate and update as appropriate.

**Comment by dbradish-microsoft** [comment]
@kiweezi, I have moved your feedback to Azure/azure-cli where this information originates. The engineering team will be notificed and will be able to repond in this new location. Please continue to follow up in [30497](https://github.com/Azure/azure-cli/issues/30497).
