### ISSUE TITLE
Self-Signed SSL Certificate help incomplete for newer Macs

### ISSUE THREAD

**Issue by rxs182** [MicrosoftDocs/azure-docs-cli#4780]
### Type of issue

Missing information

### Feedback

For Mac help, the docs seem to only cover where Homebrew installs the azure-cli for intel models.  

The docs should updated to include the install/cert bundle location for Apple silicon models as well:
`/opt/homebrew/Cellar/azure-cli/2.66.0/libexec/lib/python<version>/site-packages/certifi/cacert.pem`

### Page URL

https://learn.microsoft.com/en-us/cli/azure/use-azure-cli-successfully-troubleshooting#work-behind-a-proxy

### Content source URL

https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/docs-ref-conceptual/use-azure-cli-successfully-troubleshooting.md

### Author

@dbradish-microsoft

### Document Id

0e8af423-3d1b-3189-e74e-a471afb9d414

**Comment by PesalaPavan** [comment]
@rxs182 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by dbradish-microsoft** [comment]
@rxs182, your feedback has been incorporated in PR https://github.com/MicrosoftDocs/azure-docs-cli/pull/4833. Thanks for your help!
