### ISSUE TITLE
Typo with dashes in cli commands

### ISSUE THREAD

**Issue by Glavyanov** [MicrosoftDocs/azure-docs-cli#4809]
### Type of issue

Typo

### Feedback

If I'm not mistaken, they should only have 2 dashes each: 

![image](https://github.com/user-attachments/assets/d6839875-ec44-4cf8-8651-7780338bff19)

Best Regards!

### Page URL

https://learn.microsoft.com/en-us/cli/azure/cheat-sheet-onboarding#using-reference-commands

### Content source URL

https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/docs-ref-conceptual/cheat-sheet-onboarding.md

### Author

@dbradish-microsoft

### Document Id

e5d2a07f-afd9-e985-abda-0840ac5f59b0

**Comment by PesalaPavan** [comment]
@Glavyanov 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by PesalaPavan** [comment]
@Glavyanov 
Thanks for your feedback! I've assigned this issue to the author who will investigate and update as appropriate.

**Comment by dbradish-microsoft** [comment]
@Glavyanov, this has been fixed in PR [4850](https://github.com/MicrosoftDocs/azure-docs-cli/pull/4850). Thanks for bringing this to our attention.
