### ISSUE TITLE
New required options for `az container create` command

### ISSUE THREAD

**Issue by estokes-vs** [MicrosoftDocs/azure-docs-cli#4812]
### Type of issue

Outdated article

### Feedback

We ran into multiple errors this morning while rolling out routine updates to our Azure Container instances.  We use the command `az container create` to deploy new sets of containers, and an example of this is below. 

```
  az container create \
    --resource-group  \
    --name \
    --image \
    --restart-policy \
    --location \
    --command-line \
    --environment-variables \
    --memory \
    --registry-username \
    --registry-password \
    --only-show-errors
```

This morning we got errors for multiple new items needing to be added, which are not documented as `required`.

--os-type
```
ERROR: (InvalidOsType) The 'osType' for container group '<null>' is invalid. The value must be one of 'Windows,Linux'.
Code: InvalidOsType
Message: The 'osType' for container group '<null>' is invalid. The value must be one of 'Windows,Linux'.
```
--cpu
```
ERROR: (ResourceSomeRequestsNotSpecified) The 'Cpu' request is not specified in 'MemoryInGB '6' Cpu ''' in container 'vergesense-analytics-backend-staging-sidekiq-1' of contain group 'vergesense-analytics-backend-staging-sidekiq-1'. It is required since API version '2017-07-01-preview'.
Code: ResourceSomeRequestsNotSpecified
Message: The 'Cpu' request is not specified in 'MemoryInGB '6' Cpu ''' in container 'vergesense-analytics-backend-staging-sidekiq-1' of contain group 'vergesense-analytics-backend-staging-sidekiq-1'. It is required since API version '2017-07-01-preview'.
```

It's worth noting that I was able to run these commands with Azure CLI 2.65.0 without issue, but once upgraded to 2.67.0 I encountered both errors.  

### Page URL

https://learn.microsoft.com/en-us/cli/azure/container?view=azure-cli-latest#az_container_create

### Content source URL

https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/container.yml

### Author

@dbradish-microsoft

### Document Id

ba32e12d-8283-f980-e1d0-1ca2a75a5152

**Comment by PesalaPavan** [comment]
@estokes-vs 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by dbradish-microsoft** [comment]
@estokes-vs, I have moved your feedback to Azure/azure-cli [30496](https://github.com/Azure/azure-cli/issues/30496) where the engineering team will be notificed and can respond. Please continue the conversation in this new location. Thank you.
