### ISSUE TITLE
az aks update can cause node image update that can lead to downtime

### ISSUE THREAD

**Issue by mykolaichuk** [MicrosoftDocs/azure-docs-cli#4836]
### Type of issue

Missing information

### Feedback

Hello,

```
az aks update --resource-group myResourceGroup --name myAKSCluster --load-balancer-outbound-ports 4000
```

Microsoft documentation doesn't state elsewhere that this command could update node image version to the latest available, which might cause potential downtime. Please, describe this behavior in a more clear way.
![image](https://github.com/user-attachments/assets/ddc34ac4-0757-409b-8e8d-a517d8fa820a)
![image](https://github.com/user-attachments/assets/1e0fc4ed-e4df-437d-8eaf-d100661f7416)

### Page URL

https://learn.microsoft.com/en-us/cli/azure/aks?view=azure-cli-latest#az-aks-update

### Content source URL

https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/aks.yml

### Author

@dbradish-microsoft

### Document Id

75b0c352-762e-16ae-5cc6-d807ffc1dc3f

**Comment by PesalaPavan** [comment]
@mykolaichuk 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by PesalaPavan** [comment]
@mykolaichuk 
Thanks for your feedback! I've assigned this issue to the author who will investigate and update as appropriate.

**Comment by dbradish-microsoft** [comment]
@mykolaichuk, I am moving your feedback to Azure/azure-cli where the engineering team will be notified and can respond. Please continue the conversation with `az aks` engineering in [30495](https://github.com/Azure/azure-cli/issues/30495).
