### ISSUE TITLE
Proxy

### ISSUE THREAD

**Issue by garbacik** [MicrosoftDocs/azure-docs-cli#965]
Is the configuration for proxy use be defined somewhere for those not familiar with proxy setup? Also what URLs are required to allow azure CLI to pass thru a corporate firewall to allow it to function? Also, a note explaining why calls to dc.services.visualstudio.com will flood your network when blocked would be beneficial.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c268a98-afcb-d2c2-87c7-880d52900533
* Version Independent ID: 4c835da4-38bc-22a8-67b4-dd522adcc0e3
* Content: [Get started with Azure CLI 2.0](https://docs.microsoft.com/en-us/cli/azure/get-started-with-azure-cli?view=azure-cli-latest)
* Content Source: [docs-ref-conceptual/get-started-with-azure-cli.md](https://github.com/Azure/azure-docs-cli-python/blob/master/docs-ref-conceptual/get-started-with-azure-cli.md)
* Product: **azure**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment]
More details on the use case here are needed, in particular whether or not setting the `HTTP_PROXY` and `HTTPS_PROXY` environment variables have an effect on the CLI.

**Comment by sptramer** [comment]
Resolved by #1471. Providing a complete allow-list of Azure service endpoints is beyond the scope of the CLI documentation, but a request has been made to start compiling such a list to make it available somewhere in documentation. Currently the best option for finding the required endpoints is the [Azure services swagger specs](https://github.com/Azure/azure-rest-api-specs).

Apologies for the extremely long delay on resolving this issue but there were large numbers of high-priority items on the backlog, and proxy configuration information is easily searchable for all of our officially supported OS platforms.
